### ISSUE TITLE
'Force Full Update' link does not respect web_root setting

### ISSUE THREAD

**Issue by jallakim** [SickGear/SickGear#1001]
#### Branch version commit hash: 1bdab584c43bd0da297d1fbd6351edf9849779ed

Expectation | Result
Click URL should work |  Does not work because wrong URL

**Steps to reproduce:**
*1)* Visit a show that hasn't been updated. The text ```A force full update may return a plot overview for this ended show``` is displayed where the plot overview usually is.
*2)* Click the link (rather than the ```Force Full Update``` button in the top right).
*3)* Link does not work, as it goes to ```https://$HOST/home/updateShow``` even when web_root is set to ```/sickgear```. The link should go to ```https://$HOST/sickgear/home/updateShow```. The ```Force Full Update``` button in the top right has the correct URL.

**Comment by JackDandy** [comment]
Please check this on develop (use general config/adv tab to switch)

**Comment by jallakim** [comment]
@JackDandy, same behavior in d9216d0b893c0acf7f8210adba61873ab8eec5c8 (latest commit in develop branch).

**Comment by jallakim** [comment]
Deleted cache in browser as well. Still same URL (without respecting the web_root setting).

**Comment by JackDandy** [comment]
For realtime help on this issue, 
in your browser come and <a href="https://gitter.im/SickGear/Lobby/"><img src="https://badges.gitter.im/sickgear.svg"></a> with your git account or if you prefer sickgear @ slack

**Comment by jallakim** [comment]
No need for realtime help (-:

**Comment by JackDandy** [comment]
to test a fix it is needed

**Comment by jallakim** [comment]
What?

**Comment by JackDandy** [comment]
k, nevermind

**Comment by jallakim** [comment]
Are you drunk or something? I came to SickGear because I thought the drama over at SR/SRTV was not a case here, but this is not off to a good start.

I tested both branches, and both have the same issue. Cleared the cache after switching branches. Also tried via incognito. Hovering over the two links (```Force Full Update``` button and ```plot overview link```) clearly shows that the web_root is not part of the latter.

**Comment by JackDandy** [comment]
Please don't bring that attitude here from there. 
I asked if you want to do reeltime chat so that i could do a test with you and create a hotfix for master, your refusal left me no choice but to make a fix for develop branch only, which is already up there. You dont know how we work, fine, but dont slate us before getting a feel for how we do things here.

**Comment by JackDandy** [comment]
#1002

**Comment by jallakim** [comment]
Your comment to do a live chat was interpreted as a question/offer, which I declined (as I did not see any point of it). Deleting comments on top of that, with the addition of your "k, nevermind" comment, was not really a good start, regardless of attitude.

**Comment by JackDandy** [comment]
Superflous messages deleted to keep threads clean
