### ISSUE TITLE
Hitting Submit on Bulk Change page yields 404

### ISSUE THREAD

**Issue by jallakim** [SickGear/SickGear#1003]
#### Branch version commit hash: d9216d0b893c0acf7f8210adba61873ab8eec5c8

Expectation | Result
------------ | -------------
After clicking Submit button on the Bulk Change, SG should process the request | Sent to a page that 404's.

**Steps to reproduce:**
*1)* Click Submit on the Bulk Change page

URL is ```https://$FQDN/sickgearbulkChange?toUpdate=261690&toRefresh=&toRename=&toSubtitle=&toDelete=&toRemove=&toMetadata=```. URL before clicking Submit is ```https://$FQDN/sickgear/manage/```. web_root is also set (to ```/sickgear```).

Tried to manually set ```/sickgear/sickgearbulkChange```, ```/sickgear/home/sickgearbulkChange``` and ```/sickgear/manage/sickgearbulkChange```, but neither works.

**Comment by JackDandy** [comment]
#1004
