### ISSUE TITLE
Should this work on RPi3 OSMC?

### ISSUE THREAD

**Issue by tpitman** [SickGear/SickGear#1011]
#### Branch Latest from GIt today

Expectation | Result
------------ | -------------
Tried compiling on RPi3 with OSMC

**Steps to reproduce:**
Follow the steps on the Debian instruction page. At the installing step for the python environment you get the error show below.

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
build failure log output:

BUILD FAILED (OSMC 2017.09-1 using python-build 1.1.5-40-g5b5df15)

Inspect or clean up the working tree at /tmp/python-build.20171110161937.9681
Results logged to /tmp/python-build.20171110161937.9681.log

Last 10 log lines:
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
gcc -pthread -c -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include -I/opt/SickGear/.pyenv/versions/2.7.13/include   -DPy_BUILD_CORE -o Objects/dictobject.o Objects/dictobject.c
The bug is not reproducible, so it is likely a hardware or OS problem.
Makefile:1365: recipe for target 'Objects/intobject.o' failed
make: *** [Objects/intobject.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by JackDandy** [comment]
This is not really the place for this type of question, but i dont know of anyone who has attempted to build Python on RPi, sorry.

**Comment by tpitman** [comment]
Thank you for the quick reply.

**Comment by JackDandy** [comment]
One of the devs tells me

>  as long as that distro is at least debian jessie ... can simply install python with apt-get
