### ISSUE TITLE
Season posters are not being grabbed Kodi

### ISSUE THREAD

**Issue by normsland** [SickGear/SickGear#1027]
#### Branch version commit hash: 1b827f29324fdea3b7fdb9931dc495b2b6116513

Expectation | Result
------------ | -------------
Expected result is that when a new season of a TV show is aired season##-poster.jpg is added in to parent folder for Kodi metadata. | No additional season##-poster.jpg have been downloaded from tvDB/generated by SG for sometime. Just noticed now could have not been working for sometime.

**Steps to reproduce:**
*1)* Enable in post process Kodi metadata. Select Season Posters->season##-poster.jpg
*2)* Download show with without flattened file hierarchy.
*3)* Post-process show episode. Is relevant season##-poster.jpg created?

**Comment by JackDandy** [comment]
[Fixed 0.13.3](https://github.com/SickGear/SickGear/releases/tag/release_0.13.3)
