### ISSUE TITLE
System menu does not appear on mobile

### ISSUE THREAD

**Issue by normsland** [SickGear/SickGear#1028]
#### Branch version commit hash: 1b827f29324fdea3b7fdb9931dc495b2b6116513

Expectation | Result
------------ | -------------
System menu should appear on Chrome 62.0.3203.84 Android. It worked prior to c0fdc1452a462d4d7a0bcb5216155e2b8b09ac7c  | Browse to menu->System menu should be populated with subitems.

**Steps to reproduce:**
*1)* Use Chrome 62.0.3203.84 on Android.
*2)* Browse to SG front page. Try clicking on System menu. Should see 6 subitems 'Check for updates'...'Shutdown' etc.
...

**Comment by JackDandy** [comment]
Fixed: https://github.com/SickGear/SickGear/releases/tag/release_0.13.2
