### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Session' in sabToSickBeard.py file

### ISSUE THREAD

**Issue by wahteva** [SickGear/SickGear#1029]
#### Branch version commit hash: 7b3e702b48b99f76946c083dbeb88653fe8f6cd0

Expectation | Result
------------ | -------------
I am running SickGear on Synology.  After a TV show downloads, the sabToSickBeard script runs for fail handling.   | The script has the following error. This only started happening yesterday after update 0.13.2 was applied

Loading config from /volume1/software/apps/sabnzbd/scripts/autoProcessTV.cfg

Opening URL: http://########:8083/home/postprocess/processEpisode
Traceback (most recent call last):
File "/volume1/software/apps/sabnzbd/scripts/sabToSickBeard.py", line 30, in <module>
autoProcessTV.processEpisode(sys.argv[1], sys.argv[2], sys.argv[7])
File "/volume1/software/apps/sabnzbd/scripts/autoProcessTV.py", line 134, in processEpisode
sess = requests.Session()
AttributeError: 'module' object has no attribute 'Session'

**Steps to reproduce:**
*1)* run the SabToSickBeard.py post-processing file after successful download.
...

Additional notes:
I am not very familiar with python but I can see why the error is occurring.  Although I can import the requests module, it doesn't have the "Session" attribute.

Python 2.7.12 (default, Oct 30 2017, 11:04:41)
[GCC 4.9.3 20150311 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> dir(requests)
['__doc__', '__file__', '__name__', '__package__', '__path__']

However in the "requests" folder, the session.py file exist and the "__init__.py" explicity adds it to the import.

from . import utils
from .models import Request, Response, PreparedRequest
from .api import request, get, head, post, patch, put, delete, options
from .sessions import session, Session
from .status_codes import codes

Please let me know if there is a way to fix this or if you need more information. Thank you.

**Comment by JackDandy** [comment]
The Requests module installed in the system is an old version that lacks session support, simply update it.
