### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'replace'

### ISSUE THREAD

**Issue by Morgon** [SickGear/SickGear#1030]
#### Branch version commit hash: 023f4a9c79bcaeba1232e9ce78aa53d601dad427

I'm using nzbGet, which has an nzbToMedia script to call back to SG. After updating SG earlier, I am having the following issue. Sometimes it's a 'dict' object, you'll see here that this is an 'int':

https://pastebin.com/jxHGKRaY

SG is running on a Drobo 5N. Unfortunately I'm not sure what to do here, and I'm not sure how far back my previous version was to try and restore.

**Comment by JackDandy** [comment]
For realtime help on this issue, 
in your browser come and <a href="https://gitter.im/SickGear/Lobby/"><img src="https://badges.gitter.im/sickgear.svg"></a> with your git account

**Comment by JackDandy** [comment]
[Fixed](https://github.com/SickGear/SickGear/releases/tag/release_0.13.4)
