### ISSUE TITLE
Some shows show year after the title

### ISSUE THREAD

**Issue by rvoosterhout** [SickGear/SickGear#1032]
#### Branch version commit hash: c1b30561aa555fb7889d7f9a8ad3f4edc98e7a4d

Expectation | Result
------------ | -------------
Normally, the show title shows just the title without the year. Example: The Flash, Battlestar galactica | Now, the show titles are like this: The Flash (2014), Battlestar Galactica (2003)

**Steps to reproduce:**
*1)* Adding new show through search
*2)* Typing in Flash, and hitting search
*3)* Show comes up as Flash, the (2014)
*4)* Adding the show creates a folder called Flash (2014)

But I want the folder and show to be called: The Flash

Show is previously added, but has been deleted. I'm trying to add the show again. I still have all the video files, just removed the Sickgear entry, and trying to add it again.

**Comment by JackDandy** [comment]
That is correct. Click the TVDB icon and you will see the show listed with year.

**Comment by rvoosterhout** [comment]
Ok, but there is no way to make it so that the year doesn't shows in the title after post processing?

**Comment by JackDandy** [comment]
Yup, that is correct - original names are maintained for consistency.

**Comment by rvoosterhout** [comment]
Ah that's too bad. Thanks anyway.

**Comment by JackDandy** [comment]
Not really, consider this, someone adds a show to tvdb and the name is actually not using a year, and then later it is realised that another show was 25 years ago, then tvdb make the change and the users wants the new name so that search doesnt confuse old with new...

**Comment by rvoosterhout** [comment]
Ah yeah now I understand, seems more logical now!
