### ISSUE TITLE
Request: Subtitle management

### ISSUE THREAD

**Issue by pge-01** [SickGear/SickGear#1033]
#### Branch version commit hash: c1b30561aa555fb7889d7f9a8ad3f4edc98e7a4d

For not native english speakers (among others) the following would be of great value:

An option to set the subtitle for each show seperately. For some shows we don't need any, most with english, others we need dutch (for mum).

An option to only move the file (in postprocessing) after a suitable subtitle is found, to prevent files from showing in our Media Center. Maybe with a script. Would be nice if moving is a manual option if no subtitle is found. It is not uncommon we have to wait several days..
Thank in advance!

**Comment by JackDandy** [comment]
Thanks for the suggestions.

**Comment by JackDandy** [comment]
> An option to set the subtitle for each show seperately.

This is already how it works, you can edit a show and enable/disable subtitles for it.

> An option to only move the file (in postprocessing) after a suitable subtitle is found,  to prevent files from showing in our Media Center ... Would be nice if moving is a manual option if no subtitle is found

The request here is to create manual intervention. May as well reorganize what show folders a dedicated  profile of the media center can see, and then manually move files that **DO** have subtitles to that location because there is no actual difference in doing that and this request.  Anyway, making something a manual process goes against the **automated** flow of SG.

**Comment by pge-01** [comment]
Thanks for your response.

To clarify my questions below.

Ad 1: I mean the possibility to set the language for each show separately.

Ad 2: It would be nice if I can have the file moved (in automated postprocessing) to my TV Series folder, only if a subtitle is found. 
Because some subtitles (although rare) are never found, it would be a 'nice to have' option if I can press a button for that particular episode, to archive it anyway, more like the 'search cc' which exist now already. 

At the moment it works quite like your reply (A2 below). 
- The episodes with a corresponding  subtitle are moved (manual within some ours or days) to my TV Series folder (imported by JRMC).

- TV shows of which I do not need a subtitle are directly moved to my TV Series folder and then automatically imported by JRMC.

The idea is indeed the automation with the condition 'subtitle found' as a trigger.


And, of course, it's possible I am missing a solution already available.


Thanks a lot for all your time and effort...(excuses for my broken english).

Greetings, Paul

**Comment by JackDandy** [comment]
A1 would require a DB upgrade, but is doable.
A2 is too complicated to implement.

I can put this back into incubation for A1 :)
