### ISSUE TITLE
SickGear UI Isn't Displayed

### ISSUE THREAD

**Issue by curbro** [SickGear/SickGear#1037]
#### OS: Ubuntu 16.04 LTS

Expectation | Result
------------ | -------------
The ui should load. | The ui doesn't load and a python interpreter error is displayed instead.

**Steps to reproduce:**
*1)* Start the sickgear service
*2)* Navigate to any page
...

**edit**: removed, no longer needed, thanks

**Comment by JackDandy** [comment]
Added large drive sizes to output #1039
