### ISSUE TITLE
Subtitle settings page missing. Can't login.

### ISSUE THREAD

**Issue by kodiplh** [SickGear/SickGear#1055]
#### Branch version commit hash: (See the About page)

![sickragebug](https://user-images.githubusercontent.com/36135723/35780604-396e8600-09de-11e8-9072-9a3c425e4e3d.png)

Branch Master.

**Steps to reproduce:**
*1)* Step to take  Just run the lastest master sickgear.
*2)* Step to take report it here :)
...

Not a big deal. you just can't login to open-subtitles ect.

Additional notes:
This is fresh install 3 days old.  Im a happy user. It make mutch easyer to manage my library.
Thank you for you time!

**Comment by JackDandy** [comment]
Correct, login is not required.

**Comment by JackDandy** [comment]
A branch being worked on now has OpenSubtitles login support.

Let me know if you are interested to test.
