### ISSUE TITLE
Won't snatch

### ISSUE THREAD

**Issue by tpitman** [SickGear/SickGear#1060]
#### Branch version commit hash: 51df563c50276ea0b04ff89ff146909371d53e2c

I have a tv show (Lethal Weapon) that shows up. When I added it all existing episodes are skipped. I click on the latest one because I actually missed it. I expected it to snatch it. | The episode searches, but doesn't find it.

**Steps to reproduce:**
*1)* Add Lethal Weapon
*2)* Click search icon on latest skipped episode
*3)* Notice it searches, but doesn't find it

Additional notes:
I have several other shows I did the same thing and some did the same thing others worked.

**Comment by JackDandy** [comment]
Snatching works fine, therefore, the details here are too vague.
