### ISSUE TITLE
Adds ... behind client file path causing it to err

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#1061]
BRANCH: develop / COMMIT: 875530ce5a6f2b9df718d93236a87e22c6ab2279

With the show american dad, from any source, any release group I've tested, it seems to add a directory for the snatch, lets say, `C:/American.dad.S13` on your drive but then it adds `C:/American.dad.S13..`. as the path of the download in the client which errors out in your client saying path not found because it expects to find `C:/American.dad.S13...` while it created `C:/American.dad.S13`.
It didn't see what went wrong at first but after further inspection removing the` ...` from the client manually setting the path to the right location resolves the issue so somewhere in the snatching process something happens adding `...` to the path in the client.
Only happens with this show, haven't seen it happen with anything else and I think it only happens with seasons.

**Steps to reproduce:**
*1)* Let it snatch any American Dad season
*2)* Look in the client path for ... behind the regular path and compare it to the original path it created (without ...)
*3)* Watch the client stop the download and give an error path not found.

Log (slightly redacted)
```

DEBUG    BACKLOG-73141 :: uTorrent: Response to GET request is {"build":25203}
<snip>
DEBUG    BACKLOG-73141 :: uTorrent: sending GET request to http://localhost:<port>/gui/ with ...
DEBUG    BACKLOG-73141 :: uTorrent: sending POST request to http://localhost:<Port>/gui/ with ...
DEBUG    BACKLOG-73141 :: Calling uTorrent Client
INFO     BACKLOG-73141 :: Downloading American.Dad.S14.720p.WEB-DL.DD5.1.H.264-Group from <Provider>
```

Additional info:

Assign space is turned on so it first creates the files to avoid storage problems in Win 10.

**Comment by JackDandy** [comment]
There is no code to add a '...' to a file name.  Also, there is not enough information for your issue to be tested because both provider and client in your report are not named.

**Comment by Th3MadHatter** [comment]
1) BTN 2) utorrent 2.2.1 build 25203 3) American.Dad.S14.720p.WEB-DL.DD5.1.H.264-ViSUM

**Comment by JackDandy** [comment]
SG is not affecting this, therefore, you will have to manually handle these series.

**Comment by JackDandy** [comment]
Yeah, I cant verify this. I advise you handle this manually.

**Comment by Th3MadHatter** [comment]
Seems to be a group specific problem

It makes a giant mess of snatching the show even with scene numbering enabled. Snatches S7 while asking for S9 which is scene numbered as S8. I'll figure it out manually.

**Comment by JackDandy** [comment]
You need to be really careful with AD, scene numbering and xem come into play in terms of how a file is named, and what the release is named. Failure to appreciate what is going on will make you think "it is making a mess". I suggest you click the xem icon on the show to get a clearer understanding.

**Comment by Th3MadHatter** [comment]
I know, I had xem (the site) open already and sorted it by xem afterwards. Some groups decided to go with the tvdb numbering, others with channel numbering and some with dvd numbering, that's what made it a mess. It looks like pokemon all over again lol.
I'm manually naming the season directories correctly now and leaving the episode numbers as set by the groups, then manually adding them to the scene numbering box if they need to be changed.

**Comment by JackDandy** [comment]
Yeah, the season displacement started at s01, every season since has been +1. 

With `Scene numbering` enabled, SG handles scene release numbering using XEM perfectly fine. However, as you found, other releases do not adhere to scene, therefore, those require you to adjust the column to either remove the number (i.e. set it back to 0x0) or something else entirely.  I see that the latest s15e01 is finally back to normal with the scene release, the scene column is 0x0 for this season, and this worked normal this week (again, with scene releases).
