### ISSUE TITLE
Pushover notification priority setting does not persist across restarts

### ISSUE THREAD

**Issue by deed02392** [SickGear/SickGear#1063]
#### Branch version commit hash: (See the About page)

Expectation | Result
------------ | -------------
After setting the pushover notification priority to anything other than Lowest and saving, the priority should be loaded when SickGear restarts. | Priority reverts to Lowest after restarting.

**Steps to reproduce:**
*1)* Configure pushover, set priority to Medium.
*2)* Restart sickgear.
*3)* Observe priority has reset to Lowest.

**Comment by JackDandy** [comment]
[Fixed 0.14.5](https://github.com/SickGear/SickGear/releases/tag/release_0.14.5)
