### ISSUE TITLE
Search failing

### ISSUE THREAD

**Issue by tpitman** [SickGear/SickGear#1065]
#### Branch version commit hash: 51df563c50276ea0b04ff89ff146909371d53e2c

Search by episode name | Failing to find even though a manual find using browser works

**Steps to reproduce:**
*1)* Click to search for a episode
*2)* Go to log and see that the search failed
...

Additional notes:
I have The Pirate Bay and EZTV set up as providers. The log shows that the episode search failed. I notice that it is using this format: "[The Detour - 3x06 - The Vows]"

If I then go directly to the pirate bay or eztv and do a search with the format The Detour s03e06 if finds it. So How do I set sickgear to use that format instead of 3x06 or does it matter?

**Comment by JackDandy** [comment]
Please forward logs as a [gist ](https://gist.github.com/)

**Comment by tpitman** [comment]
i didn't realize everything with PA was public. I turned them all on and now shows are coming in again.

It was a typo. Still don't understand how the show can not be found, but when i manually go to the site I find it, but since I am getting shows now that is fine. Feel free to close this issue as you have solved it.

Thank you as always for all your hard work and efforts.
