### ISSUE TITLE
Request: Upgrade "quality" settings for 720p/1080p x265

### ISSUE THREAD

**Issue by funar** [SickGear/SickGear#1068]
I realize HEVC/x265 is not a "quality." However, it would be nice to be able to tell SickGear to "upgrade" shows to 1080p/720p x265 after already downloading a x264 (or whatever) SD/HD version of the show.

More and more release groups are starting to use x265, albeit usually delayed days after new episodes release. Those of us who collect shows for long-term storage would benefit from the smaller file sizes, even if the release becomes available days or even weeks after.

Today, we can add "x265" and/or "hevc" to the list of required words, but it would be preferred to not limit the search results that way to prevent completely missing out on an episode because an x265 version was never found.

**Comment by JackDandy** [comment]
I see merit in this suggestion, and as you said, x265 is not a quality - and does create issues, however, adding this FR to the list.

A note about [feature requests](https://github.com/SickGear/SickGear/issues/770) :)
 
Thanks.

**Comment by bblboy54** [comment]
I'd like to add an additional twist to this request.  There are certain shows that my main priority is having small file sizes and place more value in that than quality.  In these cases I'd like to be able to tell Sick Gear that I'd like it to download HD HEVC or any SD version.

Maybe the best way to implement this from a user perspective is to provide drop down boxes to select qualities in the order of preference and next to each drop down box you can add a "require HEVC" checkbox.  I, of course, don't know how complicated that is from the coding side so maybe it'd be too complicated.  Doing it this way would allow me to specify what I want in the custom wanted section and funar would be able to accomplish his task by not selecting any HEVC checkboxes in the wanted section but could select them in the upgraded quality section.

**Comment by NyvenZA** [comment]
I was actually looking for a facility to add the file encoding ( x264 or x265) as an option for file naming. 
Then I could actually see which shows needs to be updated. 

I have done the following to get my shows to properly download in 265 encoding only. 
It does mean that I had to edit the shows and add this facility :

I added all the following entries to the "required" field under the show's Common settings:
h.265,HEVC,h265,H.265,H265,x265,hevc

![image](https://user-images.githubusercontent.com/64709994/102513923-84a9f380-4094-11eb-928b-8a9260f302a2.png)

You do also have to remember to remove the following entry from the restricted words:
h265 or x265 
(I already removed mine, so not sure which is is by default) If you don't do this, the shows with these terms are excluded from searches. 
Search Settings -> Search Tasks -> "Ignore result with any word"
![image](https://user-images.githubusercontent.com/64709994/102514101-c044bd80-4094-11eb-845e-91e670623519.png)

**Comment by JackDandy** [comment]
fyi: as require ... `regex: ((h.?|x)265|hevc)`

**Comment by JackDandy** [comment]
fyi: as require ... `regex: ((h.?|x)265|hevc)` .. will capture any upper/lower case mix

**Comment by potestus** [comment]
Thanks for this.. it looks like the global setting wants to match ALL of the words?
I always collect x265 versions. what i would like is an option that 720p is acceptable and would backlog a 1080p version..
anybody worked out a good regedit for that..?
