### ISSUE TITLE
Unable to add or import any show

### ISSUE THREAD

**Issue by nv1804** [SickGear/SickGear#1070]
Hi,

I've been unable to add or import any show for the past few weeks. I always get the following error

Example: Show in N:\TV Shows\Scandal has no name on TheTVDB, probably the wrong language used to search with.

I've tried with different shows (all english language) but no luck. Could someone please help me out?

**Comment by JackDandy** [comment]
Hi,

This is an "how to" do something type question that is better dealt with in realtime IRC chat, see you in there. As this is not actually an issue, i will close this thread.
