### ISSUE TITLE
Sickgear won't add show

### ISSUE THREAD

**Issue by nv1804** [SickGear/SickGear#1071]
Hi,

Kindly do not delete this. This is not a how to question. It's an issue

I've been using sickgear for over a year now. I've never had trouble adding or importing any shows so far but now I'm unable to add or import **any** show. I've been updating sickgear in the hope that this will get fixed but is hasn't

Error received: Show in N:\TV Shows\Scandal has no name on TheTVDB, probably the wrong language used to search with.

No matter which show I try to add, I get the same result

Kindly help me out here

**Comment by JackDandy** [comment]
Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

Thanks.

**Comment by JackDandy** [comment]
btw: Rename folder Scandal to `Scandal (2012)` before you try to import. There are many shows named Scandal, I am only guessing because you refuse to give detail needed to reach a good conclusion and now this is wasting time trying to second guess you.
