### ISSUE TITLE
Request: Option to keep original filename in Episode Naming

### ISSUE THREAD

**Issue by thebandit** [SickGear/SickGear#1073]
I like to keep the original file name but it seems like this is not possible with the current Episode Naming patterns. Would it be possible to add a pattern for the original filename, something like %fn maybe?

**Comment by JackDandy** [comment]
A note about [feature requests](https://github.com/SickGear/SickGear/issues/770) :)

Thanks.

**Comment by thebandit** [comment]
Indeed that works, thank you. Didn't think to check if the naming pattern would be applied without the rename episode being checked :/
