### ISSUE TITLE
Where do I get how to help?

### ISSUE THREAD

**Issue by tpitman** [SickGear/SickGear#1076]
I would like to know how to delete an episode and all of its files when I am done watching an episode.

I am sorry about making an issue here, but I just don't know where to ask a question like that.

**Comment by JackDandy** [comment]
Hi @tpitman 

Try Shows/History/Layout/"Watched"

If you need further guidance, you're welcome to come ask in IRC.

**Comment by tpitman** [comment]
As always you are awesome!!!

**Comment by JackDandy** [comment]
@tpitman get yourself a proper IRC client and not a web browser, then IDLE in the IRC until I am around, someone new to SG answered your q (i assume you were tp_) and they don't even know the new features of SG that you asked about - therefore, you were misinformed.
