### ISSUE TITLE
"Change show" when on show details does not work properly

### ISSUE THREAD

**Issue by awenny** [SickGear/SickGear#1078]
#### OS version: Gentoo Linux with Python 2.7.14

Context is "Change show" in show details.

Expectation | Result
------------ | -------------
When on details of any show but last, and I want to jump to the next show by clicking on the right arrow, the next show will be opened. | Reload of the current show, but no jump to the next show.
When on details of the first show, the popup help of "previous show" shows the last show. By clicking on it, jumping to last show. | Reload of the current show, but no jump to the last show.

**Steps to reproduce:**
*1)* On "show list" page open details for any show (not the last one)
*2)* In left upper section ("Change show") click on the right arrow (next show)

**But working on the other hand:**
* On same page jumping to previous show works, except when on the first show.
* Popup help for next show is correct, though.

**Comment by JackDandy** [comment]
The result you describe is not reproducible, the next/previous buttons work as expected.  

Therefore, perhaps a local browser extension is causing this behavior?

Perhaps, javascript is blocked?

Try different browsers.

**Comment by awenny** [comment]
Right, works with Firefox.

But not with Safari on macOS. The "prev" button works, but not "next". That's strange. Also, no plugins are causing it.

**Comment by JackDandy** [comment]
Okay, narrowed it down to an OS specific browser.

If you come to IRC, then maybe we can solve it together, I will need your help as I don't run macOS.

**Comment by JackDandy** [comment]
Fixed: [0.15.3](https://github.com/SickGear/SickGear/releases/tag/release_0.15.3)
