### ISSUE TITLE
Page title after post-processing results missing

### ISSUE THREAD

**Issue by a-camacho** [SickGear/SickGear#1082]
#### Branch version commit hash: c912d03749ff2bc8e476b3eeb67db8a71d50405e

Hi,

**Problem:**
There seems to be no title to the web page after post-processing results on my Synology NAS.

**Expected and result**
I would expect the page title to be "SickGear - Post-processing results" or something similar.
Instead I see "SickGear -"

Thanks a lot !

**Comment by JackDandy** [comment]
Hello,

Yup, the title should indeed be "SickGear - Process Media"

You can check this by doing a view page source in your browser, and looking for tag **title** 6 or so lines from the top.

I would need more information before being able to consider this an issue though.  I would see if you can reproduce this effect again, and the steps to do so.

If you need to, please respond below, 

thanks
