### ISSUE TITLE
ST Search Provider only looking for "x264" results

### ISSUE THREAD

**Issue by funar** [SickGear/SickGear#1086]
#### Branch version commit hash: cc2e1193916220c072272db12c9b320960da18ba

Expectation | Result
------------ | -------------
ST.lol seach provider explicitly searching for "x264" leaving out x265/hevc results. | Search should not be exclusive to x264

**Steps to reproduce:**
*1)* Add ST.lol search provider
*2)* Observe scanning for episodes, with "x264" in search query.

Additional notes:
Used defaults for search provider.
"x264" is hard-coded on line 108 of "sickbeard/providers/skytorrents.py"

**Comment by JackDandy** [comment]
Yes, by design. And only at that provider.

**Comment by JackDandy** [comment]
Added [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.0)
