### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by MeD93** [SickGear/SickGear#1091]
branch master : last commit

Im sorry but your subtitle module download nothing. Only snatch subtitles on tvsubtitles nothing on addicted. I download PSA x265 files and i find subtitle on addicted when i go on the website. Why not in SickGear ?

**Comment by JackDandy** [comment]
Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

Thanks.

**Comment by JackDandy** [comment]
@MeD93 still waiting on your response
