### ISSUE TITLE
New Feature: Archiving

### ISSUE THREAD

**Issue by etetlow** [SickGear/SickGear#1096]
Hi. I was wondering if it's possible to have an archiving feature so that I can archive part of ongoing shows to free up disk space on 'ongoing shows' hdd. I suppose I could switch what I want to move to skipped and move it but it would be nice to know what's been skipped and what's been archived easily on one page. I don't code in python but expect it would be pretty easy to implement. What do you think?

**Comment by JackDandy** [comment]
Hello,

This is already in SG.

Change "Status of removed episodes" to "Set Archived" in settings/Post Processing/File Handling.

Any media file moved away/deleted from the location where SG placed it will be found as removed and acted on.  This happens during the daily Show-update, or you can force using "Re-scan" on display show page. 
You could have the ep auto change status to Skipped - but this is strongly not advised as there are search implications to do with upgrading. "Archived" means the ep is ignored by the search systems.
