### ISSUE TITLE
Cannot import tv shows

### ISSUE THREAD

**Issue by alon24** [SickGear/SickGear#1097]
I am trying to import tv shows from my harddrive (it works in sonar), I running on a windows 10 machine. (so used the installation guide u provided).

Getting this error (below), it seems you do not like UTF8? or hebrew file/dir names?

 HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/home/addShows/massAddTable?rootDir=G%3A%5Ctv', version='HTTP/1.1', remote_ip='127.0.0.1')
 2) Traceback (most recent call last):
 3)   File "C:\SickGear\SickGear\lib\tornado\web.py", line 1543, in _execute
 4)     result = yield result
 5)   File "C:\SickGear\SickGear\lib\tornado\gen.py", line 1133, in run
 6)     value = future.result()
 7)   File "C:\SickGear\SickGear\lib\tornado\concurrent.py", line 261, in result
 8)     raise_exc_info(self._exc_info)
 9)   File "C:\SickGear\SickGear\lib\tornado\gen.py", line 307, in wrapper
10)     result = func(*args, **kwargs)
11)   File "C:\SickGear\SickGear\sickbeard\webserve.py", line 651, in get
12)     result = method(**kwargss)
13)   File "C:\SickGear\SickGear\sickbeard\webserve.py", line 3360, in massAddTable
14)     return t.respond()
15)   File "C:\SickGear\data\cache\cheetah\_SickGear_SickGear_gui_slick_interfaces_default_home_massAddTable_tmpl.py", line 122, in respond
16)     show_id = VFSL([locals()]+SL+[globals(), builtin],"show_id",True) + '|' + VFSL([locals()]+SL+[globals(), builtin],"str",False)(VFSL([locals()]+SL+[globals(), builtin],"curDir",True)['existing_info'][0]) + '|' + VFSL([locals()]+SL+[globals(), builtin],"str",False)(VFSL([locals()]+SL+[globals(), builtin],"curDir",True)['existing_info'][1])
17)   File "C:\python27\lib\encodings\cp1252.py", line 12, in encode
18)     return codecs.charmap_encode(input,errors,encoding_table)
19) UnicodeEncodeError: 'charmap' codec can't encode character u'\u05d2' in position 0: character maps to <undefined>

**Comment by JackDandy** [comment]
No showname and no episode context around this error output,
so i don't know how to trigger this event.

Until there is response on this, it will be marked invalid.

**Comment by JackDandy** [comment]
For anyone else reading this.... (to clear up what is being said here)...

It is well known and made clear in the wiki FAQ that English is the language supported by SickGear.  

Therefore, the error presented in this thread is quite correct and expected. That said, if this user had given the time to present a specific show name, then an exception could have been made and the case investigated. However, that was not the case 24 hrs later, and given that everything works as expected for English, then no further action need be taken here.
