### ISSUE TITLE
Non existent episodes remain after deletion

### ISSUE THREAD

**Issue by RedSparr0w** [SickGear/SickGear#1100]
#### Branch version commit hash: https://github.com/SickGear/SickGear/commit/dd74672f8e7ccc2cc201c28448aea4a48741e6fb

Expectation | Result
------------ | -------------
Non existent episodes would be removed | Non existent episodes remain

**Steps to reproduce:**
*1)* Name file 'Dragon Ball Super S02E27' or similar
*2)* Process Media
*3)* Check 'Dragon Ball Super' TV show listings
*4)* Delete file from drive
*5)* 'Re-Scan' / 'Force Full Update'
*6)* Episodes stay as 'TBA'
![image](https://user-images.githubusercontent.com/7288322/40457812-a38d9b34-5f4c-11e8-9bbb-5344bc7dd642.png)

Additional notes:
Config Settings
![image](https://user-images.githubusercontent.com/7288322/40458065-09b61ea8-5f4e-11e8-894f-ae0eed5062d2.png)
_Most of episodes don't seem to follow `releases for this show are named like ... Show.265 instead of Show.S02E03` except for the season 2 release i downloaded which caused the original problem_

**Comment by JackDandy** [comment]
Sounds like you need to see what you have set for /config/postProcessing/File Handling/Status of removed episodes

**Comment by RedSparr0w** [comment]
I have that set to `Set Ignored (default)`

**Comment by JackDandy** [comment]
Yeah probably not, looks like you forced that episode into your system with an invalid season and ep number from the post process, there is no such ep at tvdb but SG simply respects your wishes. and adds the eps. When you delete it, it is set to TBA. This is a very edge case situation, so much so, I didn't fully understand it on the first read.  If you want those eps removed, then remove and readd the show.

**Comment by RedSparr0w** [comment]
Thought that might be the case, but figured I would check here first if there was a different solution.

Thanks for the help! 😄

**Comment by JackDandy** [comment]
@RedSparr0w

> It has now been removed from the list.

For future reference, which action did you take to achieve this ?

**Comment by RedSparr0w** [comment]
Deleted show from sickgear, then re added the show.

**Comment by KeenIIDX** [comment]
Can we get a more elegant solution to this issue? I’ve got a show that often does specials in addition to regular seasons. The specials will file as TBAs until I go and manually fix them. Having this happen on top of me having to manually fix file names a few times a year sucks.
