### ISSUE TITLE
Add HorribleSubs as a provider

### ISSUE THREAD

**Issue by B0xboi** [SickGear/SickGear#1101]
Hello, I just recently migrated from SickRage and I am enjoying SickGear a lot better. One thing that is troubling is that Nyaa.si can't find some of my animes. If possible could HorribleSubs be added a provider?

Example of Implementation: https://github.com/SickRage/SickRage/blob/72f937b3667166801ff595ea674a7877dd8b67cd/sickbeard/providers/horriblesubs.py

Website: http://horriblesubs.info/
RSS: http://horriblesubs.info/rss.php?res=all

**Comment by JackDandy** [comment]
You can add it like so...

<a name=""><img src="https://vgy.me/FoDq5d.png"></a>

**Comment by B0xboi** [comment]
Thank you!
