### ISSUE TITLE
Provider type

### ISSUE THREAD

**Issue by JackDandy** [SickGear/SickGear#1104]
Hi @mesa57

I was thinking about possibilities with SpotWeb. SickGear enhances support for this above what SickBeard provided and perhaps there could be a way to default the media provider icon to a dedicated spotweb icon to show support for your contribution.  

What do you think?

JD

p.s. I "closed" this issue to have it not display in the main "open issues" view ;-)

**Comment by mesa57** [comment]
I do not know exactly what you mean by priority type ?
But could you open an issue in on https://github.com/spotweb/spotweb/issues  that also fellow developers take a look at it ?
Furtermore : you are invited to do the change you'reself, fork and create a pull request 😉

**Comment by JackDandy** [comment]
> I do not know exactly what you mean by provider type ?

Clarified this in IRC :)

**Comment by JackDandy** [comment]
Hi @mesa57 

The integrated Spotweb support indicator [pull](https://github.com/SickGear/SickGear/pull/1106)

Here's how it looks on the UI...

<a name=""><img src="https://vgy.me/5AT8Uy.png"></a>

Let me know if that's okay with you, and I will then merge.

Again, thanks

p.s. Be great if you could update your readme.md ;-)

**Comment by mesa57** [comment]
Never look at th readme.md so I thought you meant the wiki.
Both are updated now.
Btw. sickbeard/sickrage is vastly used by synology users together with spotweb and/or other indexers.
I am sure they would appreciate if you create/maintain a Sickgear package.

**Comment by JackDandy** [comment]
It's like you and @clinton-hall have the same thinking!

Only this week Clinton kindly offered to make packages for QNAP and Asustor - a blummin' marvelous thing as we have no experience with those devices, only RPi/BPi - which does keep SG in line in terms of low resource consumption. Same goes for Synology and so SG has relied on [this Git](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-Synology) method, which in fairness has worked great, even from 5 to 6, but I would guess only a small number of users know to even look for that :|

**Comment by mesa57** [comment]
That they don't know is correct. Normally they are used to install a package from synoloy or from the synocommunity package server.
They create packages for synology devices as .spk file, a special format or .rar
But they have a funny package "sickbeard custom" where users can specify which fork they want.

**Comment by clinton-hall** [comment]
@JackDandy 
For Asustor (All models)
https://www.dropbox.com/s/sur3ywu5cuw8vz0/sickgear_20180306_any.apk
I will try and get this published to Asustor's App Center shortly (takes some verification time).

For QNAP. I'll need a bit of time to review. Basically there are several versions of Python that can cause issues. I also based by other Sick* packages on my own git package which is very old now. Somewhere along the line I ran out of time and didn't maintain these, so I believe other devs have created newer apps, in multiple stores/forums. 
Once I know what the current working approach is for the Sick* packages, I'll make an equivalent for SickGear.

**Comment by JackDandy** [comment]
@clinton-hall 

 > If you have another preferred port, I can change without too much issue, so long as it is available.

Great, sure, my preferred port is 7081 (if available).

FYI: A site did a [QNAP](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-QNAP) package but it has a pretty glaring issue that I had to address in the install guide.
 
That package omits `git` so systems fail to auto update and also the QNAP users cannot change branches in the SickGear UI .> config/general/adv tab unless they specifically come here to read the wiki and see the "_Post install steps_" text - not ideal.

Thank you.

**Comment by JackDandy** [comment]
@clinton-hall 

 > If you have another preferred port, I can change without too much issue, so long as it is available.

Great, sure, my preferred port is 7081 (if available).

FYI: A site did a [QNAP](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-QNAP) package but it has a pretty glaring issue that I had to address in the install guide.
 
That package omits `git` binary so systems fail to auto update and also the QNAP users cannot change branches in the SickGear UI > config/general/adv tab unless they specifically come here to read the wiki and see the _Post install steps_ text - not ideal.

Thank you for your help.

**Comment by JackDandy** [comment]
@clinton-hall 

Curious, is it a NZ thing to have the day next to the year in a date string as in yyyyddmm, I haven't seen that before, only yyyymmdd or ddmmyyyy (ref: the date in your package name).

**Comment by clinton-hall** [comment]
@JackDandy 
Not an NZ thing at all... In case you missed it, I have somewhat over-committed myself and I put that package together last night after a long day of building my son a new playroom.

In NZ we use dd/mm/yyyy. for the package I use yyyy/mm/dd as that allows the packages to be sorted chronologically.
yyyy/dd/mm is nonsensical and has no practical application.

because I was tired, and because my virtual machine is actually set to American mm/dd/yyyy I just reversed these and didn't actually look at the end result!

I'll update this to be 20180604 tonight, and change the default port to 7081.

**Comment by JackDandy** [comment]
> yyyy/dd/mm is nonsensical and has no practical application.

too funny ^

**Comment by clinton-hall** [comment]
https://www.dropbox.com/s/mt2t9eek9urcnuc/sickgear_20180604_any.apk  (For any Asustor Model)
For anyone wanting to test.
Now uses port 7081

I have submitted to app central, so this should just appear in the Asustor store in due course.

**Comment by JackDandy** [comment]
Hi @clinton-hall 
  
Any chance of an updated [Asustor package](https://www.asustor.com/app_central/app_detail?id=840&type=6&model=). Also, did you ever get around to looking at QNAP.
  
Thank you.

**Comment by JackDandy** [comment]
> It uses git to self update

Great, so the only thing to check, is if the package includes [post install speedups](https://github.com/SickGear/SickGear/wiki/Installation-Instructions#post-install-speedups), and that Cheetah is up to date to release 3.

> QNAP ... as it appears this is available from...

Unfortunately, that build doesn't include git and therefore, won't self-update by default. The user needs to be savvy enough to come to the wiki and follow [theses steps](https://github.com/SickGear/SickGear/wiki/Install-SickGear-[5]-QNAP#post-install-steps).  Furthermore, [post install speedups](https://github.com/SickGear/SickGear/wiki/Installation-Instructions#post-install-speedups) are not included, oh and Cheetah will likely be at v2.

**Comment by clinton-hall** [comment]
looking to add popst install speedups on Ausustor
```
SickGear prestartup checks... (Sat Jan  5 06:51:57 NZDT 2019)
Starting SickGearCloning into '/usr/local/AppCentral/sickgear/SickGear'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 35840 (delta 14), reused 22 (delta 11), pack-reused 35792
Receiving objects: 100% (35840/35840), 36.85 MiB | 1.59 MiB/s, done.
Resolving deltas: 100% (23230/23230), done.
Downloading/unpacking Cheetah3>=3.1.0 (from -r requirements.txt (line 1))
  Downloading Cheetah3-3.1.0.tar.gz (872kB): 872kB downloaded
  Running setup.py egg_info for package Cheetah3

    warning: no previously-included files matching '*' found under directory 'devscripts'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
Installing collected packages: Cheetah3
  Running setup.py install for Cheetah3
    building 'Cheetah._namemapper' extension
    x86_64-asustor-linux-gnu-gcc -fno-strict-aliasing -I/asustor/trunk_2015_08_19/x64_g1/x64_g1/staging/usr/include -I/asustor/trunk_2015_08_19/x64_g1/x64_g1/staging/usr/builtin/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/AppCentral/python/include/python2.7 -c Cheetah/c/_namemapper.c -o build/temp.linux-x86_64-2.7/Cheetah/c/_namemapper.o
    unable to execute 'x86_64-asustor-linux-gnu-gcc': No such file or directory
    One or more C extensions failed to build.
    Details: command 'x86_64-asustor-linux-gnu-gcc' failed with exit status 1
    Retrying without C extensions enabled.
    changing mode of build/scripts-2.7/cheetah-compile from 644 to 755
    changing mode of build/scripts-2.7/cheetah from 644 to 755
    changing mode of build/scripts-2.7/cheetah-analyze from 644 to 755

    warning: no previously-included files matching '*' found under directory 'devscripts'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    changing mode of /usr/local/AppCentral/python/bin/cheetah-analyze to 755
    changing mode of /usr/local/AppCentral/python/bin/cheetah to 755
    changing mode of /usr/local/AppCentral/python/bin/cheetah-compile to 755
    One or more C extensions failed to build.
    Performance enhancements will not be available.
    Pure Python installation succeeded.
  Could not find .egg-info directory in install record for Cheetah3>=3.1.0 (from -r requirements.txt (line 1))
Successfully installed Cheetah3
Cleaning up...
Downloading/unpacking lxml
  Downloading lxml-4.3.0.tar.gz (2.5MB): 2.5MB downloaded
  Running setup.py egg_info for package lxml
    Building lxml version 4.3.0.
    Building without Cython.
    ERROR: /bin/sh: xslt-config: not found

    ** make sure the development packages of libxml2 and libxslt are installed **

    Using build configuration of libxslt

    warning: no previously-included files found matching '*.py'
    warning: no files found matching '*.html' under directory 'doc'
Installing collected packages: lxml
  Running setup.py install for lxml
    Building lxml version 4.3.0.
    Building without Cython.
    ERROR: /bin/sh: xslt-config: not found

    ** make sure the development packages of libxml2 and libxslt are installed **

    Using build configuration of libxslt
    building 'lxml.etree' extension
    x86_64-asustor-linux-gnu-gcc -fno-strict-aliasing -I/asustor/trunk_2015_08_19/x64_g1/x64_g1/staging/usr/include -I/asustor/trunk_2015_08_19/x64_g1/x64_g1/staging/usr/builtin/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/usr/local/AppCentral/python/include/python2.7 -c src/lxml/etree.c -o build/temp.linux-x86_64-2.7/src/lxml/etree.o -w
    unable to execute 'x86_64-asustor-linux-gnu-gcc': No such file or directory
    Compile failed: command 'x86_64-asustor-linux-gnu-gcc' failed with exit status 1
    cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitKR7RC_.c -o tmp/xmlXPathInitKR7RC_.o
    unable to execute 'cc': No such file or directory
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'x86_64-asustor-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/local/bin/python -c "import setuptools;__file__='/tmp/pip_build_root/lxml/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lEwSp2-record/install-record.txt --single-version-externally-managed:
    Building lxml version 4.3.0.

Building without Cython.

ERROR: /bin/sh: xslt-config: not found



** make sure the development packages of libxml2 and libxslt are installed **



Using build configuration of libxslt

running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/lxml

copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/cssselect.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/__init__.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/builder.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/sax.py -> build/lib.linux-x86_64-2.7/lxml

creating build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-2.7/lxml/includes

creating build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/defs.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/clean.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/builder.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-2.7/lxml/html

copying src/lxml/html/diff.py -> build/lib.linux-x86_64-2.7/lxml/html

creating build/lib.linux-x86_64-2.7/lxml/isoschematron

copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-2.7/lxml/isoschematron

copying src/lxml/etree.h -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/etree_api.h -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-2.7/lxml

copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/__init__.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-2.7/lxml/includes

copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-2.7/lxml/includes

creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources

creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng

copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng

creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl

copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl

copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl

creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

running build_ext

building 'lxml.etree' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

creating build/temp.linux-x86_64-2.7/src/lxml

x86_64-asustor-linux-gnu-gcc -fno-strict-aliasing -I/asustor/trunk_2015_08_19/x64_g1/x64_g1/staging/usr/include -I/asustor/trunk_2015_08_19/x64_g1/x64_g1/staging/usr/builtin/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/usr/local/AppCentral/python/include/python2.7 -c src/lxml/etree.c -o build/temp.linux-x86_64-2.7/src/lxml/etree.o -w

unable to execute 'x86_64-asustor-linux-gnu-gcc': No such file or directory

Compile failed: command 'x86_64-asustor-linux-gnu-gcc' failed with exit status 1

creating tmp

cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitKR7RC_.c -o tmp/xmlXPathInitKR7RC_.o

unable to execute 'cc': No such file or directory

*********************************************************************************

Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?

*********************************************************************************

error: command 'x86_64-asustor-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/local/bin/python -c "import setuptools;__file__='/tmp/pip_build_root/lxml/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lEwSp2-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip_build_root/lxml
Storing complete log in /root/.pip/pip.log
Downloading/unpacking regex
  Downloading regex-2018.11.22.tar.gz (648kB): 648kB downloaded
  Running setup.py egg_info for package regex

Installing collected packages: regex
  Running setup.py install for regex
    building '_regex' extension
    x86_64-asustor-linux-gnu-gcc -fno-strict-aliasing -I/asustor/trunk_2015_08_19/x64_g1/x64_g1/staging/usr/include -I/asustor/trunk_2015_08_19/x64_g1/x64_g1/staging/usr/builtin/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/AppCentral/python/include/python2.7 -c regex_2/_regex.c -o build/temp.linux-x86_64-2.7/regex_2/_regex.o
    unable to execute 'x86_64-asustor-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-asustor-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/local/bin/python -c "import setuptools;__file__='/tmp/pip_build_root/regex/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-uxU6OM-record/install-record.txt --single-version-externally-managed:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

copying regex_2/regex.py -> build/lib.linux-x86_64-2.7

copying regex_2/_regex_core.py -> build/lib.linux-x86_64-2.7

copying regex_2/test_regex.py -> build/lib.linux-x86_64-2.7

running build_ext

building '_regex' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/regex_2

x86_64-asustor-linux-gnu-gcc -fno-strict-aliasing -I/asustor/trunk_2015_08_19/x64_g1/x64_g1/staging/usr/include -I/asustor/trunk_2015_08_19/x64_g1/x64_g1/staging/usr/builtin/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/AppCentral/python/include/python2.7 -c regex_2/_regex.c -o build/temp.linux-x86_64-2.7/regex_2/_regex.o

unable to execute 'x86_64-asustor-linux-gnu-gcc': No such file or directory

error: command 'x86_64-asustor-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/local/bin/python -c "import setuptools;__file__='/tmp/pip_build_root/regex/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-uxU6OM-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip_build_root/regex
Storing complete log in /root/.pip/pip.log
Requirement already satisfied (use --upgrade to upgrade): scandir in /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages
Cleaning up...
 Done (Sat Jan  5 06:52:40 NZDT 2019)
```
the main issue being the compiling tools are not available.

I note the QNAP guide makes reference to using the SickGear virtualenv for python and PIP. But I don't have these on Asustor. Am I missing something here?

**Comment by JackDandy** [comment]
I can't say or sure on that platform ofc, however, in my experience with building using SNAP (for Ubuntu et al) i did run across similar issues and needed to ensure libxml2-dev and libxslt1-dev were available.

**Comment by JackDandy** [comment]
Hi @clinton-hall

Was just updating install guides, and saw for a minute that Asustor site was unreachable. So I backed up the install package here for redundancy. In doing so, I checked over the package and found some points for a new build...

Ref: version 20180620

* Fix typo in control.tar -> start-stop.sg s/finaly/finally
* Fix typo in control.tar -> changelog.txt s/relase/release
* Fix typo in control.tar -> changelog.txt s/exisiting/existing
* Update data.tar -> repository/(python|python-32|python-arm|python-arm64)/Cheetah-2.4.4 to Cheetah-3.x.x
* Update data.tar -> repository/(bin|bin-32|bin-arm|bin-arm64)/unrar to 5.7.1

the other couple of bundled Python packages will also have updates available since your last build. 

Thanks as usual.

**Comment by clinton-hall** [comment]
Hi @ JackDandy

It looks like I had corrected the typos when I was looking at a rebuild to include the speedup installs.... but I never released this as I had some missing libs that require cross-compiling.

I am wondering if I should actually look at updating the App to use a docker environment where we can actually build etc?.. I'll have to check what Asustor models support Docker...

**Comment by jackooooo** [comment]
> @clinton-hall
> 
> > If you have another preferred port, I can change without too much issue, so long as it is available.
> 
> Great, sure, my preferred port is 7081 (if available).
> 
> FYI: A site did a [QNAP](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-QNAP) package but it has a pretty glaring issue that I had to address in the install guide.
> 
> That package omits `git` binary so systems fail to auto update and also the QNAP users cannot change branches in the SickGear UI > config/general/adv tab unless they specifically come here to read the wiki and see the _Post install steps_ text - not ideal.
> 
> Thank you for your help.

Getting an error following your instructions on https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-QNAP

"git clone git@github.com:SickGear/SickGear.git
Cloning into 'SickGear'...
The authenticity of host 'github.com (52.64.108.95)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,52.64.108.95' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

Any hints?
