### ISSUE TITLE
^ ... (cannot add, this location is in use)

### ISSUE THREAD

**Issue by gassorr** [SickGear/SickGear#1105]
BRANCH: master / COMMIT: ee04580da3bef090a7761a0627b56a8f1381f7c5

Expectation | Result
------------ | -------------
Add existing show | Can't add

**Steps to reproduce:**
*1)* Search for show
*2)* Try to add
*3)* Last step won't continue because:
![no-add](https://user-images.githubusercontent.com/3463400/40874007-4279fb10-666a-11e8-88cd-6df5ce623e4d.png)

I remember in previous versions I could select the show in the row and add it anyways, but all I can do is `redo search`

So currently the only way to add an existing show is to rename the show folder, then add it, and copy the files to the created folder. I should be able to add a folder instead?

I don't understand why it should matter if the folder exists, because it doesn't exist in sickgear yet..

**Comment by JackDandy** [comment]
Hi @gassorr 

You will find the folder exists in /media/... -- delete or move it - and you will be fine. 
It is there to prevents catastrophic error in another use case. 

Thanks
