### ISSUE TITLE
SickGear Updater Error

### ISSUE THREAD

**Issue by tpitman** [SickGear/SickGear#1112]
#### Branch version commit hash: (See the About page)
master
7a85df2d0e97ada6c718396fbd3e20fd807cef5b

Expectation | Result
SickGear Updater to update watched files so they can be deleted from the history page | When a video is marked as watched the SickGear Updater toast appears saying it is updating and the the icon turns red and an error says: Failed to contact SickGear on port 8081 at 127.0.0.1

**Steps to reproduce:**
*1)* Install SickGear for Kodi
*2)* Mark a show as watched
*3)* Notice the error message
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
This has been working fine for several months. Nothing has changed that I know of. I have updated SickGear and the SickGear Updater.

I have tried browsing to localhost:8081 on the same computer as SickGear using a browser and the UI comes up fine.

Please advise how to diagnose and help you help me figure out how to fix this.

Thank you for all that you do!

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
Hello, This is not an issue/bug. For user support, please use IRC.
