### ISSUE TITLE
Torrentday provider trying to reach wrong URL

### ISSUE THREAD

**Issue by isabellaalstrom** [SickGear/SickGear#1114]
#### Branch: Master

When using the Torrentday provider it tells me to to get user info from https://torrentday.eu but when it tries to download something it acctually acccess http://td.read-books.org/ which is currently not working. Wouldnt it be better if it acctually accessed the url that it tells me to take the user info from?

**Comment by JackDandy** [comment]
It is designed to do exactly that, but i guess, given that url is down, that it has broken down. Please come to IRC and i will explain how to get back up. Or you can enable multiple providers and another will be used anyway, as there is a rewrite in this are anyway.

Thanks

**Comment by JackDandy** [comment]
Edit: On testing, actually the logic is fine. TD have stopped all their backup URLS, maybe they haven't renewed the domains.

**Comment by JackDandy** [comment]
URLs [Changed](https://github.com/SickGear/SickGear/releases/tag/release_0.16.21)
