### ISSUE TITLE
Skipping file with 2 or more dash'es (-) after episode number

### ISSUE THREAD

**Issue by esp123** [SickGear/SickGear#1116]
BRANCH: master / COMMIT: cca7c32a8a705ee84ae330cce0ca723252c8fdf3

Expectation | Result
------------ | -------------
For specials s00 (Season 00) files, when doing a "rescan", it appears to skip or ignore filenames containing more than one dash as part of the file description text (after the Season+Episode numbers) instead of capturing the correct season/Episode.  | eg filename "My Season - s01e01 - First - Season" isn't recognized, however "My Season - s01e01 - First Season" is.

**Steps to reproduce:**
*1) Ensure your filename has more than 2 dash's (-) after the Season+Episode numbers - <Description Text without numbers> - <info text without numbers>
*2) In Sickgear, do a "re-Scan"
*3) Check if it picked up the episode in the list

...
Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags
N/A

Additional notes:
Usually specials contain a dash (-) as a replacement to a colon (:) since colons are non-usable characters in filenames. Just prior to the last dash (-) of a filename not containing a number. There were no errors Log entries and no (normal) Log entries for this issue found.

**Comment by JackDandy** [comment]
Ahh, there are no known standards for naming specials like those that exist are for non-specials, so spending time to try and fix the vast number of human thought-up naming can quickly become a futile exercise. Therefore, this will not be looked at. Simply rename the file, remove the crap and you will be good.

**Comment by JackDandy** [comment]
[Fixed](https://github.com/SickGear/SickGear/releases/tag/release_0.16.23)
