### ISSUE TITLE
Manual rename and modified file date not changing dates (on 'modified filedate' working system)

### ISSUE THREAD

**Issue by esp123** [SickGear/SickGear#1117]
BRANCH: master / COMMIT: cca7c32a8a705ee84ae330cce0ca723252c8fdf3
--

#### Branch version commit hash: (See the About page)

Expectation | Result
------------ | -------------
Not sure if this is a bug or a lacking feature (feature is already there), however when renaming episodes using "Media Renamer", the file dates do not seem to adjust to the "last modified filedate to the date that the episode aired" despite otherwise working when auto claimed/moved.  | Pressing "Media Renamer" in a series, the files rename ok, but the dates do not. Automated file moves update the file date ok otherwise.

**Steps to reproduce:**
*1)* Ensure Settings-> Post Processing - File Handling - "Change filedate" tickbox is *enabled* for "set last modified filedate to the date that the episode aired"
*2)* Select a Series
*3)* Press top right button  "Media Renamer"
*4)* Press button "Select All Episodes"
*5)* Press (green) button "Rename Selected"
*6)* Check filename dates on drive
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
Use only on systems that adjust the last modified filedate, when auto-moving the files(s)

![image](https://user-images.githubusercontent.com/41772110/44304604-9a615e00-a39f-11e8-89a3-dd5eb2363055.png)

**Comment by JackDandy** [comment]
This is behaving as designed, it's not a bug or lacking feature.
The file date is adjusted during the show-update and media process tasks.

**Comment by JackDandy** [comment]
"File Handling" groups relate functions. Manual "Rename" is specifically that, nothing else.
A "Re-scan" action calls the change file dates during its processing.

**Comment by esp123** [comment]
Fair enough, except thats not what "Scan" means - Def:
scan (skăn)►
v.	To examine closely.
v.	To look over quickly and systematically: _scanning the horizon for signs of land_.
v.	To look over or leaf through hastily: _scanned the newspaper while eating breakfast_.

FYI - There is no "Modify" in the definition of "Scan", and by "Modifying" the dates of the files, this is technically NOT a scan.

**Comment by JackDandy** [comment]
The button text "Re-scan" is a legacy from SickBeard kept for a familiarity with migrating users. However, if there is a better word, then suggestions are welcome.
