### ISSUE TITLE
Overnight I went from "updated" to Sickgear saying I was 63 updates behind (since 4/26/18)

### ISSUE THREAD

**Issue by janngobble** [SickGear/SickGear#1119]
#### Branch version commit hash: 8eb7b710a3bc603caa305561712fba811190bc98

Expectation | Result
------------ | -------------
I expected update would happen | error: Your local changes to the following files would be overwritten by merge:
Updating 8eb7b710..790e4e24
2018-08-25 11:02:04 ERROR    TORNADO :: git pull -f origin master returned : From https://github.com/SickGear/SickGear
 * branch              master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
        autoProcessTV/onTxComplete.bat
        gui/slick/css/dark.css
        gui/slick/css/light.css
        gui/slick/css/style.css
        gui/slick/interfaces/default/config.tmpl
        gui/slick/interfaces/default/config_notifications.tmpl
        gui/slick/interfaces/default/config_providers.tmpl
        gui/slick/interfaces/default/displayShow.tmpl
        gui/slick/interfaces/default/editShow.tmpl
        gui/slick/interfaces/default/history.tmpl
        gui/slick/interfaces/default/inc_addShowOptions.tmpl
        gui/slick/interfaces/default/manage_massEdit.tmpl
        gui/slick/js/configNotifications.js
        gui/slick/js/history.js
        gui/slick/js/inc_top.js
        lib/cfscrape.py
        lib/tornado/ioloop.py
        lib/tornado/web.py
        lib/tornado/websocket.py
        sickbeard/webapi.py
        tests/common_tests.py
Please commit your changes or stash them before you merge.
Aborting

**Steps to reproduce:**
*1)* Click "Update Now"

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
This is the link it tells me I'm behind from: 
https://github.com/SickGear/SickGear/compare/8eb7b710a3bc603caa305561712fba811190bc98...790e4e24e99f87b6cb848eb94677e2cbca9846a9

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
Strange, ok this should fix you up [here](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#fetch_head-error)

**Comment by janngobble** [comment]
Did this:

git stash
git stash drop
git pull


fixed..thanks!

**Comment by JackDandy** [comment]
Great.

So, there was an update to master that brings in the development work over the last few months, the upgrade process was tested as usual, but that error is though those named files have been changed and are no longer recognised by the git update tool, strange, but yeah, the fix was to reset those files, you should be updated now ;)

**Comment by janngobble** [comment]
Good. I thought my backup process on the server last night was somehow responsible for corrupting some files.
Glad I was wrong.
