### ISSUE TITLE
Not recognizing Filenames/extensons correctly

### ISSUE THREAD

**Issue by esp123** [SickGear/SickGear#1120]
**BRANCH**: master / COMMIT: 790e4e24e99f87b6cb848eb94677e2cbca9846a9

Expectation | Result
------------ | -------------
When doing a re-scan or adding a series, if a file is in folder name Specials 0 and contains a period (.) prior to the extension period (eg prior to .mkv), SickGear does not recognize the filename at all (I presume because it assumes the .???* text after first period is the extension name rather than .???$\|.????$ presuming $ is the end of filename/line/text, and if not recognized as a valid extension, it'll skip the file. | 
When a file in folder named Season 0, file should still be identified even it it has a . (period) in the name before the extension period.

**Steps to reproduce:**
*1)* find a series which as a . period in the filename (there are many, go check tvdb)
*2)* Place the file in folder "Season 0" in the relevant series folder
*3)* add or re-scan the series (ensure the file is not already listed in SickGear)
*4)* try to locate the filename in SickGear
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags
n/a - does not show up in the logs

**Additional notes:**
Tested on several files in folder named "Season 0", eg "South Park - Specials" episode "_Season 0/South Park - s00e03 - The Spirit Of Christmas (Jesus vs. Santa).mkv_" which is listed as the same filename as per tvdb/Sickgear listing (ie "South Park - s00e03 - The Spirit Of Christmas (Jesus vs. Santa)")

Tested in "**Season 0**" folder:
"_South Park - s00e03 - The Spirit Of Christmas (Jesus vs Santa).mkv_" WORKS, 
"_South Park - s00e03 - The Spirit Of Christmas (Jesus vs. Santa).mkv_" does NOT work (but should work, as its the valid listing name)

When already in the correct folder name, eg "**Season 00**", it works ok regardless of filename.

**Comment by esp123** [comment]
It appears to work ok when the filename is already in the Sick Gear recognized folder (ie Season 00). It fails with in folder named "Season 0".

**Comment by JackDandy** [comment]
The episode status was Skipped, the file moved into the **Season 0** folder, clicked [rescan], file is found. Proof that the file "_South Park - s00e03 - The Spirit Of Christmas (Jesus vs. Santa).mkv_" is recognized...
<img src="https://vgy.me/iyS7wX.png">
When hovering over ep number, the file path appears in the tooltip given that the file is found.
