### ISSUE TITLE
Pokémon entry?

### ISSUE THREAD

**Issue by esp123** [SickGear/SickGear#1125]
BRANCH: master / COMMIT: 0b2b3f35df808efc513a172c970ec442f9d2d973

Expectation | Result
------------ | -------------
When adding Pokémon and enabling "Show is anime", the episode numbers are messed up (duplicate 0's, etc.) Season 16-17 appear to have wrong (0) numbering. Season 18+ seem ok. Also, when adding this TV series as a "find episodes numbered by release groups instead of the TV network (scene/manual numbers available)", again the numbers appears to be messed up (season 16 & 17 show all episodes as 942). I am not familiar how the scene numbering is sourced (external source could be incorrect), but the Anime episode listing shouldn't all 0 for Season 16-17, then 962, 963, etc. for season 18+ (unless the "scene" never released episodes 16-17, which would be strange as they are available). | When selecting ".releases for this show are named like ... Show.265 instead of Show.S02E03" it should list the episodes in correct number sequence.

**Steps to reproduce:**
*1)* Add Pokémon as a "Show is anime" entry
*2)* Check the episode numbering XXXX from episode 16 & 17.
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
If i understand you correctly, the 0x0 simply mean there is no special numbering for that ep. Also, you can click on any ep number and change it if reqd.

**Comment by JackDandy** [comment]
Erm, all links for a show are in the shows info area in the upper right of its displayshow page, there you will see tvdb and thexem (if appropriate).

**Comment by esp123** [comment]
there is nothing wrong with the external (scene) sources - this appears to be a SG issue.

http://thexem.de/xem/show/4327 matches correctly and sequentially with thetvdb info

**Comment by JackDandy** [comment]
As I said, this topic is now a conversation, and here is not the place for that, please come to IRC to discuss.

**Comment by JackDandy** [comment]
[Fixed](https://github.com/SickGear/SickGear/releases/tag/release_0.17.5)
