### ISSUE TITLE
Using Folder Name rather than filename for recognition

### ISSUE THREAD

**Issue by esp123** [SickGear/SickGear#1126]
#### Branch version commit hash: (See the About page)

Expectation | Result
------------ | -------------
See logs below - it appears SG is renaming filenames based on sub-folder names | Folder names should be ignored since files can be scatted anywhere within the main folder. If a filename CANNOT be matched, it should be left alone not randomly renamed as per below.

**Steps to reproduce:**
*1)* Step to take
*2)* Step to take
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags
2018-09-07 18:07:28 DEBUG    TORNADO :: formatting pattern: Season %0S -> Season 11
_**2018-09-07 18:07:28 DEBUG    TORNADO :: Renaming/moving episode from the base path /media/Private/Videos/Series/Doctor Who (1963-1989)/Season 11/Doctor Who - S11E02 (071) - Invasion of the Dinosaurs - Parts 1-6/Doctor Who - Bonus - Invasion of the Dinosaurs (BW).avi to /media/Private/Videos/Series/Doctor Who (1963-1989)/Season 11/Doctor Who - s11e02 - The Time Warrior (2)**_
**2018-09-07 18:07:28 DEBUG    TORNADO :: Files associated to /media/Private/Videos/Series/Doctor Who (1963-1989)/Season 11/Doctor Who - S11E02 (071) - Invasion of the Dinosaurs - Parts 1-6/Doctor Who - Bonus - Invasion of the Dinosaurs (BW).avi: []**
**2018-09-07 18:07:28 INFO     TORNADO :: Renaming file from /media/Private/Videos/Series/Doctor Who (1963-1989)/Season 11/Doctor Who - S11E02 (071) - Invasion of the Dinosaurs - Parts 1-6/Doctor Who - Bonus - Invasion of the Dinosaurs (BW).avi to /media/Private/Videos/Series/Doctor Who (1963-1989)/Season 11/Doctor Who - s11e02 - The Time Warrior (2).avi**
2018-09-07 18:07:28 INFO     TORNADO :: Trying to clean any empty folders under /media/Private/Videos/Series/Doctor Who (1963-1989)/Season 11/Doctor Who - S11E02 (071) - Invasion of the Dinosaurs - Parts 1-6
2018-09-07 18:07:28 INFO     TORNADO :: Deleting empty folder: /media/Private/Videos/Series/Doctor Who (1963-1989)/Season 11/Doctor Who - S11E02 (071) - Invasion of the Dinosaurs - Parts 1-6
2018-09-07 18:07:28 DEBUG    TORNADO :: Setter sets location to /media/Private/Videos/Series/Doctor Who (1963-1989)/Season 11/Doctor Who - s11e02 - The Time Warrior (2).avi
2018-09-07 18:07:28 DEBUG    TORNADO :: Transaction with 1 queries executed affected 1 row
2018-09-07 18:07:28 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? AND 5=5 with args ['76107', '11', '1']

Additional notes:
really? WTF? 

There were many files in that sub-folder, why did it pick that file and rename it incorrectly? (it doesn't even conform to any known naming conventions, as such it should have been skipped - its a custom BONUS video, not in any TVDB, etc source listing).

2018-09-07 18:07:28 INFO     TORNADO :: Renaming file from /media/Private/Videos/Series/Doctor Who (1963-1989)/Season 11/Doctor Who - S11E02 (071) - Invasion of the Dinosaurs - Parts 1-6/Doctor Who - Bonus - Invasion of the Dinosaurs (BW).avi to /media/Private/Videos/Series/Doctor Who (1963-1989)/Season 11/Doctor Who - s11e02 - The Time Warrior (2).avi

**Comment by JackDandy** [comment]
Sorry, I don't understand the issue.

**Comment by esp123** [comment]
SG renamed the file called "_Doctor Who - Bonus - Invasion of the Dinosaurs (BW).avi_" to "_Doctor Who - s11e02 - The Time Warrior (2).avi_".  It shouldn't have renamed it at all, as it does not even match,

**Comment by JackDandy** [comment]
And what steps did you do take to observe this ?

**Comment by JackDandy** [comment]
As that video file is a bonus video, you need to do [this](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#extras)

**Comment by esp123** [comment]
There was a scene release package which had a bunch of bonus videos and properly named episode series with a subfolder. 4 episodes with 1 bonus vid. SG renamed one of the Bonus video and moved it as above  and left the actual episode alone.

If SG uses folder names to rename a file, it had better be sure there is only 1 video file in that folder before renaming, other wise how does it know which one to rename? SG should leave disputed filenames alone instead of marking its own shit up.

**Comment by JackDandy** [comment]
No, your suggestion will break other situations that SG handles, for example, the folder name is used to determine the release where releases have obfuscated filenames. This is only **one** highlighted case, I won't go into the many others.

Further, the release you talk is not actually a _scene_ release, and this is key because if it was, then this issue would not present as the files would not be ordered in such a way that causes issue with automation, I can confirm from the filename that it is not following scene release rules, the publicly available rules that SG follows in order to keep integrity of renaming.

I understand what you are saying and what you observe, but I cannot see a way for SG to handle this edge case (categorized "edge" because it does not comply with scene naming rules).

**Comment by JackDandy** [comment]
> Perhaps consider renaming the file if there is only 1 vid in the folder.

No, that wont work, there are releases, for example, from RARBG, that contain at least 2 videos. SG renaming has evolved from reports of nuances over many years, and consolidates issues at both p2p and usenet networks, therefore, what you consider trivial is not. Yes, you can create a grabber yourself, and then you will appreciate what I have been saying, especially if/when you experience the variations in releases over what is now 8 years of collected info.

**Comment by esp123** [comment]
Well, thanks for the info. Its not automated proof - I don't monitor the seedbox myself, I just get the complaints. If SG was properly developed using Agile or similar, it would have been with the above framework for indisputable SG renames Vs User/Disputable renames (or an editable config to cater). The rest is just opinion, and standards change over time. Thanks again and good luck! :)

**Comment by JackDandy** [comment]
Nothing is automated proof. You found a release that is named poorly. I have had the same issue myself, and in those rare cases, it's a minor pain but as I have said, these are manually managed in a trivial way. However, we have people using SG without such issues across both usenet and p2p - for years, those users understand that not every edge case can be picked up. Good luck whatever you decide, the other issue you raised took a bit of effort, shame you won't get to appreciate that but thanks anyway for your feedback and yeah, good luck to you too.
