### ISSUE TITLE
wanted quality is HD, but search ignoring 1080p WEB-DL

### ISSUE THREAD

**Issue by yhager** [SickGear/SickGear#1127]
#### Branch version commit hash: 762ba5c7e8fca7636cd6ce0c0b30caffc2286444

I hope I understand the qualities correctly. AFAICT, HD includes 1080p WEB-DL and 720p WEB-DL (verified by clicking 'Custom', and it was selected. Also tried the 'Custom' settings). 

Expectation | Result
------------ | -------------
Quality to download is HD. An episode is found that is marked 1080p WEB-DL. I expect it to download it. | I see in the log: Ignoring result ... because we don't want an episode that is 1080p WEB-DL

**Steps to reproduce:**
*1)* Edit show, mark quality to download HD
*2)* Run a search
*3)* If a result with quality 1080p or 720p WEB-DL exists, I expect it to be snatched.

Quite a few examples: https://gist.github.com/yhager/6552d8d8764bdf58fff7486dadc57ac5

Additional notes:
Seems pretty straight forward to me, but I can't figure out why these files are ignored. Let me know if there's anything else you need to figure this out.

**Comment by JackDandy** [comment]
Sounds like you set your custom quals incorrect, where you have your "Wanted quality" as something that is not found and then the  HD is in the bottom list, which can never be reached until the Wanted is met.

**Comment by yhager** [comment]
I have ignored words: core2hd, hevc, mrlss, reenc, x265, danish, deutsch, dutch, flemish, french, german, italian, nordic, norwegian, portuguese, spanish, swedish, turkish, vp9, av1.
there are no custom ignores for the show.
I have used the default HD. I also tried switching to custom, but without changing anything, so clicking save brings it back to HD, which makes sense. In any case, HD is on the top list.

**Comment by yhager** [comment]
Maybe this only happens after a failed download. My screenshot will look the same, only the snatched one was bad, and thus a new search was triggered, but there are some results who are *not* in the failed download db, and are not being selected even though quality matches. I'm on IRC now for the next few hours, with the same nickname as here.

**Comment by JackDandy** [comment]
Update; as you know, we could not replicate your issue via IRC, however, we didn't consider it invalid either. We found a number of issues with the manual search button that provoked rewriting the thread controlling logic, this overhaul is now merged to develop.

**Comment by yhager** [comment]
Whoa! I didn't realize that could trigger something like a rewrite. Thank you very much!
