### ISSUE TITLE
Infinity unpack problem

### ISSUE THREAD

**Issue by tadejp** [SickGear/SickGear#1128]
#### OS: slackware current

Expectation | Result
------------ | -------------
Archived tv shows should be unpacked once | everytime when post processor is running in the background, archives are unpacked, even though unpacked file exists already (as symbolic link though, maybe that's the problem)

**Steps to reproduce:**
*1)* Have any tv show packed in archive (.rar in my case) downloaded
*2)* Settings -> Post processing -> Post processing -> Process episode method -> Symbolic link
*3)* Settings -> Post processing -> File handling -> Unpack downloads [checked]

Additional notes:
- This is quite problematic, because if I don't have auto unpack enabled, I must do it manually each time, and if I do have it enabled, HDD is unpacking .rar's every 30 minutes in my case (default setting).

**Comment by JackDandy** [comment]
Hi,

Are you using Symbolic link for complete/seeding torrents?

If not, then use Process episode method -> "Move" instead of Symbolic link.

If yes, then I wrote a one file script solution that is waiting to be ported to Linux.

**Comment by tadejp** [comment]
For seeding of course, your fix would be much appreciated! thanks

**Comment by JackDandy** [comment]
Sure, come to IRC.
