### ISSUE TITLE
direct references to TORRENT_LABEL do not see updates after initial startup + usage

### ISSUE THREAD

**Issue by lps-rocks** [SickGear/SickGear#1139]
#### Branch version commit hash: (See the About page)f92bc48292c6c5a67e0d29056c75994dbb4ccaff

Expectation | Result
------------ | -------------
Label will be applied to torrent | Label is not applied to torrent until restart of SickGear

**Steps to reproduce:**
*1) Fresh install of SickGear
*2) Enable 'enable torrent media providers', select rtorrent, configure location, leave 'Label' field blank. Test + Save configuration.
*3) Edit Label field. Save configuration. 
*4) Label will not be applied until sickgear is restarted.
...

Additional notes:
Looks like this may be an issue with how the rTorrent client library references TORRENT_LABEL which differs from the other libraries which use it as sickbeard.TORRENT_LABEL. Since TORRENT_LABEL is an immutable type (str) direct imports of it will not reference the same assignment as sickbeard.TORRENT_LABEL. So on initial import (after a restart) it will get the correct value but any changes while running will not propagate to direct references. global also doesn't cover this since GLOBAL refers to within a module. Since these are being imported as immutable types outside of the source module, they aren't governed by that statement either.

Solution is to change all imports and references to point to import sickbeard and use sickbeard.TORRENT_LABEL

Thanks!

**Comment by JackDandy** [comment]
Hi,

The label is passed to the api library [here](https://github.com/SickGear/SickGear/blob/master/sickbeard/clients/rtorrent.py#L59-L62), and is used in the library [here](https://github.com/SickGear/SickGear/blob/master/lib/rtorrent/torrent.py#L312-L329).

I cannot see anything wrong there. However, I don't use rTorrent, so if you want to propose a code solution then great, in the absence of that, I will probably simply add text to the UI to warn users to restart SG if they change the label.

Thanks for your help.

**Comment by JackDandy** [comment]
Nevermind, Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.17.14)
