### ISSUE TITLE
DownloadStation: Unable to send Torrent: Return code undefined (already exists in client?)

### ISSUE THREAD

**Issue by blt78** [SickGear/SickGear#1140]
BRANCH: master 
COMMIT: 3b2a5ebc61c20236c81a5fec85b84523890ca6fc

Expectation | Result
------------ | -------------
Sickgear on my Synology (last DSM 6 release) cannot submit new downloads to Download Station. 
I always end up with the message : 
**DownloadStation: Unable to send Torrent: Return code undefined (already exists in client?)**
though the Connection test is OK and the file was never downloaded

[sickgear.log](https://github.com/SickGear/SickGear/files/2585318/sickgear.log)

**Comment by JackDandy** [comment]
Ah, this issue is known but no way currently to test how to fix.

Please switch to Transmission client.

**Comment by JackDandy** [comment]
I wonder what happened next on this one :)

**Comment by blt78** [comment]
Sorry, I was o little busy. 
No problem with my username and pwd. 
I have been using using it with Sonnarr without any problem.
Just switched to Transmisission ...

**Comment by JackDandy** [comment]
Alternatively, create a "watch" folder and send .torrent files to that folder by setting the "Blackhole" folder in SG's search settings to the "watch" folder. You can set the "watch" folder in settings/location in DS.

**Comment by blt78** [comment]
Thank you but I'm used (and found of) of Transmission now

Kind regards.

**Comment by JackDandy** [comment]
You're welcome, it makes a good tip for other readers too.

**Comment by JackDandy** [comment]
You're welcome, it makes a good tip for other readers too (that use the git webUI not email) .
