### ISSUE TITLE
Feature request: (season) Update after final episode

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#1142]
Latest dev. auto update

Hey JackDandy (most likely),

Tiny request, can we get a box to check or uncheck for season processed notifications?
E.g. A season is finished, process runs, Ep 1 finished send message to .., Ep 2, finished send message to... etc.
This works great on Syn's but on things like raspberries it's a huge problem when Kodi is linked with trakt as well, even if it isn't it can cause huge hangs and even crashes on most SoC's that don't have enough power.

So my request is a checkbox, if checked instead of

Ep 1 complete send update request to ....Kodi IP
Ep 2 complete send update request to.... Kodi IP
etc.

Let the checkbox mark "only send update after final episode (seasons)" and go like this

Ep 1 Complete... queued for update
Ep 2 Complete....queued for update
...
Ep 10 complete send update request to....Kodi IP
Post Process completed successfully. 

for an update of the Kodi library.
That way low powered SoC's don't get 10 or 20 requests after PP but it still updates the library and things like trakt correctly.

Thanks!

**Comment by JackDandy** [comment]
Just checking, this would work as an extra checkbox on the manual media processing page, right ?

**Comment by Th3MadHatter** [comment]
Ty, and i know  we didn't  end things well  last time but no hard feelings from my end, hope you feel the same way.

Cheers

**Comment by JackDandy** [comment]
Take a look at this [idea](https://gist.github.com/JackDandy/79bf8fd283100130edd5ca41a2c8719d), leave comment there.

**Comment by Th3MadHatter** [comment]
Sorry I didn't get that message until now.

It would be a great option in the manual PP window but also as a general option, if, for example, a season with 20 episodes is finished and it automatically PP's it sends 

Episode 1 done Updating Library, which starts updating Trakt right after
Episode 2 done Updating Library, which starts another Trakt update.
and so on.

So you can guarantee a crash on low power systems by the time it hits episode 8 or 9, even though I have seen rare (very rare) cases where it didn't completely freeze up on a Vero, but even on that it has a really hard time.

The only way to get rid of the issue right now is to turn off library syncs with Trakt and manually run them, which defeats the point of automatic syncing,

If it simply has an option for SG to see that it is a Season then Ask if you want a library update on episode or on season and then update accordingly which would process everything and then trigger "Some Show Season X Finished" or even just the final episode it would first run a full library update and then trigger trakt so everything would be neatly organized at the end.

**Comment by JackDandy** [comment]
please see this post and comment on that idea over there so that i know you have seen it - i will delete this message in 8 hours if you do not reply... https://gist.github.com/JackDandy/79bf8fd283100130edd5ca41a2c8719d

**Comment by Th3MadHatter** [comment]
I'm right here while you're editing i was reading it.

**Comment by JackDandy** [comment]
no worries, talk on the gist that i posted

**Comment by JackDandy** [comment]
Added [here](https://github.com/SickGear/SickGear/releases/tag/release_0.18.2)

**Comment by Th3MadHatter** [comment]
Awesome @JackDandy Thanks :)
