### ISSUE TITLE
Issue with NZBgeek (options duplicated)

### ISSUE THREAD

**Issue by illusiveman42** [SickGear/SickGear#1143]
#### Branch version commit hash: 2a781a0356e952c3e25890286aade058083bd0c1

I have an issue when adding NZBgeek to SickGear. Basically most of the options on `Settings->Media Providers->Options` are duplicated.

<img width="982" alt="screenshot 2018-11-30 at 12 30 13" src="https://user-images.githubusercontent.com/45486539/49286855-b646c680-f49b-11e8-9159-8a8196b4ca40.png">

Also notice that "...or contain" is `[","]`. I did not add that myself, but is automatically added whenever I saving the settings. This leads me to believe this could be template issue where something is not closed of escaped properly.

This is how the relevant setting is saved in `config.ini`

```
[NZBGEEK]
nzbgeek = 1
nzbgeek_scene_only = 1
nzbgeek_scene_rej_nuked = 1
nzbgeek_scene_nuked_active = 1
nzbgeek_scene_or_contain = "['', '']"
```

I have three other nzb providers that work and display properly. Just NZBgeek is having this issue.

Also, on `History`, every snatch from NZBgeek is shown with "Missing provider", while it works fine for other providers.

**Comment by JackDandy** [comment]
If you remove the "added" provider and use the built in one instead, is it all good (should be).

**Comment by illusiveman42** [comment]
Yes, that was it. Thank you. 

Things got a little messed up when I migrated from SickRage, so I just wiped my providers from config.ini and redid them.
