### ISSUE TITLE
Clear version view (newbie enhancement)

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#1145]
Hey @JackDandy  I can fill out the entire form but it's a newbie thing that might help you in the future since you often label things as "added v18.x" I never noticed it because I check commits instead of versions but the Version tab doesn't actually show the version!

Version: 	BRANCH: master / COMMIT: 631922a129bde5e66acd1742aa92cc1811eeb143
This is BETA software

See? No notice of 18..x here

It might be easy to add a small version file or even a text edit of "Sickgear vX.X,X - site you are on" that gets called every time the configuration menu is opened or even just the hosts site is opened, it's not a huge improvement or even necessary in my opinion but since you mention things like "fixed in version x.x.x" and I don't see it right away there might have been in the past, or will be in the future, people that ask, but what version am I on? Which makes you have to explain things that aren't useful.

Cheers and thanks for my last commit request.

**Comment by JackDandy** [comment]
@Th3MadHatter @anoma 

Addressed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.18.4)
