### ISSUE TITLE
Snap doesn't run on Ubuntu 16.04.5 LTS

### ISSUE THREAD

**Issue by Lukewh** [SickGear/SickGear#1146]
#### Branch version commit hash: 0.18.4

Expectation | Result
------------ | -------------
The snap to run | The snap doesn't run

**Steps to reproduce:**
*1)* Using Ubuntu 16.04.5 LTS
*2)* `sudo apt install snapd`
*3)* `sudo snap install sickgear`
*4)* `sickgear`

```
Data directory: /snap/sickgear/199/opt/sickgear/data must be writable (write permissions). Exiting.
```

Additional notes:
This is with default config etc.

**Comment by JackDandy** [comment]
try...

> sudo chown user1 -R /snap/sickgear/199/opt/sickgear/data

where user1 is the user you run under... does that work?
maybe you can help fix the snap file ;)

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.18.5).

**Comment by JackDandy** [comment]
@Lukewh since yesterday, nothing changed in SG, in the the GH settings i added the new webhook url as instructed. However, all builds manual or whatever are status "_**Built, failed to release**_" with no log as to why they won't release, therefore i can only assume internal issue with changes in snap build system :(

**Comment by Lukewh** [comment]
Hi @JackDandy if you go to https://dashboard.snapcraft.io/snaps/sickgear/revisions/803/ and scroll to the bottom you can see "Task 662dfd4f-5435-49b5-bf3a-9e600211be8b is waiting for execution." I don't have access, but you might be able to cancel that revision to force the others through. If that doesn't work I'll see who I can poke on my end to get things moving. Sorry for the issue!

**Comment by JackDandy** [comment]
Hi @Lukewh That put me on the right path, phew! Thank you :)
