### ISSUE TITLE
Pulls from TheTVDB for series not showing "specials" (series 350135)

### ISSUE THREAD

**Issue by janngobble** [SickGear/SickGear#1147]
#### Branch version commit hash: 631922a129bde5e66acd1742aa92cc1811eeb143

Expectation | Result
------------ | -------------
I expect series 1 and the 1 ep of the special (christmas) to be listed on the tv show page in Sick Gear | The special (christmas) is not showing up...even though it IS listed in the XML for the show

**Steps to reproduce:**
*1)* Add "Mark Kermode's Secrets of Cinema" to Sick Gear (series id: 350135)
*2)* Await full population of show.
*3)* Special does not show up - even though it's listed in the API XML for the series.
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags
<pre>
This is the link to the xml for the series:
http://thetvdb.com/api/A27AD9BE0DA63333/series/350135/all/en.xml
</pre>

Additional notes:
I tried to remove show and re-add, I also changed the status of the series from "Ended" to "Continuing" so I could ensure SickGear was ACTUALLY doing the pull of the XML and not using cached data. Nothing worked.

**Comment by JackDandy** [comment]
You have hidden "specials" and not re-enabled it again. Click "Show" next to word "Specials" that is to the right of the show title.

**Comment by janngobble** [comment]
OMG! is that the default installation? (i had to do a full git pull yesterday cos the “update check” said I was several hundred updates behind)

I’ll remember that.

**Comment by JackDandy** [comment]
Nope, it's not the default to have "Specials" hidden.

**Comment by JackDandy** [comment]
Actually, maybe, I can't recall and haven't been asked before.
