### ISSUE TITLE
Cannot add IMDB watchlist

### ISSUE THREAD

**Issue by sebk-666** [SickGear/SickGear#1148]
#### BRANCH: master / COMMIT: UNKNOWN @ 0.18.5
(I'm running the current Docker image)

I'm new to SickGear (been using the 'Beard for years).
I noticed the ability to add a IMDB watchlist, but it's not working for me.
Neither the "demo" user id (ur64552276) nor my personal id work.
It doesn't matter if I'm entering the plain user id or the whole URL.
I'm always getting a 404 in the logs, so I'm guessing the URL needs to be updated within SG.

`2018-12-12 12:24:26 DEBUG    TORNADO :: Response not ok. 404: Not Found from requested url http://www.imdb.com/user/ur64552276/watchlist/_ajax?sort=date_added,desc&mode=detail&page=1&title_type=tvSeries%2CtvEpisode&ref_=wl_vm_dtl`

Stripping everything after `/watchlist/` from the URL leads to the watchlist at least in a browser window.

Sebastian

**Comment by JackDandy** [comment]
Hi @sebk-666 

The builtin list works fine here, so perhaps its a temporary local network issue...

<img src="https://vgy.me/IalDsy.png">

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
The docker is somehow out of date.

**Comment by sebk-666** [comment]
> okay, the IMDB cards page works fine, its the config page that is having issue, correct?

That's right.

**Comment by sebk-666** [comment]
I think you just need to remove the `/_ajax`-part.
Starting at `https://www.imdb.com/user/ur64552276/watchlist`, clicking "refine" and selecting "TV Series" results in this link: 
`https://www.imdb.com/user/ur64552276/watchlist?sort=list_order%2Casc&title_type=tvSeries&view=detail`.

The original link from the log file also does work after removing the "`/_ajax`"-part, e.g.:
`http://www.imdb.com/user/ur64552276/watchlist?sort=date_added,desc&mode=detail&page=1&title_type=tvSeries%2CtvEpisode&ref_=wl_vm_dtl`

Sebastian

**Comment by JackDandy** [comment]
Yeah, it wasn't just the url that changed, plus seems they are rolling out changes that affect the main view too.

**Comment by JackDandy** [comment]
Thanks for the report, fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.18.6).

**Comment by sebk-666** [comment]
Awesome, thanks!
