### ISSUE TITLE
NZBGet integration - Priority reverts to Very High

### ISSUE THREAD

**Issue by thedaveCA** [SickGear/SickGear#1149]
BRANCH: master / COMMIT: 66c46be @ 0.18.5

Expectation | Result
------------ | -------------
Changing NZBGet priority to "Normal" should result in this staying at Normal | After restarting the service, the priority returns to Very High.

**Steps to reproduce:**
1) Configure Search Settings --> NZB Results --> NZBGet integration, with priority set to "Normal". 
2) Wait for items to be downloaded, they are added to NZBGet in Normal priority.
3) Upgrade to the latest build, reboot, or otherwise restart the service.
4) Wait for items to be downloaded, they are added to NZBGet in Very High priority.

I'm not aware of any relevant logs, but I'd be happy to provide further details as requested.

**Comment by JackDandy** [comment]
Thanks for the report. Fixed [here at 0.18.7](https://github.com/SickGear/SickGear/releases/tag/release_0.18.7)

**Comment by thedaveCA** [comment]
I was just installing as your message popped up. Confirmed fixed
here. Thanks!
