### ISSUE TITLE
Problems with non-ascii character in show title

### ISSUE THREAD

**Issue by darktka** [SickGear/SickGear#1154]
#### Branch version commit hash: snap @ 0.18.10

Expectation | Result
------------ | -------------
Tried to access the "display show" page of Les Misérables | ```Error: 'ascii' codec can't encode character u'\xe9' in position 27: ordinal not in range(128)```

**Steps to reproduce:**
*1)* Add Les Misérables (2017) as a show
*2)* Click the title in the show list
...

Full error here:
https://gist.github.com/darktka/c7feaa2917a93a7151c7e0190ee51985

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
Proof of correctly set up system with that show...

<img src="https://vgy.me/Ak6Lfy.png">

**Comment by JackDandy** [comment]
No reply so I guess the locale of this system was successfully set to work with non ASCII characters.

**Comment by deed02392** [comment]
Isn't there a way to force Unicode decoding in Python so you're not
dependent on the system locale?
