### ISSUE TITLE
Importing deletes my files

### ISSUE THREAD

**Issue by Wee-bear** [SickGear/SickGear#1157]
#### Branch version commit hash: 8d0b76e @ 0.18.11

Expectation | Result
------------ | -------------
I uses the 'Import' function as suggested and it systematically deleted my show files!

**Steps to reproduce:**
*1)* Uninstalled Sickbeard custom: SickRage fork which would not load
*2)* Installed Sickbeard custom: SickGear fork... loaded :-)
3) Set up my locations, media providers etc.
4) Set up my post processing / renaming parameters
5) Initiallized the import function... it began finding and identifying all my shows :-)
6) I opened one of the show pages and noticed it said "directory not found" !
7) I then stopped all processes and turned off the postprocessor and blanked the directory to find new shows.
8) I then continued to import and all has gone fine so far.
...
Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
I have run SickRage for many years but since I had major hardrive failure on my Synology NAS I was unable to get it working again and thus made the switch to SickGear.
It is my suspiscion that as "TV Shows" was my directory to dump new shows and my Postprocessing was using the move function.  It then found the new shows indexed in the show directories located under "TV Shows" and in its effort to move them deleated them from the drive (copy to current location followed by delete)
Fortunately I had my shows backed up on another drive and have subsequently copied the deleted ones back over.
I suggest that migrating users... ones with existing data be warned not to set up post processing before importing shows  and/or the post processor should not run until the import function has finished.
To avoid this in future I have moved my download directory from under my 'TV Shows' directory

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
> To avoid this in future I have moved my download directory from under my 'TV Shows' directory

Yeah, it's common knowledge to not have download directory under where the TV Shows are kept.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by Wee-bear** [comment]
Thanks for your response.  This will save guys like me a lot of headaches.  This was how I had SickBeard set with no issues but they are apparently not currently functional for new installations.  Also I was used to specifying 'Show Directory' in the renaming scheme but this caused 'TV Shows/ Show Name/ Show Name/ Season... etc.'  An easy correction on my part but was used to having to specify while here 'Show Directory' is assumes.  Definately a better way but caught me off guard at first.
Many thanks again

**Comment by JackDandy** [comment]
The notice is added here [migration](https://github.com/SickGear/SickGear/wiki/Install-SickGear-[0]-Migrate)
