### ISSUE TITLE
SickGear nuking files

### ISSUE THREAD

**Issue by esp123** [SickGear/SickGear#1166]
#### Branch version commit hash: 9238db3 @ 0.18.16This is BETA software

Not sure why, but SickGear appears to nuke the folder/files from the "completed" folder (while still being transferred to the completed folder by Deluge) and not transferring them to the Series Folder(s), with the below error.
...
`019-03-13 02:38:44 POSTPROCESSER :: Unable to move file  /media/Completed/Saturday.Night.Live.S44E05.Liev.Schreiber.and.Lil.Wayne.HDTV.x264-CRiMSON[rarbg]/Saturday.Night.Live.S44E05.Liev.Schreiber.and.Lil.Wayne.HDTV.x264-CRiMSON.mkv to /media/Storage/Series/Saturday Night Live/Season 44/Saturday Night Live - s44e05 - Liev Schreiber - Lil Wayne.mkv [Errno 2] No such file or directory: '/media/Completed/Saturday.Night.Live.S44E05.Liev.Schreiber.and.Lil.Wayne.HDTV.x264-CRiMSON[rarbg]/Saturday.Night.Live.S44E05.Liev.Schreiber.and.Lil.Wayne.HDTV.x264-CRiMSON.mkv'`

Additional notes:
Deluge on 1 machine, Sickgear on another.
Deluge machine using a local USB drive to download into, then moves the completions into a network share (NAS or similar)
Sickgear has no local drive, but has full access to the network share where Deluge is transferring completed files. All network shares are read/writeable from both machines.
Downloaded folder contains `A-z . 0-9 []` Characters

It doesn't happen all the time, not even sure why but SickGear should not nuke source files if it can't transfer them. It could be that Deluge is still transferring the files to the destination/completed folder and SickGear tries to process them mid-transfer to the Series Folder.

**Comment by esp123** [comment]
no way to know but it could be the []'s in the folder/file names - SickGear may not like it. I renamed the folder, and it (so far) appears to have worked, but this will need to be tested on alt setup (test with []'s, and without).

**Comment by JackDandy** [comment]
You should set up deluge properly as per [this link](https://github.com/SickGear/SickGear/wiki/Install-SickGear-[90]-Torrent-Clients)

**Comment by esp123** [comment]
I already have the seeding location separate to the completed location.

The issue is with SickGear appears to be not recognizing folders (and possibly files) with the []'s characters in them, from the isolated downloads folder. It then nukes the file rather than move it to the series folder.

**Comment by JackDandy** [comment]
> I already have the seeding location separate to the completed location.

Do you have the script that I linked you to above installed and running in Deluge ?

**Comment by esp123** [comment]
I found the issue. While the torrent program is transferring the file from the seeding folder to the completed folder, SickGear starts transferring it from the completed folder to the series folder (even though its not completely transferred yet to the completed folder). Eventually, SickGear eventually bombs out and nukes the series folder file, even though the completed folder file is still being transferred by the torrent program. It then nukes the completed folder file.

Sickgear should just wait until the completed folder files are COMPLETELY transferred (by the torrent program) before acting on them.

**Comment by JackDandy** [comment]
> Sickgear should just wait until the completed folder files are COMPLETELY transferred (by the torrent program) before acting on them.

Yes, for the **third** time, install the script - it achieves exactly this and more.
