### ISSUE TITLE
SickGear copying files still being (Deluge) transfered to a completed folder.

### ISSUE THREAD

**Issue by esp123** [SickGear/SickGear#1167]
#### Branch version commit hash: 9238db3 @ 0.18.16This is BETA software

Using (Manual) Process media appears to transfer files which are still being transferred to a completed folder. This creates an incomplete episode/series file.

**Steps to reproduce:**
*1)* Deluge on a separate machine with its own local drive + network share with a completed downloads folder that Deluge transfers the completed files/folders to.
*2)* Sickgear has access to the network completed downloads folder to process media from.
*3)* Once Deluge completes a download, it starts transfering the completed folder+files to the network share location - the transfer bytes of the destination file increase while transfering, until complete (can take some time on slower network and large files)
*4)* While Deluge is transferring the files to the network share, run "Proccess Media" using the same Deluge Completed folder where the file(s) is(are) being transferred to.
*5)* SickGear will transfer whatever the current file sized file from the completed (network) folder to the correct end series/show folder, however will NOT check if its the completed file while (Deluge is still transferring the file to completed folder). Deluge does not have a !.sync option for completed downloads being transferred to a destination completed downloads folder.
...
```
Found release name Saturday.Night.Live.S44E05.Liev.Schreiber.and.Lil.Wayne.HDTV.x264-CRiMSON
Destination folder for this episode is /media/Storage/Series/Saturday Night Live/Season 44
Moved file from /media/Completed/Saturday.Night.Live.S44E05.Liev.Schreiber.and.Lil.Wayne.HDTV.x264-CRiMSON/Saturday.Night.Live.S44E05.Liev.Schreiber.and.Lil.Wayne.HDTV.x264-CRiMSON.mkv
.. to /media/Storage/Series/Saturday Night Live/Season 44/Saturday Night Live - s44e05 - Liev Schreiber - Lil Wayne.mkv
Successfully processed Saturday.Night.Live.S44E05.Liev.Schreiber.and.Lil.Wayne.HDTV.x264-CRiMSON.mkv
-----------------------
Successfully processed.
```
Please note, the above file `Saturday.Night.Live.S44E05.Liev.Schreiber.and.Lil.Wayne.HDTV.x264-CRiMSON.mkv` was still being transfered by Deluge and reached only 1/2 of the actual size at the time of the manual Process Media action.

SickGear should not transfer incomplete files (ie files which are still being transferred by another application).

Additional notes:
Sickgear should wait until Deluge completes the transfer of the files to the completed folder before SickGear starts transferring the files.

**Comment by esp123** [comment]
It appears, on re-scan, the correct filesize is transferred.

**Comment by JackDandy** [comment]
You should set up deluge properly as per [this link](https://github.com/SickGear/SickGear/wiki/Install-SickGear-[90]-Torrent-Clients)
