### ISSUE TITLE
web_root causing issue with list view episode search button

### ISSUE THREAD

**Issue by nojp** [SickGear/SickGear#1168]
#### Branch version commit hash: eafc30410d976d283b81379226a2642ce18b12f5

Expectation | Result
------------ | -------------
When using a configured web_root value (e.g. /sickgear), and the "List" layout in the daily schedule page, clicking the magnifying glass to perform a single episode search should work. | Icon changes and briefly spins, error is logged in browser console with and HTTP 404 error.

**Steps to reproduce:**
1. Configure web_root for use with a reverse proxy (for example)
2. Set Daily Schedule page to list view
3. Click magnifying glass on upcoming episode to attempt a manual search
4. Observe F12 console for error like the following (unique stuff removed)

jquery-2.2.4.min.js?v=1997:4 GET https://myhost.myservice.com:8000/sickgear/sickgear/home/episode_search?show=12345&season=15&episode=20 404
send @ jquery-2.2.4.min.js?v=1997:4
ajax @ jquery-2.2.4.min.js?v=1997:4
n.(anonymous function) @ jquery-2.2.4.min.js?v=1997:4
getJSON @ jquery-2.2.4.min.js?v=1997:4
(anonymous) @ ajaxEpSearch.js?v=1997:229
dispatch @ jquery-2.2.4.min.js?v=1997:3
r.handle @ jquery-2.2.4.min.js?v=1997:3

Additional notes:

It looks like:

https://github.com/SickGear/SickGear/blob/8d0b76ef6b7d8821497748d0d78ba66b0df7bccc/gui/slick/interfaces/default/episodeView.tmpl#L435

and

https://github.com/SickGear/SickGear/blob/8d0b76ef6b7d8821497748d0d78ba66b0df7bccc/gui/slick/interfaces/default/episodeView.tmpl#L622

and probably

https://github.com/SickGear/SickGear/blob/2c66cc3936b3b8d5239f6c49cf7b6ac6193fb9c2/gui/slick/interfaces/default/inc_displayShow.tmpl#L112

cause a conflict with:

https://github.com/SickGear/SickGear/blob/eafc30410d976d283b81379226a2642ce18b12f5/gui/slick/js/ajaxEpSearch.js#L229

If you have a custom web_root configured, the interaction between the generated href value and the js code causes it to be doubled up, resulting in the ajax call being attempted against:

http://<server>:<port>/<web_root>/<web_root>/<uri_query>

instead of what should be:

http://<server>:<port>/<web_root>/<uri_query>

**Comment by JackDandy** [comment]
Thanks for the report... i will post reply here when fixed.

**Comment by JackDandy** [comment]
Thanks again @nojp 

[Fixed here](https://github.com/SickGear/SickGear/releases/tag/release_0.18.18).
