### ISSUE TITLE
Question: Show All / Hide Most Buttons

### ISSUE THREAD

**Issue by kevin201** [SickGear/SickGear#1169]
#### Branch: BRANCH: master / COMMIT: eafc304 @ 0.18.17

Expectation | Result
------------ | -------------
Hide Most/Show All persistent buttons always present | Only present in some (apparently random) shows.

e.g. The Cruise:

https://snag.gy/5qLat8.jpg  (has buttons)

Antiques Road Trip:

https://snag.gy/8SeTmk.jpg (No buttons)

Is this a bug, or a feature?

**Comment by JackDandy** [comment]
Yes, it is a feature, there is logic that controls how/when to display buttons.

**Comment by kevin201** [comment]
Is it a secret?

**Comment by JackDandy** [comment]
Nope, just never thought how to word it in the feature list, there are other little touches lightly sprinkled around, they're created with thought as "little" things.

**Comment by kevin201** [comment]
Ok, I only mention it because, as luck would have it, I have most wanted to use the "Show All" button on programs where it doesn't appear, and I couldn't see the logic behind why it wasn't there!

**Comment by JackDandy** [comment]
> and I couldn't see the logic behind why it wasn't there!

It is that way for the best performance. It may feel strange to you but "seeing all" is less than useful with a few shows.

Ask in IRC if you want more, there is not an actual issue here.

**Comment by kevin201** [comment]
Ok, thanks.
