### ISSUE TITLE
Cannot update default download quality

### ISSUE THREAD

**Issue by tal** [SickGear/SickGear#1170]
Master branch, commit: 1b0f9533eedce1c033762a3720dcfe4dee7d2aee

When i try and set the default quality for adding new shows it's always set to a custom value (image below). Nothing i can do will change this default so when I bulk add shows i have to go to the final step to set the quality every time. Same issue occurs if i change the value in the show selection portion of bulk import.

Nothing appears in the logs when the default changes are saved.

I've tried setting the default either with one of the presets or a different custom value and neither works.

I've tried deleting `sickbeard.db` and starting fresh, same issue occurs.

<img width="874" alt="Screen Shot 2019-04-08 at 11 12 41 PM" src="https://user-images.githubusercontent.com/18906/55771095-a431f180-5a54-11e9-83a7-de43bb0ccab9.png">

Thanks

**Comment by JackDandy** [comment]
It sounds as though the selection you are making and then attempting to save qualifies as built in type, therefore there will be no need to save them, to prove this, from the screen above, also select an SD and then save. You will find that will stick.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by tal** [comment]
None of the defaults are "sticking" I made a video to better illustrate it, in this video I'm setting the defaults to several values and reloading the page to show it afterwards. The only one that seems to stick is the `HD` one.

[![sickgear default qualities bug](http://img.youtube.com/vi/I2wVKOl-zvs/0.jpg)](http://www.youtube.com/watch?v=I2wVKOl-zvs" "sickgear default qualities bug")

**Comment by JackDandy** [comment]
ok confirmed, can you delete that video.

**Comment by JackDandy** [comment]
Hi, can you delete that video, thanks.

Investigated, it is working as designed.

**Comment by JackDandy** [comment]
@tal did that FAQ item help ?

**Comment by tal** [comment]
Maybe a little bit, but it's a very confusing user experience that I'm still not entirely convinced is working correctly. And definitely doesn't work how it did in sickbeard. But thanks for responding

**Comment by JackDandy** [comment]
K, also, can you please delete that video.
