### ISSUE TITLE
Cannot set skipped episodes to archived

### ISSUE THREAD

**Issue by tal** [SickGear/SickGear#1171]
#### Branch version commit hash: 1b0f9533eedce1c033762a3720dcfe4dee7d2aee

Expectation | Result
------------ | -------------
Setting an episode to archived will be successful | no change when setting an episode from skipped -> archived, no error is shown either.

**Steps to reproduce:**
1. Go to show with skipped episodes
2. Select one or many skipped episodes
3. Attempt to set selected episodes to archived
4. Observe new status of episode
...

No log entries or errors are emitted when this is attempted.

[![sickgear cannot set as archived](http://img.youtube.com/vi/oaIddtE32yw/0.jpg)](http://www.youtube.com/watch?v=oaIddtE32yw "sickgear cannot set as archived")

**Comment by JackDandy** [comment]
Yes, this is the correct...
<a name=""><img src="https://i.vgy.me/ZNyfxP.png"></a>

**Comment by tal** [comment]
Is there any reason it can't go straight to archived? I'm adding shows so the episodes come in as skipped, and I want to transition them to archived.

**Comment by JackDandy** [comment]
> Is there any reason it can't go straight to archived? 

Yes, it is that way by design. If you want eps to be ignored, then use the "Ignore" status instead.

**Comment by tal** [comment]
That's not really the behavior I'm interested in, nor do I really see why there's value in disallowing it, but I really appreciate your communication on the matter.

**Comment by JackDandy** [comment]
> nor do I really see why there's value in disallowing it

And yet there is, we sure don't spend time coding things to challenge Mr @tal ;-)

> not really the behavior I'm interested in

Okay, so why don't you simply set item(s) as "Downloaded (your quality choice)" and once set, then "Archived with"->"downloaded quality". That will get you where you want to be.

**Comment by JackDandy** [comment]
> nor do I really see why there's value in disallowing it

And yet there is, we sure don't spend time coding things to challenge Mr @tal ;-)

> not really the behavior I'm interested in

Okay, so why don't you simply set item(s) as "Downloaded (your quality choice)" and once set, then "Archived with"->"downloaded quality" as can be seen in the image I posted 2 days ago. That will get you where you want to be.
