### ISSUE TITLE
Scene Numbering only being partially accepted

### ISSUE THREAD

**Issue by nojp** [SickGear/SickGear#1177]
BRANCH: master / COMMIT: 122f198 @ 0.18.21

Expectation | Result
------------ | -------------
Shows with scene numbering enabled should be searched and snatched via the scene number. | Shows with scene numbering enabled appear to search with the scene number but then match using the non-scene number, and thus do not download.

**Steps to reproduce:**
*1)* Enable scene numbering on a show with a discrepancy (e.g. American Dad!)
*2)* Search for an episode that has a scene number applied (e.g. 16x3 scene numbered as 15x3)
*3)* Optionally in logs you can see providers being searched for the scene number, but then sickgear can't find a match
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

https://gist.github.com/nojp/36ec483e5c4a7da25633328599efe98d

Additional notes:
This was working a few months ago as far as I know, although I haven't been tracking closely.

**Comment by JackDandy** [comment]
"Scene Numbering" has nothing to do with your issue.

The episodes you are trying to perform a manual search using the magnify glass are all of Status type "Unknown". "Unknown" means that for some reason, those episodes were never changed from an initial "Unknown" status to a known "Wanted" or "Skipped" status.

You really should have no items that are "Unknown".

I recommend that you clean up all of your show statuses,
use menu Manage/Episode Statuses... dropdown "Unknown" and change eps found to "Skipped".
