### ISSUE TITLE
Opensubtitles API errors

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#1181]
BRANCH: master / COMMIT: d1166f9 @ 0.19.0

Expectation:
You set up subtitle search and add a login if required. It searches for matching subtitles and adds them.

Result:
It doesn't snatch and errors on Opensubtitles because it requires a login and it doesn't find a match often with the other sites or skips them.
------------ | -------------

**Steps to reproduce:**
*1)* Turn on the subtitle search
*2)* Select opensubtitles
*3)* Watch the errors
...

Gist: https://gist.github.com/Th3MadHatter/50d2ea8d9846c03cee4f796555588a77

Additional notes:
It seems to require a login from now on. Adding a username and password option will fix the problem. 
Also all subtitle sites still use http instead of https while all are available in https. Changing that in the .py files would help for a more secure connection.

Thanks Jack.

**Comment by JackDandy** [comment]
Thanks for the report. Now that his feature is no longer operational, it will be removed.

**Comment by JackDandy** [comment]
Thanks for the report. 

Now that this feature is no longer operational, it can be removed.

Perhaps use the following <a href="https://github.com/caronc/nzb-subliminal">subtitle fetcher program</a>, run it in a script that you can add to the post-processing settings page. If you can, share your successes, maybe make a little guide on how to optimally set up the dedicated fetcher.

Good luck.

**Comment by Th3MadHatter** [comment]
It still works, it still snatches things from the other subtitle sites but the results are less then with Opensubtitles.
Opensubtitles just requests a login and username to use the api which they always preferred but now they seem to block non-login scraping. Adding a query box for user and pass would fix it instead of removing the whole subtitle section which I know a lot of people use 😄 
If you don't feel like adding that removing opensubtitles from the list and upgrading the other .py files, from the other subtitle sources, from http to https is a work around of sorts.

**Comment by JackDandy** [comment]
> Adding a query box for user and pass would fix it

Not really. I won't bore you with details but the processes when that "query box" is used takes time to write, and even more time to test, simplicity it is not.

I reached out to the author of that sub fetcher to see if it could be integrated (like a library) but alas no progress was made. So it's left for someone to put together a pp script, and given that challenge is not for you, then someone else may want to step in. For now, perhaps SG can disable the OS provider.
