### ISSUE TITLE
MAIN :: DB error: too many SQL variables

### ISSUE THREAD

**Issue by shortbus** [SickGear/SickGear#1183]
#### Branch version commit hash: COMMIT: ec50d09 @ 0.19.2
2.7.9 (default, Sep 9 2015, 14:34:08) [GCC 4.2.1 20070831 patched [FreeBSD]]

Expectation | Result
------------ | -------------
Not receiving the error.|The "MAIN :: DB error: too many SQL variables" error

**Steps to reproduce:**
*1)* Nothing, I think this is a daily operation.

Link to gist:
https://gist.github.com/shortbus/440a50f79efaaddcd06ef663b83fcf5a

**Comment by JackDandy** [comment]
Thanks for the report :)

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.19.3)

Thanks for the report.

**Comment by shortbus** [comment]
Awesome. Thank you. I am going to update and test (I mean wait, ha).

**Comment by JackDandy** [comment]
fyi: that function is also run on startup as well as once a day, so after the update and its restart, you will see there is no longer the issue ;-)

**Comment by shortbus** [comment]
JackDandy, that is a great point. I did update and restart. I do not see the message any longer. Thanks!
