### ISSUE TITLE
feature request - make a one button pause that mass updates

### ISSUE THREAD

**Issue by shortbus** [SickGear/SickGear#1184]

**Comment by RedSparr0w** [comment]
Could you please expand a bit more on what exactly you are wanting?

**Comment by JackDandy** [comment]
yeah, I'm not fully understanding this either.

Feel free to add anything else below, even though it is closed that's no problem.

**Comment by shortbus** [comment]
there are a lot of shows... and the software seems like it is slow to update. There are a lot of shows that have ended that are completely downloaded (all episodes present).
I want to pause shows, but i have to step through each show, click edit, check pause, click save. wait for the page to reload, then move to the next show.

it would be great if on some management page there was a button that could "Pause all shows that are 'ended' and 'all shows are downloaded'. 

the mass update feature is nice, and i use it, but there is not a way to select 40 things based on a filter and then set them to pause.

sorry for not being able to explain myself well, and thank you for looking at this so quickly.

**Comment by JackDandy** [comment]
> a way to select 40 things based on a filter and then set them to pause.

Now I understand, yes what you want is available. Use menu Manage/ _Bulk Change_ to select multiple shows as usual, then scroll down and click _Edit Selected_, in the next page, drop down "Paused" and change to _enable_, finally _submit_.

**Comment by shortbus** [comment]
JackDandy, that is great advice. From the bulk change screen I cant see what shows have been 100% completely downloaded.

All of this is an effort to find out what is making my sickgear _seem_ slow. Shows do not seem to update in a timely manner. I was trying to 'lighten the load' a bit so it did not have so much to go through.

**Comment by Prinz23** [comment]
SickGear re-downloads every day all fanart for all ended shows. This takes very long (and a waste of time and bandwidth if you ask me).

On my SickGear i disabled the auto update of sg and edited the line 146 in sickbeard/show_updater.py from:

`cur_queue_item = sickbeard.showQueueScheduler.action.refreshShow(curShow, True, True, force_image_cache=True)`

to

`cur_queue_item = sickbeard.showQueueScheduler.action.refreshShow(curShow, True, True)`

This disables this unneeded re-download of all fanart with the show update daily.

**Comment by shortbus** [comment]
can this be made a toggle in the admin menu and pushed to master?

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.19.5)

**Comment by shortbus** [comment]
You are awesome! Thank you JackDandy
