### ISSUE TITLE
rTorrent: Unable to send torrent to client

### ISSUE THREAD

**Issue by makefu** [SickGear/SickGear#1186]
#### Branch version commit hash: 1180c2300e4296d2c6e0be80bf5ad1cedece48cd

Expectation | Result
------------ | -------------
SickGear adds new torrents and magnets to rtorrent via scgi | Got error message `rTorrent: Unable to send torrent to client`, no torrents are added to rtorrent

**Steps to reproduce:**
*1)* Install latest SickGear
*2)* Install rtorrent 0.9.6, configure `.rtorrent.rc`
```
rpc_port = localhost:5000
log.open_file = "log", rtorrent.log
# enable debug output for all rpc commands
log.add_output = "rpc_dump", "log"
```
*2.5)* configure rtorrent as *Torrent Results* Receiver, configure host as `scgi://localhost:5000`
*3)* Add horriblesubs as search provider
*4)* add a new show
*5)* start backlog search
*6)* Get error Message in Logs rtorrent `rTorrent: Unable to send torrent to client`
*7)* Get `Method 'load_raw' not defined` in `rtorrent.log`

Additional notes:
It seems that pymedusa fixed this issue as it seems to be related to changed rpc functions in rtorrent 0.9+ ( https://github.com/pymedusa/Medusa/pull/3333/files#diff-33878acf9434aa074045d228eade8661 ). With rtorrent 0.9 the method names changed from `load_start` to `load.start`, `load_raw` to `load.raw`.

When i naively changed the function names in `lib/rtorrent/__init__.py` unfortunately results in `Too few Arguments`

The related `SickChill` can be found at https://github.com/SickChill/SickChill/issues/5118

**Comment by JackDandy** [comment]
i've had code for this for a while now, if you want to help test it, come to IRC.

**Comment by JackDandy** [comment]
I wrote changes for this in 2016 but no one was available to test, if you are interested, come to IRC and I can make the update available for you.

**Comment by makefu** [comment]
@JackDandy will do, see you there

**Comment by JackDandy** [comment]
Complete [here](https://github.com/SickGear/SickGear/releases/tag/release_0.19.6)
