### ISSUE TITLE
Unable to add show: Missing params, no Indexer ID or folder

### ISSUE THREAD

**Issue by baronmog** [SickGear/SickGear#1187]
#### Branch version commit hash: 1180c23

Expectation | Result
------------ | -------------
Add the show | I get an error like `Missing params, no Indexer ID or folder:'1 TheTVDB [TVDB_IDNumber] [Show Name] and None/None`

**Steps to reproduce:**
*1)* Search for a show, it doesn't matter what
*2)* Select it
*3)* Click the "Add Show" button

**Comment by JackDandy** [comment]
Perhaps a local network connection issue, shows are adding fine here.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by baronmog** [comment]
Well, I've tried it with the snap version of SickGear and both master and develop branch versions cloned directly from github. Everything else on the system is able to connect to the internet (including Sickrage which add shows just fine).

**Comment by JackDandy** [comment]
I cannot replicate an issue here and no one else is reporting an issue. Therefore, I don't know what I can do to help you

**Comment by JackDandy** [comment]
So i just tested under Ubuntu and there is no issue here...

<img src="https://i.vgy.me/4DukjI.png">

**Comment by JackDandy** [comment]
Can you look to see if your root (parent) folder exists, I think that this is your issue.
