### ISSUE TITLE
Searching Kat for HD1080p doesn't provide WEB-DL results.

### ISSUE THREAD

**Issue by MindTooth** [SickGear/SickGear#119]
Hi,

1. (master) / COMMIT: (8bc6e7bbea76d566a66a09e00a5a401ff096cd90)

2. When setting a show to HD1080p, and searching a provider that has the content I want, it doesn't "search" for the correct content.  And therefore, no results is given.

3. Set show to HD1080p in Edit Show, mark episodes as Wanted in Show Page, no results.

4. Excerpt of log: http://pastebin.com/QkEDL96A

Example search queries:
<pre>2014-12-18 17:37:54 DEBUG    SEARCHQUEUE-BACKLOG-248742 :: [KickAssTorrents] :: Search string: http://kickass.so/usearch/Person%20of%20Interest%20Season%204%20-Ep%2A%20category%3Atv/?field=seeders&sorder=desc
2014-12-18 17:37:52 DEBUG    SEARCHQUEUE-BACKLOG-248742 :: [KickAssTorrents] :: Search string: http://kickass.so/usearch/Person%20of%20Interest%20S04%20-S04E%20category%3Atv/?field=seeders&sorder=desc</pre>

I really don't understand whats up with the "Season 4 -Ep* category:tv" part?  If I just add "1080p" after the show title, it finds the content just fine.

**Comment by MindTooth** [comment]
<pre>2015-01-11 18:02:59 DEBUG    SEARCHQUEUE-BACKLOG-82459 :: [KickAssTorrents] :: Search string: http://kickass.so/usearch/The%20Mentalist%20Season%207%20-Ep%2A%20category%3Atv/?field=seeders&sorder=desc
2015-01-11 18:02:55 DEBUG    SEARCHQUEUE-BACKLOG-82459 :: [KickAssTorrents] :: Search string: http://kickass.so/usearch/The%20Mentalist%20S07%20-S07E%20category%3Atv/?field=seeders&sorder=desc</pre>

After I've browsed to the actual address, and then sort by date.  I'm able to view the 1080p releases.  But it does not seem like the results given to SickGear contains any 1080p releases.

If I however look at the log (debug), only somewhat of 20-25 results is given to SickGear.  Meaning that quite a lot is not looked at.  Default behavior?

**Comment by JackDandy** [comment]
yes. this will not be looked at further.
