### ISSUE TITLE
Feature Request - Mass Update 'Delete' check box removes files on disk, change to remove show from daatabase, but leave files.

### ISSUE THREAD

**Issue by shortbus** [SickGear/SickGear#1190]
I used the delete show from the "mass update" (or manage) page and it removed physical files.

I find it odd that from the dsiplayShow-edit page one has to check a box and click okay to destroy files (irreversible in the color red), yet from Mass Update screen there is no warning or click through to destroy files. Seems like on the perseverance of files on single shows is important but when multiple shows are used, it is mass destruction with no regard for file protection.

**Comment by JackDandy** [comment]
Yup, this is addressed on the ChangeUI branch.
