### ISSUE TITLE
Feature Request - Add pause check box on Bulk Change page

### ISSUE THREAD

**Issue by shortbus** [SickGear/SickGear#1191]
Please add a column of checkboxes on the Bulk Change page for "Pause Show"

![Bulk Update page columns](https://i.imgur.com/qWScIxn.png)
Request: add "Pause Show" column with checkboxes allowing the pausing of a number of shows at once.

**Comment by JackDandy** [comment]
No need, simply select shows you want to pause on the left, scroll down, click edit btn, then, in the following screen, set paused there and press "save". Done.
