### ISSUE TITLE
rTorrent: Unable to send torrent to client

### ISSUE THREAD

**Issue by JackDandy** [SickGear/SickGear#1192]
**Issues moved to here, created by @makefu 18 Jun 2019**

#### Branch version commit hash: 1180c2300e4296d2c6e0be80bf5ad1cedece48cd

Expectation | Result
------------ | -------------
SickGear adds new torrents and magnets to rtorrent via scgi | Got error message `rTorrent: Unable to send torrent to client`, no torrents are added to rtorrent

**Steps to reproduce:**
*1)* Install latest SickGear
*2)* Install rtorrent 0.9.6, configure `.rtorrent.rc`
```
rpc_port = localhost:5000
log.open_file = "log", rtorrent.log
# enable debug output for all rpc commands
log.add_output = "rpc_dump", "log"
```
*2.5)* configure rtorrent as *Torrent Results* Receiver, configure host as `scgi://localhost:5000`
*3)* Add horriblesubs as search provider
*4)* add a new show
*5)* start backlog search
*6)* Get error Message in Logs rtorrent `rTorrent: Unable to send torrent to client`
*7)* Get `Method 'load_raw' not defined` in `rtorrent.log`

Additional notes:
[edit: reference removed]

When i naively changed the function names in `lib/rtorrent/__init__.py` unfortunately results in `Too few Arguments`

**Comment by JackDandy** [comment]
Complete [here](https://github.com/SickGear/SickGear/releases/tag/release_0.19.6)

**Comment by makefu** [comment]
thanks!
