### ISSUE TITLE
Feature Request - Add Downloaded status Bulk Change columns

### ISSUE THREAD

**Issue by shortbus** [SickGear/SickGear#1193]
Please add the Downloads column (the downloaded shows / the total number of shows) to the Bulk Change columns

Add this column
![Please add this column](https://i.imgur.com/KeLtgfg.png)

To this list on the Bulk Change page
![The current columns](https://i.imgur.com/fXqRd4r.png)

**Comment by JackDandy** [comment]
Hiya,

What is the reason behind this suggestion?

You can open the first information in one browser tab, and have the Bulk Change page in another tab, so it's unclear what value there is of duplicating the same data in two different places.

**Comment by shortbus** [comment]
All the information would be on one page, two pages would sort different, too many open windows is untidy and confusing. When there are < 100 shows what you suggest is not difficult, when there are >1300 what you suggest is clumsy and difficult. I understand you don't want data duplication, but information clarity is worth more.

**Comment by JackDandy** [comment]
> two pages would sort different

And this is not a bad thing, looking at it from another perspective, you have two tables on two TABS that can sort by either the same column **and** also sort by different columns.

> too many open windows is untidy and confusing

using **two** tabs is something even my grandma can handle, this point is not strong

> when there are >1300 what you suggest is clumsy and difficult

there is no difference whether one or two browser tabs here. In fact, the work done to display the Bulk Change page with the added column would actually make the Bulk Change page slower in all situations for everyone.

> I understand you don't want data duplication, but information clarity is worth more.
 
[DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) - your suggestion seems like bad design. I cannot see a case where "information clarity" is improved by this suggestion, I do see a negative impact to display performance by adding this feature.

**Comment by shortbus** [comment]
Yeah, remove the Quality column and put in Downloads column.

That way one can sort and shift-select, then click to the next screen, pause a ton of shows, and our lives will be easier.

**Comment by shortbus** [comment]
Also, I respect you, I have used your app for years, and you are doing fantastic work.

**Comment by JackDandy** [comment]
All these years and no free star :p

**Comment by shortbus** [comment]
I did not know that was a thing. The Star issue has been rectified.

**Comment by shortbus** [comment]
I am going to ask for this again. I have tried it with the two windows... It is too frustrating. Look. Check box. Search.. look... Check Box. 5 Min operation only to get maybe ten shows paused.

Very frustrating. Especially when I keep thinking if the Download Column was present I could sort.... Click, shift Click. Edit. Enable Pause and be done. Would be less than a 1 minute thing.
