### ISSUE TITLE
Show List Page - Images do not display in Firefox

### ISSUE THREAD

**Issue by GabhanOLoughlin** [SickGear/SickGear#1195]
#### Branch version commit hash: COMMIT: 5162633 @ 0.19.6

Expectation | Result
------------ | -------------
When the Show List page opens, the show banner images should appear | In Firefox (67.0.2 (64-bit)) on Windows 10 (64-bit), when the Show List page opens, the images do not load, but the placeholders and show IDs are visible instead. Scrolling the page a little causes the images to load. 

I have written a Greasemonkey script to scroll to the bottom of the page and back to the top every time the Show List page is opened, but others must be encountering this issue?

**Steps to reproduce:**
*1)* Open Firefox and navigate to the Sickgear page
*2)* Click Shows -> Show List and wait for the page to load fully
*3)* If (when?) the images fail to load, use the scroll bar to move down the page. Then the images begin to load.

![image](https://user-images.githubusercontent.com/5986207/60252914-09161e80-98c3-11e9-8458-57bd3e7c37d2.png)

**Comment by GabhanOLoughlin** [comment]
Just to confirm, on the same setup, on the same machine, Internet Explorer, Edge and Chrome display the page correctly. So it seems to be specific to Firefox (which just happens to me my preferred browser)

**Comment by JackDandy** [comment]
I'll wait to see if this issue develops with anyone else.

**Comment by JackDandy** [comment]
I can replicate

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.19.7)

**Comment by GabhanOLoughlin** [comment]
Tested and confirmed fixed. Cheers
