### ISSUE TITLE
Can't connect to page

### ISSUE THREAD

**Issue by MadAEng** [SickGear/SickGear#1197]
#### Branch: master

After installation on raspbian buster, I expected to be able to go to the web interface | Can't connect to the page

Additional notes:
I attempted both the normal snap install, as well as with Unrar 3.0.
I do get this warning:
Warning: /snap/bin was not found in your $PATH. If you've not restarted your session since you
         installed snapd, try doing that. Please see https://forum.snapcraft.io/t/9469 for more
         details.
But I've checked after a reboot, the folder is there.

**Comment by JackDandy** [comment]
sounds like you need to install snap properly, go there for those docs.

**Comment by MadAEng** [comment]
I'm not entirely convinced that's the issue here.
When running `snap services`, the response is `There are no services provided by installed snaps.`
When running `snap list`, the response is :
```
Name      Version    Rev   Tracking  Publisher   Notes
core      16-2.39.3  7274  stable    canonical✓  core
sickgear  0.20.0     465   stable    sickgear    -
```
So, snap doesn't recognise sickgear as a service, shouldn't it?

I also tried the Debian-manual install, but that also doesn't seem to work unless I run the non-systemd command.

Now, it could be due to me running Raspbian buster that there's some kind of compatibility issue here, but as far as I can tell, it's not snap.

**Comment by JackDandy** [comment]
> So, snap doesn't recognise sickgear as a service, shouldn't it?

Yup, that's correct, SG is _not_ installed as a `service`.  
  
Just run it as any any normal snap app.

**Comment by JackDandy** [comment]
> So, snap doesn't recognise sickgear as a service, shouldn't it?

Yup, that's correct, SG is _not_ installed as a `service`.  
  
Just run it as any you would any other snap app, in a terminal window, you will see SG info output and therefore will know that you can connect to it via your chosen browser, and then minimize (not close) the SG window. Of course, you can run that terminal command as a background process if you really wanted to close the window.

**Comment by JackDandy** [comment]
> So, snap doesn't recognise sickgear as a service, shouldn't it?

Yup, that's correct, SG is _not_ installed as a `service`.  
  
Just run it as you would any other snap app, in a terminal window, you will see SG info output therefore will know that you can connect to it via your chosen browser, and then minimize (not close) that window. Of course, you can run that terminal command as a background process if you really wanted to close the window.

**Comment by JackDandy** [comment]
> So, snap doesn't recognise sickgear as a service, shouldn't it?

Yup, that's correct, SG is _not_ installed as a `service`.  
  
Just run it as you would any other snap app, in a terminal window, you will see SG info output therefore will know that you can connect to it via your chosen browser, and then minimize (not close) that window. Of course, you can run that terminal command as a background process if you really wanted to close the window.

So... `sudo /snap/bin/sickgear` (use `which sickgear` to find path, e.g. `/snap/bin/sickgear`)

If that doesn't work for you, then i would consider it a buster/snap issue.

**Comment by MadAEng** [comment]
>  So... `sudo /snap/bin/sickgear` (use `which sickgear` to find path, e.g. `/snap/bin/sickgear`)

I see where I messed up... *facepalm*
Sorry about that, I'm still pretty new to this.

Is there a way I can contribute to the wiki? Adding that line of code might prevent people making the same dumb mistake as yours truly.
Also I'd like to add a way to run it at startup.

**Comment by JackDandy** [comment]
> Is there a way I can contribute to the wiki? 

I will add the run line to the wiki.

**Comment by MadAEng** [comment]
Cool! Thanks for the help, sorry to ask a n00b question!
