### ISSUE TITLE
LimeTorrents provider not working

### ISSUE THREAD

**Issue by GabhanOLoughlin** [SickGear/SickGear#1201]
#### Branch version commit hash: 48c312b @ 0.20.2

Expectation | Result
------------ | -------------
Enabling LimeTorrents provider should return results from LimeTorrents | Error log shows error below for each episode searched:

[LimeTorrents] :: Failed to parse. Traceback: Traceback (most recent call last):
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/sickbeard/providers/limetorrents.py", line 83, in _search_provider
    ['torrent', 'size']])]
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/lib/bs4/element.py", line 742, in __getattr__
    self.__class__.__name__, attr))
AttributeError: 'Doctype' object has no attribute 'find_all'

**Steps to reproduce:**
*1)* Go to Settings -> Media Providers
*2)* Enable LimeTorrents (no account required)
*3)* Once episodes are searched for, the above error appears for each episode searched

If this isn't the place to log Search Provider issues, apologies.

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.20.3)
