### ISSUE TITLE
Synology Download station torrents stay "snatched"

### ISSUE THREAD

**Issue by steff2632** [SickGear/SickGear#1202]
#### Branch version commit hash: (See the About page) 642f65d

I'm using Sickgear on Synology with download station torrent provider. 

Sickgear manages to add torrents and they get added correctly (download fine & to the right directory) but sickgear doesn't seem to notice that they've downloaded and they stay in the "Snatched" state.

It also doesn't do the Post-Processing either.

I have the downloaded torrents downloaded to a "downloads" folder inside my "show root directory"

**Comment by JackDandy** [comment]
Sounds like a setup issue, we have not had issues with syno users, so i suggest you look at the paths you have set up.

**Comment by steff2632** [comment]
ok, had a feeling that might be it since running the "Process Media" would report that the folder was under the show root directory so ignoring. Thanks for the edit, knew it would be configuration issue was just looking for some help
