### ISSUE TITLE
Request - Use Freeleech tokens on Alpharatio

### ISSUE THREAD

**Issue by st0neh** [SickGear/SickGear#1205]
Hi,

I'm just wondering if it would be possible to add support for the Freeleech token system on Alpharatio? It looks like using one just adds a &usetoken=1 to the end of the download URL so I'm assuming it could be possible.

Thanks!

**Comment by JackDandy** [comment]
Look in the section "Only allow release that are" in settings providers -> Alpha.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by st0neh** [comment]
Yeah there's currently a system to only download Freeleech torrents in Sickgear, but AlphaRatio also has a system of Freeleech tokens that you can choose to make any torrent Freeleech. Sorry if that wasn't more clear in my original post.

**Comment by JackDandy** [comment]
Ah right, I understand what you mean. Yeah, that system was indeed considered long ago, but rejected to prevent possible accidental token use. For example, a user can trigger a search that results in multiple incorrect items and a token spent for each one of those wrong items - bad. Therefore, it was decided to leave tokens to user manual use.
