### ISSUE TITLE
SickGear Doesn't Update Episode Watched Status From Plex (PMS 1.18.xxx+)

### ISSUE THREAD

**Issue by OrGoN3** [SickGear/SickGear#1207]
#### Branch version commit hash: (See the About page) 5d9a0dc

Expectation | Result
------------ | -------------
I expect SickGear to continuously update the watched status of episodes I've watched through Plex, as it always has. | No shows' watched status gets updated. According to SickGear, I'm not watching anything.

**Steps to reproduce:**
*1)* Use Windows 7 x64
*2)* Install Plex Media Server 1.18 (any from this branch)
*3)* Have SickGear completely set up for Plex in Coinfig->Notifications and make sure the connection works.
*4)* Watch episodes on TV/plex and then check SickGear. If in doubt, press the 'Update Plex' button.
*5)* No shows are added to SIckGear's Watch History.
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags https://gist.github.com/OrGoN3/60c15ffcc8b42e366ae3b769963f8828

Additional notes:
Windows 7 x64 Genuine, fully updated.
Python Version: | 2.7.16 (v2.7.16:413a49145e, Mar 4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)].
Included are two photos: one showing my recent play history on Plex, and the other on SickGear. Notice how anything fully watched on Nov 9 does not show up on the SickGear history list. This is when I updated to the 1.18 branch of PMS again. Sickgear history has worked on all previous versions of PMS for me, including 1.17. Even if I revert to 1.17 it'll work. I've never gotten it to work on 1.18.xxxx.

***In the logs files I found this:
2019-11-09 03:43:14 WARNING  Q-PLEX-WATCHED :: Connection error msg:HTTPConnectionPool(host='192.168.1.119', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',)) while loading URL http://192.168.1.119:32400/

I've included a third photo showing the notification is set up correctly. As I said, it worked in every previous version of Plex. After updating Plex to 1.18 branch, I got a new notification that SickGear notifier accessed my library. So I know it has valid credentials.
![PlexWatchHistory](https://user-images.githubusercontent.com/56672656/68536642-feb16a00-0323-11ea-834f-200db10d6a9e.jpg)
![SickGearHistory](https://user-images.githubusercontent.com/56672656/68536643-feb16a00-0323-11ea-9dff-fe56c84cc4bb.jpg)
![SickGearNotificationSettings](https://user-images.githubusercontent.com/56672656/68536644-feb16a00-0323-11ea-91ce-be117e2e24ce.jpg)

**Comment by OrGoN3** [comment]
Might as well close this up. I cannot gather any further logs as the hard drive SickGear was located on, just crashed. 

I never understood this issue that I had, and I don't think I ever will. PMS up through 1.17.xxxx worked just fine with history, and 1.18.xxxx never did. As soon as I reverted back to 1.17.0.1841 and hit update plex, all history was properly updated.

I had updated Python to 2.7.17, and all pip related tools to their latest as well. I tried a fresh install fo SickGear, and I even tried the dev branch. The logs looked the same in SickGear: the program pulls from Plex's database, multiple times/attempts. Then tells me there are 0 shows updated. Maybe the hard drive as always the issue?

Anyways, thanks for your help. Might as well close this up for good.

**Comment by JackDandy** [comment]
Hi,

I did see an issue where an error would happen if the Server IP:Port did not begin with http(s). That is now fixed that, but i have just seen another issue if plex auth server is down and where auth is required, so the next release will fix that by outputting something useful for that scenario.

**Comment by OrGoN3** [comment]
Thanks so much for your feedback. I actually tested the version with the http fix. I also tried without auth (same network, same computer, so I don't require auth in Plex). That didn't work. 

I also created a thread on the Plex forums in case someone else had the same issue. No bites yet.

I'm hoping to recover my database file. If not I'll be starting fresh. Thanks again!

**Comment by JackDandy** [comment]
fwiw: Check this wiki answer [What to check if "Test Plex Server" fails](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#testplexserver)

**Comment by JackDandy** [comment]
Ok, I'm happy that everything is working correctly.

Another user also fed back that things are working 100% properly as they should be - I cannot suspect any issue with Plex or SG.

One thing I noticed during tests... if a media file is deleted before SG knows about its existence, but Plex knows about it, then that episode will not be recognised by SG as watched. Therefore, SG will not list it. This can happen if SG is not processing and not telling Plex that the file exists to begin with via the notifications mechanisms - this is something I don't expect to be happening with you - but is worth a mention, just in case.

So, I feel the symptom you saw was probably caused by your HD failure.

That said, the minor config issue was fixed, so that's a bonus.

Thanks for your report though, i will now mark this issue `Complete`.

**Comment by OrGoN3** [comment]
Thanks so much for your investigation and all of your support. Fwiw I often checked the Plex connection through sick, and it always was successful.

I also think it's the hard drive and perhaps one of the other fixes you already pushed.

Thanks again for your support and for continuing this project.

**Comment by JackDandy** [comment]
Perhaps update your post on Plex to lay the issue to rest and not confuse others.
