### ISSUE TITLE
"Add show" not working for me

### ISSUE THREAD

**Issue by BhaalM** [SickGear/SickGear#1208]
#### Branch version commit hash: c69affb @ 0.20.7

Expectation | Result
------------ | -------------
After successfully finding a show, when I select "Add show" I would expect  to add this show to my show list | The show is not added

**Steps to reproduce:**
*1)* Go to add show menu
*2)* Search for a show, for example "Doom patrol" (it happened with all the titles I tried)
*3)* Select one of the results
*4)* Click "Add show"

LOG:

`2019-11-16 21:49:02 ERROR    SHOWQUEUE-ADD :: Show Doom Patrol was not found on TheTVDB, maybe show was deleted
2019-11-16 21:49:02 INFO     SHOWQUEUE-ADD :: TheTVDB: {'apikey': 'F9C450E78D99172E', 'cache': '/volume1/@appstore/sickbeard-custom/var/cache/indexers/TheTVDB', 'language': 'en'}
2019-11-16 21:49:02 INFO     SHOWQUEUE-ADD :: Starting to add show /volume1/video/Series/Doom Patrol`

Additional notes:
I'm using SickGear in a Synology

**Comment by anoma** [comment]
TVDB very sick this now. Likely that.

**Comment by curbro** [comment]
It looks like TheTVDB have updated their API to only return JSON responses and stopped providing anything back in XML. Everything that integrates with it is broken. Hopefully SickGear gets updated to use the new API.

**Comment by Neomaster67** [comment]
The issue isn't just with adding new shows. SickGear now reports that the shows I have listed have abandoned ID's, and that they will be ignored. Back to a manual process in the interim. :(

**Comment by Neomaster67** [comment]
The issue isn't just with adding new shows. SickGear now reports that the shows I have listed have abandoned ID's, and that they will be ignored. Back to a manual process in the interim. :(

**Comment by JackDandy** [comment]
Hi,

fyi SickGear collects info across the early to latest API versions for a spread of info. 

We've seen service disruption at both api's. 

Changes this week to thetvdb api meant only a subset of expected data was returned from a request to TVDb API.  Other issues have also been reported in the TVDb community, so ignore warnings in the SG UI currently. Hopefully, things should clear up soon with the tvdb API.

**Comment by kevin201** [comment]
Thanks Jack, your continued support is much appreciated!

**Comment by kevin201** [comment]
Still waiting for my 90 odd shows to update. So far, removing and re-adding seems to be the only solution for me.

**Comment by JackDandy** [comment]
Yeah, that was a mistake to do that. Repeated from other threads, **take no action, just wait**

We are aware of the TVDB issues, they are still fixing some and others are low/no priority. SG does have changes in the pipeline. expected a release today.

**Comment by kevin201** [comment]
Only did it with two shows to test. The other 90 are still waiting. Not a problem, will carry on waiting! You carry on the great work!

**Comment by JackDandy** [comment]
TVDB issues seem to be settled, a new SG build today adds improved support.
