### ISSUE TITLE
Shows are showing abandoned Master ID 

### ISSUE THREAD

**Issue by Beetrstand** [SickGear/SickGear#1209]
#### Branch version commit hash: c69affb @ 0.20.7

Expectation | Result
------------ | -------------
When I check the show process tab I expect the shows to be correctly matched to a master id | Currently I have 104 shows showing: The master ID of this show has been abandoned since 11/15/2019
search for a replacement in the "Related show IDs" section of the "Other" tab

**Steps to reproduce:**
*1)* Updated and Restarted SickGear and Show Processes started showing the error
*2)* Viewed shows and confirmed it is the same Master ID as in the TVDB currently.
...

I confirmed shows Master ID had not changed in TVDB and when I go to try and correct it via the Search it shows the original show saying exists in DB and i cannot select it

Additional notes:
As this just started occurring not sure if it an API reset or perhaps something on the TVDB end.

**Comment by fredamn76** [comment]
It seems that thetvdb has moved to version 3 of their API. 
https://forums.plex.tv/t/notice-metadata-using-tvdb-agent/491272
https://forums.thetvdb.com/viewtopic.php?f=3&t=60048

**Comment by JackDandy** [comment]
Hi,

please read [my reply here](https://github.com/SickGear/SickGear/issues/1208)

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
