### ISSUE TITLE
add support for version 3 of thetvdb api

### ISSUE THREAD

**Issue by fredamn76** [SickGear/SickGear#1210]
Add support for version 3 of thetvdb API.

**Comment by JackDandy** [comment]
SG already supports the latest api version.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
The latest SG adds improved support for API v3.
