### ISSUE TITLE
TheTVDB API error resulting in spurious "abandoned ID" messages

### ISSUE THREAD

**Issue by infogrind** [SickGear/SickGear#1211]
#### Branch: The name of the branch (e.g. master or develop)
master

#### Branch version commit hash: (See the About page)
c69affb

This is to report a currently open issue with TheTVDB's API, which results in series information requests resulting in a 404 "not found" response from the API. (This is tracked in https://forums.thetvdb.com/viewtopic.php?f=17&t=60121)

The consequence for SickGear is that since about November 15, 2019, shows may be shown with a warning like "The master ID of this show has been abandoned since 11/16/19, replace it here".

I post this here to make others who have the same problem aware of the root cause. I hope that once TheTVDB folks fix their API, SickGear will no longer be marking shows as abandoned.

**Comment by Merwenus** [comment]
Didn't TheTVDB admins write they fixed it already this morning?

**Comment by infogrind** [comment]
I haven't seen anything from the TheTVDB admins, but then I didn't know where to look so I just checked the forums. Can you post a link to the communication you refer to?

I just checked again:

- This works: https://api.thetvdb.com/series/121361/episodes
- This doesn't work: https://api.thetvdb.com/series/121361

So it doesn't look like it's been fixed.

**Comment by jackmetal** [comment]
Was just about to post a bug, but saw you beat me to it.  Thanks!

**Comment by Merwenus** [comment]
Fair enough, misread it, my bad:

[https://forums.thetvdb.com/viewtopic.php?f=3&t=60048](https://forums.thetvdb.com/viewtopic.php?f=3&t=60048)

**Comment by infogrind** [comment]
No worries. The issue is now being raised in a couple of threads in the [V3 API update forum](https://forums.thetvdb.com/viewforum.php?f=122), but there is nothing about a resolution yet.

**Comment by JackDandy** [comment]
Hi,

fyi SickGear collects info across the early to latest API versions for a spread of info.

Our continued tests are showing service disruption at both api's is still ongoing at this time.

Ignore warnings in the SG UI currently. Hopefully, things should clear up soon with the tvdb API.

SG will still continue to work as normal with the data it has already carries, and will keep trying to update infos in the background, and has already done so in many cases.  Some new api information has been available for a couple of hours.. but other data sets have not so good results.

Thanks community for feeding the helpful updates and info into this thread.

JD

**Comment by janngobble** [comment]
Unfortunately I could not get them to go away when I tried to "update the master id" so I (stupidly) deleted 4 series. I then re-added them. They are all showing as "Loading... (The Crown)" for instance...
Assuming this will fix when the API starts working again?

I'm not blaming SG... this was ALL on the TVDB... I had to rewrite my own file-tagging-code (in another program) to work past their api "failures" yesterday morning - so forgive me if I'm a bit bitter right now ;)

**Comment by JackDandy** [comment]
> **Ignore warnings in the SG UI currently. Hopefully, things should clear up soon with the tvdb API.**

**Comment by Beetrstand** [comment]
I will say I appreciate this being opened in a way a whole lot better than I did. Nice to see the community working together and providing the info to the rest of us.

**Comment by ubuntu748** [comment]
Just checked this morning and all seems to be working as expected. No shows are showing as deleted and I can add shows without problems.

Kodi was also posting a comment on this
"18 Nov 2019- TVDB are still in the process of fixing a number of bugs that have broken the TVDB scraper and any add-on that relies on TVDB data. TVDB are still working to rectify the problems."

So looks like it has been fixed.

**Comment by Merwenus** [comment]
New shows added without thumbnails, but at least no error messages.

**Comment by janngobble** [comment]
All the spurious "update the master id" errors are gone ...and it seems that *most* queries are working fine again.

**Comment by infogrind** [comment]
> it seems that _most_ queries are working fine again

What is not working yet, that would warrant to keep this issue open?

**Comment by janngobble** [comment]
This issue should be closed. It is not that the abandoned ID messages are an issue anymore, it’s that their API is returning “absolute order” or episodes vs regular order.

We can open up a new ticket to see how SG should deal with that - indeed if it should.

For instance: The Good Place (311711) returns 15 episodes in S01, (adding abs order # E15 & E28) even though it should only be E01-E13 in s01.

This  has been mentioned in the forums at tvdb (and experienced by me) but only quirky work-arounds have been offered as solution by users - and no answer by devs if this is intended behavior or not.
see:
https://forums.thetvdb.com/viewtopic.php?p=163597#p163597

Let me know if anyone thinks this should be new issue. I tend to think it's something we should be concerned about - if SG can do a quick patch to avoid grabbing absolute order. If not, I don't know.

**Comment by infogrind** [comment]
Let me close this issue, because the specific problem it refers to has been solved. If I were you I'd create a new issue for the ordering issue in any case, no harm done if it turns out not to be needed.

**Comment by JackDandy** [comment]
TVDB issues seem to be settled, a new SG build today adds improved support.
