### ISSUE TITLE
Unable to open History page

### ISSUE THREAD

**Issue by 0bliv1an** [SickGear/SickGear#1212]
#### Branch: The name of the branch (e.g. master or develop)
master
#### Branch version commit hash: (See the About page)
c69affb @ 0.20.7

Expectation | Result
open the history page
https://localhost:8082/history/ 

| -------------
Error

time data '0' does not match format '%Y%m%d%H%M%S'
Traceback

Traceback (most recent call last):
File "D:\SickGear\SickGear\lib\tornado\web.py", line 1592, in _execute result = yield result
File "D:\SickGear\SickGear\lib\tornado\gen.py", line 1133, in run value = future.result()
File "D:\SickGear\SickGear\lib\tornado\concurrent.py", line 261, in result raise_exc_info(self._exc_info)
File "D:\SickGear\SickGear\lib\tornado\gen.py", line 307, in wrapper result = func(*args, **kwargs)
File "D:\SickGear\SickGear\sickbeard\webserve.py", line 690, in get result = method(**kwargss)
File "D:\SickGear\SickGear\sickbeard\webserve.py", line 5493, in index return t.respond()
File "D:\SickGear\data\cache\cheetah\_SickGear_SickGear_gui_slick_interfaces_default_history_tmpl.py", line 225, in respond _v = VFN(VFFSL(SL,"sbdatetime.sbdatetime",True),"sbfdatetime",False)(VFN(VFFSL(SL,"datetime.datetime",True),"strptime",False)(str(VFFSL(SL,"earliest",True)), VFFSL(SL,"history.dateFormat",True))) # u'$sbdatetime.sbdatetime.sbfdatetime($datetime.datetime.strptime(str($earliest), $history.dateFormat))' on line 62, col 47
File "C:\Python27\lib\_strptime.py", line 332, in _strptime (data_string, format))
ValueError: time data '0' does not match format '%Y%m%d%H%M%S'
Request Info

body:
files: {}
protocol: https
connection:
body_arguments: {}
uri: /history/
query_arguments: {}
_start_time: 1574039634.97
headers: Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate, br Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 User-Agent: Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0 Host: localhost:8082 Cookie: snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_top_dvd_rentals_view=thumb; imdb_top_250_movies_view=thumb; wanted_view=list; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; manage_view=list; advanced_toggle_checked=1; user="2|1:0|10:1571608291|4:user|44:ZjE4OTRkMDliM2ZiNGIwY2E1OGVhMzk5NDRiMDFlZTE=|04b037ec176b988ba7fbda6453a9ae8d54cfd6402b6d8eb1a7ce2f2aa95a5b58"; _xsrf=2|9b3a53b0|256e11c9ce30f442bfb94bfd6af67377|1574033141; sickgear-session-cf888b76944a4bc70251d5bb9e4093f9="2|1:0|10:1574038365|49:sickgear-session-cf888b76944a4bc70251d5bb9e4093f9|60:NmNWaVJUQTNSMytnRDU4VkVVc0tZcGFTekw1OFkwcitua0drVVZqemNvMD0=|51ff5901ec5def886351d82934a67b64f2e8e558ec62050614c761c232900846" Upgrade-Insecure-Requests: 1 Authorization: Basic aWFuOmx5bndlc3RTaGF6YW04NQ==
host: localhost:8082
version: HTTP/1.1
server_connection:
host_name: localhost
_finish_time: None
query:
arguments: {}
path: /history/
_cookies: Set-Cookie: _xsrf=2|9b3a53b0|256e11c9ce30f442bfb94bfd6af67377|1574033141 Set-Cookie: advanced_toggle_checked=1 Set-Cookie: blu_ray_com_new_releases_view=thumb Set-Cookie: imdb_box_office_view=thumb Set-Cookie: imdb_movies_in_theaters_view=thumb Set-Cookie: imdb_top_250_movies_view=thumb Set-Cookie: imdb_top_dvd_rentals_view=thumb Set-Cookie: late_view=list Set-Cookie: manage_view=list Set-Cookie: sickgear-session-cf888b76944a4bc70251d5bb9e4093f9="2|1:0|10:1574038365|49:sickgear-session-cf888b76944a4bc70251d5bb9e4093f9|60:NmNWaVJUQTNSMytnRDU4VkVVc0tZcGFTekw1OFkwcitua0drVVZqemNvMD0=|51ff5901ec5def886351d82934a67b64f2e8e558ec62050614c761c232900846" Set-Cookie: snatched_view=list Set-Cookie: soon_view=thumb Set-Cookie: suggest_view=thumb Set-Cookie: user="2|1:0|10:1571608291|4:user|44:ZjE4OTRkMDliM2ZiNGIwY2E1OGVhMzk5NDRiMDFlZTE=|04b037ec176b988ba7fbda6453a9ae8d54cfd6402b6d8eb1a7ce2f2aa95a5b58" Set-Cookie: wanted_view=list
method: GET
remote_ip: 127.0.0.1

Additional notes:
This is a fresh install today, it was working for about the first hour or so, and now this. 
Restarted SG a few times, no change.

This is what the logs show
ERROR    TORNADO.APP :: Uncaught exception GET /history/ (127.0.0.1)
 1) HTTPServerRequest(protocol='https', host='localhost:8082', method='GET', uri='/history/', version='HTTP/1.1', remote_ip='127.0.0.1')
 2) Traceback (most recent call last):
 3)   File "D:\SickGear\SickGear\lib\tornado\web.py", line 1592, in _execute
 4)     result = yield result
 5)   File "D:\SickGear\SickGear\lib\tornado\gen.py", line 1133, in run
 6)     value = future.result()
 7)   File "D:\SickGear\SickGear\lib\tornado\concurrent.py", line 261, in result
 8)     raise_exc_info(self._exc_info)
 9)   File "D:\SickGear\SickGear\lib\tornado\gen.py", line 307, in wrapper
10)     result = func(*args, **kwargs)
11)   File "D:\SickGear\SickGear\sickbeard\webserve.py", line 690, in get
12)     result = method(**kwargss)
13)   File "D:\SickGear\SickGear\sickbeard\webserve.py", line 5493, in index
14)     return t.respond()
15)   File "D:\SickGear\data\cache\cheetah\_SickGear_SickGear_gui_slick_interfaces_default_history_tmpl.py", line 225, in respond
16)     _v = VFN(VFFSL(SL,"sbdatetime.sbdatetime",True),"sbfdatetime",False)(VFN(VFFSL(SL,"datetime.datetime",True),"strptime",False)(str(VFFSL(SL,"earliest",True)), VFFSL(SL,"history.dateFormat",True))) # u'$sbdatetime.sbdatetime.sbfdatetime($datetime.datetime.strptime(str($earliest), $history.dateFormat))' on line 62, col 47
17)   File "C:\Python27\lib\_strptime.py", line 332, in _strptime
18)     (data_string, format))
19) ValueError: time data '0' does not match format '%Y%m%d%H%M%S'

**Comment by 0bliv1an** [comment]
nevermind.
I opened the history via https://localhost:8082/history/?layout=compact and it worked
and then every other view now seems to be working again, including https://localhost:8082/history/

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.20.10)
