### ISSUE TITLE
Adding show fails with TVDB error message

### ISSUE THREAD

**Issue by badboybeyer** [SickGear/SickGear#1213]
#### Branch: The name of the branch (e.g. master or develop)

develop

#### Branch version commit hash: (See the About page)

799e9ec9a268f165868493839fc3e808a92f9761

Expectation | Result
------------ | -------------
Added show appears in show list | Error emitted: "Show in /path/to/shows/The Mandalorian has no name on TheTVDB, probably the wrong language used to search with." and the show does not appear in show list

**Steps to reproduce:**
*1)* Search for the show "mandalorian" in the "Shows" -> "Add Show..." -> "search" dialog box 
*2)* Wait for the "add from TV info source" page to find the single show result: "Mandalorian (The) (started: 2019-11-12) [TheTVDB via Trakt]" 
*3)* Press the "Add Show" button
*4)* Wait for the error "Show in /path/to/shows/The Mandalorian has no name on TheTVDB, probably the wrong language used to search with." to emit
*5)* Confirm that the show does not appear in the "Show List" page

[log file](https://gist.github.com/badboybeyer/5cc0e12630d554e6d10d32bbb17477ae)

* Using language "en" in search
* Same error for any show attempted

**Comment by JackDandy** [comment]
Hi,

As a test, I just added 371668 from the Trakt cards view - worked fine.

No doubt you are experiencing issues, but, the new changes to TVDB API this last week will probably still be in a state of oddness so we're still watching, and running tests.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
Not in current user interface.

**Comment by badboybeyer** [comment]
It looks like sickgear has a vendored tvdb api with logging. It doesn't look like the logger has a handler. I got it to dump to console with a small change:
```
--- a/sickbeard/indexers/indexer_config.py
+++ b/sickbeard/indexers/indexer_config.py
@@ -1,3 +1,5 @@
+import logging
+logging.basicConfig(level=logging.DEBUG)
 from lib.tvdb_api.tvdb_api import Tvdb
 from lib.tvdb_api_v1.tvdb_api import TvdbV1
 from lib.libtrakt.indexerapiinterface import TraktIndexer
```

Sickgear is getting a 401 from its tvdb api calls:

<pre>
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.thetvdb.com:443
DEBUG:urllib3.connectionpool:https://api.thetvdb.com:443 "GET /search/series?name=mandalorian HTTP/1.1" 401 26
DEBUG:lib.cachecontrol.controller:Status code 401 not in (200, 203, 300, 301)
</pre>

I am also getting a 401 with wget to "https://api.thetvdb.com/search/series?name=mandalorian".

I guess the next step is to figure out why sickgear isn't authorizing to with the tvdb.

**Comment by JackDandy** [comment]
Yeh, we already fixed that internally, the public release will come soon.

**Comment by JackDandy** [comment]
TVDB issues seem to be settled, a new SG build today adds improved support.

**Comment by badboybeyer** [comment]
I still am getting 401s from tvdb api calls through sickgear. The requests library is rewriting the TVDB's authorization headers into an HTTP basic authorization header. [Here is my work around.](https://gist.github.com/badboybeyer/839bee6b5eb58f9a3abe48cdfe4e0150)

**Comment by JackDandy** [comment]
@badboybeyer we have confusion about your suggested change.  The problem is that we cannot replicate an issue, however, there have been reports on TVDB about a 401 issue. Therefore, are you absolutely, positively, 100% sure that your change works at your side ?

**Comment by badboybeyer** [comment]
Yes, I am positive. I added print debugging in `sickbeard/helpers.py`, `lib/tvdb_api/tvdb_api.py` and `lib/urllib3/connectionpool.py`. I was able to verify that the authorization headers given to `session.get` in `getURL` line 1122 of `helpers.py` were rewritten to a basic authorization by the time that `urllib3` was calling the `request` method of an `HTTPConnection`. This was an invalid authorization string, and was refused by the tvdb api and caused the 401.

I made a simplified version of `tvdb_api.py` to demonstrate this behavior of the requests library. Maybe you can reproduce my failure with this script? I also included a Pipfile in case my environment is important. [gist](https://gist.github.com/badboybeyer/1b50ce5496685f22341139e4c5e0c53b)

**Comment by badboybeyer** [comment]
I decoded the basic auth, and it looks like requests is using the `default` entry from my `.netrc` configuration. Maybe try creating a `.netrc` file in your users home directory with the contents:  `~/.netrc`

```
default
login anonymous
password nonone@nowhere.com
```

**Comment by badboybeyer** [comment]
Please review the [requests documentation](https://2.python-requests.org/en/master/user/authentication/) about authorization and the .netrc file: 

> netrc Authentication
> If no authentication method is given with the auth argument, Requests will attempt to get the authentication credentials for the URL’s hostname from the user’s netrc file. The netrc file overrides raw HTTP authentication headers set with headers=.
> 
> If credentials for the hostname are found, the request is sent with HTTP Basic Auth.

**Comment by JackDandy** [comment]
okay, test... in your `reproduce.py` add `session.trust_env = False` before the `session.get(...)`

**Comment by badboybeyer** [comment]
That fixes the issue and is simpler than my proposed solution.

**Comment by JackDandy** [comment]
Fix pushed to both master and develop branches.

Thank you for your lead direction in helping to fix this 😃
