### ISSUE TITLE
Feature request - Post Process -  Move associated files (only subtitles)

### ISSUE THREAD

**Issue by Merwenus** [SickGear/SickGear#1214]
config/postProcessing/Move associated files
move srr/srt/sfv/etc files with the episode when processed

Please give an option to decide what files should sickgear postprocess (even in config.ini). for example:
Post process only SRT/ASS/subtitle files, but skip NFO/SFV/etc files.

Thank you

**Comment by JackDandy** [comment]
There is an option "Move associated files" in post processing setting, what are you considering for this feature request is a nice way to handle if that existing setting is not sufficient?

**Comment by Merwenus** [comment]
When I tick the Move Associated files in sick gear, it copies NFO files too:
Family.Guy.S17E09.Pawtucket.Pete-SickGear.mkv
Family.Guy.S17E09.Pawtucket.Pete-SickGear.**nfo**

Spamming the folders with NFO files. I'm not talking about the **tvshow.nfo** I talk about the episode nfo files beside the MKV files.

**Comment by JackDandy** [comment]
maybe enable this...

<img src="https://i.vgy.me/qsEOcB.png">

**Comment by Merwenus** [comment]
But I don't want any NFO there, I only want subtitle files, this will make even more NFO files, or not?

**Comment by JackDandy** [comment]
so disable "move associated files", and don't enable the above nfo that kodi uses.

**Comment by Merwenus** [comment]
Disabling it wont copy subtitle files. I'm not a programmer, but a regexp can't help it, and make variable in config.ini? :)

**Comment by JackDandy** [comment]
Ok, you have an issue with very small associated files being copied, you don't want the original release nfo, yet i told you how to overwrite the original release nfo with a kodi generated one via meta settings. I would personally enable move associate files and have the meta creation. That is the best you can have in this situation for now, until there is time to look at this.

**Comment by JackDandy** [comment]
I may have a lead on this, if you are still interested to test an idea, let me know.

**Comment by Merwenus** [comment]
I'm using docker, I can test anything there, if you provide a container.

**Comment by JackDandy** [comment]
There is our official docker **updates_enabled** build which allows developers and advanced users to test custom branches.  If you confirm that you can access and run this container, then I will push the test.

**Comment by Merwenus** [comment]
Alright, made a backup, renamed and stopped my current SickGear and instaled sickgear/sickgear:develop
Up and running, so far without errors, so whats next?

**Comment by JackDandy** [comment]
Go to settings/General/Advanced under drop down "Branch version" select "hotfix/0.21.23", then click btn Checkout Branch... SG will restart and the about page will show the new branch.

On settings/media process, disable "Move associated files", then save.

Do your test to see if the issue your originally reported is now fixed. That is, no files except subtitle files should be moved with the release file _provided_ that subtitles are enabled.

**Comment by Merwenus** [comment]
Version: | BRANCH: master @ py2.7.17 / COMMIT: docker  @ 0.22.0
This is BETA software
sickgear/sickgear:develop docker

I must have done something wrong, because I have no Branch version dropdown list:
[https://i.imgur.com/6vOmf1t.png](url)

**Comment by JackDandy** [comment]
yeah `Version: | BRANCH: master` is wrong - and I know this works.

**Comment by JackDandy** [comment]
one thing you could try is tochange "master" to "devel" in your config.ini

**Comment by JackDandy** [comment]
one thing you could try is to change "master" to "develop" in your config.ini, then restart sg.

i cannot help you further here as the other docker user was able to trigger this fine, but i guess he was using a fresh config files. 

therefore, all i can suggest is to install somewhere the devel version from git external to docker to do the test or you simply cannot test any changes.

**Comment by Merwenus** [comment]
BRANCH: develop @ py2.7.17 / COMMIT: docker @ 0.22.0
This is BETA software
But still no branch option in general/advanced.

**Comment by JackDandy** [comment]
again, as i said, 

_install somewhere the devel version from git external to docker to do the test or you simply cannot test any changes._

**Comment by JackDandy** [comment]
You posted,
> Post process only SRT/ASS/subtitle files, but skip NFO/SFV/etc files.
  
You posted,
> I don't want any NFO there, I only want subtitle files
  
Reply,
> disable "move associated files"
  
You posted,
> Disabling it wont copy subtitle files

Actually, according to tests made today, your statement is incorrect.  
  
Under tests...
1) settings Media Process/"move associated files" is disabled (off).
2) settings Subtitles/Search Subtitles is enabled (on).
3) edit show -> "Subtitles" is enabled (on).

a test, manual Manage/"Process Media" with method `Copy`, copied **both** a `release.mkv` file and a `release.srt` file, the `release.nfo` file was **not** copied.  
  
Perhaps your files were faulty; maybe your original subtitle file contained a space before the file extension, or some other filename anomaly that prevented SG from associating the subtitle file with the release file.

I haven't heard back from you regarding your test, therefore, because I have now completed tests successfully, unless you can show me steps to demonstrate an issue, then I will have to consider this thread invalid.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
posted a note about this here... https://github.com/SickGear/SickGear/wiki/Settings#associated

this thread will now be deleted
