### ISSUE TITLE
Unable to configure providers on Synology

### ISSUE THREAD

**Issue by canepan** [SickGear/SickGear#1218]
#### Branch version commit hash: BRANCH: master / COMMIT: 497caeb @ 0.20.11

Hello, I am new to SickGear (previously I used SickRage), and I am trying to set it up on my Synology DSM 6.

Expectation | Result
------------ | -------------
I was expecting to find, under settings, a way to enable search providers and download providers | no list of available providers anywhere

I tried to look both under "Media providers" and under "Search settings", with no luck

**Steps to reproduce:**
*1)* Install SickGear via "SickBeard custom" and the SickGear URL: git://github.com/SickGear/SickGear.git
*2)* Go to configuration

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
<img src="https://i.vgy.me/G2T50V.png">
<img src="https://i.vgy.me/Xb8uab.png">
Then Save.

**Comment by JackDandy** [comment]
Answer add [here](https://github.com/SickGear/SickGear/wiki/Settings#name)

**Comment by JackDandy** [comment]
Answer added [here](https://github.com/SickGear/SickGear/wiki/Settings#name)
