### ISSUE TITLE
Allowed browser hostnames unexpected behaviour

### ISSUE THREAD

**Issue by boredazfcuk** [SickGear/SickGear#1219]
#### Branch version commit hash: 6f228e0 @ 0.21.0

Expectation | Result
------------ | -------------
Entering a list of hostnames into "General Settings >  Interface > Web  Interface> Web Interface >Allowed browser hostnames" restricts the WebGUI so it can only be accessed if the request is made to a hostname in that list. | If a single hostname is entered (e.g. allowed_hosts = "test1") it will correctly respond to http://test1:8081/. However, if multiple hostnames are entered (e.g allowed_hosts = "test1, test2") then the WebGUI will not respond to any of the listed hostnames.

**Steps to reproduce:**
*1)* create Docker container from sickgear/sickgear with 8081 port published on host
*2)* Shut down container
*3)* Edit container's config.ini with **allowed_hosts = "test1, test2, test3, test4"**
*4)* Start container
*5)* Edit local computer's hosts file so test1, test2, test3 and test4 resolve to Docker host
*6)* Attempt to access SickGear on http://test1:8081, http://test2:8081 etc.
...

Additional notes:
If configured with a webroot of /sickgear, then SG will respond to http://sickgear:8081/sickgear even if allowed_hosts does not include the hostname "sickgear". SG also always responds to requests made to an IP address. If SG is listening on 192.168.2.222:8081 inside the container, it will still respond if a request is made to the host's forwarded port eg 192.168.1.111:8081. I would expect to be able to input the host's and the container's IP addresses into "allowed_hosts" to prevent it responding to anything else. I have not tested to see if it responds to requests made to public addresses, rather than just private ones.

**Comment by JackDandy** [comment]
Thanks for the report.

I'm not actually sure of the history of this setting, or even if it gives any value. I think we will remove it as it seems like some stupid legacy guff.

**Comment by JackDandy** [comment]
Okay, I have a fix for the issue In regards to IPs, the settings has nothing to do with IPs. It is allowed hostnames as the label says.
Multiple hostnames has now been fixed and will be in the next release.

**Comment by JackDandy** [comment]
In regards to IPs, the settings has nothing to do with IPs. It is allowed hostnames as the label says.
Multiple hostnames has now been fixed and will be in the next release.

**Comment by JackDandy** [comment]
In regards to IPs, the settings has nothing to do with IPs. It is allowed **hostnames** as the label says.
Multiple hostnames has now been fixed and will be in the next release.

**Comment by boredazfcuk** [comment]
Thanks for the fix already. That was super fast.

I did wonder whether allowed_hostnames accepted IP addresses or not, but presumed it would do. The 'allowed_hostnames' option seems a bit ineffective if the WebGUI always responds to requests made to the IP address.

Would it be possible to change allowed_hostnames to be check box option? When activated, the text input box appears for the hostnames and underneath is a second check box. The second check box would restrict WebGUI IP address access to the private address ranges only (10.0.0.0/8, 172.16.0.0/12 and 192.168.0.0/16).

This would prevent the WebGUI responding to requests to the IP address which are coming from the internet. The vast majority of unwanted scans against my server are to its IP and not its hostname.

In regards to the webroot issue, I think this is something to do with the SSL certificate I'm auto-generating in my Docker container. I'm generating it like this:

```
openssl req -new -subj "/C=NA/ST=Global/L=Global/O=SickGear/OU=SickGear/CN=SickGear/" -key "${CONFIGDIR}/https/sickgear.key" -out "${CONFIGDIR}/https/sickgear.csr"
```
This results in a cert with a CommonName of SickGear. 

Presumably it's responding on https://sickgear:8081/sickgear, even when it's not configured as an allowed hostname, because it matches the certificate name? I still wouldn't expect it to respond on https://sickgear:8081 without explicitly setting it in allowed_hosts though.

**Comment by JackDandy** [comment]
I think you should run SG in reverse proxy mode at the level you are talking about, and what you are wanting to achieve.

**Comment by JackDandy** [comment]
I think you should run SG in reverse proxy mode at the level you are talking about, and what you are wanting to achieve. Something like NGinX will provide for your needs, see the WIKI install page for help on setting that up with your SSL cert. And then look into NGinX config to restrict access the way you want.

**Comment by boredazfcuk** [comment]
I'm already running an nginx reverse proxy. That has a LetsEncrypt SSL cert and is public facing. The cert I'm generating in my SickGear container is so I have end to end encryption.

Yes, I could configure nginx to workaround the issue, but ultimately it's SickGear that's behaving improperly so I thought it would be best to report it here.

**Comment by JackDandy** [comment]
Yeah, the main issue is testing change - if you are able to come to IRC, then something can be done.

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.20.12)

**Comment by boredazfcuk** [comment]
Fantastic. I'll set aside some time tonight and check it out. Thank you.
