### ISSUE TITLE
Synology DSM GIT-errors

### ISSUE THREAD

**Issue by Wee-bear** [SickGear/SickGear#1221]
#### Branch version commit hash: f4984bb @ 0.20.12
Version says master branch yet also says beta software??

Expectation | Result
Hello Jack,
  It has been a while, don't know if you remember me but I am the guy you were accessing via VSAT to work on the Synology part of SG.  I am now in Canada and just moved my DiskStation over to SickGear and it is throwing some errors you might be interested in. | Please make sure you have the correct access rights
and the repository exists.
2019-12-15 19:44:34 TORNADO :: git ls-remote --heads None returned : fatal: 'None' does not appear to be a git repository
fatal: Could not read from remote repository.

It is currently importing my shows that I previously downloaded with SickRage. 

Secondly If you could point me to the page or let me know how to name the Specials for show.  It does not seem to be coming in on the import.  I have put them all in "Season 00" as per what I have previously done with Sick Gear.
Blessings and an early wish for a Merry Christmas,
   Paul Weber

...

**Comment by JackDandy** [comment]
Of course i remember you, hope you are well, and a merry xmas to you too :)

Your first point [read here](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#cannot-switch-branch)

Nothing has changed on how specials are managed - i can't even remember.

**Comment by JackDandy** [comment]
Finally, the DSM updated code tested on your system - thank you - is now merged [here](https://github.com/SickGear/SickGear/releases/tag/release_0.20.15)

Merry Christmas :)
