### ISSUE TITLE
Logfile: WARNING  SHOWQUEUE-REFRESH :: 77750: Error changing modify date of <File with UTF-8 name> to show air date Sep 03,1992 (00:00)

### ISSUE THREAD

**Issue by gdevenyi** [SickGear/SickGear#1222]
#### Branch: The name of the branch (e.g. master or develop)
develop
#### Branch version commit hash: (See the About page)
5401b4b

Expectation | Result
------------ | -------------
No error in logfile | Error in logfile

**Steps to reproduce:**
*1)* Delete .nfo file for video with UTF-8 filename
*2)* Run mass update->rescan on series to re-generate metadata nfo
...

Following up on failure to properly create NFO files with UTF-8 filenames reported earlier, I've now run into this issue with these newly generated files which were previously missing due to the previous bug now throw a warning on the modified time/date being updated. I presume the same wrapper code around filenames need to be applied to that codepath.

**Comment by JackDandy** [comment]
No response about testing the previous issue.
I dont understand this issue.

**Comment by gdevenyi** [comment]
> No response with a promised test result of the previous fix.

Excuse me?

I presume you're talking about the previous issue, which appears to have been deleted after first marking it as invalid before finally pushing a hotfix that fixed it. I cannot reference it because it is now gone. After which, we had a quick discussion about how to generate the missing NFO files, which was successful (thank you), but now throws this warning.

I can say, this function (or a similar one) does work on the video files, which have had their dates adjusted to the airdate.

**Comment by JackDandy** [comment]
The thread was tagged `invalid`, and that tag later revoked. You requested further help while ignoring a clear request for feedback on the fix. Therefore, the thread was deemed low value and deleted. Look, without simple clear back and forward comms, our time and effort is wasted.

**Comment by gdevenyi** [comment]
Wow. I am speechless.
