### ISSUE TITLE
snapd doesn't restart sickgear after updating it

### ISSUE THREAD

**Issue by JensTimmerman** [SickGear/SickGear#1224]
#### Branch version commit hash: snap @ 0.20.14

Expectation | Result
------------ | -------------
after snap updates sickgear, sickgear is restarted so the new version is running| the old sickgear is still running, but because snap has removed the underlying directory it fails with errors on finding template files.

**Steps to reproduce:**
*1)*install centos 7.12; yum install snapd;  snap install sickgear
*2)* vim  /etc/systemd/system/sickgear.service: 
[Unit]
Description=sickgear daemon
After=network.target

[Service]
User=root
Group=root
WorkingDirectory=/snap/sickgear/current/sickgear/
ExecStart=/var/lib/snapd/snap/bin/sickgear

[Install]
WantedBy=multi-user.target
*3)* service sickgear start
*4)* wait for snap to update sickgear
*5)* see errors when visiting sickgear's url :  no such file or directory /snap/sickgear/539/sickgear/...

```
2019-12-23 17:08:23 ERROR    TORNADO.APP :: Uncaught exception GET /about (192.168.122.1)
 1) HTTPServerRequest(protocol='http', host='192.168.1.202', method='GET', uri='/about', version='HTTP/1.0', remote_ip='192.168.122.1')
 2) Traceback (most recent call last):
 3)   File "/snap/sickgear/539/sickgear/lib/tornado/web.py", line 1592, in _execute
 4)   File "/snap/sickgear/539/sickgear/lib/tornado/gen.py", line 1133, in run
 5)   File "/snap/sickgear/539/sickgear/lib/tornado/concurrent.py", line 261, in result
 6)   File "/snap/sickgear/539/sickgear/lib/tornado/gen.py", line 307, in wrapper
 7)   File "/snap/sickgear/539/sickgear/sickbeard/webserve.py", line 696, in get
 8)   File "/snap/sickgear/539/sickgear/sickbeard/webserve.py", line 686, in page_not_found
 9)   File "/snap/sickgear/539/sickgear/sickbeard/webserve.py", line 121, in __init__
10)   File "/snap/sickgear/539/lib/python2.7/site-packages/Cheetah/Template.py", line 1337, in __init__
11)   File "/snap/sickgear/539/lib/python2.7/site-packages/Cheetah/Template.py", line 1631, in _compile
12)   File "/snap/sickgear/539/usr/lib/python2.7/genericpath.py", line 62, in getmtime
13) OSError: [Errno 2] No such file or directory: '/snap/sickgear/539/sickgear/gui/slick/interfaces/default/404.tmpl'
```
This seems to happen because the 539 snap version of sickgear is still running because snapd never restarted it after updating it. 
Can you please provide a working systemd service file that restarts the service after snapd restarted it, or alternatively let snapd restart sickgear after it has updated it?

`sudo service sickgear restart` fixes the issue but I need to do this manually every time snapd removes a directory (notice that my systemd service file uses the `current` directory and not the 539 dir.

**Comment by JackDandy** [comment]
Hi,

SG is developed on Windows, and the snap is provided as best as we can help not being from a Linux background. It would be most helpful if you or one of you Ubuntu experts submit a service file to the specification that you describe. 

Thanks
JD

**Comment by JackDandy** [comment]
Hi,

SG is developed on Windows, and the snap provided as best as can be to help - especially not being from a Linux background. You will appreciate that most of the hard work is done for you in actually creating the snap - that alone took a few weeks.

I'm sure the guys over at snapcraft will be able to offer assistance, as this is what this thread really is about, its not really an SG issue anymore, it's about how snap actually works. Therefore, it would be **most helpful** if you or one of you Linux experts submit a service text file that fits the spec that you described, and with a guide on how to use it for us Linux noobs. 

Thanks in advance
JD

**Comment by JensTimmerman** [comment]
Thank you for this clear answer, I am an expert linux user but have never used snap and had no experience with it, since there was a snap available in the repo I believed this to be supported. 
I fully understand your position as a windows developer.

I have read https://snapcraft.io/docs/service-management

It looks like I should not create a systemd service file but snap should take care of running services.
but it turns out that the sickgear snap has no services associated with it.

reading https://snapcraft.io/docs/services-and-daemons
learned me that probably the only change needed would be to have sickgear be defined as a simple daemon, after which snap will start it automatically on installation and restart it after refreshing.
So it seems that you would just need to uncomment
https://github.com/SickGear/SickGear/blob/master/snap/snapcraft.yaml#L22
(it is unclear to me why this line is commented out, I could not find an issue for it.

**Comment by JackDandy** [comment]
That line is commented out because i could not see a reason to enable it, but I opted to include it for a case where someone might get to the stage that you have. I cannot simply enable it at this point, in case it breaks everyone's current position of use. So if you want to take it to the next level, you are welcome to pick up the baton as it is, enable the option, build it and see if the option does have value - like i said, after weeks of getting the build working, i got tired and stopped at the point of getting it working reliably. It is supported in the way that all i have to do now is trigger new releases. For a build system, the weeks spent for a non Linux user was enough to tire me.
