### ISSUE TITLE
Invalid cookie details

### ISSUE THREAD

**Issue by JackDandy** [SickGear/SickGear#1226]
Opened as a new thread from what is considered a spam account - just in case that account is actually a legit user.
----

#### Branch version commit hash: (See the About page)

Expectation | Result
------------ | -------------
Login to TL media provider works | it does not, gives the following error for TorrentLeech

2019-12-27 18:40:37 INFO     MANUAL-79836 :: Unable to find a download for: [XXXXX]
2019-12-27 18:40:37 INFO     MANUAL-79836 :: No suitable candidates
2019-12-27 18:40:37 ERROR    MANUAL-79836 :: [TorrentLeech] :: Invalid cookie details for TorrentLeech. Check settings
2019-12-27 18:40:37 INFO     MANUAL-79836 :: [TorrentLeech] :: Performing episode search for XXXXX
2019-12-27 18:40:36 INFO     MANUAL-79836 :: Beginning manual search for: [XXXXX]

**Steps to reproduce:**
*1)* Update the settings for the media provider accordingly to this use... 'tluid=xx; tlpass=yy'
I have tried: the following:
'tluid=username; tlpass=password'
and
tluid=username; tlpass=password

*2)* restart browser
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:

**Comment by JackDandy** [comment]
The answer to this has always been [here](https://github.com/SickGear/SickGear/wiki/FAQ-Cookies) in the Wiki Faq.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

p.s. @jonas78 account has star, this thread will be deleted in a short time unless this changes.

**Comment by JackDandy** [comment]
The answer to this has always been [here](https://github.com/SickGear/SickGear/wiki/FAQ-Cookies) in the Wiki Faq.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by jonas78** [comment]
Thanks for the explanation, it's working now. Merry Xmas and Happy New Year
