### ISSUE TITLE
Default metadata Language

### ISSUE THREAD

**Issue by desmoloch** [SickGear/SickGear#1228]
#### Branch version commit hash: 0.20.18 (Docker)

Expectation | Result
------------ | -------------
Setting to choose metadata default  language >> | Every show is added with metadate language "eng". 

**Steps to reproduce:**
*1)* Add new show
*2)* Chosse metadata language (non eng)
*3)* Do it again...

I can´t find an option to set default metadata language. Is this missing?!
Thanks!

**Comment by JackDandy** [comment]
> Is this missing?!

Hiya,

Nope, this is not missing. SG is Eng.

**Comment by JackDandy** [comment]
> Is this missing?!

Hiya,

Its right there on the right side of add show.

**Comment by desmoloch** [comment]
Sorry maybe i was a bit unclear:
I'm missing the Option to set a default language (ie not english) :)
I tried adding over 130 existing shows and i have to set this for every show...

**Comment by JackDandy** [comment]
You reported the steps...
```
1) Add new show
2) Choose metadata language (non eng)
```
1) At step one, finding a show to add, lang 'es' is set, then the show is added
2) The correct 'es' was observed when viewing the show page, see image...

<a name=""><img src="https://i.vgy.me/PXBxrS.png"></a>

**Comment by desmoloch** [comment]
Yepp the steps are a bit misleading. i meant i'm searching for an option to set **default** metadata language. I cant find any global option nor it is possible to set it as default when adding a new show.

**Comment by JackDandy** [comment]
Ah okay, so how about a new feature that saves the selected meta language value when the search to add a show is performed, and reuses that as default the next time a show search is performed?

**Comment by desmoloch** [comment]
Great :)
Maybe you could add a global setting for metadata language.

**Comment by JackDandy** [comment]
My suggest does not need a global setting because the last used is saved **as** the global setting.

**Comment by JackDandy** [comment]
Added to branch develop 
<a name=""><img src="https://i.vgy.me/zhYZ3k.png"></a>
