### ISSUE TITLE
NFO's break OSMC/Kodi (confirmed)

### ISSUE THREAD

**Issue by DecipherIt** [SickGear/SickGear#1234]
#### Branch version commit hash: (See the About page)

Version: 	BRANCH: master / COMMIT: b2a5bab @ 0.21.1
This is BETA software

NFO's when generated for Kodi make OSMC crash over and again until you turn off auto library scans. 

Copied quote from a user:

> 
> Same issue as someone had a few days ago
> 
>   
>the < doesn't work so everything is in plain text
>ratings
>rating default="" max="10" name="thetvdb"
>value7/value
>votes27/votes

> </rating>

>   

> </ratings>

> 
> The missing argument in default="" makes Kodi crash
> 

Reported in two topics I could find while looking for my own issue.

**Steps to reproduce:**
*1)* Generate a Kodi based NFO for Show or Episode
*2)* try to import the show and watch it crash
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Reported in two topics I could find

https://discourse.osmc.tv/t/crash-when-updating-library/83764
https://discourse.osmc.tv/t/vero-4k-and-pi3-rebooting-after-scan-to-library/83879/12

Additional notes:
Adding the right arguments should fix it and allow it to scan and update.

**Comment by JackDandy** [comment]
> Adding the right arguments should fix it

In the [left column](https://kodi.wiki/view/NFO_files/tvshows#nfo_Tags) of the Kodi `.nfo` docs shows to use `default=""` in the `rating` xml tag.

Clearly this is not valid. Worse, under some environments, a system crash is the result.

Now, to create a fix.

**Comment by DecipherIt** [comment]
That is correct.

A fresh generated NFO by SickGear makes OSMC crash.

```
<tvshow>
  <title>Carnival Row</title>
  <premiered>2019-06-03</premiered>
  <uniqueid default="true" type="tvdb">365026</uniqueid>
  <uniqueid default="" type="imdb">tt489974</uniqueid>
  <uniqueid default="" type="tmdb">90027</uniqueid>
  <ratings>
    <rating default="" max="10" name="thetvdb">
```
Makes all OSMC Kodi systems crash.

So does the episode NFO
```
<episodedetails>
  <title>Some Dark God Wakes</title>
  <showtitle>Carnival Row</showtitle>
  <season>1</season>
  <episode>1</episode>
  <uniqueid default="true" type="tvdb">7221943</uniqueid>
  <aired>2019-08-30</aired>
  <plot> Plot </plot>
  <runtime>60</runtime>
  <displayseason/>
  <displayepisode/>
  <thumb>https://artworks.thetvdb.com/banners/episodes/365026/7221943.jpg</thumb>
  <watched>false</watched>
  <credits>|René Echevarria|Travis Beacham|</credits>
  <director/>
  <ratings>
    <rating default="" max="10" name="thetvdb">
      <value>10</value>
      <votes>27</votes>
    </rating>
  </ratings>
```

These are two NFO's generated at random by SickRage from a random popular show on TVDB, it is the same problem for every other show and episode which causes all cause crashes, OSMC based boxes can not be used with SickGear created NFO's without crashing right now.
The cause, should be the `default=""` argument according to OSMC developers in the posts mentioned above and the problem is new because I never heard of it before this but multiple people are reporting issues.

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.2)

Thanks for the report.

**Comment by ihatemicrosoft-was-already-taken** [comment]
This change breaks SickGear for me. It's now just stuck displaying "Changing Kodi Nfo: 0.00%"

**Comment by JackDandy** [comment]
@ihatemicrosoft-was-already-taken 

* Shutdown SickGear task
* Open a command prompt/shell and change directory to the SickGear app 
* Enter `git reset --hard origin/master`
* Start SickGear and click menu item "Check for Updates"

**Comment by ihatemicrosoft-was-already-taken** [comment]
Well, I can't even start SickGear, so ....
I have checked out the whole repo again, no change.

I guess this might be related:
`2020-01-12 17:45:47 INFO     MAIN :: SickGear.Start() exception caught no element found: line 1, column 0: Traceback (most recent call last):
  File "/SickGear/sickgear.py", line 710, in <module>
    SickGear().start()
  File "/SickGear/sickgear.py", line 533, in start
    sickbeard.metadata.kodi.remove_default_attr()
  File "/SickGear/sickbeard/metadata/kodi.py", line 453, in remove_default_attr
    xmltree = etree.ElementTree(file=xml_file_obj)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 611, in __init__
    self.parse(file)
  File "<string>", line 38, in parse
ParseError: no element found: line 1, column 0`

**Comment by ihatemicrosoft-was-already-taken** [comment]
I commented lines 532/533 so SickGear works again. I'd rather _not_ update for now.. ;)

```
if not db.DBConnection().has_flag('kodi_nfo_default_removed'):
            sickbeard.metadata.kodi.remove_default_attr()
```

**Comment by JackDandy** [comment]
Fix pushed.

Can you let me know if that is ok for you.

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.3).

Can you let me know if that is ok for you.

**Comment by ihatemicrosoft-was-already-taken** [comment]
Pulled latest update, SickGear starts up OK, so I guess that fixed that :)

Thanks for the quick reaction, much appreciated!

**Comment by JackDandy** [comment]
And the heart of the issue in Kodi has been fixed [here](https://github.com/xbmc/xbmc/pull/17194)
