### ISSUE TITLE
Stuck on Changing Kodi Nfo

### ISSUE THREAD

**Issue by stgreenb** [SickGear/SickGear#1236]
#### Branch version commit hash: doesn't boot so not exactly sure

Expectation | Result
------------ | -------------
After a recent update to "latest"(I didn't' look to see what version it was pulling down, and I am not sure how to pull the ver before full boot) upon starting back up the system hangs at "Changing Kodi Nfo." Rebooting another time gets the same output. 
![image](https://user-images.githubusercontent.com/18483964/72226233-b4837980-355c-11ea-95db-2e9dcbee52f6.png) 

**Steps to reproduce:**
*1)* Restart

Additional notes:
Note this is running on Synology DSM 6.2.2-24922 Update 4

**Comment by JackDandy** [comment]
1) Shutdown SickGear task
2) Open a command prompt/shell and change directory to the SickGear app 
3) Enter `git reset --hard origin/master`
4) Enter `git checkout -f --track -B master remotes/origin/master`
5) Start SickGear and click menu item "Check for Updates"
