### ISSUE TITLE
Add Show button not shown in Poster layout

### ISSUE THREAD

**Issue by mjanki** [SickGear/SickGear#1243]
#### Branch: master

Expectation | Result
------------ | -------------
See the button Add Show in Poster layout | Add Show button doesn't exist in Poster layout

**Steps to reproduce:**
*1)* Go to Show List
*2)* Choose Layout [Poster]

The button [Add Show] that shows on all other layouts doesn't show there. Adding a show that already exists is impossible from that view.

**Comment by JackDandy** [comment]
> Adding a show that already exists is impossible from that view.

You are not seeing this ?
<img src="https://i.vgy.me/OReFF8.png">

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
