### ISSUE TITLE
Process Media error: 'WindowsError' is not defined

### ISSUE THREAD

**Issue by MacinEnterprise** [SickGear/SickGear#1249]
#### Python Version: 2.7.13 (default, Oct 23 2017, 23:50:18) [GCC 4.9.2]

Expectation | Result
------------ | -------------
SickGear automatically snatches new episodes, passes them off to Deluge to download, then processes episodes once download is finished. | SickGear automatically snatches new episodes, passes them off to Deluge to download, then does not process the episodes—instead giving a 'WindowsError' is not defined error.

**Steps to reproduce:**
*1)* From Manage menu, select Process Media
*2)* Click Process button.
...

https://gist.github.com/MacinEnterprise/7e26d65b58ec4a29439923c4a4df1f40

Additional notes:
When I manually post-process, I get the following error page:

https://gist.github.com/MacinEnterprise/bd8c6db614c9277c3e5da0acbfee5a9d

Tried with both master and develop branches.

**Comment by JackDandy** [comment]
Hi,

Are you able to test a fix shortly ?

**Comment by MacinEnterprise** [comment]
Yes.

**Comment by JackDandy** [comment]
Ok,

On the develop branch, can you follow the steps here and then replicate your steps to recreate the same issue in order to see if this fix works... then let me know...

<img src="https://i.vgy.me/wPVjnE.png">

**Comment by MacinEnterprise** [comment]
<pre>2020-02-01 17:35:41 TORNADO :: Failed: git checkout -f hotfix/0.21.12 returned: error: pathspec 'hotfix/0.21.12' did not match any file(s) known to git.</pre>

**Comment by JackDandy** [comment]
Ok your system is not set up correctly for git. Ok i will just merge this fix and you can figure the rest out

**Comment by MacinEnterprise** [comment]
I'll fix my git, whatever the issue is, if that will help investigate/debug the issue.

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.12)

Thanks for your report.

**Comment by MacinEnterprise** [comment]
This fixed it. Thanks.

**Comment by JackDandy** [comment]
fyi: there are notes in the FAQ page about fixing git and your installation - which does have localized issues.
