### ISSUE TITLE
"maxage=0" not returning results from some search providers

### ISSUE THREAD

**Issue by wahteva** [SickGear/SickGear#1250]
#### Branch version commit hash:  093ab4c @ 0.21.13

Expectation | Result
------------ | -------------
I have recently noticed that all api queries set the optional parameter "maxage=0". For some search providers, they are returning 0 results.  | Would it be possible to add an option so this parameter can be enabled/disabled per search provider?

**Steps to reproduce:**
*1)Running the following api query against multiple search providers.
<websit,api&searchstring>&limit=100&attrs=rageid%2Ctvdbid%2Ctvmazeid&offset=0&season=1&t=tvsearch&ep=3&maxage=0&cat=5020%2C5030%2C5040

*2) Only some return results.

**Comment by Prinz23** [comment]
maxage is the value you set in Settings -> Search "Usenet retention"

**Comment by wahteva** [comment]
many thanks for that.
