### ISSUE TITLE
Can not upgrade

### ISSUE THREAD

**Issue by dkyr1968** [SickGear/SickGear#1252]
BRANCH: master / COMMIT: c69affb @ 0.20.11

In the last couple months i've tried to upgrade with no success. I'm currently 171 commits behind!!! | Upgrade in the latest version
------------ | -------------
Clicking on the "Update now" link in the show list page i get the following 
"Update Failed
Update wasn't successful, not restarting. Check your log for more information."

Below is the log information:
"2020-02-09 18:04:17 TORNADO :: git pull -f origin master returned : From https://github.com/SickGear/SickGear
 * branch              master     -> FETCH_HEAD
Updating c69affbd..093ab4c9
error: Your local changes to the following files would be overwritten by merge:
	CHANGES.md
	gui/slick/interfaces/default/history.tmpl
	lib/cfscrape/__init__.py
	lib/plex/plex.py
	lib/tvdb_api/tvdb_api.py
	sickbeard/helpers.py
	sickbeard/indexers/indexer_config.py
	sickbeard/indexers/indexer_exceptions.py
	sickbeard/logger.py
	sickbeard/metadata/generic.py
	sickbeard/metadata/helpers.py
	sickbeard/notifiers/emby.py
	sickbeard/providers/generic.py
	sickbeard/providers/torrentday.py
Please commit your changes or stash them before you merge.
Aborting"

**Comment by JackDandy** [comment]
Hi,

1. Shutdown SickGear
2. Open a command prompt/shell and change directory to the SickGear app folder...
3. Enter git reset --hard origin/develop
4. Start SickGear and click menu item "Check for Updates"
