### ISSUE TITLE
How to start snap package at boot up on server install

### ISSUE THREAD

**Issue by kevin201** [SickGear/SickGear#1258]
Not really an issue (except for me!). Just installing on Ubuntu 18.4 server - is snap package or standard install recommended? If snap, how to auto start properly at boot up?

**Comment by JackDandy** [comment]
A standard install is the most established method, the `init-scripts` folder contains an auto start script for that install type and documentation is in the Wiki. All the hard work has been done to get the snap package working but no Linux user has contributed an auto start script for that method, maybe you could?

**Comment by JackDandy** [comment]
A standard install is the more established method, the SG `init-scripts` folder contains an auto start script for that install type and documentation is in the Wiki - update amendments to the manual install instructions are welcome.

All the hard work has been done to get the snap package working but no Linux user has contributed an auto start script for that method, maybe you could?

**Comment by kevin201** [comment]
Many thanks for the info. Much as I thought. I have searched high and low for any info on automating snap startups, but with no success. They seem to be aimed more at desktop uses.

The test that I installed works fine in the foreground, and writes messages to the terminal. I think I will continue to install the regular version though. If I was to go with the snap I would probably just put an entry in rc.local

Thanks again.

**Comment by JackDandy** [comment]
> If I was to go with the snap I would probably just put an entry in rc.local

It would useful if you can verify if that works and supply specific text on how to do that

**Comment by kevin201** [comment]
Hi Jack,
I've spent a bit of time on this today, and it does seem to work ok.

Install using snap: snap install sickgear, then start it manually (there always seems to be an error on first run). Next time I started it ran and printed progress messages, then:

1. Edit /etc/rc.local (create it if it's not already there)
2. Add /snap/bin/sickgear & (to put it in the background)
3. Add 'exit 0' as the last line if it's not already.

Reboot. On the return ps aux | grep sick gave this:
root      1121  7.3  2.6 1284172 102860 ?      Sl   21:11   0:10 python /snap/sickgear/703/sickgear/sickgear.py --datadir=/var/snap/sickgear/common/data

Easy as pie! Hope that's helpful.

**Comment by JackDandy** [comment]
@kevin201 great, to build upon your findings, there are two separate startup arguments which are better than using `&` and `exit 0`  
  
one is `-s, --systemd`, the other is `-d, --daemon` - one of those should serve well here.   
  
the help text in core reads...
```
('-d', '--daemon', 'Run as double forked daemon (includes options --quiet --nolaunch)'),
('-s', '--systemd', 'Run as systemd service (includes options --quiet --nolaunch)'),
```
at ... https://github.com/SickGear/SickGear/blob/master/sickgear.py#L153-L154

lemme know how you get on (I'm guessing `-s` is the one you want as that does an `exit(0)`).

**Comment by kevin201** [comment]
That's brilliant, I never knew about those! That reduces the snap install to less than 5 minutes!

**Comment by JackDandy** [comment]
Please remember to let me know which startup argument you settle on, so that we can feed that info back into the wiki install page for others.

**Comment by kevin201** [comment]
More on this: /snap/bin/sickgear & appears  to run, but spews gigabytes of logs into the syslog:
`Mar  3 21:24:34 kevin-One-Z1402 rc.local[1119]: 21:24:34 ERROR TORNADO.APP :: Exception in callback (<socket._socketobject object at 0x7f698c1c0600>, <function null_wrapper at 0x7f698cb4dc80>)
Mar  3 21:24:34 kevin-One-Z1402 rc.local[1119]: Traceback (most recent call last):
Mar  3 21:24:34 kevin-One-Z1402 rc.local[1119]:   File "/snap/sickgear/703/sickgear/lib/tornado_py2/ioloop.py", line 1073, in start
Mar  3 21:24:34 kevin-One-Z1402 rc.local[1119]:     handler_func(fd_obj, events)
Mar  3 21:24:34 kevin-One-Z1402 rc.local[1119]:   File "/snap/sickgear/703/sickgear/lib/tornado_py2/stack_context.py", line 300, in null_wrapper
Mar  3 21:24:34 kevin-One-Z1402 rc.local[1119]:     return fn(*args, **kwargs)
Mar  3 21:24:34 kevin-One-Z1402 rc.local[1119]:   File "/snap/sickgear/703/sickgear/lib/tornado_py2/netutil.py", line 249, in accept_handler
Mar  3 21:24:34 kevin-One-Z1402 rc.local[1119]:     connection, address = sock.accept()
Mar  3 21:24:34 kevin-One-Z1402 rc.local[1119]:   File "/snap/sickgear/703/usr/lib/python2.7/socket.py", line 206, in accept
Mar  3 21:24:34 kevin-One-Z1402 rc.local[1119]:     sock, addr = self._sock.accept()
Mar  3 21:24:34 kevin-One-Z1402 rc.local[1119]: error: [Errno 13] Permission denied
`

So, attempt 2, with /snap/bin/sickgear -s  never booted up at all.  I had to boot in single user mode to take it out of the rc.local.

Attempt 3, with /snap/bin/sickgear -d actually does seem to work, and no error messages in the log.
![Screenshot from 2020-03-04 14-05-00](https://user-images.githubusercontent.com/16619495/75854092-f4126780-5e21-11ea-9b6d-3d3c3598ad5d.png)

Hope that's useful!

**Comment by JackDandy** [comment]
The logs in the first attempt show permissions error, most likely because of not running with `sudo` and therefore not giving correct perms to the running process to create PIDs for socket use, file creation etc.

Can you try using `sudo` to run, e.g. 
* `sudo /snap/bin/sickgear -s`
* `sudo /snap/bin/sickgear -d`
* `sudo /snap/bin/sickgear &`

**Comment by kevin201** [comment]
Hi, yes, not sure why that would be, only happened in the first try with '&'. Everything from rc.local runs as root afaik, as demonstrated by the ps fragment in my first post...

root 1121 7.3 2.6 1284172 102860 ? Sl 21:11 0:10 python /snap/sickgear/703/sickgear/sickgear.py --datadir=/var/snap/sickgear/common/data

**Comment by JackDandy** [comment]
k, so that would explain your reported syslog items containing `Mar  3 21:24:34 kevin-One-Z1402 rc.local[1119]: error: [Errno 13] Permission denied`.

So `-s` failed and `-d` worked, then I guess that's everything tested and covered, thanks for your help.

**Comment by JackDandy** [comment]
k, so that would explain your reported syslog items containing `Mar  3 21:24:34 kevin-One-Z1402 rc.local[1119]: error: [Errno 13] Permission denied`.

So `-s` failed and `-d` worked, then I guess that's everything tested and covered,

One last question, did you enter the startup param `--datadir=/var/snap/sickgear/common/data` output in the `ps aux` or was that added by SickGear ?

thanks for your help.

**Comment by JackDandy** [comment]
p.s. so i added the auto start notes [here](https://github.com/SickGear/SickGear/wiki/Install-  SickGear-[3]-Ubuntu#snap)

If there is anything I should add to improve the text, please say :-)

Again, thanks for your help on this.

**Comment by JackDandy** [comment]
p.s. so i added the auto start notes <a href="https://github.com/SickGear/SickGear/wiki/Install-SickGear-[3]-Ubuntu#snap">here</a>

If there is anything I should add to improve the text, please say :-)

Again, thanks for your help on this.

**Comment by kevin201** [comment]
Hi, not at all, thanks for the excellent software (and I don't say *that* often!)

I didn't add anything except the '-d'. Snap took care of the rest. I would have found it useful to know the location of the db and conf files. I found them after searching, but if I had known they were there, I could have looked in 'about'.

I would add to run the snap manually a couple of times, as I *always* got the following error on the first run:

`$ sudo /snap/bin/sickgear
[sudo] password for kevin: 
Starting up SickGear from /var/snap/sickgear/common/data/config.ini
Traceback (most recent call last):
  File "/snap/sickgear/703/sickgear/sickgear.py", line 710, in <module>
    SickGear().start()
  File "/snap/sickgear/703/sickgear/sickgear.py", line 366, in start
    sickbeard.initialize(console_logging=self.console_logging)
  File "/snap/sickgear/703/sickgear/sickbeard/__init__.py", line 589, in initialize
    init_stage_1(console_logging)
  File "/snap/sickgear/703/sickgear/sickbeard/__init__.py", line 749, in init_stage_1
    if not ek.ek(os.path.isdir, ZONEINFO_DIR) and not helpers.make_dirs(ZONEINFO_DIR):
  File "/snap/sickgear/703/sickgear/lib/sg_helpers.py", line 510, in make_dirs
    NOTIFIERS.NotifierFactory().get('SYNOINDEX').addFolder(sofar)
AttributeError: 'NoneType' object has no attribute 'NotifierFactory'

`

I ended up going for the standard install on my server, being a bit of a traditionalist(!), and the only place I had a little problem with, after copying the supplied file to the /etc/init dir was remembering to run the 'sudo update-rc.d sickgear enable' command to copy the syslinks to the rc.0-6 directories.

First time I tried it I got an error:
`~# update-rc.d sickgear
update-rc.d: error: not enough arguments
usage: update-rc.d [-f] <basename> remove
       update-rc.d [-f] <basename> defaults
       update-rc.d [-f] <basename> defaults-disabled
       update-rc.d <basename> disable|enable [S|2|3|4|5]
                -f: force

The disable|enable API is not stable and might change in the future.
`

So I ran `# update-rc.d sickgear enable [2345]` and it ran fine. Don't understand the reason for that, as the file looks ok to me!


Thanks.

**Comment by JackDandy** [comment]
```
AttributeError: 'NoneType' object has no attribute 'NotifierFactory
```
Ooer! that's a bug and now made aware, has been fixed for the next hotfix release. There should be zero errors on startup, a warning for timezone data at most should exist on first run.

**Comment by kevin201** [comment]
Hi!,
I checked that file against init.ubunu, using diff -u, and then using 'vim', and inadvertently saved it, to find that it works now. No idea what was wrong. I copied the file from init_scripts again, and it works fine! Sorry to have taken your time on that.

**Comment by JackDandy** [comment]
Not a problem, and the snap method should no longer contain the error you reported. If you could confirm that a fresh fetch starts up without issue ;)

**Comment by kevin201** [comment]
All working first time now. The snap install and configuration takes literally seconds!
![image](https://user-images.githubusercontent.com/16619495/75965307-3196f380-5efb-11ea-9757-2b4d93674087.png)
