### ISSUE TITLE
Banners do not load with Show List

### ISSUE THREAD

**Issue by bcamp929** [SickGear/SickGear#1259]
#### Branch version commit hash: 68ed2bf @ 0.21.17

Expectation | Result
------------ | -------------
When accessing show list page in sickgear, all show banners should load with the page. | Instead, as the page is loaded, most images aren't loaded until you scroll the page.

**Steps to reproduce:**
*1)* Go to server:8081
*2)* observe most series banners do not load

Additional notes:
Under General Settings - Interface, i have Use as Default Home Page set to Show List.
Under General Settings - Interface, i have Display Theme set to Light.

![2020-03-04_07h27_55](https://user-images.githubusercontent.com/13508867/75879864-2a33f500-5dea-11ea-93f0-93247950dd1b.png)

**Comment by JackDandy** [comment]
browser ?

**Comment by bcamp929** [comment]
Google Chrome, sorry for omitting that.

**Comment by JackDandy** [comment]
np. Chrome version ?

**Comment by bcamp929** [comment]
80.0.3987.122

**Comment by JackDandy** [comment]
so Chrome have yet again broken something - its always Chrome - every time, id rather use ie6

**Comment by JackDandy** [comment]
ok, I have ...
```
Chromium Version 80.0.3987.122 (Official Build) (64-bit)
```
and the issue is not presenting, maybe you have a script blocker extension ?

**Comment by bcamp929** [comment]
Would AdBlocker cause this?

**Comment by JackDandy** [comment]
Also, we have tested with `82.*` and that is not presenting the issue.

**Comment by bcamp929** [comment]
Is that a developer version or something? Mine won't update past 80.*

[image: image.png]

**Comment by JackDandy** [comment]
i suspect it 82.* is yeah. the other dev just fed back that info. mine is also 80.*

**Comment by JackDandy** [comment]
anyway, this is now chat, if you want chat, come to irc,

**Comment by JackDandy** [comment]
There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
I feel this issue is a high dpi screen issue or something, perhaps using a screen tool will solve the issue for you. smaller browser window and not full screen may also help.

**Comment by bcamp929** [comment]
Appreciate your attention to this anyways. I suspect it is likely just
a caching issue anyways, or something like that. Thanks again.

**Comment by JackDandy** [comment]
no i dont think so, like i said, i suspect your monitor is high res, and the js in the browser is not detecting the screenheight, therefore, does not know to fetch the images until you scroll. however, im not into testing theories unless you come to irc.
