### ISSUE TITLE
Unable to update - Git merge changes

### ISSUE THREAD

**Issue by bcamp929** [SickGear/SickGear#1263]
#### Branch version commit hash: 08097f4 @ 0.21.18

Expectation | Result
------------ | -------------
When updating, update will succeed | When updating, update fails

**Steps to reproduce:**
*1)* Message appears at top of webui stating newer version is available.
*2)* Click Update Now.
*3)* Update Fails.

Additional notes:
The log states that changes need to be merged to git before updating. Only changes made to app files were made by the app itself, and therefore should be handled by the app itself.

Log info (Log file too large to attach):
Updating 08097f4b..7d45bdd1
2020-03-29 07:39:33 ERROR    TORNADO :: Failed: git pull -f origin master returned: From https://github.com/SickGear/SickGear
 * branch              master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	_cleaner.py
	gui/slick/interfaces/default/manage_massEdit.tmpl
	lib/dateutil/tz/win.py
	lib/dateutil/zoneinfo/.gitignore
	lib/dateutil/zoneinfo/__init__.py
	sickbeard/network_timezones.py
	sickbeard/providers/torrentleech.py
	sickbeard/search_queue.py
	sickbeard/sgdatetime.py
	sickbeard/tv.py
	sickbeard/webapi.py
	tests/network_timezone_tests.py
	tests/newznab_tests.py
Please commit your changes or stash them before you merge.
Aborting

**Comment by JackDandy** [comment]
Right there in the Wiki, see [here](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#update-develop)

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
