### ISSUE TITLE
SG API more detailed output

### ISSUE THREAD

**Issue by PowerCoder** [SickGear/SickGear#1265]
#### Branch version commit hash: 7d45bdd @ 0.21.22

This probably falls into the feature request category.

I've been writing a PowerShell module to interact with SG's API to perform some of the more common activities like `sg.shows`, `sg.show.update` and `sg.shows.queue`, in part because SG's Process Media doesn't seem to be capable of handling show names with a `US` or a year in the title unless I named the folder just so and partly because I just love working with PowerShell.

In writing the PwSh equivalent of Process Media I ran into 2 little things so far:
1. If I run an `sg.show.update` on a show that is already in the queue to be updated the reply is `result : failure` and `message : Unable to update <showname>`
I would really like it if it were possible for the message to state **why** it failed.
2. To compensate for the above, I had to write a new function that looks in the queue to see if the show is currently queued. It would be great if that status could be listed as a property of the show itself, so I could find it with `sg.shows`.

**Comment by JackDandy** [comment]
> handling show names with a US or a year in the title

See [here](https://github.com/SickGear/SickGear/wiki/FAQ-Alt-Names)

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
> doesn't seem to be capable of handling show names with a US or a year in the title

See [here](https://github.com/SickGear/SickGear/wiki/FAQ-Alt-Names)

> I had to write a new function ... to see if the show is currently queued  

Yes, that is exactly what you should do.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by PowerCoder** [comment]
Thank you. I apologize if you feel I wasted a good issue.

I did not know about the alternate names, will set those right away. Won't stop me from writing my own code though, since it's good exercise and a lot of fun.

> You could simply note that the update wasn't successful and/or take some action... the why doesn't actually add value, after all, it is what it is, i.e. not updating, so, act or skip.

I do not how how many different reasons there can be for it failing to update, so I wouldn't know which action to take. Maybe it's broken or half removed, maybe it can't access the folder, or maybe it is updating/refreshing (whatever the difference is).

I could skip, but that might mean the new episode isn't registered until the next daily cycle, which may not be desirable if it concerns a manual download (which therefor is still marked as "Wanted" by SG and could trigger a snatch in the meantime).

> Yes, your proactive approach is fine there. This is much like, the logical sequence to create a file, e.g. if file not exists then create it - where you do, if show not being updated then update it.

And this approach does work. But from a coder's perspective it is highly inefficient. To be able to get a list of shows, I query `sg.shows`, which results in a table with index-numbers as titles. In order to be able to search by property (like name), I need to essentially reverse the X and Y axis of the resulting table by parsing through the entire list of shows, writing them out into a new table in memory.

Now, in order to figure out if the show is currently in the queue, I need to query `sg.shows.queue`, which may result in yet another large table that needs to be parsed. If the script runs for a long time, I may need to do this query multiple times throughout.

Even though it may only take a few seconds more even with 1000+ shows in the database, it's still inefficient. Hence I figured I would at least ask for a `queued_*` property.

But no problem, I'll work with what you're already exposing. Thanks!

**Comment by Prinz23** [comment]
There is only 1 reason for the `message : Unable to update <showname>`. It's because that the show update/refresh is already queued, there are no other reasons for this message.

**Comment by JackDandy** [comment]
So there it is. Try to update, if it fails, then it can only be for one reason, no need to pre-check anything - efficient.

**Comment by JackDandy** [comment]
Added [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.25)
