### ISSUE TITLE
Unable to set episodes to status Archived

### ISSUE THREAD

**Issue by PowerCoder** [SickGear/SickGear#1266]
#### BRANCH: master @ py2.7.17 / COMMIT: 800d42b @ 0.21.24

Expectation | Result
------------ | -------------
The ability to change any episode status to Archived | Only episodes with status Downloaded can be set to Archived

**Steps to reproduce:**
*1)* Choose any episode with status Wanted, Skipped or Ignored.
*2)* Check it and select "Change selected episodes to..." and pick either of the 2 Archived options.
*3)* Click Go. The screen will refresh, the status of the episode remains unchanged.

The same happens in setting a Wanted episode to any of the Downloaded options.

To set an episode to Archived, I first need to set the status to Skipped or Ignored. Next, set it to any of the Downloaded statuses. Finally, set it to Archived.

I've been able to reproduce this often enough that I've gotten used to it.

```
2020-04-08 03:19:03 DEBUG    TORNADO :: Transaction with 1 queries executed affected 1 row
2020-04-08 03:19:03 DEBUG    TORNADO :: Attempting to set status on episode 1x3 to 6
2020-04-08 03:18:57 DEBUG    TORNADO :: Transaction with 1 queries executed affected 1 row
2020-04-08 03:18:57 DEBUG    TORNADO :: Attempting to set status on episode 1x3 to 104
2020-04-08 03:18:50 DEBUG    TORNADO :: 1:357163: Not creating SQL queue - record is not dirty
```

Additional notes:
Sometimes after watching an episode before it has been logged in the database, like when watching it on Netflix or TV, it is nice to be able to set it to Archived directly as an indicator that it has been watched. I used to do this in -Beard before moving to -Gear.

**Comment by JackDandy** [comment]
> Only episodes with status Downloaded can be set to Archived
> Setting a Wanted episode to any of the Downloaded

Indeed, and these two behaviors are by design. 

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
> Only episodes with status Downloaded can be set to Archived
> Setting a Wanted episode to any of the Downloaded

Indeed, and these two behaviors are by design. 

> it is nice to be able to set it to Archived directly as an indicator that it has been watched

This is not the purpose/meaning of Archived. Such misuses of statuses, were part reason things changed here, so that we use them for correct reasons. Archived means the file was downloaded, and no longer exists (deleted). For watched state proper, I recommend you look under the history view, and drop select the layout in there, that wasn't in -Beard ;)

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by PowerCoder** [comment]
So if I downloaded an episode manually and watched it right away before deleting it, without first registering it in Gear, that's not a valid reason to have for this functionality, mainly to ensure the Show List doesn't indicate there are episodes missing from a show?

For some shows I use Gear as a means to track what I've watched instead of having it download for me. Ever considered a Watched status?

Accidentally changing in bulk is still a risk, you can never completely cover user actions. And especially Ignored is a dangerous status. Sometimes I open up a show page only to see one or more episodes marked as Ignored for some mysterious reason (I think it jumps to Ignored instead of Archived if it no longer finds a previously downloaded file in its show folder), meaning I never realized I had not gotten that episode and by then it is very hard to get to. I know, that's what Episode Overview is for.

I'm doing well, two issues both considered non-issues. 🙂

**Comment by JackDandy** [comment]
> mainly to ensure the Show List doesn't indicate there are episodes missing from a show?

Did you not read, "there are others reasons behind these enforced flows too." ? Maybe you are responding via an email, I suggest you use the GitHub website to see any amendments to the post that I made.

> Ever considered a Watched status

You have clearly written this without taking the time to go through everything i spent time writing about.

And you have continued to theorize of sequence flows, where as we have developed based on practical day to day usage. Sure, one can figure some way to figure around the logic flows in, much like no system is complexity secure. Anyway, i will stop now, you have things to go look at.

**Comment by JackDandy** [comment]
> mainly to ensure the Show List doesn't indicate there are episodes missing from a show?

Did you not read, "there are others reasons behind these enforced flows too." ? Maybe you are responding via an email, I suggest you use the GitHub website to see any amendments to the post that I made.

> Ever considered a Watched status

You have clearly written this without taking the time to go through everything i spent time writing about.

And you have continued to theorize of sequence flows, where as we have developed based on practical day to day usage. Sure, one can figure some way to figure around the logic flows in, much like no system is complexity secure. Anyway, i will stop now, you have things to go look at, for example...

> I think it jumps to Ignored instead of Archived if it no longer finds a previously downloaded file in its show folder during its nightly cycle

i already noted about the settings on that, you have not read my words.

**Comment by PowerCoder** [comment]
I wouldn't disrespect you by not reading what you posted. I've done enough support to know how that feels. And I am grateful you are taking the time to answer. Feel free to ignore this reply if you are so inclined.

> Did you not read, "there are others reasons behind these enforced flows too." ?

I did, and I do not doubt that, I merely asked if my User Story (downloading -> watching -> deleting outside of Gear but still wanting it "checked off") was sufficient reason to support said functionality of bypassing the default flow, not if it was technically feasible.

It would seem the answer is a resounding "no".

> You have clearly written this without taking the time to go through everything i spent time writing about.

Not at all. You mentioned what you envisioned Archived to be. I understood that logic. Then you stated...

> For watched state proper, I recommend you look under the history view, and drop select the layout in there, that wasn't in -Beard

...which is where you lost me. I went to the History page, which dropped me by default into the Activity view. I then looked for a blue button stating "Watched", googled for "sickgear layouts" thinking it was something custom I had to do. I did not associate the term "drop select" with "open the drop-down menu and select the filter". Lost in translation, I guess.

It isn't until just now that I noticed the little icon in the rollout menu. After reading both the resulting page as well as the API example it links to, I came to the conclusion that if I were to watch an episode outside of Gear, not having a media server, there does not appear to be an easy, GUI supported means to enable the Watched status on an episode.

So I couldn't go to the Show page for Arrow and select the episodes up to S04E17 to set them as Watched, knowing that I may want to remember which episode I got to next week since I haven't got the time to watch for a little while.

Which is a habit I have developed over the years from _practical day to day usage_. My guess is I'm not the only user "abusing" the Archived status for this purpose. And I am likely also not the only user unaware of your sequence flows and wondering why, whilst possessing insufficient Python skills to figure it out.

Obviously I could use a cloud-based service like Trakt, but I prefer the local alternative.

In this case, I will follow your flows to manually set my episodes to Archived.

> i already noted about the settings on that, you have not read my words.

Since at the time I was unable to find said watched-layout, I figured the link you posted had something to do with that. I read it through, noticed which ones were included in stats and progress bars, but I admit I missed `The post processing setting "Status of removed episodes" should be set to "Set Archived"` until just now.

Thank you, and do forgive me for annoying you.

**Comment by JackDandy** [comment]
> there does not appear to be an easy, GUI supported means to enable the Watched status on an episode.

Actually, there is, it's in all the supported media servers. The media server as player have function to set an episode to watched, which propagates to SickGear. I appreciate a stripped down basic player does not have concept of a library, but media servers were chosen as a great accompaniment with features that SG doesn't need to duplicate, therefore, development could be focused on more important stuff. At the very least, you can determine what in your player constitutes a "watch" status change, and then trigger an api call to sg to mark ep as watched. Or just use a media server for Windows, it's all been done already. 

> Obviously I could use a cloud-based service like Trakt, but I prefer the local alternative.

I totally appreciate you wanting to avoid external services for your watched state, this is one of the driving reasons that solutions for Kodi, Plex and Emby were crafted, however, with a future thinking that others would be using different players, the API documentation was made. You have Powershell, so here is perhaps something for you to get your teeth into, that is, interfacing your player of choice. And if you can suitably interface a popular player like Media Player Classic, then we could add this to the other known players, kinda like how notifiers, providers, or indeed media servers all present choices for user preference.
