### ISSUE TITLE
Full Update re-generates tvshow.nfo which makes SickGear not recognize it for import later

### ISSUE THREAD

**Issue by aMvEL** [SickGear/SickGear#1267]
**BRANCH: develop @ py3.8.2 / COMMIT: 469236d @ 0.22.0**
Tested on clean install

Expectation | Result
------------ | -------------
Full update should create same nfo as when adding show first time  | different and possibly invalid nfo-file

**Steps to reproduce:**
*1)* Add new show to SickGear. I used SEAL Team when testing this issue
*2)* Check the resulting tvshow.nfo, and observe that it has the tags,  **id** and **indexer** toward the bottom of the nfo-file.
*3)* Run a Full Update on that series, and see that the tvshow.nfo has ben re-written without those two tags.
*4)* Remove the show from SickGear.
*5)* Try to import the existing show, and see that SickGear does not detect the tvshow.nfo as valid.
<pre>2020-04-09 22:52:24 INFO     TORNADO :: Invalid info in tvshow.nfo (missing name or id):SEAL Team None None None
2020-04-09 22:52:24 DEBUG    TORNADO :: Loading show info from metadata file in D:\New folder\SEAL Team
</pre>

**Additional notes:**
I am guessing that the issue is either that the Full Update logic should not remove those tags, or that the import show function should not look for those tags.

Either way there probably should not be generated different tvshow.nfo files when adding shows first time, and when running Full Update.

**Comment by JackDandy** [comment]
> Check the resulting tvshow.nfo

What metadata settings ?

**Comment by aMvEL** [comment]
> > Check the resulting tvshow.nfo
> 
> What metadata settings ?

Metadata target: Kodi

I have checked for creating the following.
_tvshow.nfo
Season##\filename.nfo
fanart.jpg
poster.jpg
banner.jpg_

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.25)

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.25)

Thanks for the report.
