### ISSUE TITLE
SyntaxWarning: "is not" with a literal

### ISSUE THREAD

**Issue by boredazfcuk** [SickGear/SickGear#1270]
#### OS version: Alpine Linux v3.11

When launching SickGear in the above environment, I get: 
```
/SickGear/lib/tzlocal/unix.py:141: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while start is not 0:
```
Looks like line 141 of /SickGear/lib/tzlocal/unix.py needs changing to `while start != 0:`

**Comment by JackDandy** [comment]
Thanks for the heads up, will be handled on next push.

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.27).

Thanks for the report.
