### ISSUE TITLE
error on saving renaming patterns - object has no attribute '_epid'

### ISSUE THREAD

**Issue by IvoPo** [SickGear/SickGear#1274]
#### a1898d1 @ 0.22.0

Expectation | Result
------------ | -------------
remove anime renaming pattern | The save spinner is not ending and i have absolute numbering in the sample and the renamer says my episodes are correctly named with unwanted absolute numbers

**Steps to reproduce:**
*1)* Sadly i don't know what lead up to this state

[LOG](https://gist.github.com/IvoPo/ace5ef4e954c7314b3ddb5f971d1a36c)
[screenshot](https://i.imgur.com/LmBPR5q.png)

Additional notes:
I wanted to change or remove anime absolute numbering because the processor couldn't find epsiode numberings in some SxxExx - xxx - EN formats. So i ticked the box for that off, but it wouldn't save. Then i disabled anime patterns alltogether. When i reload the page, the UI has changed but "Rename Media" hasn't

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.29)

Thanks for the report.
