### ISSUE TITLE
[Bug] Telegram notification option "Send icon image" not working as expected

### ISSUE THREAD

**Issue by boredazfcuk** [SickGear/SickGear#1275]
#### Branch version commit hash: dff879b @ 0.22.0

Hi,

I've noticed odd behaviour with the the Telegram "Send icon image" setting. Every time I recreate my Docker container, SG will start sending icon images again, instead of remembering the previous setting.

If the `telegram_send_icon` setting is not in the config, SG will default to sending the icon. I would expect SG not to send icons.

If I check the `Send icon image` setting box and click `Save` SG will add `telegram_send_icon = 1` and send the icon, as expected.

If I uncheck the `Send icon image` setting and hit save, SG will remove `telegram_send_icon = 1` from the config file and stop sending the icon, as expected.

It seems that SG doesn't check the setting at launch and defaults to on.

Setting `telegram_send_icon = 0` has no effect, presumably it's an invalid config and SG requires `telegram_send_icon = 1` or for `telegram_send_icon` to not be present at all.

Hopefully this is a simple fix.

Thanks for all your effort on this project.

**Comment by JackDandy** [comment]
Docker environments are not supported, please try without docker.

**Comment by boredazfcuk** [comment]
What about other virtualization technologies? If I install the same OS (Alpine Linux 3.11) inside a libvirt or hyper-v virtual machine, would that be supported? I don't run anything on my physical server any more.

**Comment by boredazfcuk** [comment]
I can prove the bug in whatever environment you wish. I'm just trying to understand what you consider "a regular python desktop env"?

I have two Debian servers and an Ubuntu laptop knocking about, but all these have KVM installed so those are ruled out. I have two Windows 10 laptops, but both have the Hyper-V role installed, so those are ruled out too.

I can stick Raspbian on a Raspberry Pi 2 and prove there?

I just find it really bizarre that, as a dev, you don't have Hyper-V installed on your machine.

Plus running in a Docker container is super beneficial from a dev perspective. It guarantees a clean OS, with nothing but SG and it's dependencies installed. If there's a problem with the container, I can destroy it and re-create it in a couple of minutes, instead of having all the pain of re-installing the host OS. Makes things so much easier.

**Comment by JackDandy** [comment]
Docker was a diversion, it has nothing to do with the symptom. A vanilla install, that is; any install that is not inside a docker container, would have been far more time saving and **helpful** - you have Windows and were not willing to do a simple install as presented in the wiki install guide.

As for your assertion about Docker containers, we have no pain and we never re-install a host OS. We simply run with a DB/data folder in the same way most people run the application. Thankfully, given its disadvantaged redundant resource waste and overhead on non Linux, Docker is far from ubiquitous.

The Telegram notification provider is still under development, that option cannot be disabled at this time, it will be when the feature is completed.

Thanks.

**Comment by boredazfcuk** [comment]
> we don't develop in your virtual systems.

Windows is a virtualised system. It's a Tier-1 Hypervisor so the host machine's OS is actually runs inside the virtual stack alongside any other virtual operating systems that are created through the Hyper-V management console.

> you have Windows and failed to do a simple install as presented in the wiki install guide.

You said you didn't support virtualised systems, i.e. Windows.

> Docker was a diversion, it has nothing to do with the symptom.

I knew this, you knew this, yet here we are doing a merry little virtualisation dance.

> The Telegram notification provider is still under development, the saving of that option it not complete at this time, it will be when the feature is completed. Given the incomplete stage of this feature, this thread will now be marked complete.

Thanks. I was only trying to bring this bug to your attention, in case you were not aware of it.

**Comment by JackDandy** [comment]
> Every time I recreate my Docker container, SG will start sending icon images again, instead of remembering the previous setting.

This is what threw me, you indicated strongly to Docker, so I asked to confirm outside of Docker, you ignored what I asked, and made something simple, complicated, this was unhelpful. Anyway, it's done now.
