### ISSUE TITLE
RARGB provider is not working

### ISSUE THREAD

**Issue by bero02** [SickGear/SickGear#1276]
#### Branch: The name of the branch (e.g. master or develop)
master

#### Branch version commit hash: (See the About page)
f4cbee4 @ 0.21.30

Expectation | Result
----- | -----
backlog search via rargb is working | error thrown

Sickgear does not seem to support search via rargb.

Error thrown:
`2020-05-01 21:52:04 BACKLOG-1:71663 :: [Rarbg] :: Error while searching Rarbg, skipping: api_token
2020-05-01 21:52:04 BACKLOG-1:71663 :: [Rarbg] :: Traceback (most recent call last):
  File "/usr/local/share/sickgear/sickbeard/search.py", line 778, in search_providers
    try_other_searches=try_other_searches)
  File "/usr/local/share/sickgear/sickbeard/providers/generic.py", line 1038, in find_search_results
    item_list += self._search_provider(cur_param, search_mode=search_mode, epcount=len(ep_obj_list))
  File "/usr/local/share/sickgear/sickbeard/providers/rarbg.py", line 81, in _search_provider
    if not self._authorised(reset=True):
  File "/usr/local/share/sickgear/sickbeard/providers/rarbg.py", line 63, in _authorised
    response = self.get_url(self.urls['api_token'], parse_json=True)
KeyError: 'api_token'`

**Comment by JackDandy** [comment]
please supply full version as requested from the about page.

**Comment by JackDandy** [comment]
Cannot replicate an issue here - that api_token you see in your error is working fine. Therefore, i can only assume a localized network issue to the Rarbg api, maybe try accessing the API with `https://torrentapi.org/pubapi_v2.php?app_id=SickGear` to see if it says `Invalid token`, and then seeing if SG is still not working for you depending on that.

**Comment by bero02** [comment]
Actually, it is valid. No network issue as you can see below, cURL was executed from same instance running SickGear:

![image](https://user-images.githubusercontent.com/64684291/80869753-9031e100-8ca2-11ea-8f0b-9137cd80c8a8.png)

at the same time I forced backlog search, rargb still failing (I am running default settings for that media provider):

![image](https://user-images.githubusercontent.com/64684291/80869808-bb1c3500-8ca2-11ea-8bf1-4218f590a49a.png)

**Comment by JackDandy** [comment]
what about... `https://torrentapi.org/pubapi_v2.php?app_id=SickGear&get_token=get_token`

**Comment by JackDandy** [comment]
Talking of other forks adds no value at all as other forks are not the same code as SG.

I have no idea what is going on in your system. That error is basically saying that a variable does not exist, thing is, that variable does exist.

**Comment by JackDandy** [comment]
Hi, did you figure this out ?
