### ISSUE TITLE
Processing media does not seem to be done in own thread

### ISSUE THREAD

**Issue by bero02** [SickGear/SickGear#1277]
#### Branch: The name of the branch (e.g. master or develop)
master

#### Branch version commit hash: (See the About page)
f4cbee4 @ 0.21.30

Expectation | Result
UI thread is not blocked when processing media | UI thread is blocked

When invoking "Process Media" in a folder the UI thread is blocked, meaning you cannot see or do anything on the web page until processing is done. I for instance would like to keep an eye on the log or history while it is processing to see the progress. Other SickBeard forks (sickchill etc.) **do not block** UI thread when processing media. It is not a OS/environment issue since I have ran other forks in exactly same high-end server environment: Xeon D-2123IT, 256GB RAM running FreeBSD 11.3. Also, please look into completely migrating to Python 3 since 2 is now officially dead.

**Steps to reproduce:**
*1)* Click Manage -> Process Media
*2)* Select folder containing shows to be processed
*3)* Select "Process"

Result: Can't do anything, just wait for processing to complete.

**Comment by JackDandy** [comment]
Tabled for a future dev.

**Comment by JackDandy** [comment]
1) Thread for media process tabled for future dev.
2) Re: Python support see [here](https://github.com/SickGear/SickGear/wiki/FAQ-Roadmap)

**Comment by bero02** [comment]
I am aware that both are supported, in all honesty I was not able to get SickGear running on a freshly installed FreeBSD installation only running Python 3 since it still seems to require python2, I I had to install that just for this software :/

**Comment by JackDandy** [comment]
> since it still seems to require python2

you are the first to say this, quite a few have been running py3.8 fine. maybe there is something about freebsd though - dunno.

**Comment by JackDandy** [comment]
> since it still seems to require python2

Incorrect, quite a few have been running py3.8 just fine. What exact version of Python did you attempt to run? Did you check for messages from SG on startup?

As I understand it, FreeBSD 12.1 is the first version that actually **ships** with Python 3.7. FreeBSD 12.0 shipped with Python 3.6 which is not good enough (and this failing is clearly reported on startup by SG).  You reported that you are on FreeBSD 11.3 - therefore, you needed to upgrade your Python 3 instead of assuming Python 2 was required - that or update your operating system.

**Comment by JackDandy** [comment]
This feature request is now in final dev testing phase, if you want to help test it, come idle in IRC.

**Comment by JackDandy** [comment]
Added [here](https://github.com/SickGear/SickGear/commit/7c483ec95b93e093f70ae75aef0c718b132966ae)

No response from you, so i guess you left the room.
