### ISSUE TITLE
[Bug] Show continues to update after setting "Upgrade Once"

### ISSUE THREAD

**Issue by NyvenZA** [SickGear/SickGear#1281]
#### Branch version commit hash: b9d0bd7 @ 0.21.32

Expectation | Result
------------ | -------------
Tick the "Upgrade Once" tickbox on a show to Stop upgrading the show after the first update was done.  | The tick box for this feature doesn't save and the show continues to update. 

**Steps to reproduce:**
*1)* Click the Edit button at the top of an existing show that has a Custom Quality Download. 
*2)* Tick the box for "Upgrade Once" to stop further upgrades. 
*3)* Click "Update Show". 
*4)* When you go back into the EDIT show, the tick box is unticked. It continues to update the show.

Running on Linux Ubuntu server.

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.34)

Thanks for the report.
