### ISSUE TITLE
tvshow.nfo files are updated daily

### ISSUE THREAD

**Issue by NyvenZA** [SickGear/SickGear#1282]
#### Branch version commit hash: 7603ea7 @ 0.21.34

Expectation | Result
------------ | -------------
Only TV series that has updated or new TV information should be updated | All the TVseries nfo files are updated every day. 

I am not sure if this a bug or not, but i could not find a setting to disable this behavior. The TVShow.nfo files are being update every day. I don't know why. This causes the checksum/last access date to change and the files get re-indexed for searching every day. 

These are the settings that I thought might be relevant and what my settings are set too:

- General -> Misc -> Update shows on startup -> DISABLED
- Media Process -> Metadata -> KODI 
  - ALL enabled except SHOW BANNER, SEASON ALL POSTER and SEASON ALL BANNER

**Comment by JackDandy** [comment]
This is as designed as tvinfo can be updated at any time at souce.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
