### ISSUE TITLE
Provider Request (not an error)

### ISSUE THREAD

**Issue by Mikhail-Zex** [SickGear/SickGear#1285]
So, I have been trying to get Disney Gallery: The Mandalorian S01 E05, E06 at 720p. No results found as some of the sites are down and other unaccessable. So i manually searched for it. It would be nice if you could as [Kickass](https://katcr.co/) as a source.

**Comment by JackDandy** [comment]
A note about [feature requests](https://github.com/SickGear/SickGear/issues/770) :)

Thanks.

**Comment by JackDandy** [comment]
After a look, that URL leads to nowhere.

Also, I recommend you get yourself into a private tracker, they are far more stable and reliable.

Due to the URL being no good i have to decline this request.

**Comment by Mikhail-Zex** [comment]
Ok, cool. Thank you.
