### ISSUE TITLE
IRC channel not found

### ISSUE THREAD

**Issue by DecipherIt** [SickGear/SickGear#1286]
I tried connecting to the IRC channel but there seems to be no channel named SickGear on freenode. Sickrage is available but no sickgear.

**Comment by JackDandy** [comment]
Try lowercase `#sickgear`

**Comment by DecipherIt** [comment]
I did! but could only find sickbeard and sickrage, I tried searching on Kiwi, Mibbit and Hexchat, is the channel still on freenode?

**Comment by JackDandy** [comment]
yup. did you make sure you identified with the network. the channel will not appear on listings. you must simply join it (provided you are identified with nickserv)

**Comment by DecipherIt** [comment]
Weird I'm identified with NS but can't find it.

**Comment by JackDandy** [comment]
dunno what to tell you, we've been in there is 2014

**Comment by anoma** [comment]
are you forgetting the # in the name cause it def exists :)

**Comment by JackDandy** [comment]
There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
