### ISSUE TITLE
onTxComplete.bat not working

### ISSUE THREAD

**Issue by DecipherIt** [SickGear/SickGear#1287]
BRANCH: master @ py2.7.13 / COMMIT: a15197e @ 0.21.36

Expectation | Result
------------ | -------------
I expect onTxComplete.bat to work after a file completes but it doesn't start.

**Steps to reproduce:**
*1)* Run utorrent on win10 with  cmd /c start "" /B C:\SickGear\SickGear\autoProcessTV\onTxComplete.bat "F:\sg_pp" "SG" "%L" "%D\%F" as the "run on complete" option.
*2)* see it do nothing.but open C:\WINDOWS\system32 in a file browser
...

No logs, it doesn't  seem to do anytthng.

Additional notes:

I followed the tutorial on github, it simply doesn't work. I used to  use the post process script from Clint (couchpotato) but that just gets worse every update and errors out, so I switched to onTxComplete but it doesn't do anything when a file finishes from utorrent.
it just opens the system32 folder every time a file finishes.

I think i'm just doing something wrong but since there is no IRC I have to go through this way.

**Comment by JackDandy** [comment]
As stated in the instruction, you must be using **uTorrent 2.2.1 clients**

**Comment by DecipherIt** [comment]
I'm using utorrent 2.2.1, i'ts the one of the only utorrents still allowed in most places.

**Comment by JackDandy** [comment]
Do you actually have a folder called `sg_pp` on an `F:` drive, or did you realise to change it to your system? Or are you just copy pasting and thinking that that is it?

**Comment by JackDandy** [comment]
Do you actually have a folder called `sg_pp` on an `F:` drive, or did you realise to change it to your system? Or are you just copy pasting and thinking that that is it?

it sounds like maybe your system may not be set up to run the batch file from uT, some security measure perhaps? Try changing out the command to run with something simple like `dir c:\temp` and making sure that that works first. Also, the script contains a test mode flas `SET testmode=` set that to 1 and you should see the script simply output stuff when it is run, if not, then you have an issue running external scripts from uT. This is not a problem with the script itself.

**Comment by DecipherIt** [comment]
I followed the guide to the letter so no I don't have an F:drive and yes I copy and pasted it assuming it would work. I have no idea what else to put there and the guide doesn't really explain otherwise.

No real security measures, Avast running on the background but I whitelisted the directory but doesn't block anything tp begin with.

**Comment by JackDandy** [comment]
> I followed the guide to the letter so no I don't have an F:drive and yes I copy and pasted it assuming it would work

Sounds like you neglected the bit about `param1` as that line is not a copy/paste line... it is an example. This is why the guide describes what all the params are about, because you adjust to **your** system setup. If the script simply worked for all systems then there would be no need to document with the level of detail and attention that you can see there. I suggest you read again, as I am now away for some hours.
