### ISSUE TITLE
Enhancement: Don't mark as snatched episodes for pseudo-season pack that haven't been aired yet

### ISSUE THREAD

**Issue by skepticalwaves** [SickGear/SickGear#1290]
#### Branch version commit hash: e22281e

Expectation | Result
------------ | -------------
When using the "season packs only" or "use alternate episode search mode", SickGear will sometimes grab "pseudo" full-season episode packs, which are marked as full seasons when the season has yet to be fully aired. When this happens, future episodes are marked as snatched and not searched for anymore. | When grabbing an episode pack for a season, don't mark episodes yet to be aired as snatched.

**Steps to reproduce:**
*1)* Search for an episode pack before a season has completely aired

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags
No errors logged

Additional notes:
The "Search Tasks" -> "Unaired episodes" setting, which I currently have *unchecked*, should probably interact with the effect above so that if checked it would allow unaired episodes to be marked as snatched (or at least imported if found in the completed download?)

**Comment by JackDandy** [comment]
> SickGear will sometimes grab "pseudo" full-season episode packs, which are marked as full seasons when the season has yet to be fully aired

Correct, and due to such shenanigans, it is actually recommended on the UI to only enable season packs searching when you are sure you want to use it, and disable afterwards to run with the far better episode method. 

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by skepticalwaves** [comment]
> To delve a little deeper, how do we know for sure of a "psuedo" season pack

Sure, I agree here, I don't think SickGear should be able to determine this, but rather, as an extension of the `` "Search Tasks" -> "Unaired episodes"`` setting that episodes which are unaired won't be imported (existing config) and also won't be marked as "snatched" (my enhancement request).

**Comment by JackDandy** [comment]
okay, so here we consider, if a season pack says it has all eps, sg must mark all as snatched, this cannot change, and it overrides that setting, correctly. What i think you are saying, is that after post processing, episodes that do not exist should be marked back to the previous state. Does this sound right?

**Comment by skepticalwaves** [comment]
Yes, that would be one way to handle this that would be acceptable.

**Comment by JackDandy** [comment]
On talking this idea over, there is too much of a can of worms to go down reverting items here.

The bottom line is that it's simply bad that something that is not really an entire season pack is labelled as such. Another reason to get into private trackers, this issues rarely occurs there.
