### ISSUE TITLE
EZTV provider choosing wrong table

### ISSUE THREAD

**Issue by PhantasmNZ** [SickGear/SickGear#1292]
Hey there - thanks for all your hard work on this - I'm just coming back to looking at this after an absence and struggled tor get the eztv provider to work.  What I'm noticing is that the script seems to be returning results only from the "EZTV 15 Most Popular Torrents (last 24 hours)" table and not the search results above it.  

Also there is an EZTV API now - wonder if that would make a better provider. 

Sorry if these have been asked before (I did a search and didn't find anything) 

Thanks

**Comment by JackDandy** [comment]
Hi,

I'll label this issue as an `enhancement` for the API stuff and look into it later.

**Comment by PhantasmNZ** [comment]
Thanks @JackDandy  I'll keep an eye out.  Totally understand that it takes some time when you're giving your own time to projects - and thanks again for all you do. 

In the meantime, could you point me to a resource that would allow me to have a go at troubleshooting why the HTML parser is looking at the wrong table (sorry have no experience with Beautiful Soup -so  if you have any documentation or comments about how the py script directs the parser to the right areas (both tables have the same class so I'm unsure both why it only picks up one table and not both, and if that's expected, how I could direct it to only the first)

**Comment by JackDandy** [comment]
>  What I'm noticing is that the script seems to be returning results only from the "EZTV 15 Most Popular Torrents (last 24 hours)" table and not the search results above it.

When i go directly to the site in a browser i do not see the "most popular" list that you refer to, am i doing something wrong? as i don't see an issue here
