### ISSUE TITLE
Media Provider error

### ISSUE THREAD

**Issue by Androkiller** [SickGear/SickGear#1293]
#### Branch version commit hash: fa227f7 @ 0.21.37

Got this in my logs and yes TD wont work

2020-06-30 09:18:31 WARNING  SG_HELPER :: Exception caught while loading URL https://tday.workisboring.net/
 1) Detail... Error #1 Cloudflare anti-bots changed, please notify SickGear for an update
 2) Traceback (most recent call last):
 3)   File "/opt/sickgear/lib/sg_helpers.py", line 299, in get_url
 4)     response = session.get(url, timeout=timeout, **kwargs)
 5)   File "/opt/sickgear/lib/requests/sessions.py", line 550, in get
 6)     return self.request('GET', url, **kwargs)
 7)   File "/opt/sickgear/lib/cfscrape/__init__.py", line 63, in request
 8)     resp = self.solve_cf_challenge(resp, **kwargs)
 9)   File "/opt/sickgear/lib/cfscrape/__init__.py", line 129, in solve_cf_challenge
10)     js = self.extract_js(body, domain)
11)   File "/opt/sickgear/lib/cfscrape/__init__.py", line 172, in extract_js
12)     raise RuntimeError('Error #1 Cloudflare anti-bots changed, please notify SickGear for an update')
13) RuntimeError: Error #1 Cloudflare anti-bots changed, please notify SickGear for an update

**Comment by JackDandy** [comment]
Yes, confirmed, thanks for the report.

**Comment by galant56k** [comment]
is this issue fixed? as I am still having the same problem.

**Comment by JackDandy** [comment]
Yes @galant56k this issue still exists.

**Comment by ambreswe2** [comment]
Still an issue for IPT.

**Comment by JackDandy** [comment]
BTW this is only an issue for a **minority** of providers that use CF IUAM and do not have a dedicated API. 

The current situation is that it _may_ be impractical to address this issue, and TD/IPT etc. _may_ need to be removed until either a solution is found, or a proper API is added to affected sites.

The core issue lies in a sophisticated game-like protection akin to Denuvo DRM system that CF deployed.

One library claims to have solved this and is requesting payment from everyone that uses it, SickGear has never used that library and wonders about it's stability and reliability given our research into the CF protection mechanics. Also, the CF CEO posted on Twitter how his daily amusement is reading issues on GitHub projects that talk about being blocked from accessing CF IUAM sites and he references the same library, therefore, CF will change mechanics at any point. <img src="https://i.vgy.me/h1D0Aw.png"> 

Conclusion, on one side is a company with staffers dedicated to task, on the other, a project making money thwarting the output of those staffers. A cat and mouse situation is here in earnest, this is why this situation seems impractical to resolve, _perhaps_ it is better not to bother with provider sites that use IAUM unless that site creates a dedicated API for its users. We shall see.

**Comment by ryanneufeld** [comment]
Apparently for TD there is a json api that can be used for back searching
https://www.torrentday.com/forums.php?t=5135868

Is this supported?

**Comment by JackDandy** [comment]
That endpoint is also behind the Cloudflare screen, so nope. Ideally, like rarbg did years ago, and many others do, providers should have an independent URL that has nothing to do with Cloudflare and uses a simple authentication token for access security.

**Comment by jstevenson72** [comment]
I had to switch to Jackett/Sonarr unfortunately.  Jackett has no issues scraping IPT.

I do miss SickGear though.

**Comment by JackDandy** [comment]
@jstevenson advertising other app is not a nice way to go about helping is it?

**Comment by JackDandy** [comment]
All is not lost, someone reported something to me privately to research at the weekend.

**Comment by ambreswe2** [comment]
> All is not lost, someone reported something to me privately to research at the weekend.

Sounds promising!

**Comment by ryanneufeld** [comment]
At the moment, I can't even load the media providers config page.

Even if I had somewhere else to search, I can't even add it.
--Ryan Neufeld BSc CIS
ryan@neufeldmail.com

**Comment by JackDandy** [comment]
Stop sg, edit the config.ini, remove `torrentday = 1`, start sg, should be fine, no one has reported such an issue since this one started though. If this doesnt make sense to you, please come to the IRC as I'd rather keep this thread clear to the core point, the web view of this thread is not like your email perspective ;)

**Comment by JackDandy** [comment]
@jstevenson72 I removed your post as it contained inappropriate content, you could easily have pm'd me to be real.

To expand on the above, the latest system has very few similarities to the previous, the previous contained obfuscated JS code in the original fetched html content, performed a JS challenge in the browser, then sent the result back to CF, the latest, sets up a config object in the original html, makes an additional request for an encrypted JS file, and then performs a number of other tasks from arbitrary mutating JS code. This distinction is important to know because it enables viable identification of a solution.    

Anyway, after looking into what you asserted, I can confirm that Jackett includes a third party library that does **not** contain any handling for the latest CF IUAM revision. To be clear, the library does not have any of the identifiers known to be required to decrypt the latest CF challenge. The .net library was last compiled/updated 26.05.2020, when the release of the previous version of CF IUAM code took place and before the latest system was deployed.  

So, the question is, how was it thought to work, perhaps misinformation, who knows.  Anyway, I suspect simply browsing to a CF cloaked site in a local browser, will flag the IP or something, as not needing to be served another challenge until days or weeks later in time at the server side of CF. Also, maybe more cookies are used than what is currently used in SG, and perhaps a CF clearance cookie is the difference.  It would be interesting to clarify this, and if true, the cookie should need manually refreshing at some point later.

**Comment by jstevenson72** [comment]
I'm sorry if I stirred things up, that was not my intention. If you'd like
me to provide you with anything let me know.

Jackett for whatever reason has always worked.  I can get you any logs you
need, if you would like to see more with how it's doing things.

I'd only ever used it with Radarr, but I had to switch to Sonarr
regretfully, to keep my wives TV shows working.

Let me know if I can help.  I tried asking about you about Jackett with
when the problem first came up, but your reply wasn't helpful, suggesting I
not use it.

**Comment by JackDandy** [comment]
> Jackett for whatever reason has always worked

Nope, you are absolutely mistaken, and that statement is misinformation.

Jackett is functioning as a **cookie proxy**. A cookie proxy is not a challenge solver, therefore you need to manually refresh the cookies from your browser once a month... or every hours when CF reduce the cookie timeout to spoil this trick.  

I don't expect you to take my _unhelpful_ word for it, so the lib that Jackett uses is [here](https://github.com/RyuzakiH/CloudflareSolverRe/issues) - if you look at the issue 32 in that project, `ngosang` links to Jackett development thread 8840 where he explains his findings, the situation as he sees it, and what he considers to do next. He started two currently experimental projects on issue thread 9029, `FlareSolverr` and `FlareSolverrSharp`. You will also see there `D3faIt` talking about configuring the cookie proxy trick. But the thing with *arr + *err, is the resource hit.

This is why SG is seeking a proper solver. If you can update CloudflareSolverRe for the latest CF revision - we can port it from .net to Python - and this would be helpful for all communities.

**Comment by JackDandy** [comment]
> Jackett for whatever reason has always worked

Nope, you are absolutely mistaken, and that statement is misinformation.

Jackett is likely functioning as a **cookie proxy**. A cookie proxy is not a challenge solver, therefore you need to manually refresh the cookies from your browser once a month... or every hours when CF reduce the cookie timeout to spoil this trick.  

I don't expect you to take my _unhelpful_ word for it, so the lib that Jackett uses is [here](https://github.com/RyuzakiH/CloudflareSolverRe/issues) - if you look at the issue `32` in that project, `ngosang` links to Jackett development thread `8840` where he explains his findings, the situation as he sees it, and what he considers to do next. He started two currently experimental projects on issue thread `9029`, `FlareSolverr` and `FlareSolverrSharp`. You will also see there `D3faIt` talking about configuring the cookie proxy trick. But the thing with *arr + *err, is the resource hit.

This is why SG is seeking a proper solver. If you can update CloudflareSolverRe for the latest CF revision - we can port it from .net to Python - and this would be helpful for all communities.

[edit: looking even further, issue 9429 states logging out of site will break Jackett - the dev says, "Jackett cannot handle the cloudflare challenge"]

**Comment by jstevenson72** [comment]
I guess what I mean by always worked, is I haven't had it fail.

I do however hit IPT with my browser quite often, and as you suspect that
could be what is making things work.

I'll review those projects today and see if I can be of any help.

**Comment by JackDandy** [comment]
@Androkiller @ambreswe2 @ecoolaid @galant56k @Namlaz @jstevenson72 @ryanneufeld 

Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.46)

**Comment by JackDandy** [comment]
This solution is not great. It would be far better if TD/IPT had an independent URL that is not behind the CF IUAM cloak. This is not what I meant by needing an API, I'm aware TD has a JSON/RSS offer, but those URLs are also behind the CF cloak so is equally as useless as not having an API if CF decide to prevent users from using cookies.

**Comment by Namlaz** [comment]
> 
> 
> @Androkiller @ambreswe2 @ecoolaid @galant56k @jstevenson72 @Namlaz @ryanneufeld
> 
> Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.46)

Thank you for the update !

Could you please support EZTV too ? 🙏

**Comment by JackDandy** [comment]
There is an added dimension that makes EZTV problematic with this method, so for now, disable it.

**Comment by JackDandy** [comment]
This is now fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.23.14).

@Namlaz EZTV is back online.

When you guys dig into the new feature added here, you will see links to an SG doc info about all of this. Enjoy.

**Comment by Namlaz** [comment]
This is great thank you 👍  just set this up.

Cheers !

**Comment by JackDandy** [comment]
Great to hear, thank you for the feedback @Namlaz 👍
