### ISSUE TITLE
migration from Sickchil failed/rejected

### ISSUE THREAD

**Issue by mgaulton** [SickGear/SickGear#1295]
Hi All, 
Wondering if you could point out what I may be doing wrong. Following the wiki to migrate, I get an error.

clean git clone of sickgear
cp config.ini and sickbeard.db from sickchill

python3 sickgear.py.

Ends with
12:42:07 ERROR MAIN :: SickGear does not currently support upgrading from this database version

Any assistance appreciated.

**Comment by JackDandy** [comment]
> Following the wiki to migrate

The very first sentence of the wiki states `This guide shows how to migrate from SickBeard.` because that particular database is pure to any fork, it is the grandfather of SickGear, and is what is fully supported. 

However, the DB of all forks diverged a few years ago and writing fixes for what often proved corrupt data that actually caused issues inside SG soon came to a head.  It had to be decided whether to risk instability inside SG due to those corruptions, therefore, stability won out and support stopped for those DBs.

So, these days, install SG fresh, set it up, and do right side menu/import shows, as explained in the wiki guide at the paragraph starting _For other forks_. The guidance you wanted is all there in that wiki page.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by mgaulton** [comment]
Sorry, wasn't sure what avenue to ask the questions :)

I actually flushed clean and tried again with a new DB and when I mass
selected shows to import, it goes to a error page with empty response
messages.
Is there a limit to the number of shows you can import in one pass?
1500 shows I believe in my list.

**Comment by JackDandy** [comment]
I recommend, to first try with 1 show to gain a comfortable feeling of the process.
Then, scale up to 5 shows to gain an understanding of the time taken for importing with your set up.
Then go for say a couple hundred at a time, and leave it to it given it will take some time given there is a lot going on to import, for example, the many cache image types as well as timed interactions with tvdb api, and other resources overheads involved in the import process.

**Comment by JackDandy** [comment]
I recommend, to first try with 1 show to gain a comfortable feeling of the process.
Then, scale up to 5 shows to gain an understanding of the time taken for importing with your set up.
Then go for say a couple hundred at a time, and leave it to it given it will take some time given there is a lot going on to import, for example, the many cache image types as well as timed interactions with tvdb api, and other resources overheads involved in the import process. Throwing 1500 shows at it is not a good idea.

**Comment by mgaulton** [comment]
OK, that's kind of what I was thinking. I imported 1 show with no issues.
Seemed painless.
I have 3 NAS on the network so it may be a while lol
I"ll give her a go, thanks again.

**Comment by mgaulton** [comment]
Guessing while I wait on imports. When I try and enable Trakt integration,
I get the PIN, it adds the user but when I go to save I get the below
message

```
2020-07-08 16:39:44 DEBUG    TORNADO :: stack_size -> 0
2020-07-08 16:39:58 ERROR    TORNADO.APP :: Uncaught exception POST
/config/notifications/save-notifications (192.168.2.27)
HTTPServerRequest(protocol='http', host='192.168.2.5:8182', method='POST',
uri='/config/notifications/save-notifications', version='HTTP/1.1',
remote_ip='192.168.2.27')
Traceback (most recent call last):
  File "/opt/SickGear/lib/tornado_py3/web.py", line 1700, in _execute
    result = await result
  File "/opt/SickGear/lib/tornado_py3/gen.py", line 191, in wrapper
    result = func(*args, **kwargs)
  File "/opt/SickGear/sickbeard/webserve.py", line 822, in get
    self.route_method(route, use_404=True)
  File "/opt/SickGear/sickbeard/webserve.py", line 219, in route_method
    result = method(**request_kwargs)
  File "/opt/SickGear/sickbeard/webserve.py", line 7387, in
save_notifications
    sickbeard.TRAKT_UPDATE_COLLECTION = build_config(**kwargs)
  File "/opt/SickGear/sickbeard/trakt_helpers.py", line 40, in build_config
    if account_id and decode_str(base64.urlsafe_b64encode(cur_dir)) ==
location:
  File "/usr/lib64/python3.8/base64.py", line 118, in urlsafe_b64encode
    return b64encode(s).translate(_urlsafe_encode_translation)
  File "/usr/lib64/python3.8/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

```

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.38)

Thanks for the report.
