### ISSUE TITLE
Cannot start SickGear

### ISSUE THREAD

**Issue by 5p0ng3b0b** [SickGear/SickGear#1298]
#### Branch: master

Expectation | Result
------------ | -------------
start sickgear daemon | OSError: File not found

**Steps to reproduce:**
*1)* git clone https://github.com/SickGear/SickGear.git sickgear
*2)* cd sickgear
*3)* python -m pip install -r requirements.txt
*4)* ipkg install libxlm2 libxslt sqlite
*5)* python -m pip install lxml
*6)* python -m pip install regex
*7)* ./sickgear.py --daemon

  File "./sickgear.py", line 88, in <module>
    import sickbeard
  File "/mnt/system/opt/apps/sickgear/sickbeard/__init__.py", line 41, in <module>
    from . import classes, db, helpers, image_cache, indexermapper, logger, metadata, naming, providers, \
  File "/mnt/system/opt/apps/sickgear/sickbeard/classes.py", line 28, in <module>
    from .common import Quality
  File "/mnt/system/opt/apps/sickgear/sickbeard/common.py", line 30, in <module>
    from _23 import map_list
  File "/mnt/system/opt/apps/sickgear/lib/_23.py", line 219, in <module>
    from lib.scandir.scandir import scandir, GenericDirEntry as DirEntry
  File "/mnt/system/opt/apps/sickgear/lib/scandir/scandir.py", line 456, in <module>
    libc = ctypes.CDLL(ctypes.util.find_library('c'), use_errno=True)
  File "/opt/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: File not found

**Comment by JackDandy** [comment]
You have not included all expected info, so i can only say this... do not run with `--daemon` switch.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
`find_libary()` uses the os functions that are avalible via 1 of the 3 methods: "ldconfig -p" or "gcc cc objdump" or "ld objdump" 

Try that, and let me know.

**Comment by 5p0ng3b0b** [comment]
Thanks for getting back. I was trying to install on an old arm based NAS running [optware-ng](http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng/) packages. ipkg is a bit like apt but all copied and linked to /opt folder. I had sickbeard running on it about 6 years ago and only needed to add cheetah back then. I can normally debug stuff but I only have a VERY basic knowlege of python.

**Comment by JackDandy** [comment]
ahh okay, in that case, u can alternatively try installing py3, that has the packages built in ;)

**Comment by JackDandy** [comment]
ahh okay, in that case, u can alternatively try installing py3, that has the scandir package requirement built in ;)

**Comment by 5p0ng3b0b** [comment]
erm......
After running down many rabbit holes in the last 24+, a couple of things learned.
The shebang in sickgear.py specifies python2 rather than just python (didn't see the 2).
I had made symlink to` python3 > python` and couldn't get my head around why running `./sickgear.py` kept saying my python2.7 was out of date (can't remove it from firmware or update it). So I ended up trying to troubleshoot doing a bunch of unrelated stuff with pip etc and got into a bit of a pickle.
When I ended up running `python3 sickgear.py`, I still had problems because i had installed cheetah and not cheetah3 (didn't see the 3 and yes I know a pattern is developing). cheetah had installed in a strange folder (some bug I don't know) and I ended up trashing more shuff trying to fix cheetah. By then I was then fixated with pip being the problem and borked even more unrelated stuff up. Eventually I saw the 3 and finally got there.
Definitely worth slogging it out though amazing ui. No time to play for a while now.
Thank you!

**Comment by JackDandy** [comment]
Ah yeah, people that run bare `./sickgear.py` and refuse to explicitly run `python /sickgear.py` will fall down rabbit holes, it does show everywhere to be explicit, but I guess those that have enough knowledge to be dangerous are the ones that trip over. As you may be aware, we have no plans to change the shebang as it works perfectly for Python2 users, and given SIckGear fully supports both, then there is no plans to change it.  Glad you got there, and for reading your story, I'll look to add some texts into the wiki here and there to reinforce the explicit specifying of the binary `python` in light of your feedback.

Thanks.

**Comment by psi5asp** [comment]
shouldn't sickgear.py should just have #!/usr/bin/env python instead of #!/usr/bin/env python2 to avoid this?

**Comment by JackDandy** [comment]
People read the instructions, so in the main, they know how to run things here.

To change such learned things at this point may break things, and stability across all platforms is key. 

That said, when a time comes that py2 support is removed, then this will change. But that time is not here.
