### ISSUE TITLE
Exception caught while loading URL https://www.torrentday.com/

### ISSUE THREAD

**Issue by ecoolaid** [SickGear/SickGear#1301]
#### Branch version commit hash: (See the About page)
BRANCH: master @ py2.7.10 / COMMIT: 1f418ac @ 0.21.42

Expectation | Result
------------ | -------------
From my log file:
2020-08-13 17:44:57 WARNING  SG_HELPER :: Exception caught while loading URL https://www.torrentday.com/
 1) Detail... Error #1 Cloudflare anti-bots changed, please notify SickGear for an update
 2) Traceback (most recent call last):
 3)   File "/opt/sickgear/lib/sg_helpers.py", line 299, in get_url
 4)     response = session.get(url, timeout=timeout, **kwargs)
 5)   File "/opt/sickgear/lib/requests/sessions.py", line 550, in get
 6)     return self.request('GET', url, **kwargs)
 7)   File "/opt/sickgear/lib/cfscrape/__init__.py", line 63, in request
 8)     resp = self.solve_cf_challenge(resp, **kwargs)
 9)   File "/opt/sickgear/lib/cfscrape/__init__.py", line 129, in solve_cf_challenge
10)     js = self.extract_js(body, domain)
11)   File "/opt/sickgear/lib/cfscrape/__init__.py", line 172, in extract_js
12)     raise RuntimeError('Error #1 Cloudflare anti-bots changed, please notify SickGear for an update')
13) RuntimeError: Error #1 Cloudflare anti-bots changed, please notify SickGear for an update

**Steps to reproduce:**
I manually searched for an episode that had not automatically downloaded.  

Additional notes:
Please let me know if there is more info required?

**Comment by JackDandy** [comment]
#1293
