### ISSUE TITLE
Norwegian metadata from TheTVDb not getting fetched.

### ISSUE THREAD

**Issue by aMvEL** [SickGear/SickGear#1303]
BRANCH: develop @ py3.8.5 / COMMIT: b1274b8 @ 0.22.0

Expectation | Result
------------ | -------------
Norwegian metadata to be fetched and used when selected in SG and available on thetvdb | English metadata is fetched regardless. so it often returns emtpy info and episode titles for Norwegian shows with no English info..

**Steps to reproduce:**
*1)* Add a tv show that is known to have Norwegian metadata to SG. For Example https://thetvdb.com/series/fremvandrerne. aka Beforeigners.
*2)* Observe that English info/titles are fetched.
...

Additional notes:
It seems that TheTVDb API v3 is confused. Because I edited SG code to hard code use language tag 'nb' on API requests, and it fetched the info correctly. I suspect that when migrating to v3 API they somehow merged the Norwegian (no) and Norwegian Bokmål (nb/nob) language codes. I tried reporting the "bug" on their forums, and it supposedly got ticketed, but nothing has happened. Hopefully it will be fixed for v4, but as a reminder this issue is created for whenever v4 gets released, and SG gets migrated to it. So that you can take a look at it then.

**Comment by JackDandy** [comment]
Will be looked at during tvdb v4 dev
