### ISSUE TITLE
Subtitle search gives a traceback, even when search is disabled

### ISSUE THREAD

**Issue by seabert** [SickGear/SickGear#1307]
#### Branch version commit hash: COMMIT: f2ac809 @ 0.21.45

Expectation | Result
------------ | -------------
Subtitles being searched and found when the search is enabled. After turning of the search, I expect that the task for it would also be disabled. | With all or any plugin enabled, the subtitle search results in a traceback. When the search for it is disabled, the task is still executed and again results in a traceback.

**Steps to reproduce:**
*1)* Enable search for subtitle with all plugins
*2)* Let SG search for subtitles
*3)* Get errors, turn off substitle search

Two [logs](https://gist.github.com/seabert/3259ebed376db8d145167b39c79c7059), one when disabled and one with enabled search.

Additional notes:

```
$ egrep -i '^(use_)?sub' config.ini
use_subtitles = 0
subtitles_languages = en
SUBTITLES_SERVICES_LIST = "addic7ed,opensubtitles,thesubdb,tvsubtitles"
SUBTITLES_SERVICES_ENABLED = 1|1|1|0
subtitles_services_auth = username:::password
subtitles_dir = ""
subtitles_default = 0
subtitles_history = 1
subtitles_finder_frequency = 1
subtitles_os_hash = True
```
Above config was when it was disabled. The same settings are used when enabled. The username:::password is obviously retracted.

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.47)

Thanks for the report.

**Comment by seabert** [comment]
Thanks for the fix, Jack. But I'm not sure if it also fixes the traceback when the subtitles _are_ enabled? Maybe I should have been more clear.

**Comment by JackDandy** [comment]
No you didn't need to raise about the trace-backs, they are known. and a larger change is underway to upgrade the third party libraries used for subtitles.

Unfortunately, the upgrade is not a drop in one, it contains many breaking changes. This means time, and any issues with the the existing subtitle code can not be addressed as that code is not likely to even exist in the upgrade.  So what we have been doing is collecting episodes names that we can use a tests when that migration is complete.

**Comment by JackDandy** [comment]
No you didn't need to raise about the trace-backs, they are known. and a larger change is underway to upgrade the third party libraries used for subtitles.

Unfortunately, the upgrade is not a drop in one, it contains many breaking changes. This means time, and any issues with the the existing subtitle code can not be addressed in the current code, because that code change will most likely not even exist in the upgrade code, such is the difference.  All that can be done is to collect episodes names that can be used as tests when that migration is complete.

**Comment by seabert** [comment]
Ah, I wasn't aware. Thanks again, for the explanation too. I can dig up some other episode names if that's helpful.

**Comment by JackDandy** [comment]
> I can dig up some other episode names if that's helpful.

Yes it is. Pop them in a gist, and if you can PM me on IRC it would be better.
