### ISSUE TITLE
Can't start sickgear

### ISSUE THREAD

**Issue by DecipherIt** [SickGear/SickGear#1308]
#### Branch version commit hash: don't know

Expectation | Result
Sickgear to start | Errors out without producing a log

**Steps to reproduce:**
*1)* start sickgear from link D:\Users\Computer\AppData\Local\Programs\Python\Python38\python.exe D:\SickGear\SickGear\sickgear.py --datadir "D:\SickGear\data"
*2)* opens then closes with an error I can't read because it's so fast but what I can understand from it says "During handeling of the above execution, another exception occured"and then some lines of code I can't read because it closes so fast. No log is created.
...

Additional notes:
This is a fresh install on a new computer with the data directory copy and pasted in the directory like I have previously done before. I must be doing something else wrong.
I followed the entire setup guide but it doesn't start up (tried running as user and as Admin). Please help.

**Comment by JackDandy** [comment]
come to irc

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by DecipherIt** [comment]
Where can I find the IRC info?

**Comment by JackDandy** [comment]
It's been a 30 minute wait, and you have not come to IRC for help or replied here even. It is normal to take the help that you ask for, and not leave people waiting around for you.

**Comment by JackDandy** [comment]
homepage says it at the bottom, but here it is copied... (irc.freenode.net channel #SickGear)
