### ISSUE TITLE
Only using the first object of many in the required words list against the search results retrieved from the search provider..

### ISSUE THREAD

**Issue by MacGyverr** [SickGear/SickGear#1311]
BRANCH: master @ py2.7.12 / COMMIT: 2dcfabb @ 0.22.1

Expectation | Result
------------ | -------------
use multiple keywords against results of search results when separated by a comma | only uses the first word/term before the comma, ignoring all other after

**Steps to reproduce:**
1) search for something, watch it fail
2) review log, and notice that many results should have matched your required keywords, notice that only the first is being applied to those results.
3) remove all search words from the required field, replace them with only one (that matches one of the results on the log)
4) run scan again, it finds it now.
...

**Comment by JackDandy** [comment]
1) there are two places for require words, which one are you talking about?
2) are you using regex, what is an example of the items in the setting?

**Comment by MacGyverr** [comment]
Common words, like this "720P.HDTV.X264-KILLERS,HDTV.X264-SVA,720P.HEVC.X265-MeGusta", the log shows that the results returned by the site match at least one of those terms, but only the first one is being compared in the log.
If I remove everything before one of the terms that match, it then matches.

**Comment by JackDandy** [comment]
Please read my edits, your answer is not covering everything.

**Comment by MacGyverr** [comment]
In the show search settings, the master list is empty.

**Comment by MacGyverr** [comment]
It looks like it may only be working with just one term, not just the first, but only when it is one.

**Comment by JackDandy** [comment]
Yes, this is a confirmed bug. Thanks for the details.

**Comment by MacGyverr** [comment]
No problem, always happy to help if I can, you guys rock :)

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.22.2)

Again, thanks for your report, help, and time :)
