### ISSUE TITLE
bulk change quality?

### ISSUE THREAD

**Issue by prankousky** [SickGear/SickGear#1313]
#### Branch version commit hash: (See the About page)

Hi everybody,

---

branch: `master`
branch version commit: `py3.8.5 / COMMIT: UNKNOWN @ 0.22.2`
python version: `3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]`
installed **via docker**

---

I am looking for a way to bulk change quality to the `CUSTOM` setting that I have created as a default. When initially adding shows, I added a bunch of them as `SD` quality. Later on, I made a custom setting containing multiple formats that I'd like **all my** newly added files to have as minimum.

This is more a request than a bug report, so I did not use the template. I hope this is okay. Unfortunately, I don't know much about IRC, so I was not able to locate the `#SickGear` channel (tried on `FreeNode`).

Thank you in advance for your help :)

**Comment by JackDandy** [comment]
Hello,

So if i understand this correctly, this feature request is...

Initialise the `Bulk Change` quality to the `custom setting` saved as default, during the add shows flow.

Correct?

**Comment by prankousky** [comment]
Pretty much so. Unless there is already a way (perhaps by changing the configuration or some other internal file) to automatically apply the default quality setting.

**Comment by JackDandy** [comment]
Added [here](https://github.com/SickGear/SickGear/releases/tag/release_0.22.3)

Enjoy.

**Comment by prankousky** [comment]
Awesome, thank you so much.
