### ISSUE TITLE
Make sabToSickBeard.py script Python 3 compatible

### ISSUE THREAD

**Issue by Zaister** [SickGear/SickGear#1316]
Please change this script not to force Python 2 which is being sunset on various Linux distributions.

For this, change line 1 from
#!/usr/bin/env python2
to
#!/usr/bin/env python

**Comment by JackDandy** [comment]
Hi, did you fully read [this](https://github.com/SickGear/SickGear/wiki/FAQ-Roadmap)?

**Comment by Zaister** [comment]
Yes I have read it, but it doesn't really help me. The script no longer runs for me, but terminates with the error "You need to install python requests library", because my system will no longer support python 2.7 and will not install the 2.7 version of that library.

Changing that line makes it run for me, but I have to change it again with every update.

**Comment by JackDandy** [comment]
> Yes I have read it

and why does the last paragraph not work for you ?

**Comment by Zaister** [comment]
I have COMMAND="python3.7 /usr/share/sickgear/sickgear.py" in my init-script. (Gentoo Linux). The script is still started with Python 2.7. The line is not ignored, since it works if I change it.

Am I missing something?

**Comment by JackDandy** [comment]
I think you are...

Your issue is about running the core file `sabToSickBeard.py` not `sickgear.py`

Check, is `sabToSickBeard.py` also set properly?

**Comment by Zaister** [comment]
The sabToSickBeard.py is called from inside sabnzbd, where I can select the script in its config, but I cannot force it to call it in any special way.

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.22.7)

Thanks for the report.

**Comment by Zaister** [comment]
Thank you, that works nicely now. (I needed to set the script to executable, though.)

**Comment by JackDandy** [comment]
Ah I've set it +x for the next hotfix, thanks for that feedback.
