### ISSUE TITLE
SickGear broken after forceful restart of the app

### ISSUE THREAD

**Issue by IvoPo** [SickGear/SickGear#1317]
#### Branch version commit hash: [9ff90c7](https://github.com/SickGear/SickGear/commit/9ff90c76eb611571f248b35dd2ee5dee8b22490e)

Expectation | Result
------------ | -------------
SickGear should start :) | It doesn't

#### Steps to reproduce:
*1)* python SickGear.py --help

https://gist.github.com/IvoPo/f3fed035e9efffd6330e2448bcef13c6

#### Additional notes:

- just updated the last 10? or so commits via the webinterface notification banner thingy and sickgear didn't restart on it's own after a few minutes, so i tried restarting it by hand
- Python 2.7.14
- OS: x86_64 GNU/Linux Kernel 4.14 (QNAP NAS)

**Comment by JackDandy** [comment]
Fix pushed

**Comment by JackDandy** [comment]
fyi, you showed a screenshot of an old QNAP version, are you aware that the main first-time install package was updated this year? It now stands at 0.21.3.
