### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by pge-01** [SickGear/SickGear#1324]
Hi Jack,
I wanted to add the links to some images but got the following message: 

This issue has been moved to a repository you don't have access to

Where can I post now?

#### Branch version commit hash: (See the About page)

Expectation | Result
------------ | -------------
Your expectation paragraph(s) text here. Before the bar >> | then, your result paragraph(s) text here.

**Steps to reproduce:**
*1)* Step to take
*2)* Step to take
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
why did you simply not post the screenshots to this new thread?

**Comment by pge-01** [comment]
I uploaded those for some days.
https://www.strongholdstudios.nl/IMG_0747.PNG
https://www.strongholdstudios.nl/IMG_0748.PNG
https://www.strongholdstudios.nl/IMG_0749.PNG
https://www.strongholdstudios.nl/IMG_0750.PNG

**Comment by pge-01** [comment]
Let me know you got them, so I can remove

**Comment by pge-01** [comment]
Okay

**Comment by pge-01** [comment]
Thanks
