### ISSUE TITLE
Sick gear acts as if it's a fresh installation every time

### ISSUE THREAD

**Issue by Mikhail-Zex** [SickGear/SickGear#1326]
#### Branch version commit hash: (See the About page)

Expectation | Result
------------ | -------------
Open SickGear, click on my TV series, download the latest episode by triggering a manual search. | Every time I open SickGear after a week or two, I have to re-setup all of the search providers, my connection to qBitTorrent, re-add all my show,s update the installed seasons and search for the new episodes.

**Steps to reproduce:**
Not sure, it used to work just fine 2 months back, I factory reset my system in b/w, and then this started.

[Log as gist](https://gist.github.com/Mikhail-Zex/4c15a1fb4ccb89b6a2f027106b721111) (best as they are easily deleted)

Additional notes:
- I have my SickGear config folder in the same folder as SickGear, all the config files are untouched but they don't read for some reason.
- It shows `Unknown current version number: If you've never used the SickGear upgrade system before then current version is not set. — Update Now` in spite of this being my third update.

**Comment by JackDandy** [comment]
missing branch and version detail from about page.

**Comment by Mikhail-Zex** [comment]
B/w = between

**Comment by Mikhail-Zex** [comment]
Well thank  you.

But then,
- I have git installed and on my PATH
- I thought it was permission problem and have enabled all permissions for all users on my sickgear datadir. That was the first thing I did.

**Comment by JackDandy** [comment]
> I have git installed and on my PATH

Did you try adding it to the settings directly?

The issue you raise has never occurred before, if it had, then many would be reporting it. Therefore, perhaps something else is conflicting with your SG, perhaps antivirus software or something.

**Comment by Mikhail-Zex** [comment]
I'll try add8ngbit to settings.

No antivirus. Just windows security center.

**Comment by JackDandy** [comment]
This app is developed on Windows 10, the issue you describe must be local.

**Comment by JackDandy** [comment]
This app is developed on Windows 10, the issue you describe must be local. Please let us know when you discover what is conflicting.

Edit: idea Windows Defender?.  Maybe you installed to a folder on `C:` - cannot do this on newer Windows updates, also may have trouble installing to a folder of `D:` theses days.  Try installing to `c:/users/your_username/SickGear/`.

**Comment by JackDandy** [comment]
This app is developed on Windows 10, the issue you describe must be caused by something distinct to your setup... 

Ideas 
1) Windows Defender a cause? 
2) Tried running SickGear with the parameter `--datadir=path/to/a/different/and/new/sg_data/folder` ?
3) Maybe you installed to a folder on `C:` - cannot do this on newer Windows updates, also may have trouble installing to a folder of `D:` theses days.  Perhaps try installing to `C:/users/your_username/SickGear/`. 
4) Other than that, sounds like something in your system is restoring the factory reset position and nuking SG settings

Please let us know when you discover what is conflicting.

**Comment by Mikhail-Zex** [comment]
Will do. But can I query you on a different question in the mean while?

I am the admin on spotDL/spotify-downloader. And we have a hard time keeping up with issues and stuff. How do you guys go about it?

**Comment by JackDandy** [comment]
> How do you guys go about it?

funnily enough, keeping a thread precisely focused on the original point helps, digressions will keep a thread ongoing needlessly.

**Comment by Mikhail-Zex** [comment]
Ok. Won't do that in the future but is there anything else? We really need to get our act together.

**Comment by JackDandy** [comment]
> is there anything else?
  
previous post edited to add other tips.

**Comment by Mikhail-Zex** [comment]
Thanks. I'll let you know if I make a break through with SG issues
