### ISSUE TITLE
Option --daemon fails on py2.

### ISSUE THREAD

**Issue by dikdom** [SickGear/SickGear#1329]
#### Branch version commit hash: BRANCH: develop @ py2.7.16 / COMMIT: 0b6e0c6 @ 0.24.0

Expectation | Result
------------ | -------------
I expect that the ```systemctl start sickgear``` starts the SickGear program. | It was working for years, now it doesn't work.

**Steps to reproduce:**
*1)* systemctl start sickgear
*2)* systemctl status sickgear
* sickgear.service - LSB: starts instance of SickGear
   Loaded: loaded (/etc/init.d/sickgear; generated)
   Active: active (exited) since Mon 2020-11-30 10:06:13 CET; 3s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 6959 ExecStart=/etc/init.d/sickgear start (code=exited, status=0/SUCCESS)

Nov 30 10:06:00 osmc sickgear[6959]: Starting SickGear
Nov 30 10:06:13 osmc systemd[1]: Started LSB: starts instance of SickGear.
Nov 30 10:06:13 osmc sickgear[6959]: Traceback (most recent call last):
Nov 30 10:06:13 osmc sickgear[6959]:   File "sickgear.py", line 732, in <module>
Nov 30 10:06:13 osmc sickgear[6959]:     SickGear().start()
Nov 30 10:06:13 osmc sickgear[6959]:   File "sickgear.py", line 344, in start
Nov 30 10:06:13 osmc sickgear[6959]:     self.daemonize()
Nov 30 10:06:13 osmc sickgear[6959]:   File "sickgear.py", line 623, in daemonize
Nov 30 10:06:13 osmc sickgear[6959]:     os.dup2(stdout.fileno(), sys.stdout.fileno())
Nov 30 10:06:13 osmc sickgear[6959]: AttributeError: 'UnicodeStdout' object has no attribute 'fileno'

...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
SickGear can be started from commandline, without getting this error.

**Comment by JackDandy** [comment]
Fix pushed.

Thanks for the report.
