### ISSUE TITLE
SickGear cannot execute git

### ISSUE THREAD

**Issue by dikdom** [SickGear/SickGear#1330]
#### Branch version commit hash: BRANCH: develop @ py2.7.16 / COMMIT: 0b6e0c6 @ 0.24.0

Expectation | Result
------------ | -------------
SickGear shall be able to update itself, using git. | For some reason the git binary is not accessible to SickGear.

**Steps to reproduce:**
*1)* start SickGear (```~/SickGear/sickgear.py```)
*2)* Checking logs, I can see:
``` 
2020-11-30 10:19:21 DEBUG    MAIN :: Checking if git commands are available
2020-11-30 10:19:21 DEBUG    MAIN :: git to execute /usr/bin/git
2020-11-30 10:19:21 DEBUG    MAIN :: Executing /usr/bin/git version with your shell in /home/osmc/SickGear
2020-11-30 10:19:21 DEBUG    MAIN :: git output: usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
[. . .]
```
*3)* Checking on the GUI I can see this message:
```Unable to find your git executable - Shutdown SickGear and EITHER set git_path in your config.ini OR delete your .git folder and run from source to enable updates.```
In the config.ini I set the git_path to /usr/bin/git
When I deleted the .git folder then there was no option to update the software..

...

Additional notes:
```
$ which git
/usr/bin/git
$ /usr/bin/git version
git version 2.20.1

```

**Comment by JackDandy** [comment]
> When I deleted the .git folder then there was no option to update the software..

Yup, because you deleted the.git folder. You will now have to do a `git clone` to recreate it.

As to the actual issue, a fix is now pushed for this. For now, you can run SG without `--daemon` arg, that will be investigated next.
