### ISSUE TITLE
Downloads Text Color

### ISSUE THREAD

**Issue by Tonkapug** [SickGear/SickGear#1332]
#### Branch: The name of the branch (e.g. master or develop)
master
#### Branch version commit hash: (See the About page)
COMMIT: snap @ 0.23.4

Expectation | Result
------------ | -------------
Your expectation paragraph(s) text here. Before the bar >> | then, your result paragraph(s) text here.

**Steps to reproduce:**
*1)* Step to take
Enable dark mode
*2)* Step to take
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:

Is it possible to change the text color on the 'Downloads' menu items within the 'Show List' menu?

Sorry for not filling the above out in my previous request. I've attached an image below showing the text. On my desktop, it's readable but still not clear. On my laptop, I had to turn the dark mode off as I couldn't read it at all. If the text was bold it may be a little better but I think bold black would make it very clear. I was just wondering if this was possible? Thanks

![ScreenShot001](https://user-images.githubusercontent.com/6201305/101167305-46342380-3614-11eb-862e-a13f93df443b.jpg)

**Comment by JackDandy** [comment]
Sure, will look at changing that.

Thanks for the report.

**Comment by JackDandy** [comment]
Changing the text color to black is unacceptably ugly, and does not perform on dark backgrounds when the bar is not less than 100% width (which you didn't test/see in your image). Therefore, the background colour has been adjusted instead...

<img src="https://i.vgy.me/xW8fAX.png">

**Comment by JackDandy** [comment]
Changing the text color to black is unacceptably ugly, and does not perform on dark backgrounds when the bar is not 100% width (which you didn't test/see in your image). Therefore, the background colours green/gold have been adjusted instead...

<img src="https://i.vgy.me/xW8fAX.png">

**Comment by JackDandy** [comment]
Change [here](https://github.com/SickGear/SickGear/releases/tag/release_0.23.5)

Thanks for the report.
