### ISSUE TITLE
Unable to access any PA Provider

### ISSUE THREAD

**Issue by MikhailZex** [SickGear/SickGear#1335]
#### Branch version commit hash: (See the About page)

Expectation | Result
------------ | -------------
Manual search works | Can't connect to any public access torrent provider

**Steps to reproduce:**
*1)* Enable all PA Torrent Providers
*2)* Search for Disney Gallery: The Mandalorian S2 E1 (or any other ep for that matter, I didn't though)
...

Gist: [ErrorLog](https://gist.github.com/MikhailZex/d8910506cd87caf020c560c9836402a9)

Additional notes:
- Win10 Home 20H2, build 19042.685
- CLoudFlare bot related code needs to be updated (I think)

**Comment by JackDandy** [comment]
Cloudflare started giving trouble last July, non pa providers do not have this trouble.

**Comment by MikhailZex** [comment]
2 things:
- not able to access any PA provider. Is that normal?
- just a suggestion, you could try using cfscrape

**Comment by JackDandy** [comment]
* as you see in your logs, all pa providers are behind cloudflare,therefore all of them are affected 
* `cfscrape` now require payment for the cloudflare protection

**Comment by JackDandy** [comment]
* as you see in your logs, all pa providers are behind Cloud Flare, therefore those are affected 
* `cfscrape` now require payment for the Cloud Flare protection, a free solution is wanted
* non-pa providers that _are_ behind CF use a cookie that does not fall into this issue

**Comment by MikhailZex** [comment]
>cfscrape now require payment for the Cloud Flare protection, a free solution is wanted

[Anorov/cloudflare-scrape](https://github.com/Anorov/cloudflare-scrape) - Not under paywall. Either that or i think i misunderstood.

Got the rest. Thanks for the help.

**Comment by JackDandy** [comment]
> Either that or i think i misunderstood.

Yeah, observe that project has not been updated since 23 Mar 2020... development stalled because **_substantial_** changes to the CF protection system was released around Jul 2020 that broke all solutions.

**Comment by JackDandy** [comment]
> Either that or i think i misunderstood.

Yeah, observe that project has not been updated since 23 Mar 2020, and look at their issues page... development stalled because **_substantial_** changes to the CF protection system was released around Jul 2020 that broke all solutions. It is another project that require payment, you are correct. If you do find a true solution in any language, remember that it can be ported to Python ;)

**Comment by MikhailZex** [comment]
Yessir. I'll ping you if I come across anything.

**Comment by MikhailZex** [comment]
The PA torrent providers work on qbittorrent. Afaik the qbittorrent search runs on python. 

Just a heads up.

**Comment by JackDandy** [comment]
@MikhailZex This is now fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.23.14).
