### ISSUE TITLE
SickGear Wiki's Debian install guide is inconsistent with provided systemd init script

### ISSUE THREAD

**Issue by LazyT1ger** [SickGear/SickGear#1337]
**Branch:** Master
**Version:** Wiki
**Page:** https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B7%5D-Debian#installation

**Issue:**
Debian manual install guide suggests copying and editing systemd script from SickGear/app/init-scripts/init.systemd which sets:  "WorkingDirectory=/opt/sickgear" despite having users create this directory with camel-case "/opt/SickGear" earlier in the guide. Using this as-is will result in service failure with code=exited, status=200/CHDIR because WorkingDirectory is case-sensitive.

**Suggested fix:**
Add the following instruction to the appropriate section of the Debian Manual Install guide:
-  Replace line:  `WorkingDirectory=/opt/sickgear` 
    with line: `WorkingDirectory=/opt/SickGear`

Alternatively, SickGear/app/init-scripts/init.systemd and associated guides could be checked for consistency and edited accordingly. A consistent naming scheme across all guides is advisable- whether camel-case or all-lower.

**Comment by JackDandy** [comment]
Your recommendation has been made to the wiki page as per your guidance.

Thanks for your feedback.
