### ISSUE TITLE
Ignoring legitimate episodes names containing the word "Extra"

### ISSUE THREAD

**Issue by psi5asp** [SickGear/SickGear#1339]
#### Branch version commit hash:  3520ef3 @ 0.23.13

Expectation | Result
------------ | -------------
Importing a series with any episode (S01+ with E01+) containing the word "Extra" in it to be recognised as an episode (with the correct name) | SG does not include legitimate episode names with the word "Extra" in the episide name, rather than just those in the "Extra(s)" folder or S00E**.

**Steps to reproduce:**
*1)* Import existing series called: "Three's Company"
*2)* Check "Three's Company - s07e04 - Extra, Extra" entry.
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags
<pre>
WARNING  POSTPROCESSER :: Failed! Did not process any files.
INFO     SHOWQUEUE-ADD :: 1:77505: Updating NFOs for show with new TV info
INFO     SHOWQUEUE-ADD :: 1:77505: Writing NFOs for all episodes
INFO     SHOWQUEUE-ADD :: 1:77505: Writing NFOs for show
INFO     SHOWQUEUE-ADD :: Get wanted didn't find any episodes that need to be set wanted (...2 repeat lines)
INFO     SHOWQUEUE-ADD :: 1:77505: Loading all episodes from the show directory /mnt/TV/Series/Three's Company
INFO     SHOWQUEUE-ADD :: 1:77505: Loading all episodes for [Three's Company] from TheTVDB..
INFO     SHOWQUEUE-ADD :: 1:77505: Parsed latest IMDb show info for [Three's Company]
INFO     SHOWQUEUE-ADD :: 1:77505: Loading show info [Three's Company] from TheTVDB
INFO     SHOWQUEUE-ADD :: 1-77505: Unable to find the show in the database
INFO     SHOWQUEUE-ADD :: TheTVDB: {'apikey': '*', 'cache': '/opt/SickGear/data/cache/indexers/TheTVDB', 'language': u'en'}
INFO     SHOWQUEUE-ADD :: Starting to add show /mnt/TV/Series/Three's Company
</pre>

Additional notes:
- Possibly any episode of a series that contains the word "Extra" and any other recognisable exclusions.
- Regexpr installed.

**Comment by psi5asp** [comment]
Temporary workaround: 
1) rename the file without the word "Extra" in it, 
2) refresh/import the series (recognises the episode)
3) rename the series (renames back to original name)

**Comment by JackDandy** [comment]
Yes, the rename action is exactly how to handle this rare case.  "Extra" is used far more often as a tag for an extra or special episode for a DVD/Bluray... for example... `Show.S04.Special` or `Show.S05.Part.2.Extras`.  Both cases overlap so there is no clear way to choose one over the other, and so manual intervention is needed on those rare occasions, as you discovered.

**Comment by psi5asp** [comment]
Hi, I'm not familair enough with the usage of these words under the majority of cases (eg catagory/type/classification uses of the word "extra" and "special"). I was under the impression these uses were only used as sufixes and not part of the name? dunno... I've only seen them used with the dash eg. -Extras -Specials. Then there's pural usage Vs singlar usage, eg Extra Vs Extras, but again not sure about the standards SG wants to use here (ie if at all, comparing to media centres/players, etc.).

I like the idea of user choice, or even having an option (tickbox) in the settings - which may be easier. Suggestions and ideas to try to improve SG making it more robust.
