### ISSUE TITLE
Backlog search is due in the past

### ISSUE THREAD

**Issue by ressu** [SickGear/SickGear#134]
Ok, this is a bug that I've mentioned on the IRC channel a few times, but never managed to file a bug for. I've neglected filing a bug in the past because I have no idea what information to provide, so bear with me.

The image below should illustrate the basic issue. The backlog search is due on 31.12.2014 and it's been 1.1.2015 for about 12 hours now.

![sickgear - branch master - manage searches](https://cloud.githubusercontent.com/assets/468618/5591948/7b44f442-91aa-11e4-8c61-5d023e986bbe.png)

The backlog will stay at that date for an indefinite time, even if I run backlog manually it hardly ever updates. Let me know what information is useful and I'll add it to the issue. My current logs don't appear to go back far enough to have any mention of backlog search, so I'm not including them here by default.

**Comment by adam111316** [comment]
Hmm need to look into this a bit more... Not sure if those messages are meant to represent the 'last backlog search' or the 'next scheduled backlog search'....

**Comment by ressu** [comment]
At least in the past (with SR) it represented the next occurrence. Whenever backlog is properly run, that date is listed to be in the future.
