### ISSUE TITLE
Cannot connect after latest update

### ISSUE THREAD

**Issue by pjoksanen** [SickGear/SickGear#1340]
#### Branch version commit: 7ca7225a236961697e0d880dd973148202f26f73

Expectation | Result
------------ | -------------
To be able to connect | ERR_CONNECTION_FAILED

**Steps to reproduce:**
*1)* Update to 7ca7225a236961697e0d880dd973148202f26f73
*2)* Try to connect http://sickgear.ip:8081
...

Running Sickgear on Ubuntu 20.04 (on Proxmox 6.3-4 Linux container). It has been running fire for a long time, but today I got notice at 7.01 EET that Sickgear has been updated to 7ca7225a236961697e0d880dd973148202f26f73 and after that I am unable to connect. Also tried to reinstall, but with the same result. 

Prowl from SickGear on 10.3.2021, 7.01:

SickGear updated: SickGear updated to commit#: 7ca7225a236961697e0d880dd973148202f26f73

**Comment by JackDandy** [comment]
Hello,

You did not provide logs, perhaps you have none?
If you have no logs, start SG as a test from console to see what happens at startup.

**Comment by pjoksanen** [comment]
Logs directory is empty.

pete@ct-sickgear:/opt/sickgear$ python3 ./sickgear.py 
Starting up SickGear from /opt/sickgear/config.ini
--------

pete@ct-sickgear:/opt/sickgear$ sudo systemctl start sickgear
pete@ct-sickgear:/opt/sickgear$ sudo systemctl status sickgear.service 
● sickgear.service - SickGear Service
     Loaded: loaded (/etc/systemd/system/sickgear.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-03-10 12:22:25 EET; 13s ago
   Main PID: 1113 (python3)
      Tasks: 1 (limit: 4915)
     Memory: 55.9M
     CGroup: /system.slice/sickgear.service
             └─1113 /usr/bin/python3 /opt/sickgear/sickgear.py --systemd --datadir=/opt/sickgear

Mar 10 12:22:25 ct-sickgear systemd[1]: Started SickGear Service.
pete@ct-sickgear:/opt/sickgear$ ls Logs/
pete@ct-sickgear:/opt/sickgear$ 
pete@ct-sickgear:/opt/sickgear$ python3 -V
Python 3.8.5
pete@ct-sickgear:/opt/sickgear$ uname -a
Linux ct-sickgear 5.4.101-1-pve #1 SMP PVE 5.4.101-1 (Fri, 26 Feb 2021 13:13:09 +0100) x86_64 x86_64 x86_64 GNU/Linux
pete@ct-sickgear:/opt/sickgear$ host ct-sickgear
ct-sickgear.home.lan has address 192.168.10.15
pete@ct-sickgear:/opt/sickgear$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
pete@ct-sickgear:/opt/sickgear$ 

And still http://ct-sickgear.home.lan:8081 gives me ERR_CONNECTION_REFUSED

**Comment by JackDandy** [comment]
When i say run from console, i mean totally back to the basics....

`/usr/bin/python3 /opt/sickgear/sickgear.py --datadir=/opt/sickgear`

**Comment by pjoksanen** [comment]
This site can’t be reached

192.168.10.15 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by JackDandy** [comment]
Okay, can you try rebooting the machine, and do the same test again.

**Comment by JackDandy** [comment]
Do you have Flaresolver running?

**Comment by pjoksanen** [comment]
pete@ct-sickgear:/opt/sickgear$ sudo reboot
pete@ct-sickgear:/opt/sickgear$ Connection to ct-sickgear closed by remote host.
Connection to ct-sickgear closed.
┌──(pete📛wks-lt-x201)-[/etc]
└─$ ssh ct-sickgear
ssh: connect to host ct-sickgear port 22: Connection refused
┌──(pete📛wks-lt-x201)-[/etc]
└─$ ssh ct-sickgear
pete@ct-sickgear's password: 
Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.4.101-1-pve x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Wed Mar 10 13:10:58 2021 from 192.168.10.191
pete@ct-sickgear:~$ sudo systemctl stop sickgear.service 
[sudo] password for pete: 
pete@ct-sickgear:~$ /usr/bin/python3 /opt/sickgear/sickgear.py --datadir=/opt/sickgear
Starting up SickGear from /opt/sickgear/config.ini

**Comment by JackDandy** [comment]
Okay, can you come to IRC.

**Comment by pjoksanen** [comment]
I have to leave very soon, so no time to be in IRC

**Comment by pjoksanen** [comment]
pete@ct-sickgear:~$ /usr/bin/python3 /opt/sickgear/sickgear.py --datadir=/opt/sickgear
Starting up SickGear from /opt/sickgear/config.ini
MAIN :: Failed 3 times, skipping provider for 0:14:59, last failure at 2021-03-10 13:32:50 with fail type: connection
13:32:57 INFO TORNADO :: Starting SickGear on http://0.0.0.0:8081/
13:32:58 INFO MAIN :: Database schema is up-to-date, no upgrade required
13:32:58 INFO MAIN :: Checking database structure...
13:32:58 INFO MAIN :: Checking database structure...
13:32:58 INFO MAIN :: No orphan episodes, check passed
13:32:58 INFO MAIN :: No UNAIRED episodes, check passed
13:32:58 INFO MAIN :: Loading initial show list
13:32:58 INFO MAIN :: Loaded.. TheTVDB,  328724,  Young Sheldon
13:32:58 INFO MAIN :: Loaded.. TheTVDB,  364093,  Star Trek: Picard
13:32:58 INFO MAIN :: Loaded.. TheTVDB,  373355,  Richard Hammond's BIG
13:32:58 INFO MAIN :: Loaded.. TheTVDB,  78804,   Doctor Who (2005)
....
....
...
13:32:58 INFO MAIN :: Loaded.. TheTVDB,  368166,  Resident Alien
13:32:58 INFO LOAD-MAPPINGS :: Start loading TV info mappings...
13:32:58 INFO LOAD-MAPPINGS :: TV info mappings loaded
13:33:05 INFO FETCH-XEMDATA :: Fetching show ids with xem scene mappings for origin TheTVDB
13:33:05 INFO FETCH-XEMDATA :: Finished fetching show ids with 1130 xem scene mappings for origin TheTVDB
13:37:59 INFO RECENT-SEARCH :: No unaired episodes marked wanted
13:38:06 INFO RECENT-SEARCH :: Updating provider caches with recent upload data
13:38:07 INFO RECENT-SEARCH :: [Zooqle] :: No cache items in response from https://zooqle.com/search?q=* category:TV %2Blang%3Aen&s=dt&v=t&sd=d
13:38:08 INFO RECENT-SEARCH :: [LimeTorrents] :: 40 cache items in response from https://www.limetorrents.cc/browse-torrents/TV-shows/
13:38:08 INFO RECENT-SEARCH :: [Nyaa] :: 75 cache items in response from https://www.nyaa.si/?f=0&c=1_0&q=
13:38:08 INFO RECENT-SEARCH :: [EZTV] :: 20 cache items in response from https://eztv.ag/page_0
13:38:11 INFO RECENT-SEARCH :: [TorLock] :: 100 cache items in response from https://torlock.unblocked.bet/television/1/added/desc.html
13:38:12 INFO RECENT-SEARCH :: [Skytorrents] :: 2 cache items in response from https://skytorrents.to/?search=x264&sort=created&page=1
13:38:12 INFO RECENT-SEARCH :: [EZTV] :: 50 cache items in response from https://eztv.ag/page_1
13:38:17 INFO RECENT-SEARCH :: [MagnetDL] :: 80 cache items in response from http://www.magnetdl.com/download/tv/, http://www.magnetdl.com/download/tv/2
13:38:17 INFO RECENT-SEARCH :: [Skytorrents] :: No cache items in response from https://skytorrents.to/?search=x265&sort=created&page=1
13:38:17 INFO RECENT-SEARCH :: [TokyoToshokan] :: 150 cache items in response from https://tokyotosho.info/rss.php?filter=1
13:38:28 INFO RECENT-SEARCH :: [Snowfl] :: 64 cache items in response from https://snowfl.com/qpsCheFVBciUmyQyTKProCrFQXgBpIvGzsS/Q/en9G9oEh/0/DATE/24/0?_=16153762956401231




And now the GUI answers.

**Comment by JackDandy** [comment]
So basically,the statup process was taking a time due to a failure to connect to a provider, those connections are attempted before starting the webserver, therefore, in the time period, you get a cannot connect. On the history page you can reach connection failures.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
