### ISSUE TITLE
Documentation Clarification, Migrate SickGear to new machine

### ISSUE THREAD

**Issue by skepticalwaves** [SickGear/SickGear#1342]
#### Branch: The name of the branch (e.g. master or develop)
NA

#### Branch version commit hash: (See the About page)
NA

I would just like to clarify the migration instructions linked here:
https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B0%5D-Migrate

Which does not explicitly note migrating SickGear itself.

Which steps (copying database and config vs just importing existing directory) is recommended for SickGear->SickGear migration?

Thanks!

**Comment by JackDandy** [comment]
Copying existing data files is recommended because they do not need to be recreated.

**Comment by JackDandy** [comment]
Copying existing SickGear database and config files is recommended because they do not need to be recreated. 

The wiki guide title reads, "Migrate from Sick Beard", and is nothing about migrating SickGear to another place, which is why the case you raised is not included there.
