### ISSUE TITLE
Automatic Boot Installation for python and pyenv via installation guides do NOT work for ubuntu

### ISSUE THREAD

**Issue by usafltg** [SickGear/SickGear#1344]
#### Branch version: Latest at time of writing

Expectation | Result
------------ | -------------
service started or blank return | "Failed to start SickGear.service: Unit SickGear.service not found."

**Steps to reproduce:**
*1)* Follow the installation Guides for: https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B3%5D-Ubuntu
*2)* Try Steps 1 and / or Steps (Install Manually or Install with pyenv)
*3)* Follow all steps in guide until you get to "If you want SickGear to start at boot"
*4)* Follow the rest of the steps for either of these
*5)* when attempting to start the service results are the same - "Failed to start SickGear.service: Unit SickGear.service not found."
...

Additional notes:

It doesn't matter which of these directions you take, both result in an identical error. It's as if creating the service was missed somewhere... or the guide is incorrect.

**Comment by JackDandy** [comment]
Thanks for the heads up.

Unless you are doing something wrong, then I guess things have changed since those were written, we are not Ubuntu, so unless you or someone can assist on what to change, then the docs will remain as is.

This is not really an issue with he software, more just systems set up so i will close this issue for now, and hope someone can help with the wiki doc.

**Comment by usafltg** [comment]
No problem - I would maybe suggest putting a comment on the page that the sickgear.service is missing for now, and to get around the issue, regardless of starting via python3 or pyenv, to make a “crontab -e” entry. Though it’s not as clean, adding a line like ***@***.*** python3 /<directory of sickgear startup script> /sickgear.py

Though crontab is not as clean… it’s a workaround to get it auto booting at start. 

Chris

On May 14, 2021, at 18:00, JackDandy ***@***.***> wrote:

﻿
Thanks for the heads up.

Unless you are doing something wrong, then I guess things have changed since those were written, we are not Ubuntu, so unless you or someone can assist on what to change, then the docs will remain as is.

This is not really an issue with he software, more just systems set up so i will close this issue for now, and hope someone can help with the wiki doc.

**Comment by JackDandy** [comment]
Actually, I would rather know ...

* What build of Ubuntu and architecture you failed to auto run on?
* Did you check that your system created the service file, and does its content fit your environment?
* Are you using py2 or 3?
* Have you checked your system is correctly set up to run the correct pyenv?
* Have you checked and made any changes for py3 in init.ubuntu if that is what you are using
* What did the `update-rc.d` report when run 

there are way too many unanswered questions here stemming from the reported error `Unit SickGear.service not found`, that i cannot take it as valid that the already verified method simply no longer works as you are suggest.

**Comment by usafltg** [comment]
I ran the latest clean Ubuntu setup, from scratch. I tried both Ubuntu Server and Ubuntu Desktop 21.04. I followed the instructions to the letter step by step. Python 3 is installed per the instructions and pyenv (whatever version is listed in the instructions) is also installed. I originally wanted an Ubuntu Server without the GUI but thought well maybe there’s something in the desktop version that’s missing. Didn’t matter. Same result.

The instructions also both specify using “user1” as part of the environment variables, but I assumed they meant to plug-in a local account as there are no instructions indicating to create a separate user called “user1”. 

You can start both of them manually since what you’re really doing is using python to start the script that’s included, but the instructions that follow regarding setting them up to boot on start do not work. I’ve built them from scratch 3 times on a brand new Hyper-V VM instance, and they result in the same issue. 

As far as the “service” file goes. It’s looking for a service file called “sickgear.service” which wouldn’t be something created as part of a fresh O/S install. I would expect that to be created somewhere as part of the instructions. The instructions simply have you grab the sickgear version via a Git request and clone the repository. Then you setup a .conf file, and some environment variables in /opt/sickgear and /etc/init. But there’s never any instructions to copy or create a “sickgear.service” file.

Chris

On May 15, 2021, at 11:05, JackDandy ***@***.***> wrote:

﻿
Actually, I would rather know ...

What build of Ubuntu and architecture you failed to auto run on?
Did you check that your system created the service file, and does its content fit your environment?
Are you using py2 or 3?
Have you checked your system is correctly set up to run the correct pyenv?
Have you checked and made any changes for py3 in init.ubuntu if that is what you are using
What did the update-rc.d report when run
there are way too many unanswered questions here stemming from the reported error Unit SickGear.service not found, that i cannot take it as valid that the already verified method simply no longer works as you are suggest.

**Comment by JackDandy** [comment]
> But there’s never any instructions to copy or create a “sickgear.service” file.

Really?

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
