### ISSUE TITLE
Feature Request: Search anime indexers with standard episode format

### ISSUE THREAD

**Issue by malton33** [SickGear/SickGear#1345]
Hello,

Recently I've been trying to add an Anime series that uses standard (season x episode) format.
Searching with it set to standard yields no results as it doesn't search Nyaa.si.
Searching with it set to anime also yields no results because it is searching for absolute number while all the releases use the standard format.
Could there be a way to override this to either search all indexers when set to standard, or search by standard format when set to anime?

Thanks in advance.

**Comment by JackDandy** [comment]
> an Anime series that uses standard (season x episode) format

which ?

**Comment by JackDandy** [comment]
> an Anime series that uses standard (season x episode) format

1) which series ? 
2) which provider ?

**Comment by malton33** [comment]
> > an Anime series that uses standard (season x episode) format
> 
> 1. which series ?
> 2. which provider ?

my hero academia on nyaa.si, searching my hero academia 93 gets different results than S05E05 or S5 - 05

**Comment by JackDandy** [comment]
Hi,

I added the show, enabled nyaa, first search failed due to me not setting show as type anime, I edited show, set as anime, performed a manual search by setting item s5x5 as wanted, SG found ep 93 720p by Puya and so performs as expected, am I missing something?
