### ISSUE TITLE
Wrong timestamps in CHANGES.md

### ISSUE THREAD

**Issue by flederohr** [SickGear/SickGear#1346]
#### Branch version commit hash: e7480e589b2e5bfad1990bdf1b8caec3d1a4c7fe

Expectation | Result
------------ | -------------
0.23.17 (2021-04-12 12:40:00 UTC) | 0.23.17 (2020-04-12 12:40:00 UTC)

Since version 0.23.17 all version timestamps in the [changelog](https://github.com/SickGear/SickGear/blob/master/CHANGES.md) are predated by one year, the current changes should have the year 2021

**Comment by JackDandy** [comment]
Thanks, it will be fixed in next release.
