### ISSUE TITLE
Synology DSM 7 has broken SickGear's access to Download Station

### ISSUE THREAD

**Issue by imavroukakis** [SickGear/SickGear#1347]
#### Branch version commit hash: e33494547c547c4841135418f2dfcb44437b92fc

Expectation | Result
------------ | -------------
Synology DSM 7 download station works with SickGear| It doesn't :)

**Steps to reproduce:**
*1)* Upgrade to DSM 7, now that it has been released to the public
*2)* Attempt to download eps from a sweet sweet show
*3)* sickgear fails because Synology is evil and changed their API.

With debug logging turned on that is all I get
<pre>
2021-07-04 17:17:47 HOME^WEB_0 :: DownloadStation replied with: The requested method does not exist
</pre>

**Comment by JackDandy** [comment]
Yeah, need access to a machine, until that can happen i will mark this up as enhancement.

**Comment by imavroukakis** [comment]
happy to help, what do you need?

**Comment by JackDandy** [comment]
Ah okay, can you come to IRC so that we can chat in real-time, irc.libera.chat channel #sickgear

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.24.9).
