### ISSUE TITLE
Do I miss the checkbox that a succesful downloaded episode get automatically deleted from the torrent client?

### ISSUE THREAD

**Issue by spiderbit** [SickGear/SickGear#1348]
I don't find the checkbox to delete the file from the torrent client after download, is that feature missing or do I just not find it?

**Comment by JackDandy** [comment]
This is a feature request, and will be marked as so.

Thanks

**Comment by spiderbit** [comment]
Why is it closed? I get the renaming, but why close?

**Comment by JackDandy** [comment]
> 
> 
> Why is it closed? I get the renaming, but why close?

see [here](https://github.com/SickGear/SickGear/issues/770)

**Comment by JackDandy** [comment]
@spiderbit which client ?
