### ISSUE TITLE
Error: Api key for SpeedApp is empty in Media Providers/Options

### ISSUE THREAD

**Issue by boredazfcuk** [SickGear/SickGear#1350]
Hi,

I think I've found a bug...

BRANCH: master @ py3.9.5 / COMMIT: 5a1a122 @ 0.24.12

Expectation | Result
------------ | -------------
I would not expect to see the empty API key error without enabling SpeedApp as a media provider | Even with SpeedApp not enabled, the error is logged.

**Steps to reproduce:**
*1)* Do not enable SpeedApp
*2)* Leave API key empty
...

```
2021-07-26 22:47:41 CONFIGPROVIDERS^WEB_0 :: Api key for SpeedApp is empty in Media Providers/Options
2021-07-26 22:46:45 CONFIGPROVIDERS^WEB_2 :: Api key for SpeedApp is empty in Media Providers/Options
2021-07-25 22:55:26 CONFIGPROVIDERS^WEB_2 :: Api key for SpeedApp is empty in Media Providers/Options
```

Presumably this is a newly added Media Provider and the logic for detecting an API key is running even when provider is not enabled.

Thanks,

Bored.

**Comment by JackDandy** [comment]
k, thanks for the report. will be fixed on next release.

**Comment by JackDandy** [comment]
fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.24.13)

**Comment by boredazfcuk** [comment]
Thanks. I've just upgraded and the error no longer appears.
