### ISSUE TITLE
If show's "Location for files" is not writable by SickGear, episodes will be simply deleted during post-processing

### ISSUE THREAD

**Issue by cheezecat** [SickGear/SickGear#1351]
Branch: master
Branch version commit hash: 0fdde84

Expectation: If an episode can't be moved to the target folder it should not be deleted.

**Steps to reproduce:**
*1)* Change permissions on a show's Location for Files folder to not be writable by SickGear
*2)* Add episode for show to Completed TV Downloads folder
*3)* Wait for post-processing to kck in, note that warning about not being able to move file appears in Log, note that file is gone from Completed TV Downloads
...

`2021-08-01 11:18:39 POSTPROCESSER :: Unable to move file  /home/user/Desktop/data/Shows/_qtorrentdownloads/MyShow.S01E05.mkv to /home/user/Desktop/MyShow/MyShow.S01E05.mkv [Errno 2] No such file or directory: "/home/user/Desktop/MyShow/MyShow.S01E05.mkv"`

**Comment by cheezecat** [comment]
@JackDandy I can't tell; was this rejected?  If so, is there more info I could provide?  (If rejected because you don't care, would you accept a pull?)

**Comment by JackDandy** [comment]
@cheezecat this is labelled "investigating", but low priority. But yes, a pull request is perfectly acceptable, thanks.

**Comment by JackDandy** [comment]
@cheezecat okay, its been a couple of days and nothing from you, i do have an idea on this, so can you to come to IRC so a test can be arranged.

**Comment by cheezecat** [comment]
Whoops, yeah, I didn't plan to make a pull until I accidentally got myself back in the bad state.  I'll try to figure out the IRC business...

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.24.15)

Thanks for your report.
