### ISSUE TITLE
Synology DSM 7 finds all versions of Sickgear Files Invalid File Format

### ISSUE THREAD

**Issue by Beetrstand** [SickGear/SickGear#1353]
#### Branch version commit hash: 0.24.15

Expectation | Result
------------ | -------------
Following the install guide I have tried manually installing and installing from the Synology store. One error on the install guide for Synology DSM 7 is that there is no way to chand the Trust Level to any publisher. | Every time I attempt an install I get Invalid file format. 

**Steps to reproduce:**
*1)* Synology 1821+ with DSM 7 
*2)* Install via Synology apps
*3)* Install manually from GitHub
...

Additional notes:

Synology 1821+ w/ DSM 7.0-41890

**Comment by JackDandy** [comment]
@imavroukakis Can you help with this, of course the issue you found 4 weeks ago was fixed, so I wonder how did you get SG installed so that i could connect and fix it on your server, but this issue is reporting install failure, can you help? 

I am going to close this issue for now, replies can continue below, but there is a chance that there may not be a quick reply, perhaps @Beetrstand you can come up with a solution.

**Comment by Beetrstand** [comment]
@JackDandy Be happy to help anyway I can. Just wanted to reach out to find out how others perhaps got it installed. Having the same issue with SABNZBD but they are still working on a new version.

**Comment by JackDandy** [comment]
@Beetrstand can you come to IRC and I will send you a PM when I have a package ready for you to test.

**Comment by imavroukakis** [comment]
Hey folks! I am running SG in a Docker container, so I am not running into permission issues such as the one you described.

**Comment by JackDandy** [comment]
Thanks anyway @imavroukakis.  In this case, for @Beetrstand and everyone else, I have a Syno package ready for testing :)

**Comment by Beetrstand** [comment]
Thanks will check in later today when I am back home with you or just send
me the link to it and will try a manual install.

**Comment by JackDandy** [comment]
@Beetrstand later today is fine, see you as arranged.

**Comment by JackDandy** [comment]
@Beetrstand can you let me know when UTC you are available, thanks

**Comment by JackDandy** [comment]
hi, where are you?
