### ISSUE TITLE
How to pick anidb has the tv info source?

### ISSUE THREAD

**Issue by mloureiro** [SickGear/SickGear#1354]
**Branch: `master`**
**Branch version commit hash:** 🤷‍♂️ (couldn't find the about page)
**Version:** `0.24.15`

Hi

I'm trying to use the AniDB as a source for my animes.
Already setup the log in credentials for the AniDB in the `/config/anime/`, but when I go to `/add-shows/import` it shows the unmatched series, and on the tv show info source dropdown only TheTVTB is there.

This is probably a basic question, but I've been diving around the wiki without finding the solution.

Thanks for the help

Expectation | Result
------------ | -------------
AniDB would be an option in the tv info source | it isn't

**Steps to reproduce:**
1. go to `/config/anime/` and setup AniDB credentials
2. then go to `/add-shows/import` and import a directory that as animes
3. on the "TV info source" dropdown for each show, only TheTVDB is available

**Comment by JackDandy** [comment]
Hi,

AniDb isn't used as a TVinfo source. 

It is used when adding/editing a show, to populate the groups list and is also used to present menu Shows/Anime Cards.
