### ISSUE TITLE
sg.history.clear API command is not clearing the API history

### ISSUE THREAD

**Issue by brandan-schmitz** [SickGear/SickGear#1357]
#### Branch version commit hash: `f9c5778f9aa31f8f0e2cdcb462048cd8609c0f42`

Expectation | Result
------------ | -------------
Sending a request to `/api/<api-key>/?cmd=sg.history.clear` should clear the history for both the UI and API allowing you to call `/api/<api-key>/?cmd=sg.history` right after calling the clear API command and receive a blank list similar to what it would be as if you never added anything to begin with. See the return type below for what would be expected for the history directly after calling the clear command. | The history in the UI is cleared but the history in the API is not cleared and returns the same thing as it did before.

Expected return data for a query to the history command directly after calling the clear command:
```json
{
  "data": [],
  "message": "",
  "result": "success"
}
```

**Steps to reproduce:**
**1)** Add a show to SickGear and wait for it to start snatching/downloading episodes.
**2)** Send a GET request to the `/api/<api-key>/?cmd=sg.history` endpoint to see what the history is prior to clearing it.
**3)** Send a GET request to the `/api/<api-key>/?cmd=sg.history.clear` endpoint to clear the history.
**4)** Send another GET request to the `/api/<api-key>/?cmd=sg.history` endpoint to see the history now, note that it has not been cleared and is the same as before.
**5)** Load the history in the UI, notice that it is empty as one would expect after clearing the history.

There are no logs produced for this, neither in the log or in the error log even with the log level set to debug.

SickGear is installed on a Ubuntu 20.04 LTS server and I just updated SickGear to the 0.25.0 release today and the issue is still present. I installed it using the manual method as outlined in the Wiki.

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.25.1)

Thanks.
