### ISSUE TITLE
Cannot install via snap on Raspbian 9

### ISSUE THREAD

**Issue by 0x646e78** [SickGear/SickGear#1358]
#### Branch version commit hash: (See the About page)

Looking at my Raspbian version this is probably a case of installing a newer OS image and trying form there, but thought I'd raise it. 

This host had been running smoothly for a couple years but recently sickgear has consistently frozen with a high cpu load so thought I'd try the snap route before a full rebuild. Previously installed using the git + systemd route.

Will probably upgrade to pi4 instead of pi2 also if I need to rebuild the host.

Expectation | Result
------------ | -------------
Installation via snap | Failure to install

**Steps to reproduce:**
*1)* Successfully install snap via apt
*2)* sudo snap install sickgear

Error message:

```
$ sudo snap install sickgear
error: cannot perform the following tasks:
- Mount snap "sickgear" (1126) (cannot find required base "core18")
```

```
$ cat /sys/firmware/devicetree/base/model
Raspberry Pi 2 Model B Rev 1.1

$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

$ cat /etc/debian_version
9.13

$ uname -a
Linux bmo 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

```

**Comment by JackDandy** [comment]
The only thing i can think of is that the OS is too new. But i do not know for sure. Sorry.

**Comment by 0x646e78** [comment]
Hi @JackDandy yeah I think I will try a rebuild on a current OS on a Pi4. been meaning to rebuild anyhow.

When you say try a new db, is that a usual performance improver? I'd do a clean install, copy the config in and then populate the shows?

Thanks

**Comment by JackDandy** [comment]
> I'd do a clean install, copy the config in and then populate the shows?

Exactly, you would use the "Import" function from the menu, only last week someone regained original perf from that. And to actually observe the gain, I would do this on the existing Pi2 **not** the Pi4.

**Comment by JackDandy** [comment]
> I'd do a clean install, copy the config in and then populate the shows?

@0x646e78 Exactly, you would use the "Import" function from the menu, only last week someone regained original perf from that. And to actually observe the gain, I would do this on the existing Pi2 **not** the Pi4, otherwise you are comparing apples to oranges and that will be a invalid test.

**Comment by JackDandy** [comment]
> I'd do a clean install, copy the config in and then populate the shows?

@0x646e78 Exactly, you would use the "Import" function from the menu, only last week someone regained original perf from that. And to actually observe the gain, I would do this on the existing Pi2 **not** the Pi4, otherwise you compare apples to oranges which would be an invalid test.
