### ISSUE TITLE
History API not showing snatched item when it is marked as a proper

### ISSUE THREAD

**Issue by brandan-schmitz** [SickGear/SickGear#1359]
**Branch:** `master`
**Branch version commit hash:** `4af00e586a4b34da3c3935877d094271d3b7f74f`

Expectation | Result
------------ | -------------
Any episode that is snatched should show up in the history in the API. | If an episode is shown in the UI with a status of `Snatched (Proper)` it will not appear in the results obtained from `/api/<api_key>/?cmd=sg.history` however it does appear in the UI history. See the screenshots below.

They appear in the UI:
![image](https://user-images.githubusercontent.com/6267549/134051706-1262124b-7664-4b83-8d6a-c94fe4323116.png)

They do not show up in the API results:
![image](https://user-images.githubusercontent.com/6267549/134052347-4405e29c-6dbe-4e4f-87fc-d2ddd6799df7.png)

**Steps to reproduce:**
**1)** Locate a show to download, I used Tacoma FD.
**2)** Let SickGear locate episodes.
**3)** Check the history in UI and API to see the differences.

**Log output:**
https://gist.github.com/brandan-schmitz/98d1ad429b172efe2ea2fb5172f9ad63

**Additional notes:**
Previous backlog searches have found all the episodes plus these. For demonstration purposes I used the UI to set the status of the two episodes that were marked as propers back to wanted to trigger a backlog search for season 1 of Tacoma FD. Those were episodes 1 and 3 of season 1. They were sourced from EZTV as Rarbg is not responding because of a high number of API hits from me testing different things.

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.25.2)

Thanks.

**Comment by brandan-schmitz** [comment]
I am noticing that there is still an issue with this. If you add the filter `type=snatched` to the `/api/{api_key}/?cmd=sg.history` command then it still does not list those episodes in the history.

**Comment by JackDandy** [comment]
okay, for the best of planning...

could you collect a set of issues and list them here so that we can handle them all at once instead of releasing a hotfix only to find another issue exists.

and thanks again for your feedback.

**Comment by brandan-schmitz** [comment]
I have spent a while and gone through the various endpoints that I am using and might use and do not see any other issues aside from this.

I do have one other question or request if it is possible that is related to the history API:
Does SickGear determine if an specific episode that is being downloaded is a combined file where two or more episodes are in one? If so, is there a way to have the history item reflect that for the snatched or downloaded items? Perhaps a boolean field in the return data type that specified it is a combined episode and another field or array of numbers that specifies which episodes are combined? I am not sure if that would also work when searching season packs or not or how exactly you are parsing data out.

**Comment by brandan-schmitz** [comment]
I take that back, I am noticing and issue in the logs with some magnet/torrent files. It seems that when trying to load a magnet URL in some cases it is appending an extra `magnet:` to the front of the string:

```
2021-09-20 22:24:57 WARNING  SG.HELPER :: Exception caught while loading URL magnet:magnet:?xt=urn:btih:6a5c17118b68c64322de16ebd5775ea559e71fb9&dn=Brooklyn.Nine-Nine.S02.1080p.AMZN.WEBRip.DDP5.1.x264-TrollHD%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2810&tr=udp%3A%2F%2F9.rarbg.to%3A2810?xt=urn:btih:6a5c17118b68c64322de16ebd5775ea559e71fb9&dn=Brooklyn.Nine-Nine.S02.1080p.AMZN.WEBRip.DDP5.1.x264-TrollHD%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2810&tr=udp%3A%2F%2F9.rarbg.to%3A2810
 1) Detail... No connection adapters were found for 'magnet:magnet:?xt=urn:btih:6a5c17118b68c64322de16ebd5775ea559e71fb9&dn=Brooklyn.Nine-Nine.S02.1080p.AMZN.WEBRip.DDP5.1.x264-TrollHD%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2810&tr=udp%3A%2F%2F9.rarbg.to%3A2810?xt=urn:btih:6a5c17118b68c64322de16ebd5775ea559e71fb9&dn=Brooklyn.Nine-Nine.S02.1080p.AMZN.WEBRip.DDP5.1.x264-TrollHD%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2810&tr=udp%3A%2F%2F9.rarbg.to%3A2810'
 2) Traceback (most recent call last):
 3)   File "/opt/sickgear/lib/sg_helpers.py", line 897, in get_url
 4)     response = method(url, timeout=timeout, **kwargs)
 5)   File "/opt/sickgear/lib/requests/sessions.py", line 555, in get
 6)     return self.request('GET', url, **kwargs)
 7)   File "/opt/sickgear/lib/cfscrape/__init__.py", line 50, in request
 8)     resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
 9)   File "/opt/sickgear/lib/requests/sessions.py", line 542, in request
10)     resp = self.send(prep, **send_kwargs)
11)   File "/opt/sickgear/lib/requests/sessions.py", line 649, in send
12)     adapter = self.get_adapter(url=request.url)
13)   File "/opt/sickgear/lib/requests/sessions.py", line 742, in get_adapter
14)     raise InvalidSchema("No connection adapters were found for {!r}".format(url))
15) requests.exceptions.InvalidSchema: No connection adapters were found for 'magnet:magnet:?xt=urn:btih:6a5c17118b68c64322de16ebd5775ea559e71fb9&dn=Brooklyn.Nine-Nine.S02.1080p.AMZN.WEBRip.DDP5.1.x264-TrollHD%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2810&tr=udp%3A%2F%2F9.rarbg.to%3A2810?xt=urn:btih:6a5c17118b68c64322de16ebd5775ea559e71fb9&dn=Brooklyn.Nine-Nine.S02.1080p.AMZN.WEBRip.DDP5.1.x264-TrollHD%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2810&tr=udp%3A%2F%2F9.rarbg.to%3A2810'
```

The actual contents of the magnet file that was saved to disk for this episode is this:
```
magnet:?xt=urn:btih:6a5c17118b68c64322de16ebd5775ea559e71fb9&dn=Brooklyn.Nine-Nine.S02.1080p.AMZN.WEBRip.DDP5.1.x264-TrollHD%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2960&tr=udp%3A%2F%2F9.rarbg.to%3A2960```

**Comment by JackDandy** [comment]
> appending an extra magnet: to the front of the string

I cannot reproduce this, so I am missing something that is triggering this for you.

**Comment by brandan-schmitz** [comment]
I am not actually sure what is causing that issue precisely. I have my settings set to download season packs, with fallback to episode mode enabled. I have Rarbg and EZTV enabled as media providers. I am encountering the issue with the show `Brooklyn Nine-Nine` for s02e23 and s03e18. All other episodes have been downloaded, however the two aforementioned episodes are still showing as wanted.

If I trigger a manual search, or by forcing the backlog to run it displays the error in the log and nothing is found for the episodes. The full log output given when I triggered a manual search for s02e23 is here: https://gist.github.com/brandan-schmitz/6ab1ea1d626a6f1c15abd67034524ac1

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.25.3)

Thanks.
