### ISSUE TITLE
SG Media Process errors

### ISSUE THREAD

**Issue by ghost** [SickGear/SickGear#1360]
BRANCH: master @ py2.7.16 / COMMIT: d12943b @ 0.25.3

Expectation | Result
------------ | -------------
OS Updated, SG now errors >> | then, your result paragraph(s) text here.

**Steps to reproduce:**
*1)* Proccess Media Manually
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags
` POSTPROCESSER :: Exception generated in thread POSTPROCESSER: 'NoneType' object has no attribute 'strftime'
POSTPROCESSER :: 'Traceback (most recent call last):\n  File "/opt/SickGear/app/sickbeard/scheduler.py", line 127, in run\n    self.action.run()\n  File "/opt/SickGear/app/sickbeard/auto_post_processer.py", line 39, in run\n    self._main()\n  File "/opt/SickGear/app/sickbeard/auto_post_processer.py", line 55, in _main\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, is_basedir=True)\n  File "/opt/SickGear/app/sickbeard/processTV.py", line 1208, in processDir\n    pp_type, cleanup, show_obj)\n  File "/opt/SickGear/app/sickbeard/processTV.py", line 434, in process_dir\n    force, force_replace, use_trash=cleanup, show_obj=show_obj)\n  File "/opt/SickGear/app/sickbeard/processTV.py", line 1069, in _process_media\n    file_success = processor.process()\n  File "/opt/SickGear/app/sickbeard/postProcessor.py", line 1230, in process\n    cur_ep_obj.airdate_modify_stamp()\n  File "/opt/SickGear/app/sickbeard/tv.py", line 5204, in airdate_modify_stamp\n    aired_dt.strftime(\'%b %d,%Y (%H:%M)\')), loglevel)\nAttributeError: \'NoneType\' object has no attribute \'strftime\'\n'
BACKLOG-1:368166 :: [Rarbg] :: No usable API token returned from: https://torrentapi.org/pubapi_v2.php?app_id=SickGear&get_token=get_token`

Additional notes:
Python version: | 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
DietPi v7.6.2 + RPi 4 Model B (aarch64)

[sg-fail.txt](https://github.com/SickGear/SickGear/files/7224294/sg-fail.txt)

**Comment by JackDandy** [comment]
Github has marked this account as a ghost account, therefore, issue marked invalid and closed.

That said, there will be an attempt to look at the reported issue given the logs supplied.

Thanks.

**Comment by JackDandy** [comment]
For now, disable, "Change file date", under Options/Media Process/file handling.

The error has no effect on the actual processing. However, this finding is fixed for the next release.

Thanks for your report.

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.25.4)

Thanks.
