### ISSUE TITLE
Failed to unpack JSON Data

### ISSUE THREAD

**Issue by Zaxxon709** [SickGear/SickGear#1371]
#### Branch version commit hash: (See the About page)

Version: | BRANCH: master @ py2.7.17 / COMMIT: snap @ 0.25.20This is BETA software
-- | --
Config file: | /var/snap/sickgear/common/data/config.ini
Database file: | /var/snap/sickgear/common/data/sickbeard.db
Cache dir: | /var/snap/sickgear/common/data/cache
Arguments: | ['--datadir=/var/snap/sickgear/common/data', '-d']
Web root: | /
Python version: | 2.7.17 (default, Feb 27 2021, 15:10:58) [GCC 7.5.0]

Expectation | Result
------------ | -------------
No errors

**Steps to reproduce:**
*1)* Start Sickgear
*2)* Wait and error will appear
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
```
I'm running Sickgear on a Raspberry pi. Recently the below error keeps appearing each day. Is this anything to be concerned about? Any idea how i can sort the error? Thank you

`2021-12-15 03:38:51 SHOWUPDATER :: Failed to unpack json data: /var/snap/sickgear/common/data/cache/alts/tmp/alt.rar with error: No JSON object could be decoded`
```

**Comment by JackDandy** [comment]
Hi, nothing to worry about.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
