### ISSUE TITLE
Missing network logos

### ISSUE THREAD

**Issue by Nummer11** [SickGear/SickGear#1372]
#### Branch version commit hash: COMMIT: 8af5199 @ 0.25.24

Expectation | Result
------------ | -------------
Missing network logos for at least Apple TV+, Amazon Prime Video and Disney+ | Add logo files to the network images folder

**Comment by JackDandy** [comment]
Doesn't
There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck. matter, the default text system works fine.
