### ISSUE TITLE
Startup loop help?

### ISSUE THREAD

**Issue by potestus** [SickGear/SickGear#1375]
#### Branch version commit hash: (See the About page)

Using qnap latest version
How can I get out of this loop where it keeps restarting and doing a forced update ? Is there a setting in the configuration for startup options?

Expectation | Result
------------ | -------------
Your expectation paragraph(s) text here. Before the bar >> | then, your result paragraph(s) text here.

**Steps to reproduce:**
*1)* Step to take
*2)* Step to take
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved
![Screenshot_20220116-000511_Chrome](https://user-images.githubusercontent.com/2980512/149642120-f50a254a-664b-431f-9201-25c94576981a.jpg)

**Comment by potestus** [comment]
![Screenshot_20220116-001614_Chrome](https://user-images.githubusercontent.com/2980512/149642254-3efe3b77-dc1e-41e6-8b03-a0c6a7b91554.jpg)

**Comment by JackDandy** [comment]
```
Is there a setting in the configuration for startup options
```

There is, in file config.ini set `update_packages_auto=0`

**Comment by potestus** [comment]
Thanks for that.. I upgraded my qnap from a very old slow one to a new quick one.. that's sorted it..
