### ISSUE TITLE
Archive setting

### ISSUE THREAD

**Issue by potestus** [SickGear/SickGear#1376]
#### Branch version commit hash: (See the About page)
Archived
this status can be preferred over Ignored/Skipped to mark an episode. It is used where an episode is known to have existed via a filesystem check during the daily update, and where the file is later deleted or archived offline. The post processing setting "Status of removed episodes" should be set to "Set Archived"
is plus one toward the individual episode count
is included in total episode count and progress bars

How is this set ? the option in the show screen doesn't work. Where is "Status of removed episodes"?

Expectation | Result
------------ | -------------
Your expectation paragraph(s) text here. Before the bar >> | then, your result paragraph(s) text here.

**Steps to reproduce:**
*1)* Step to take
*2)* Step to take
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
For statuses see [here](https://github.com/SickGear/SickGear/wiki/Status-Modes)

**Comment by JackDandy** [comment]
"How is this set ?"

you already posted the answer... `The post processing setting`

**Comment by potestus** [comment]
I realise that that's why I posted it. I can't get the Archived process to work. I was using sickchill before. I can't see where to set status of removed episode's..

**Comment by JackDandy** [comment]
so removed eps should auto change to archived if you have the setting set.

manually;
<a name="" id=""><img src="https://i.vgy.me/l671Tg.png"></a>
