### ISSUE TITLE
Video subfolders

### ISSUE THREAD

**Issue by pmanach1971** [SickGear/SickGear#1377]
#### Branch version commit hash: (See the About page)

Trying to create subfolders for video | PreExisting Folders under video cannot be seen and new subfolders cannot be created
------------ | -------------
Your expectation paragraph(s) text here. Before the bar >> | then, your result paragraph(s) text here.

**Steps to reproduce:**
1) Add show 
2) Select next after results are found
3) Try to add a new folder or an existing one by selecting /volume1/video
4) No possibility to expand anymore

Thus, the show can't be added.

**Comment by JackDandy** [comment]
Permissions.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
