### ISSUE TITLE
Cant see the root files in sickgear pull down

### ISSUE THREAD

**Issue by potestus** [SickGear/SickGear#1378]
#### Branch version commit hash: (See the About page)

BRANCH: master @ py3.10.0 / COMMIT: 50ce9df @ 0.25.25This is BETA softwareNo checks are run for outdated software, see "Software updates" in Config > General.
--
Config file: | /share/CACHEDEV1_DATA/.qpkg/OSickGear/config/config.ini
Database file: | /share/CACHEDEV1_DATA/.qpkg/OSickGear/config/sickbeard.db
Database backups: | /share/CACHEDEV1_DATA/.qpkg/OSickGear/config/backup
Cache dir: | /share/CACHEDEV1_DATA/.qpkg/OSickGear/config/cache
Arguments: | ['--daemon', '--nolaunch', '--datadir', '/share/CACHEDEV1_DATA/.qpkg/OSickGear/config', '--pidfile', '/var/run/OSickGear.pid']

Expectation | Result
------------ | -------------
Using the pull-down to pick a parent folder. I can't see the root of my qnap. The is a new on in v5.0.0. It worked OK on the old one.. sabbworks fine..

**Steps to 
![Screenshot_20220122-143114_Chrome](https://user-images.githubusercontent.com/2980512/150646831-aa674096-159d-42b9-b745-b6bde6762a24.jpg)
 
...
The share folder doesn't contain it either
![Screenshot_20220122-162103_Chrome](https://user-images.githubusercontent.com/2980512/150646898-3410be15-f66a-4897-b014-631a5ba82281.jpg)

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
Pleases fix your permissions. this is NOT an sg issue.

**Comment by potestus** [comment]
Give us a clue., as far as I can see all permissions sions are given?

**Comment by JackDandy** [comment]
`Give us a clue.,`

If we knew, then this would be included in install docs, we do not hold back info that would help. 

From time to time, perms are raised, like in the case here, we always ask for feedback so that we can update docs, clearly we have not been given any for your system type.

**Comment by JackDandy** [comment]
hi, did you solve it?
