### ISSUE TITLE
Alternative release names ?

### ISSUE THREAD

**Issue by potestus** [SickGear/SickGear#1379]
BRANCH: master @ py3.10.0 / COMMIT: 50ce9df @ 0.25.25

Expectation | Result
------------ | -------------
I can't get the alternate name to commit.  It just goes back to Zero.
How's it supposed to work?

**Steps to reproduce:**
*1)* Step to take
*2)* Step to take
...

![Screenshot_20220129-101501_Chrome](https://user-images.githubusercontent.com/2980512/151657813-996500c1-4697-46f2-aba6-7dfa9962c882.jpg)

**Comment by JackDandy** [comment]
did you check ... [FAQ-Alt-Names](https://github.com/SickGear/SickGear/wiki/FAQ-Alt-Names)

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by potestus** [comment]
OK.

**Comment by potestus** [comment]
Again this is working OK..  its just not clear from the interface which
options are chosen.

Terry
