### ISSUE TITLE
API downloads to SABnzbd always go to https for fetching

### ISSUE THREAD

**Issue by billruehl** [SickGear/SickGear#1380]
Currently there is a bug with SABnzbd where it cannot process https api calls.  Even though the api is listed as http://api.nzbplanet.net, the api calls to the sabnzbd show as coming back with https://  .  Is there a way to force the http:// for the api nzb fetches?

The version of SickGear I'm using for QNAP is as follows:

<html>
<body>

Version: | BRANCH: master @ py3.10.0 / COMMIT: 6c92c7c @ 0.25.26This is BETA softwareNo checks are run for outdated software, see "Software updates" in Config > General.

Python version: | 3.10.0 (default, Dec 10 2021, 08:29:27) [GCC 8.4.0]
Timezone version: | 2021e

</body>
</html>

**Comment by JackDandy** [comment]
Tell the SAB team, they will fix it quick enough.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by billruehl** [comment]
I guess the question is to why the api is pulling on https as opposed to http when that is what was put into the settings.  I agree that the issue is with the SAB guys, and I think they're aware of it.

**Comment by JackDandy** [comment]
The server can easily redirect `http` requests to `https`.

**Comment by billruehl** [comment]
The issue was 100% SABnzbd.  Wiping out the entire installation and going with a qpackage as opposed to sherpa install fixed everything.
