### ISSUE TITLE
how do I edit columns on the Show List screen?

### ISSUE THREAD

**Issue by OneCDOnly** [SickGear/SickGear#1381]
Hi guys, I'm fairly new to SickGear but have used a few SickBeard forks over the years. Most recently been a SickChill user, but I'm shopping for a new fork to use as my daily driver. 

I feel like I must be missing something quite simple here: how do I choose which columns are displayed on the Show List screen? E.g. I don't need `Network`, `Active`, `Quality`, so how do I hide them?

Apologies if there is a better place to ask this - I couldn't find it. 

Thank you.

**Comment by JackDandy** [comment]
Hi,  
  
SickGear is older than SickChill and does not contain features or issues that it created, such as hiding columns. 
  
SickGear vastly improves on SickBeards original features and new features developed.  
  
And with that, I **highly** recommend the well maintained install guides and wiki pages for a most optimal set up.  
  
Feel free to ask anything else below, even though it is closed that's no problem.

**Comment by OneCDOnly** [comment]
Thank you @JackDandy - no problem. 

Much appreciation for the work you guys do, SickGear looks like a very stable fork. 👍🏽

**Comment by JackDandy** [comment]
> SickGear looks like a very stable fork.

Yeah, we don't get many issues these days, and things are pretty stable at this point.
