### ISSUE TITLE
Support Python 3.10.3

### ISSUE THREAD

**Issue by PowerCoder** [SickGear/SickGear#1383]
BRANCH: master @ py3.10.3 / COMMIT: c7e1de3 @ 0.25.30

`Python 3.10.3 detected.`
`Sorry, SickGear requires a Python version 2. 7. 9 - 2. 7. 18, 3. 7. 1 - 3. 8. 12, 3. 9. 0 - 3. 9. 2, 3. 9. 4 - 3. 9. 10, 3. 10. 0 - 3. 10. 2`

My monthly maintenance/update cycle tripped over it. I altered the range in `sickgear.py` and it appears to work fine.

I get one error on starting which I can't raise as an issue since I'm technically running unsupported, but FYI:
`  File "/usr/lib/python3.10/json/encoder.py", line 179, in default`
`    raise TypeError(f'Object of type {o.__class__.__name__} '`
`TypeError: Object of type range is not JSON serializable`

I'll try to reset back to `master` next month. Or sooner if you let me know when the range change was merged.

Apologies if you consider this too trivial to report.

**Comment by JackDandy** [comment]
Will be in next hotfix.

There is not an actual issue here. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
