### ISSUE TITLE
Not fetching subtitles

### ISSUE THREAD

**Issue by Dohnerd** [SickGear/SickGear#1384]
After a reinstall i moved entire config folder over, everything is fine except subtitles, it dosnt fetch ANY subtitles, i get errors like this:

2022-03-30 18:31:21 ERROR    SUBLIMINAL :: Error consuming task ListTask(Episode, {Language(b'English')}, addic7ed, ServiceConfig(True, /share/CACHEDEV1_DATA/.qpkg/OSickGear/config/cache))
 1) Traceback (most recent call last):
 2)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/subliminal/api.py", line 60, in list_subtitles
 3)     result = consume_task(task, service_instances, os_auth=os_auth)
 4)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/subliminal/core.py", line 132, in consume_task
 5)     result = service.list(task.video, task.languages)
 6)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/subliminal/services/__init__.py", line 155, in list
 7)     return self.list_checked(video, languages)
 8)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/subliminal/services/addic7ed.py", line 64, in list_checked
 9)     return self.query(video.path or video.release, languages, get_keywords(video.guess), video.series, video.season, video.episode)
10)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/subliminal/services/addic7ed.py", line 71, in query
11)     series_id = self.get_series_id(series.lower())
12)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/subliminal/cache.py", line 127, in cached
13)     result = function(*args)
14)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/subliminal/services/addic7ed.py", line 61, in get_series_id
15)     return self.cached_value(self.get_series_id, args=(name,))
16)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/subliminal/services/__init__.py", line 103, in cached_value
17)     return self.config.cache.cached_value(self.__class__.__name__, func, args)
18)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/subliminal/cache.py", line 98, in cached_value
19)     return self.function_cache(service_name, func)[args]
20)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/subliminal/cache.py", line 88, in function_cache
21)     func_key = self.cached_func_key(func)
22)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/subliminal/cache.py", line 85, in cached_func_key
23)     return ('%s.%s' % (cls.__module__, cls.__name__), func.__name__)
24) AttributeError: 'NoneType' object has no attribute '__module__'

it on BRANCH: master @ py3.10.0 / COMMIT: dab88e3 @ 0.25.31 on a QNAP NAS

**Comment by JackDandy** [comment]
disable it and use some other tool to get subtitles

**Comment by Dohnerd** [comment]
Ehh seems to be your code thats is failing? using subliminal from command line does the job fine ??

**Comment by JackDandy** [comment]
> Ehh seems to be your code thats is failing? using subliminal from command line does the job fine ??

correct, that third party library is newer than what is shipped with SG, it is so different that it broke backwards compatibility, and the new had no nice way for devs to re-implement, therefore, we have been waiting for complaints as a trigger to simply remove it - seems that time is here.

Thank you for your report.

**Comment by Dohnerd** [comment]
So there is no way i can rollback, install or otherwise fix it, I liked the feature being from Denmark ?

**Comment by JackDandy** [comment]
Oh sure, if you are able to upgrade the packaged Subliminal and its related libraries, and the interactions of those within the SG codebase, then that would be awesome.

**Comment by JackDandy** [comment]
> So there is no way i can rollback, install or otherwise fix it, I liked the feature being from Denmark ?

Oh sure, if you are able to upgrade the packaged Subliminal and its related libraries, and the interactions of those within the SG codebase, then that would be awesome.
