### ISSUE TITLE
web_password and torrent_password do not work upon restart

### ISSUE THREAD

**Issue by wimpomp** [SickGear/SickGear#1385]
BRANCH: master @ py3.9.5
COMMIT: 6c92c7c @ 0.25.31

Expectation | Result
------------ | -------------
After restarting I should be able to login and sickgear should also be able to authenticate with transmission (my torrent client) | I cannot login until I make web_password in config.ini empty, then I can set my password again in the sickgear gui. Authentication to transmission also fails until I set the password again. I use no other features requiring passwords in sickgear.

**Steps to reproduce:**
*1)* Restart sickgear
*2)* Try to log in 

<pre>
[General]
config_version = 22
branch = master
git_remote = origin
cur_commit_hash = 6c92c7c4f7c18570bdf44fe2493d051855b25322
cur_commit_branch = master
encryption_version = 1
log_dir = Logs
file_logging_preset = DEBUG
file_logging_db = 0
socket_timeout = 30
web_host = 0.0.0.0
web_port = 8081
web_ipv6 = 0
web_ipv64 = 0
web_log = 0
web_root = ""
web_username = [username]
web_password = [password]
cpu_preset = DISABLED
anon_redirect = ""
use_api = 0
api_keys = ""
debug = 0
enable_https = 0
https_cert = server.crt
https_key = server.key
handle_reverse_proxy = 1
send_security_headers = 1
allowed_hosts = ""
allow_anyip = 1
use_nzbs = 0
use_torrents = 1
nzb_method = blackhole
torrent_method = transmission
usenet_retention = 500
mediaprocess_interval = 10
recentsearch_interval = 40
backlog_period = 21
backlog_limited_period = 7
download_propers = 1
propers_webdl_onegrp = 1
allow_high_priority = 1
recentsearch_startup = 0
backlog_nofull = 0
skip_removed_files = 7
results_sortby = ""
indexer_default = 0
indexer_timeout = 20
quality_default = 22020596
wanted_begin_default = 0
wanted_latest_default = 0
pause default = 0
status_default = 5
scene_default = 0
flatten_folders_default = 0
anime_default = 0
provider_order = alpharatio bb bithdtv blutopia btn ettv eztv fano filelist funfile grabtheinfo hdbits hdme hdspace hdtorrents immortalseed iptorrents limetorrents magnetdl milkie morethan ncore nebulance pretome privatehd ptfiles rarbg revtt scenehd scenetime shazbat showrss snowfl speedcd the_pirate_bay torlock torrentday torrenting torrentleech tvchaosuk xspeeds zooqle nyaa tokyotoshokan speedapp torrentdb
provider_homes = "{'limetorrents': ('https://www.limetorrents.cc/', 1648991711), 'torlock': ('https://www.torlock.com/', 1648991711), 'eztv': ('https://eztv.it/', 1648991711), 'rarbg': ('https://rarbg2018.org/', 1648991711)}"
update_notify = 0
update_auto = 0
update_interval = 1
notify_on_update = 0
update_packages_notify = 0
update_packages_auto = 0
update_packages_menu = 0
update_packages_interval = 24
naming_strip_year = 0
naming_pattern = %SN - %Sx%0E - %EN
naming_custom_abd = 0
naming_abd_pattern = %SN - %A.D - %EN
naming_custom_sports = 0
naming_sports_pattern = %SN - %A-D - %EN
naming_custom_anime = 0
naming_anime_pattern = Season %0S/%SN - S%0SE%0E - %EN
naming_multi_ep = 1
naming_anime_multi_ep = 1
naming_anime = 3
launch_browser = 1
update_shows_on_start = 0
show_update_hour = 3
trash_remove_show = 0
trash_rotate_logs = 0
home_search_focus = 1
display_freespace = 1
sort_article = 0
proxy_setting = ""
proxy_indexers = 1
metadata_xbmc = 0|0|0|0|0|0|0|0|0|0
metadata_xbmc_12plus = 0|0|0|0|0|0|0|0|0|0
metadata_mediabrowser = 0|0|0|0|0|0|0|0|0|0
metadata_ps3 = 0|0|0|0|0|0|0|0|0|0
metadata_wdtv = 0|0|0|0|0|0|0|0|0|0
metadata_tivo = 0|0|0|0|0|0|0|0|0|0
metadata_mede8er = 0|0|0|0|0|0|0|0|0|0
metadata_kodi = 0|0|0|0|0|0|0|0|0|0
search_unaired = 0
unaired_recent_search_only = 1
flaresolverr_host = http://127.0.0.1:8191/
cache_dir = cache
root_dirs = 0|/tv
tv_download_dir = /tv
keep_processed_dir = 0
process_method = hardlink
process_last_dir = /incoming
process_last_method = hardlink
process_last_cleanup = 0
move_associated_files = 1
postpone_if_sync_files = 1
nfo_rename = 1
process_automatically = 1
unpack = 1
rename_episodes = 1
airdate_episodes = 0
create_missing_show_dirs = 0
show_dirs_with_dots = 0
add_shows_wo_dir = 0
add_shows_metalang = en
remove_filename_chars = ""
import_default_checked_shows = 0
extra_scripts = ""
sg_extra_scripts = ""
git_path = ""
ignore_words = ""
require_words = ""
calendar_unprotected = 1
[Updates]
updates_todo = {}
[Backup]
backup_db_oneday = 0
backup_db_max_count = 14
[EZTV]
eztv = 1
[LIMETORRENTS]
limetorrents = 1
[MAGNETDL]
magnetdl = 1
[RARBG]
rarbg = 1
[SNOWFL]
snowfl = 1
[TORLOCK]
torlock = 1
[ZOOQLE]
zooqle = 1
[NYAA]
nyaa = 1
[TOKYOTOSHOKAN]
tokyotoshokan = 1
[FILESHARINGTALK]
filesharingtalk_digest = ""
[OMGWTFNZBS]
omgwtfnzbs_api_key = ""
omgwtfnzbs_username = ""
[NZBGet]
nzbget_username = nzbget
nzbget_password = RB1fAEJfVQFcCw==
nzbget_category = tv
nzbget_priority = 100
[SABnzbd]
sab_password = XRlMGxZVRA==
sab_category = tv
[TORRENT]
torrent_username = [username]
torrent_password = [password]
torrent_host = http://localhost:9091/
torrent_path = /downloads/seeding/series
[Emby]
emby_watchedstate_interval = 10
[Kodi]
kodi_password = XRlMHhdWQw==
kodi_always_on = 1
[Plex]
use_plex = 1
plex_username = [username]
plex_update_library = 1
plex_watchedstate_scheduled = 1
plex_watchedstate_interval = 10
plex_server_host = 192.168.1.33:32400
[XBMC]
xbmc_always_on = 1
[Telegram]
telegram_send_image = 1
[Email]
email_host = localhost
email_from = [email]
email_list = [email]
email_notify_onsnatch = 1
email_notify_ondownload = 1
email_notify_onsubtitledownload = 1
[Newznab]
newznab_data = "Sick Beard Index|https://lolo.sickbeard.com/||5030,5040|0|eponly|0|1|1|1|0!!!NZBgeek|https://api.nzbgeek.info/||5030,5040|0|eponly|0|1|1|1|0!!!DrunkenSlug|https://api.drunkenslug.com/||5030,5040|0|eponly|0|1|1|1|0!!!NinjaCentral|https://ninjacentral.co.za/||5030,5040|0|eponly|0|1|1|1|0"
[GUI]
gui_name = slick
theme_name = dark
default_home = episodes
fanart_limit = 3
fanart_panel = highlight2
fanart_ratings = {}
use_imdb_info = 1
imdb_accounts = 64552276, SickGear
fuzzy_dating = 0
trim_zero = 0
date_preset = "%a, %d. %b %y"
time_preset = %H:%M:%S
timezone_display = local
show_tags = Show List
showlist_tagview = standard
home_layout = poster
footer_time_layout = 0
poster_sortby = name
poster_sortdir = 1
display_show_glide = {}
display_show_glide_slidetime = 3000
display_show_viewmode = 2
display_show_background = 1
display_show_background_translucent = 0
display_show_viewart = 2
display_show_minimum = 1
display_show_specials = 1
episode_view_viewmode = 2
episode_view_background = 1
episode_view_background_translucent = 1
episode_view_layout = list
episode_view_sort = time
episode_view_display_paused = 1
episode_view_posters = 1
episode_view_missed_range = 7
show_tag_default = Show List
history_layout = compact_watched
browselist_hidden = ""
browselist_prefs = {}
[Subtitles]
use_subtitles = 1
subtitles_languages = "en,ru,nl"
SUBTITLES_SERVICES_LIST = "opensubtitles,thesubdb,addic7ed,tvsubtitles"
SUBTITLES_SERVICES_ENABLED = 1|1|1|1
subtitles_services_auth = :::
subtitles_dir = ""
subtitles_default = 0
subtitles_history = 0
subtitles_finder_interval = 1
subtitles_os_hash = True
[FailedDownloads]
use_failed_downloads = 1
delete_failed = 1
[ANIDB]
use_anidb = 0
anidb_username = ""
anidb_password = ""
anidb_use_mylist = 0
[ANIME]
anime_treat_as_hdtv = 0
</pre>

Additional notes:
I encountered this issue first on Ubuntu 20.04, the issue persisted after switching sickgear to the latest docker image: sickgear/sickgear:latest.

**Comment by JackDandy** [comment]
i just added a username and password, logged in, restarted, logged in again, worked fine. please refine the steps taken to see the issue you saw, I used a very simple "sg" as username and pw just to test.
