### ISSUE TITLE
Customize URL for IPtorrents

### ISSUE THREAD

**Issue by Dillonmartine** [SickGear/SickGear#1389]
#### Branch version commit hash: (See the About page)

Expectation | Result
------------ | -------------

IPTorrents has multiple URLS that are designed to ensure access when ISPs are blocking. SickGear should have an option to allow you to specify a URL for IPTorrents so that the application can continue to operate. (Some Urls even bypass Cloudflare) | SickGear searches and pulls torrent info from the custom URL. 

N/A

**Comment by JackDandy** [comment]
do you see ipt not actually working?

**Comment by Dillonmartine** [comment]
@JackDandy It is more about the fact that cloud flare bypass stops working every few months, using the custom url allowed me to bypass Cloudflare entirely.

**Comment by JackDandy** [comment]
I see, then you have not completed all post install setups, as one handles cloudflare

**Comment by Dillonmartine** [comment]
Is allowing customizing the URL an enhancement you won't consider? That was the only ask I had, it's okay if not, I was thinking it is an enhancement that would make sense

**Comment by JackDandy** [comment]
It's not that, it's simply that this provider has never produced an issue that needs the suggested enhancement, so if it ain't broke...
