### ISSUE TITLE
Cant flag subtitle provider's 

### ISSUE THREAD

**Issue by potestus** [SickGear/SickGear#1392]
#### Branch version commit hash: (See the About page)

Version: | BRANCH: master @ py3.10.5 / COMMIT: 2bb7933 @ 0.25.43
-- | --

![Screenshot_20221006_150411_Chrome](https://user-images.githubusercontent.com/2980512/194333903-34667f04-d205-41fb-8026-48ff02ce8a23.jpg)
![Screenshot_20221006_150403_Chrome](https://user-images.githubusercontent.com/2980512/194333907-ddc6b754-a949-452a-96d1-7b399e79fa2b.jpg)
![Screenshot_20221006_150411_Chrome](https://user-images.githubusercontent.com/2980512/194334035-3fbd535b-dc4f-4836-8791-ae1222a05a31.jpg)
![Screenshot_20221006_150403_Chrome](https://user-images.githubusercontent.com/2980512/194334040-98c7509c-8741-4315-959e-75575551ee00.jpg)

Expectation | Result
------------ | -------------
Your expectation paragraph(s) text here. Before the bar >> | then, your result paragraph(s) text here.

Checkboxes don't work

**Steps to reproduce:**
*1)* Step to take
*2)* Step to take
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
> Checkboxes don't work

Did you try another browser, the checkboxes work fine, so perhaps it is a browser issue.

**Comment by potestus** [comment]
Using chrome on a tablet. Haven't used a PC for decades..

Terry
