### ISSUE TITLE
Mark download as bad and retry - Not available

### ISSUE THREAD

**Issue by bishop62-MN** [SickGear/SickGear#1393]
#### Branch version commit hash: / COMMIT: 1a89784 @ 0.25.48

Expectation | Result
------------ | -------------
Expect to select the episode and get the Mark download as bad and retry and get new episode | Bad download for episode keeps pulling the same bad episode

**Steps to reproduce:**
*1)* Select the show
*2)* click on the episodes check box and mark wanted
*3)* click on the episodes check mark
*4)*just goes into a search pulling same bad file
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

[**edit** log removed, no longer reqd.]

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
This is correct behaviour. to mark as bad, you need to use the mag glass. This is to allow for difference use cases.
