### ISSUE TITLE
Feature request: Subtitle work arounds

### ISSUE THREAD

**Issue by pge-01** [SickGear/SickGear#1397]
Branch: master @ py3.8.12

When considering to remove the SUBLIMINAL subtitles, can you **please** **keep** the subtitle flags on the View Show page indicating there are subtitles included in the video container (in the right language!).

It would be even nicer if it is possible to move the downloads which are flagged (with subtile) to the archived folder by the press of a button or if selected / set to archived.

Expectation                                            | Result
Detection of existing subtitles             | Workable system for not native English speakers!
Detection of manual added subtitles  |

**Thanks in advance.**

Ps. Did I say please? I really enjoyed the work so far, but the subtitles really matter a lot.

**Comment by JackDandy** [comment]
Points noted.

Thanks for your feedback.
