### ISSUE TITLE
Files with date but without a suffix are not processed & not logged.

### ISSUE THREAD

**Issue by kevin201** [SickGear/SickGear#1398]
BRANCH: master @ py3.8.0 / COMMIT: d9d762b @ 0.25.50

Expectation | Result
------------ | -------------
Files are processed as normal, some informational output is given in log | No files are processed. Log shows only Failed! Did not process any files.

**Steps to reproduce:**
*1)* mkdir "Target"
*2)* touch "Target"/"Showname (date).mp4"
*3)* Go to Process Media page and manually process files

```
Checking folder... /share/Multimedia/0.NewAdditions
Processing folder... /share/Multimedia/0.NewAdditions
Processing sub dir: Target
----------------------------------
Failed! Did not process any files.
```

Additional notes:
This is not a search issue. Adding, for example, "Showname (date) [480p HD TV].mp4" gives the expected result. https://gist.github.com/kevin201/91b2b66f42e619fccdf6802c0ca8b672

Adding any non blank characters at all after the date gives the expected result. https://gist.github.com/kevin201/3de338e0ee04e0748a261d8594724385

In this case, SD quality is assumed. 

"Showname" is in the database.

It's quite possible that this is intended behaviour, but it would be useful to have some output in the log.

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.25.51)

Thanks.
