### ISSUE TITLE
Processing error

### ISSUE THREAD

**Issue by Acscorp1** [SickGear/SickGear#1399]
#### Branch version commit hash: 0a75683 @ 0.25.51

Expectation | Result
Process downloads | Error page
Your expectation paragraph(s) text here. Before the bar >> | then, your result paragraph(s) text here.

**Steps to reproduce:**
*1)* click process media

[Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags](https://gist.github.com/Acscorp1/b84273e714f8be585f0e96f68f5beca6)

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.25.52)

Thanks
