### ISSUE TITLE
Search for show returns error

### ISSUE THREAD

**Issue by potestus** [SickGear/SickGear#1401]
#### Branch version commit hash: (See the About page)
BRANCH: master @ py3.10.5 / COMMIT: ddeaabd @ 0.25.52

Expectation | Result
------------ | -------------
Your expectation paragraph(s) text here. Before the bar >>

Search for " his dark" times out and causes an error. Happens on any search

 | then, your result paragraph(s) text here.

2022-11-27 09:48:02 ERROR    TORNADO.APP :: Uncaught exception GET /add-shows/search-tvinfo-for-showname?search_term=His+dark&lang=en&search_tvid=0 (192.168.1.45)
 1) HTTPServerRequest(protocol='http', host='192.168.1.78:7181', method='GET', uri='/add-shows/search-tvinfo-for-showname?search_term=His+dark&lang=en&search_tvid=0', version='HTTP/1.1', remote_ip='192.168.1.45')
 2) Traceback (most recent call last):
 3)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/tornado_py3/web.py", line 1704, in _execute
 4)     result = await result
 5)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/tornado_py3/gen.py", line 769, in run
 6)     yielded = self.gen.throw(*exc_info)  # type: ignore
 7)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/sickbeard/webserve.py", line 898, in get
 8)     yield self.route_method(route, use_404=True)
 9)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/tornado_py3/gen.py", line 762, in run
10)     value = future.result()
11)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/tornado_py3/gen.py", line 769, in run
12)     yielded = self.gen.throw(*exc_info)  # type: ignore
13)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/sickbeard/webserve.py", line 245, in route_method
14)     result = yield self.async_call(method, filter_kwargs)  # method(**filter_kwargs)
15)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/tornado_py3/gen.py", line 762, in run
16)     value = future.result()
17)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/sg_futures/py3.py", line 32, in run
18)     result = self.fn(*self.args, **self.kwargs)
19)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/sickbeard/webserve.py", line 255, in async_call
20)     raise e
21)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/sickbeard/webserve.py", line 251, in async_call
22)     return function(**kw)
23)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/sickbeard/webserve.py", line 4054, in search_tvinfo_for_showname
24)     [[[id_names[tvid], in_db(*((tvid, int(show['id'])),
25)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/sickbeard/webserve.py", line 4054, in <listcomp>
26)     [[[id_names[tvid], in_db(*((tvid, int(show['id'])),
27)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/sickbeard/webserve.py", line 4072, in <listcomp>
28)     or self.get_uw_ratio(term, show['seriesname'], show.get('aliases') or [],
29)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/sickbeard/webserve.py", line 4165, in get_uw_ratio
30)     s = fuzz.UWRatio(search_term, showname)
31)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/fuzzywuzzy/fuzz.py", line 306, in UWRatio
32)     return WRatio(s1, s2, force_ascii=False, full_process=full_process)
33)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/fuzzywuzzy/fuzz.py", line 276, in WRatio
34)     base = ratio(p1, p2)
35)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/fuzzywuzzy/utils.py", line 38, in decorator
36)     return func(*args, **kwargs)
37)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/fuzzywuzzy/utils.py", line 29, in decorator
38)     return func(*args, **kwargs)
39)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/fuzzywuzzy/utils.py", line 47, in decorator
40)     return func(*args, **kwargs)
41)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/fuzzywuzzy/fuzz.py", line 28, in ratio
42)     return utils.intr(100 * m.ratio())
43)   File "/share/CACHEDEV1_DATA/.qpkg/OSickGear/OSickGear/lib/fuzzywuzzy/StringMatcher.py", line 64, in ratio
44)     self._ratio = ratio(self._str1, self._str2)
45) NameError: name 'ratio' is not defined

**Steps to reproduce:**
*1)* Step to take
*2)* Step to take
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
what OS/arch ?

**Comment by JackDandy** [comment]
The thought is that this is due to a newly updated lib and seems to be a Linux only issue.

    What OS
    What architecture

are you running sg on ?

**Comment by potestus** [comment]
Qnap Architecture ? Using Sherpa.

**Comment by JackDandy** [comment]
try this....
```
python -m pip uninstall python-Levenshtein
python -m pip install --force-reinstall Levenshtein
```

**Comment by potestus** [comment]
Running the following fixed the issue for me:

# /opt/bin/python3 -m pip uninstall python-Levenshtein
# /opt/bin/python3 -m pip install --force-reinstall Levenshtein
# sherpa restart OS

**Comment by JackDandy** [comment]
This issue should now be fixed.

Thanks for the report.
