### ISSUE TITLE
first run of SickGear removes `cheetah3` and `CT3` PyPI modules

### ISSUE THREAD

**Issue by OneCDOnly** [SickGear/SickGear#1402]
Hi guys, got a weird one here and I'm hoping you can please advise. :)

- Environment is QTS (QNAP's modified Ubuntu OS). 
- SickGear is installed via `git pull` from GitHub master branch. 
- Python3 environment is installed via Entware `opkg`
- Python modules are installed via `pip`

Now the issue: when I first run SickGear, it won't start - it complains that Cheetah is missing. Even though it was there before I attempted to start SickGear. 

This used to work just fine, but I haven't tested the startup of SickGear for several months. 

Here's my service script startup log:
```
     33 = ExecuteAndLog()
     34 output: "The Python module Cheetah is required
     35 Manually install using...
     36 cd <sickgear_installed_folder>
     37 python -m pip install --user -r requirements.txt
     38 python sickgear.py"
     39 result: [1]
```

Here's a snippet of the output from `pip list` before starting SickGear: 
```
...
charset-normalizer    2.1.1
Cheetah3              3.2.6.post1
cheroot               8.6.0
CherryPy              18.8.0
click                 8.1.3
configobj             5.0.6
constantly            15.1.0
cryptography          3.4.8
CT3                   3.3.0
deluge                2.1.1
...
```
And after attempting to start SickGear and seeing it fail, 2 modules are indeed missing:
```
...
charset-normalizer    2.1.1
cheroot               8.6.0
CherryPy              18.8.0
click                 8.1.3
configobj             5.0.6
constantly            15.1.0
cryptography          3.4.8
deluge                2.1.1
...
```
Oddly, these are the same 2 modules listed in `requirements.txt`. 

Additionally, other packages that depend on Cheetah3 will also fail to start because Cheetah3 is now missing. 

~~If I manually install these modules and start SickGear again, it works fine. From here on, I can stop/start/restart it and it still works fine. Until I reboot, and SickGear will be run for the first time after bootup - then it kills the modules again.~~

**update:** no, it's now not working at-all after reinstalling Cheetah3. It removes this module, then complains as before that it's missing. 

I don't know why this is happening. I'm not a Python guru, but I can usually follow instruction without issues. Any hints? 

Thank you.

**Comment by JackDandy** [comment]
> Oddly, these are the same 2 modules listed in requirements.txt.

They are listed as one is required for py2, the other for py3.

Cheetah3 has been renamed CT3.

Please request the QNAP packager to update the package.

**Comment by OneCDOnly** [comment]
Thank you @JackDandy. 

I'm the package maintainer for this one. I'll remove Cheetah3 as an installable package and retest. 

Any thoughts as-to why those PyPI modules are being removed when attempting to run SickGear?

**Comment by JackDandy** [comment]
> Any thoughts as-to why those PyPI modules are being removed when attempting to run SickGear?

SG is calling for this action, to replace Cheetah3 with CT3.

**Comment by OneCDOnly** [comment]
OK, but it seems rather odd behaviour - to silently remove an installed package, then complain the package isn't installed. 🤷🏽 

Maybe letting the user know what it's doing would be more helpful?

**Comment by JackDandy** [comment]
> Maybe letting the user know what it's doing would be more helpful?

Cheetah _is_ the output UI template module and a special case was made to replace it before it's loaded. Output isn't readily available at this point like it is with normal module updates.

**Comment by JackDandy** [comment]
> I'm the package maintainer for this one

Great news! We've also received specific QNAP reports,

1) The startup file in `/share/CACHEDEV1_DATA/.qpkg/SickGear/` is still pointing to `SickBeard.py`, can you change it to run `sickgear.py`
2) The latest firmware upgrades for QTS prevents SickGear from starting.

**Comment by OneCDOnly** [comment]
No, I'm not the maintainer of the package version you've mentioned. 

I maintain the `OSickGear` QPKG installable via [sherpa](https://github.com/OneCDOnly/sherpa). 

The `SickGear` QPKG is maintained by @QNAP_Stephane (also-known-as Qoolbox).

**Comment by Bsunshine18** [comment]
> No, I'm not the maintainer of the package version you've mentioned.
> 
> I maintain the `OSickGear` QPKG installable via [sherpa](https://github.com/OneCDOnly/sherpa).
> 
> The `SickGear` QPKG is maintained by @QNAP_Stephane (also-known-as Qoolbox).

Hi - I am the user the @JackDandy referred to regarding the issues above. I've intsalled Qoolbox's package (from QnapClub Store following SickGear install instructions) and have been able to manually fix the start up file issue but have been unable to resolve the QTS version issue (I have stopped updating my QNAP at QTS firmware version 5.0.0.2131 - any version after this stops SickGear from starting up). I also note that this package 

I've tried to look up OSickGear but can't find any reference to the package anywhere. Not sure if you've solved the issue above but if you have I'd be interested in installing the OSickGear version. 

Thanks

**Comment by OneCDOnly** [comment]
> I've tried to look up OSickGear but can't find any reference to the package anywhere. Not sure if you've solved the issue above but if you have I'd be interested in installing the OSickGear version if it brings the package more up to date.

You won't find many references to it. It's just another SickGear QPKG, but with an enhanced service script. It also runs from GitHub source, and upgrades everytime you start it via the service script. 

`OSickGear` is available by first installing sherpa: https://github.com/OneCDOnly/sherpa

**Comment by JackDandy** [comment]
@Bsunshine18 

did the Sherpa install build work for you?
