### ISSUE TITLE
Search in anime providers without using alternative episode format

### ISSUE THREAD

**Issue by MyDigitalLife** [SickGear/SickGear#1404]
#### Branch version commit hash: ddeaabd4602ea0e5e62ea7a820400abc7f668d3e

Expectation | Result
------------ | -------------
When marking a show as anime it can be searched in both formats (SxxExx and Sxx xxx)  | When marked as anime it will only be searched in the episode only format.

**Steps to reproduce:**
*1)* Add The show My hero academia
*2)* Mark My Hero academia as anime
*3)* Add search provider nyaa
*4)* Perform search as for a episode of My hero academia
*5)* No episode will be found as the SxxExx format is used on Nyaa while a search is performed using Sxx xxx
...

<pre>
2022-12-15 12:22:09 INFO     MANUAL-1:305074 :: [Nyaa] :: No suitable result at [Nyaa]
2022-12-15 12:22:08 INFO     MANUAL-1:305074 :: [Nyaa] :: 1 episode item in response from https://www.nyaa.si/?f=0&c=1_0&q=My Hero Academia S6 124
</pre>

Additional notes:
These days anime sometimes also use the more traditional SxxExx format on torrent sites. It should be possible to use anime providers while using the traditional episode format notation.

**Comment by JackDandy** [comment]
For now, disable the "As anime" to processing as traditional format, a group tends to stick to one format or the other anyway.

Other than that, this is not really an issue but more a feature "Enhancement" request, so it will be tagged.

**Comment by JackDandy** [comment]
Hi, did the answer address your query? It's more efficient that way rather than to 2x the number of server search requests.
