### ISSUE TITLE
Startup is stalled at "Starting a forced show update"

### ISSUE THREAD

**Issue by WafflesMcDuff** [SickGear/SickGear#1406]
#### Branch version commit hash: 0f8f7afca64cb0a7a1ca1ddb83cc53a53aaca326

Expectation | Result
------------ | -------------
Sickgear Starts Up  |  Startup is stalled at "Starting a forced show update"

**Steps to reproduce:**
*1)* Start up SickGear
...

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
Investigating. Feel free to ask anything else below, even though it is closed that's no problem.

**Comment by JackDandy** [comment]
For now, you can
edit the `config.ini` file, 
find... `update_shows_on_start` and make it `update_shows_on_start = 0`
this will get the UI accessible again. 

A hotfix is being tested that resolves this issue by running the show update in the background.

**Comment by JackDandy** [comment]
This is handled [here](https://github.com/SickGear/SickGear/releases/tag/release_3.26.1)

Thanks for reporting this issue.
