### ISSUE TITLE
Manual search for episode throws an Error

### ISSUE THREAD

**Issue by vzografos** [SickGear/SickGear#1407]
#### Branch version commit hash: 0f8f7af @ 0.25.60

Expectation | Result
------------ | -------------
Clicking on the Manual Search Magnifying glass next to an episode. Expected to search for and possibly grab the episode  | Throws an error in the log

Show in question is this:   [Kaleidoscope](https://thetvdb.com/series/kaleidoscope) 

```
2023-01-25 13:46:24 MANUAL-1:410092 :: Traceback (most recent call last):
  File "/opt/sickgear/sickbeard/search_queue.py", line 661, in run
    search_result = search.search_providers(self.show_obj, [self.segment], True, try_other_searches=True)
  File "/opt/sickgear/sickbeard/search.py", line 946, in search_providers
    individual_results = nzbSplitter.splitResult(best_season_result)
  File "/opt/sickgear/sickbeard/nzbSplitter.py", line 202, in splitResult
    separate_nzbs, xmlns = getSeasonNZBs(result.name, resp, season)
  File "/opt/sickgear/sickbeard/nzbSplitter.py", line 78, in getSeasonNZBs
    showXML = etree.ElementTree(etree.XML(url_data))
  File "src/lxml/etree.pyx", line 3201, in lxml.etree.XML
  File "src/lxml/parser.pxi", line 1872, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

**Steps to reproduce:**
*1)*  Click on Manual search icon (Magnifying glass)

...

**Comment by JackDandy** [comment]
Can you see if the issue exists with Python 3?

**Comment by JackDandy** [comment]
If you can get the nzb file to me, we can look deeper.

**Comment by JackDandy** [comment]
I have an idea for a very easy fix, but need your help to test the URL that has the specific NZB.

**Comment by vzografos** [comment]
ok let me know how I can help. Do you want me to paste the NZB link here?

**Comment by vzografos** [comment]
> I strongly recommend you upgrade to Python 3.
>
I have Python 3 as well but `python` calls python 2.7 and `python3` is for python 3. I can change the default `python` but I am afraid it might break something else.

**Comment by vzografos** [comment]
a little bit more background on this problem. It seems to happen only with that show (something in the nzb link perhaps?) and it is repeatable.
Does not happen with other shows/links

**Comment by JackDandy** [comment]
> Do you want me to paste the NZB link here?

Yup, I will remove it when I have it

**Comment by JackDandy** [comment]
Yup, the issue is indeed specific to this show and comes from the originating indexer for the specific season nzb file. I suggest you disable season snatching so that episode nzb files are snatched which will avoid the bad season nzb file.

**Comment by vzografos** [comment]
removing the season snatching + fallback works. Thanks

**Comment by JackDandy** [comment]
finally, rather than start SG with just `sickgear.py ...` run it with `python3 sickgear ...`
