### ISSUE TITLE
bug: startup always fails first time after install, but works everytime afterward

### ISSUE THREAD

**Issue by OneCDOnly** [SickGear/SickGear#1408]
Hi guys. :)

I'm having some trouble. 

`BRANCH: main @ py3.10.7 / COMMIT: 1630b3d @ 3.27.1`

Running in QTS (QNAP's Ubuntu-based NAS OS).

SickGear will fail with a traceback only on the first run after installation. But then works fine everytime after this. 

The error shown is (the exec is used within my service script):
```
exec: '. /share/CACHEDEV2_DATA/.qpkg/OSickGear/venv/bin/activate && cd /share/CACHEDEV2_DATA/.qpkg/OSickGear/repo-cache && /share/CACHEDEV2_DATA/.qpkg/OSickGear/venv/bin/python3 /share/CACHEDEV2_DATA/.qpkg/OSickGear/repo-cache/sickgear.py --daemon --nolaunch --datadir /share/CACHEDEV2_DATA/.qpkg/OSickGear/config --pidfile /var/run/OSickGear.pid'
Traceback (most recent call last):
  File "/share/CACHEDEV2_DATA/.qpkg/OSickGear/repo-cache/sickgear.py", line 95, in <module>
    import sickgear
  File "/share/CACHEDEV2_DATA/.qpkg/OSickGear/repo-cache/sickgear/__init__.py", line 39, in <module>
    from . import classes, db, helpers, image_cache, indexermapper, logger, metadata, naming, people_queue, providers, \
  File "/share/CACHEDEV2_DATA/.qpkg/OSickGear/repo-cache/sickgear/helpers.py", line 34, in <module>
    from . import db, logger, notifiers
  File "/share/CACHEDEV2_DATA/.qpkg/OSickGear/repo-cache/sickgear/notifiers/__init__.py", line 22, in <module>
    from . import emby, kodi, plex, xbmc, \
  File "/share/CACHEDEV2_DATA/.qpkg/OSickGear/repo-cache/sickgear/notifiers/telegram.py", line 29, in <module>
    from sickgear.image_cache import ImageCache
  File "/share/CACHEDEV2_DATA/.qpkg/OSickGear/repo-cache/sickgear/image_cache.py", line 44, in <module>
    from lib.hachoir.parser import createParser, guessParser
ModuleNotFoundError: No module named 'lib.hachoir.parser'
failed!
```
This happens regardless of the installed state of the `hachoir` PyPI package. 

A log isn't written by SickGear during the failed first run. The second run generates a log where everything is just-fine, so no help there. 

Thinking it may be a compiling issue, I tried to replicate it by removing `*.pyc` and `*.pyo` before exec, but this doesn't cause the original error. 

This also only happens on a fresh clone from GitHub. SickGear configuration files are kept separately, and are the same used for every session. 

All modules from `requirements.txt` and `recommended.txt` are installed. 

Any ideas please?

**Comment by JackDandy** [comment]
Hiya,

Thanks for the report.

This a vanilla install from source?

**Comment by OneCDOnly** [comment]
Hey Jack. :)

Correct.

**Comment by JackDandy** [comment]
can you test branch hotfix/3.27.2

**Comment by OneCDOnly** [comment]
Works fine! :)

**Comment by JackDandy** [comment]
great, okay, the issue isolated, i made the fix less aggressive, can you test again, same branch

**Comment by OneCDOnly** [comment]
Works fine also. 👍🏽

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_3.27.2)

Thanks again for the report

**Comment by OneCDOnly** [comment]
Thank you for the quick response. Much appreciated! :)

**Comment by JackDandy** [comment]
just so you know, the issue..

Fix installations that don't have previously saved cleanup lock files.

Because these installations don't have lock files, they run a legacy cleanup that no longer applies to the v3 migration that results in the removal of required module files. The legacy rules have been deleted.

So existing installation do not encounter this issue.
