### ISSUE TITLE
News: A new QNAP package is available

### ISSUE THREAD

**Issue by JackDandy** [SickGear/SickGear#1410]
The 0.21.3 package was reported to fail on newer QTS versions.
  
A new QNAP package is [available here](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-QNAP)
  
If anyone can feedback if it works or fails + with the version of QNAP, then that would be great!

**Comment by JackDandy** [comment]
Any one upgraded their system newer than ... 5.0.0.2055 ?

**Comment by jillmess** [comment]
I installed yesterday on TS-451+ with QTS 5.0.1.2277.  All ok - but I did already have all dependent/required packages from a previous install of Sherpa/OSickGear.

**Comment by JackDandy** [comment]
Fantastic! Thank you for taking the time and for the feedback <3
