### ISSUE TITLE
Error adding show when using TVmaze

### ISSUE THREAD

**Issue by mayoko185** [SickGear/SickGear#1411]
#### Branch version commit hash: 63cfb52 @ 3.27.4

Expectation | Result
------------ | -------------
Hi Im trying to add an anime [**edit**: no longer reqd.] to sickgear, when I used TVdb as a source it adds just fine however TVDB doesnt have the correct seasons for the show list but TVmaze does  have the correct seasons listed. When I select tvmaze as an option when I add the show I get an error | tried re-added the show again with tvdb works fine deleted show tried again w tvmaze same error with tvmaze

**Steps to reproduce:**
*1)* adding show with tvdb works as expected 
*2)* deleting show and trying to add using tvmaze gets the bellow error

<pre>2023-02-16 12:01:55 ERROR    SHOWQUEUE-ADD :: Traceback (most recent call last):
 1)   File "/opt/Sickgear/sickgear/show_queue.py", line 1015, in run
 2)     result = new_show_obj.load_from_tvinfo()
 3)   File "/opt/Sickgear/sickgear/tv.py", line 2796, in load_from_tvinfo
 4)     show_info = t.get_show(self.prodid, actors=True)  # type: Optional[TVInfoShow]
 5)   File "/opt/Sickgear/lib/tvinfo_base/base.py", line 1106, in get_show
 6)     self._get_show_data(show_id, self.map_languages.get(self.config['language'],
 7)   File "/opt/Sickgear/lib/api_tvmaze/tvmaze_api.py", line 366, in _get_show_data
 8)     person = self._convert_person(cur_ch.person)
 9)   File "/opt/Sickgear/lib/api_tvmaze/tvmaze_api.py", line 526, in _convert_person
10)     show.network = clean_data(net.name)
11) AttributeError: 'NoneType' object has no attribute 'name'

2023-02-16 12:01:55 ERROR    SHOWQUEUE-ADD :: Error trying to add show: 'NoneType' object has no attribute 'name'
2023-02-16 12:01:55 INFO     SHOWQUEUE-ADD :: 3-13687: Unable to find the show in the database
2023-02-16 12:01:55 INFO     SHOWQUEUE-ADD :: TVmaze: {'cache': '/opt/Sickgear/cache/indexers/TVmaze', 'language': 'en'}
2023-02-16 12:01:55 INFO     SHOWQUEUE-ADD :: Starting to add show /pool/TV Shows/Anime/[**edit**: no longer reqd.]</pre>

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_3.27.5)

Thanks for the report.

**Comment by mayoko185** [comment]
Confirmed fix working was able to add the show with tvmaze. Thanks for the quick fix!
