### ISSUE TITLE
Feature Request: Add Notifications option for Jellyfin

### ISSUE THREAD

**Issue by mayoko185** [SickGear/SickGear#1412]
Hopefully Im doing this right... I've been messing with some alternative media servers to plex and pretty much settled on Jellyfin but miss having the notification option like plex has. I run everything in a VM so Jellyfin's (and also plex) auto detect feature doesnt work, I have to have it scan for new stuff contently which id like to avoid. Plus its just nice having stuff pop in there once Sickgear moves it into place :). Thanks for everything!

**Comment by JackDandy** [comment]
you can use emby notifier with jf details for unofficial support
