### ISSUE TITLE
Info language ignored

### ISSUE THREAD

**Issue by EntenMelker** [SickGear/SickGear#1414]
#### Branch: BRANCH: main @ py3.10.10 / COMMIT: 68f81f9 @ 3.27.5

Expectation | Result
------------ | -------------
Changing show info language, e.g. fr, es, de >> | stays en, no change

**Steps to reproduce:**
*1)* try to change Show -> Edit -> Search -> Info language dropdown field
*2)* Update Show
*3)* Reloading page after show updated, seeing no changes, no matter which language choosen
*4)* formerly choosen episode naming (in this case "de") overwritten with english
*5)* reproducable with any other shows

[Log snippet](https://gist.github.com/EntenMelker/5b76ce5eb4fb2a51b6bc200d4db832f9)

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_3.27.6).

Thanks for the report

**Comment by EntenMelker** [comment]
Thanks.
