### ISSUE TITLE
SickGear QPKG is already available for QNAP NAS

### ISSUE THREAD

**Issue by OneCDOnly** [SickGear/SickGear#1415]
Hi guys,

just a heads-up: I've been maintaining a SickGear QPKG for QNAP NAS since 2020 that does the same thing as your new package. Entware is installed so we get access to Python3, then SickGear is updated from this repo before each startup. The service script also adds the ability to backup and restore settings. I also ensure it runs on all QNAP NAS, right back to the early ARMv5 models. 

It's available via the sherpa package manager: https://github.com/OneCDOnly/sherpa

**Comment by JackDandy** [comment]
Hi 

The (official SickGear package](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-QNAP) is small (~40 Kb), **dedicated**, and has no distractions.  

Sherpa is a lean compilation of packages, like QNAP club, QuickBox and others so it didn't fit right to ask you for a dedicated SG package.  However, experience with compilations is not great, with maintenance failures; the QNAP club package was over complicated and could not be improved, our feedback was ignored while other packages received improvements, this pushed some to category alternatives.  QuickBox, of similar age to Sherpa, now seems abandoned. The conclusion is not stable, not reliable, and not assured enough for SG.  
  
The (official SickGear package](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-QNAP) was quickly and really well taken care of, including our suggestions for how to make it work better and faster.

**Comment by JackDandy** [comment]
Hi 

The [official SickGear package](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-QNAP) is small (~40 Kb), **dedicated**, and has no distractions.  

Sherpa is a lean compilation of packages, like QNAP club, QuickBox and others so it didn't fit right to ask you for a dedicated SG package.  However, experience with compilations is not great, with maintenance failures; the QNAP club package was over complicated and could not be improved, our feedback was ignored while other packages received improvements, this pushed some to category alternatives.  QuickBox, of similar age to Sherpa, now seems abandoned. The conclusion is not stable, not reliable, and not assured enough for SG.  
  
The [official SickGear package](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-QNAP) was quickly and really well taken care of, including our suggestions for how to make it work better and faster.

**Comment by OneCDOnly** [comment]
Hi @JackDandy

A few misunderstandings here, so I'll try to correct these:

- No, sherpa is a package and service manager. Most QPKGs are written and maintained by myself, with the exception of Entware and Par2. sherpa QPKGs are not sourced from elsewhere (with the exception of Entware and Par2). Most sherpa QPKGs are written to pull applications from GitHub/GitLab and update them automatically. 

- "QuickBox". I don't know what that is. Maybe Qoolbox? Qoolbox is also know as QNAP_Stephane, and he maintains a great deal of QPKGs out there (approx 95% of all QPKGs are maintained by Stephane). He can always be reached on the QNAP Community Forum. 

- The QPKGs available on the QnapClub are not being maintained and the QnapClub should no-longer be considered a source for QPKGs. The site-admin decided to cut-off all communication with Stephane and myself, which eventually led to the creation of a new repository called MyQNAP. 

- the SickGear package available via sherpa is well-maintained, and I've put a great deal of effort into it to make it available to the QNAP community.

**Comment by JackDandy** [comment]
Hi,  
  
I feel that I understood.  
  
A selection of items, or packages, is a compilation. Like sherpa, "QuickBox" is a compilation that also has a service manager. Naturally, there are others similar projects.  
  
We are SickGear focused, so whatever happened at QnapClub and other projects is simply a reality of risk to SickGear users that we try to reduce because ... stability, reliability, assured.  
  
Therefore, the [official SickGear package](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-QNAP) is a hugely reduced risk, and is **ONLY** about SickGear.  
  
This thread will now be locked because there is not actually a code issue here, but you are welcome to drop by IRC if you would like to chat.  
  
Thanks for making contact, and for your understanding.
