### ISSUE TITLE
will you be supporting users with packages other than your "official" package? 

### ISSUE THREAD

**Issue by OneCDOnly** [SickGear/SickGear#1416]
I had a question I would have liked to ask in my previous issue, however it was locked before I could ask it. And I don't use IRC. 

Will you be supporting QNAP users who use SickGear packages other than your new "official" QPKG? I need an "official" statement so I know whether to discontinue support for SickGear. 

Please advise.

**Comment by JackDandy** [comment]
What a strange question, have you ever been denied support?

You are always welcome to come here for SickGear support, like any SickGear user always has.

**Comment by JackDandy** [comment]
Please can you acknowledge that you have read this answer.

**Comment by OneCDOnly** [comment]
I'd like to ensure you'll still support users with SickGear issues without simply advising them to switch to your "official" QPKG.

**Comment by JackDandy** [comment]
We will not simply advise someone to switch unless there is clear reason for a switch. For example, if the package fails to start, then it is clearly a package issue.

**Comment by OneCDOnly** [comment]
If a sherpa QPKG fails to start, sherpa user's know full-well they can rely on me for support getting it started again. 

I only ever direct them to the original applications developers when it's something I can't fix, and appears to be an application bug.

**Comment by JackDandy** [comment]
That is also fair.

**Comment by JackDandy** [comment]
Are you okay?

**Comment by JackDandy** [comment]
cool, i will delete this thread now
