### ISSUE TITLE
Issue when installing on Synology DSM 7

### ISSUE THREAD

**Issue by NederWeb** [SickGear/SickGear#1417]
#### Branch version commit hash: unknown

Expectation | Result
------------ | -------------
Running SickGear on Synology DSM 7

**Steps to reproduce:**
New Synology, latest DSM 7.
Install package for sickgear, start.

Error in /var/log/packages/sickgear.log:
python3: can't open file '/volume1/@appstore/sickgear/src/start.py': [Errno 2] No such file or directory

In file: /var/packages/sickgear/scripts/start-stop-status
STARTMODULE="${SYNOPKG_PKGDEST}/src/start.py"

In older file it was: SG_APP="${SYNOPKG_PKGDEST}/app/sickgear.py"
(Old synology)

**Comment by JackDandy** [comment]
Package updated to 1.08 [here](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-Synology#method-1-install-using-package)

If you can let us know... 
1) what version of Syno you are using, 
and
2) if the 1.08 works,

then that would be great!

**Comment by NederWeb** [comment]
I'm using DS923+   DSM 7.1.1-42962 Update 4
Downloaded the syno package this week, but haven't gotten around to do my migration, so haven't noticed it not working.
Unfortunately I can't test it, since I changed it myself in the startup script, and have migrated my DB, with changed paths etc. 
After changing the script, SickGear would start normally. 

I thought I would mention this issue.

**Comment by JackDandy** [comment]
Ah, well thank you for your feedback, appreciate it.
