### ISSUE TITLE
Change file date no longer working

### ISSUE THREAD

**Issue by mayoko185** [SickGear/SickGear#1421]
#### Branch version commit hash:  COMMIT: 327add5 @ 3.27.10

Expectation | Result
------------ | -------------
Processed files have the modify date set to the air date | at some point this stopped working, Im not sure when just noticed recently its no longer being applied to processed files.

**Steps to reproduce:**
I currently run Sickgear in a VM so I thought maybe it has something to do with VirtualBox being weird. However as a troubleshooting step I installed a fresh copy of Sickgear on BareMetal with direct access to the drive. Currently have this fresh install of sickgear running as root to test (just to make sure its not some weird permissions thing) and no dice.

Only thing I could find in the logs is (Both the baremetal insall and one in the VM give the same generic error):

2023-03-06 17:13:09 WARNING  SHOWQUEUE-REFRESH :: 1:153021: Error changing modify date of The Walking Dead - S01E01 - Days Gone Bye.mkv to show air date n/a

Quick edit: Ran the touch command and was able to change one of the files modified date normally as expected.

Additional notes:
OS: Ubuntu 22.04.2 LTS
Python version: | 3.10.6
Filesystem: ext4

**Comment by JackDandy** [comment]
That part of code hasn't been touched in forever, and it is known to sometimes fail, or fail on some systems.

**Comment by JackDandy** [comment]
Replicatable.

**Comment by JackDandy** [comment]
Sorry about the confusion earlier.

**Comment by mayoko185** [comment]
No worries, I appreciate your support anyways. Didn't see if it was a bug that's was posted so thought I'd let you know incase it was an easy fix.

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_3.27.11)

Thanks for the report.
