### ISSUE TITLE
"postprocess/processEpisode" url changed in develop, breaking API for other programs

### ISSUE THREAD

**Issue by qorron** [SickGear/SickGear#1422]
#### 7060da794d9085039ea2671697a19ace40314d06

urls like "home/postprocess/processEpisode" used by the current version of:
https://github.com/clinton-hall/nzbToMedia
don't work in the develop branch.

**Steps to reproduce:**
*1)* have an old sickgear in delevop branch
*2)* do a pull to upgrade to most recent version
*3)* sg starts, behaves normally in the UI
*4)* sg finds a new episode and hands it over to sabnzbd
*5)* sabnzbd finishes download and calls nzbToMedia
*6)* nzbToMedia fails because it gets a 404 on the "postprocess/processEpisode" url it tries to use to tell sg that a new episode is ready.
*7)* log captured by sabnzbd is below

```
[09:52:45] [DEBUG]::SICKBEARD: Opening URL: https://192.168.1.23:7070/home/postprocess/processEpisode with params: {'dir': '/data/storage/Media/Sab/AutoSab/sg/File', 'failed': 0, 'quiet': 1, 'nzbName': 'File'}
[09:52:45] [ERROR]::SICKBEARD: Server returned status 404
```
(Filename redacted)

Additional notes:
current master 18ad266ea4f70936a13031ec3d138101707f71ea works.

Perhaps an alias to the old url could be used if the url hast to be changed for some reason.

I tried updating nzbToMedia to the latest master -> no change

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/commit/a38ce369365402168d12faa68eba191203d87309)

Thanks for the report.

**Comment by JackDandy** [comment]
Hi,

To follow up on this, that method is deprecated and I can see that nzbToMedia is ready to use the more secure API psot processing method, if it is configured...

Can you...
1) Check SG API is enabled at... config/general/Interface/Web Interface/"API enable"
2) "Generate" a key in SG->config/general/Interface/Web Interface/"API Key"
3) Add generated API Key to nzbToMedia config
4) Do a test process

And could you let me know how that goes.
