### ISSUE TITLE
Problem with distro-info package

### ISSUE THREAD

**Issue by Fire69** [SickGear/SickGear#1425]
#### Ubuntu Server 22.04.2

Hey,

I had a problem with the nzb360 app on my phone not connecting correctly so I opened Sickgear and noticed the exclamation mark at the top so I checked the error log.

It's giving me an error about the distro-info package:
https://gist.github.com/Fire69/8a936f80f80cf959121ff0212a750117

I checked and the package is up-to-date.

When trying to check for updates in Sickgear it throws an error, as far as I understand also about the distro-info package:
https://gist.github.com/Fire69/bd834b233fbbe238985214e1438ae891

I tried updating Sickgear manually with git but it's up-to-date.

Anything else I can try to solve this?

Thanks!

**Comment by JackDandy** [comment]
Turn off SG, edit `config.ini` and make change...
* `update_packages_notify = 0`
* `update_packages_menu = 1`

And do not enable package updates on that system (you have to do package updates manually).

**Comment by JackDandy** [comment]
1. It looks like you may have a stray file containing `1.1build1` in a file under folder `setuptools\pkg_resources.extern.packaging...` - but folder `pkg_resources.extern` should now only contain one file that is `__init__py`.

So if you delete all but that `__init__.py` file, then restart SG, everything should be okay. 

2. If not, then disable package updates using... 

Turn off SG, edit `config.ini` and make change...
* `update_packages_notify = 0`
* `update_packages_auto = 0`
* `update_packages_menu = 0`

And do not enable package updates on that system (you have to do package updates manually).

If you let me know if (1) fixes things, then a fix can be made to clean up those stray files in future.

Thanks for the report.

**Comment by JackDandy** [comment]
see this 
https://stackoverflow.com/questions/75272737/error-invalid-version-0-23ubuntu1-package-distro-info

**Comment by JackDandy** [comment]
you can simply list all package versions to identify the bad ones by doing...

`python -m pip list`

**Comment by Fire69** [comment]
Before adding my edit, I had used the`pip list` method, and got over ~5 'bad' versions.
I started with distro-info, but using apt to remove it was also going to remove some other stuff I wasn't sure about if needed or not (ubuntu-release-upgrader-core and some other important sounding stuff...)
I risked it, removed it and used pip to install the 1.0 version of distro-info.  After that SG gave an error on gpg (1.16.0-unknown) when checking for updates.
So I removed it with apt and tried installing with pip but I threw lots of other errors about not being able to compile the wheel file.

I just gave up after that... :)

SG is working, that's what's important and I would like to thank you for this great piece of software! (and your support!)

**Comment by JackDandy** [comment]
Yeah, that does sound like a bit of a mess, with things missing in order to do things properly, e.g. wheels and dev stuff by the sounds of it. Too bad that something has made your env as complex as this, its far from normal, that's for sure.

**Comment by Fire69** [comment]
Don't know why it's like this, there's not much running on the server except SG, Sabnzbd, Couchpotato, ...

I tried updating some outdated packages, but now I'm stuck with 3 install locations:
- location before update: /usr/lib/python3/dist-packages
- normal update: /home/fire69/.local/lib/python3.10/site-packages
- update with sudo: /usr/local/lib/python3.10/dist-packages

Why is this so complicated...
Anyways, thanks for you time!

**Comment by JackDandy** [comment]
Issue fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_3.27.13)

An update to the bundled package parser threw the error for modules that are not actually used by SG but part of the system. Those errors are now skipped over.

The issues still exist in your system environment, but none of the modules that SG uses has the version number issue that setuptools is trying to address. Therefore, you can now reenable the package updater system in SG settings to keep at least SG used modules updated as normal.

Thanks for the report.
