### ISSUE TITLE
PP'd a promotional .mp4 for the releasgroup as the episode, after PPing the episode .mkv itself.

### ISSUE THREAD

**Issue by ItsMeMike** [SickGear/SickGear#143]
I just now Snatched Falling Skies S04E02 on KickAss Torrents, on 1080p quality.
It snatched Falling.Skies.S04E02.1080p.WEB-DL.DD5.1.H264-RARBG.

After downloading it started Post-Processing the folder. And it found the .mkv file, processed it as usual without problems. However very shortly after that, it found a .mp4 file which is a very small (993kb) promotional video for the releasegroup RARBG. It then decided to replace the already Post-processed .mkv file for the promotional .mp4.

Logs below, let me know if there is more info that you need.

Steps to reproduce:
1. Setup SG to PP files from a folder
2. Setup torrent client to download to that folder..
1. Add the torrent client to SG
2. Add Kick-ass torrents as a search provider
3. Add Falling Skies to SG, in 1080p quality.
4. Set S04E02 on Wanted, and let SG do it's magic.

**Comment by JackDandy** [comment]
hmm, so... post process the largest sized file found as suitable in any given release ?

**Comment by ItsMeMike** [comment]
At work now, so keeping it short. I wouldn't know the best approach, however this should at least be looked at since RARBG is planned to be added as a seperate provider.

**Comment by JackDandy** [comment]
Okay, we need a manual behaviour that you would take so that we can code automation.  As a user, look at several of their releases to see if what I suggest holds up, or does my idea fail too :)

**Comment by ItsMeMike** [comment]
Happened with new RARBG provider.
1. Setup SG to PP files from a folder
2. Setup torrent client to download to that folder..
1. Add the torrent client to SG
2. Enable RARBG as a search provider
3. Enable Confirmed download option
4. Add Sons of Anarchy to SG, in 1080p quality.
5. Set S07E01 on Wanted, and let SG do it's magic.
