### ISSUE TITLE
Opensubtitles.org API deprecation notice

### ISSUE THREAD

**Issue by HMAZonderland** [SickGear/SickGear#1430]
I wanted to point out that opensubtitles.org put up a deprecation notice about the XML-RPC API on [their Trac page](https://trac.opensubtitles.org/projects/opensubtitles).

> any API running on OpenSubtitles.org is deprecated and not possible to register new user agents anymore, we plan to turn off OpenSubtitles.org API by the end of 2023. Please use new, stable ready-to-use [​OpenSubtitles.com REST API](https://www.opensubtitles.com/docs/api/html/index.htm) instead.

**Comment by JackDandy** [comment]
Thanks for the report
