### ISSUE TITLE
Manual change episode status

### ISSUE THREAD

**Issue by PickledCucumber15** [SickGear/SickGear#1431]
#### Branch version commit hash: main @ py3.11.2 / COMMIT: 930b5ed @ 3.29.0

Expectation | Result
------------ | -------------
Manually changing status of an episode to "downloaded" (any quality) isn't allowed. Error log reports:
2023-05-25 08:32:53 HOME^WEB_3 :: Refusing to change status of 1x4 to downloaded because it's not snatched/downloaded/archived
Have to change to "ignored" or "skipped" first, then able to change to "downloaded" (any quality).

**Comment by JackDandy** [comment]
Yes, this is **exactly** as designed for date protection.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
This behavior is now included [here](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#status-change) in the FAQ
