### ISSUE TITLE
Provider Wait Times and Priority

### ISSUE THREAD

**Issue by alazare619** [SickGear/SickGear#150]
https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/filter/series.py
 is the file that flexget uses for its wait 
http://flexget.com/wiki/Plugins/series/timeframe

https://github.com/midgetspy/Sick-Beard/pull/466

seems to be sorta what was being asked but in a diffrent aspect and the same 

Clarity: Id always prefer HDTV > SDTV  if a HDTV is released on BTN id be willing to wait 1 hr if SD is up there to see if HDTV is released if after say 1 HR (user defined) it does not have HDTV download the SDTV.

Also: I would always prefer BTN > Torrentshack (rss feed) > Freshontv > Kat.ph.sh.whateverthe hell the extension is now

Lets say kat has the show doctor who (2005) s09e01 it was released at 12:00 i would be willing to wait 8 hrs for it to be on btn or torrentshack at the very least. If torrent shack has it i would be willing to wait 1hr for btn to have it. This is hard to explain but the above links have managed to do it in a way that works for what is being requested and both are python so it is possible. basically I never want to use freshon.tv or kat.ph unless i absolutely have to.

**Comment by adam111316** [comment]
@JackDandy will implement for you

**Comment by rssw** [comment]
A friend showed me this post after me expressing an interest in similar functionality.  Awesome!

If I may, my thoughts were along these lines:
- Keep a record of when an episode is aired or marked as wanted (for when backfilling old eps) as init.date
- Allow a "delay" setting per provider (as described above)
- Search providers only after today.date > init.date + provider.delay

So basically, only use my torrents if the content doesn't appear on usenet after X days/hrs.  And when searching multiple providers, still search them from least to greatest delay.

Keep up the good work and thanks for a BRILLIANT app!

**Comment by adam111316** [comment]
@rssw
Hmm you make a good point about the storing the date an episode was 'marked as wanted' for backfilling. I hadn't really considered that case. However if you are backfilling something from say a few months ago, you would expect it to be on torrents/usenet. 

Another possible issue is dealing with archiving qualities. Suppose a bluray is released 6 months after the 'airdate'. Might have issues if it hits torrents/usenet etc at different times.

**Comment by rssw** [comment]
@adam111316 
Agreed, if you add backfilling eps after a few months you would expect to get it anywhere, but right now it's backfilling at random from all the sources I have configured.  So the idea would be to honor the delays to ensure the channel priorities are maintained.  I'm spending a lot of time right now looking for usenet versions of torrents that were snatched for backfilling.

Treating lower qualities like a separate provider is a great idea i hadn't considered.  So wait a week for 720p, but after that start searching for 480p.  It's technically the same backend functionality, but the config could get quite tricky in the front end.

I'd say let's not over complicate things.  Do per provider first and if it's working and ppl use it, expand to qualities.

**Comment by ressu** [comment]
I'm not quite sure if this is related, but it would be nice if we could set priorities based on groups as well.

For example I prefer to get my Anime from Nyaa, mostly because it helps the groups making the releases, so in my case Nyaa > BTN for Anime releases, but I don't want to set priority to everything on Nyaa since it's pointless to search for all series there.

The Flexget way of doing priorities is nice, but it's horrible to configure. It's not easy to implement without making it overly complicated.

**Comment by adam111316** [comment]
Just popping a note for my own reference later...

1. Provider delay. 
x days after airdate

2. Quality delay.
x days after airdate

If curairdate > max(provider delay, quality delay):
> download

Notes. 
Would rely in saving potential downloads with a first seen airdate

**Comment by adam111316** [comment]
Even more musing
I think two difference mechanisms.

1. Provider delay. 
Wait X days on a particular result until downloading it. This other providers time to release a result. This resolves the issue if we are waiting for a bluray result that is released months after the airdate.

2. Quality delay. 
Wait X days after airdate before downloading a certain quality. Gives a grace period for web-dls to be released. for example set web-dl delay to 0 days, and HDTV delay to 3 days after airdate.

Test cases.
HDTV delay 3 days
WEB-DL delay 0 days
Provider 1 delay 0 days
Provider 2 delay two hours

1. HDTV episode is released on provider 2.
2. One day passes and HDTV is released on provider 1.
3. Two more days pass and there is no WEBDL
4. HDTV is downloaded from provider 1

**Comment by rssw** [comment]
So, the delay is measured from the first sighting  Delay from airdate is an alternative, but first sighting is a good start.  May need to add logic to ignore any sightings before the listed airdate + some reasonable delay for encoding to screen out fakes.

Case A OK
Case B OK
Case C OK

Case D
1. HDTV is released on provider 1
2. Two days and 23 hours later, WEB-DL is released on provider 2
3. One hour later HDTV is downloaded from provider 1.

Unlikely, but to be considered.  So a tickbox to select preference between provider or quality in the case of a stalemate.

Case E (prefer quality)
1. HDTV is released on provider 1
2. 2 days and 23 hours pass
3. WEB-DL is released on provider 2
4. 1 hour later WEB-DL is nabbed from provider 2.

Case F (prefer provider)
1. HDTV is released on provider 1
2. 2 days and 23 hours pass
3. WEB-DL is released on provider 2
4. 2 hours later HDTV is nabbed from provider 1.

So I'm thinking that the preferred delay should always be allowed to expire before moving on to it's fallback.  Once a WEB-DL has been spotted, the 2 hours preference on provider starts counting, and even though the quality delay expires in the meantime, it's alternative isn't considered until the 2 hours are up.

Obviously if NO WEB-DL is spotted by the time the quality timer expires, it doesn't impede the failover.  So Case F would become:

Case G (prefer provider)
1. HDTV is released on provider 1
2. 2 days and 23 hours pass
3. Nothing happens.
4. 1 hour later HDTV is nabbed from provider 1.

**Comment by deed02392** [comment]
Just would like to add my support for wait times specifically. But I would also like to be able to configure a minimum time before archive quality is downloaded, after initial is downloaded, to ensure that I keep a copy of the initial quality download for some time first. This is beneficial mainly for symlink users.
