### ISSUE TITLE
Not all SG generated files get renamed with the episode

### ISSUE THREAD

**Issue by ressu** [SickGear/SickGear#170]
SickGear doesn't rename all the files along with the episode. There are files left behind that are generated by SickGear, while some other files generated by SickGear get renamed in the batch.

Reproduced with:
BRANCH: (master) / COMMIT: (4bb52ead46133deb04fd6e6ebf50df1b969a98bd) 

Steps to reproduce:
1) Go to SickGear Post Processing settings and under metadata, turn on xbmc 12+ metadata and select Show metadata and episode thumbnails
2) Add a show to SickGear (for the purpose of this issue, it doesn't matter which one)
3) In the show directory create a file S01E01.avi
4) Run rescan for the show (you should notice that SG creates an .nfo and a thumb file for the episode)
5) select the preview rename from webui
6) select S01E01 for renaming and complete the rename.

What happens:
The S01E01.avi is renamed according to file naming rules. The S01E01.nfo is renamed to follow the same convention, but the S01E01-thumb.jpg is left behind.

What is expected to happen:
Either both the .nfo and the -thumb file are left behind or both of them get renamed.

**Comment by JackDandy** [comment]
#171
