### ISSUE TITLE
API call to episode, episode argument not found

### ISSUE THREAD

**Issue by HazCod** [SickGear/SickGear#204]
`
/api/<API>/?cmd=episode&episode=4079947
`
Returns: error_msg": "int() argument must be a string or a number, not 'NoneType'"

Running latest stable.

**Comment by HazCod** [comment]
Disregard.

**Comment by HazCod** [comment]
I'm reopening this one up, I originally got this error because I didn't supply all arguments.
Some more appropriate error message would be in place.

**Comment by CtrlAltDefeat94** [comment]
https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues

**Comment by adam111316** [comment]
See above.

Also could you clarify what your issue is? Is the api command working now? Is your issue now that there is insufficient logging information when a required api parameter is missing?

**Comment by HazCod** [comment]
I point is insufficient/incorrect information, it looked like the episode argument could not be found while the real problem was that I didn't supply the other arguments.

**Comment by JackDandy** [comment]
**/api/builder** click the help checkbox, then a function, then go.
