### ISSUE TITLE
Missing TV channel logos (Swedish) + Vimeo

### ISSUE THREAD

**Issue by Malmis** [SickGear/SickGear#208]
There are some missing logo's for a few tv channels.

Vimeo
TV4 (Swedish)
Kanal 5 (Swedish)
SVT (Swedish)
![tv4](https://cloud.githubusercontent.com/assets/1018037/6284098/1d0893f6-b8ed-11e4-8eef-b939a44c5935.png)
![kanal 5](https://cloud.githubusercontent.com/assets/1018037/6284099/1d0b8c82-b8ed-11e4-9c7a-ee5be0da0b80.png)
![vimeo](https://cloud.githubusercontent.com/assets/1018037/6284101/1d0d669c-b8ed-11e4-9230-27ceca61fb86.png)
![svt](https://cloud.githubusercontent.com/assets/1018037/6284100/1d0d559e-b8ed-11e4-9f76-e224140d9a52.png)

**Comment by Malmis** [comment]
Well.. there is a few others also..

Kanal 9 (Swedish)
Sjuan (Swedish)
TV3 (Swedish)
TV6 (Swedish)
TV8 (Swedish)
TV10 (Swedish)

![kanal 9](https://cloud.githubusercontent.com/assets/1018037/6284219/1c2d67da-b8ee-11e4-8723-dfa81c39b7ba.png)
![sjuan](https://cloud.githubusercontent.com/assets/1018037/6284216/1c2c255a-b8ee-11e4-926b-9bfa7609c992.png)
![tv3](https://cloud.githubusercontent.com/assets/1018037/6284215/1c2ba0b2-b8ee-11e4-9614-7edeb5e2f666.png)
![tv6](https://cloud.githubusercontent.com/assets/1018037/6284218/1c2c9a08-b8ee-11e4-9273-54361d720ce6.png)
![tv8](https://cloud.githubusercontent.com/assets/1018037/6284217/1c2c7960-b8ee-11e4-9f5d-21346a60d9b3.png)
![tv10](https://cloud.githubusercontent.com/assets/1018037/6284220/1c2e3f66-b8ee-11e4-8a36-d3369246d3ab.png)

**Comment by adam111316** [comment]
https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Submit-Logos

**Comment by JackDandy** [comment]
These channels are **NOT** English channels.
