### ISSUE TITLE
Cannot open show page after dc95006

### ISSUE THREAD

**Issue by ItsMeMike** [SickGear/SickGear#238]
SG displays this error on a blank page, when opening any show detail page.
Happens after updating to commit dc95006.
Before opening any show page, I did select some Kodi metadata, after finding out this error, I unselected those all again. However that didn't make a difference.
I also clicked on the Kodi Notification checkbox, but didn't save afterwards.

Error

global name 'haveKODI' is not defined

Traceback

Traceback (most recent call last): 
File "D:\SickGear\tornado\web.py", line 1341, in _execute result = yield result 
File "D:\SickGear\tornado\gen.py", line 642, in run value = future.result() 
File "D:\SickGear\tornado\concurrent.py", line 110, in result raise_exc_info(self._exc_info) 
File "D:\SickGear\tornado\gen.py", line 174, in wrapper result = func(*args, **kwargs) 
File "D:\SickGear\sickbeard\webserve.py", line 295, in get result = method(**kwargss) 
File "D:\SickGear\sickbeard\webserve.py", line 1053, in displayShow showObj.name.encode('utf-8')), 'requires': haveKODI}) 
NameError: global name 'haveKODI' is not defined 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/displayShow?show=281485
query_arguments: {'show': ['281485']}
_start_time: 1424888034.86
headers: {'Accept-Language': 'nl,en-US;q=0.8,en;q=0.6,ja;q=0.4,de;q=0.2', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36', 'Host': 'dezeisvanmike:8081', 'Referer': 'http://dezeisvanmike:8081/episodeView/', 'Cookie': 'advanced_toggle_checked=0; wanted_view2=details; manage_view2=list; GUID=6e1YZSiiLyjKy58ZR5rN; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=suggestions; late_view2=list; user="2|1:0|10:1424888031|4:user|60:ZlpSOVR5a2VRUVdoNVNXSnUrVytucmhRV3dTZloweUN2RnJUazlDUEo5ST0=|be6606691e98c809ac45eb82bdf90bf03d971c20d7819b663015e409c26206d4"'}
host: dezeisvanmike:8081
version: HTTP/1.1
arguments: {'show': '281485'}
_finish_time: None
query: show=281485
path: /home/displayShow
_cookies: Set-Cookie: GUID=6e1YZSiiLyjKy58ZR5rN Set-Cookie: advanced_toggle_checked=0 Set-Cookie: late_view2=list Set-Cookie: manage_view2=list Set-Cookie: plushContainerWidth=100%25 Set-Cookie: plushMultiOps=1 Set-Cookie: plushNoTopMenu=0 Set-Cookie: snatched_view2=list Set-Cookie: soon_view2=thumbs Set-Cookie: suggestions_charts_menu_selected=suggestions Set-Cookie: user="2|1:0|10:1424888031|4:user|60:ZlpSOVR5a2VRUVdoNVNXSnUrVytucmhRV3dTZloweUN2RnJUazlDUEo5ST0=|be6606691e98c809ac45eb82bdf90bf03d971c20d7819b663015e409c26206d4" Set-Cookie: wanted_view2=details
method: GET
remote_ip: 192.168.1.114

**Comment by JackDandy** [comment]
The only i can repro here is that the Update Kodi menu items fails.

**Comment by ItsMeMike** [comment]
Fixed!
