### ISSUE TITLE
Passwords include stars when appended to on configuration pages

### ISSUE THREAD

**Issue by adam111316** [SickGear/SickGear#241]
Branch / commit: develop 9f55f91c

1. Set a password, eg set the web interface password to 'testing'
2. The web interface will show "*******"
3. Append '123' to the end of the stars currently in the password field and save
4. Check config.ini

Expected result: password becomes "testing123"
Actual result: password becomes "******123"

Possible fixes:
- As soon as the password fields are edited, the field should clear itself

**Comment by JackDandy** [comment]
This is not a bug because the normal to add text after asterisks, normally one would select the field and enter a new password. Therefore, this proposal in an enhancement.
