### ISSUE TITLE
Fix arch install guide

### ISSUE THREAD

**Issue by adam111316** [SickGear/SickGear#254]
https://github.com/SickGear/SickGear/wiki/Installation-Instructions#arch

Bad references to folders and files that don't exist, unclear references to 'user1:group1' etc

**Comment by alazare619** [comment]
user 1 and group 1 are defining the user you wish sick to run as if you want sickgear:sickgear you must create user sickgear and group sickget folders are using command line switches so they do exist.

**Comment by adam111316** [comment]
oh I know, I think it could just be worded a bit better

**Comment by JackDandy** [comment]
done.
