### ISSUE TITLE
Mass Update - Subtitles not selectable

### ISSUE THREAD

**Issue by sendas** [SickGear/SickGear#260]
Hi

When I try to mass update all the shows that I have, so I can add subtitles to all, the option is not selectable... :( 

I can edit each show individually but that would take ages...

What can I do ?

I'm using the latest version of sickgear

Pedro
![gear](https://cloud.githubusercontent.com/assets/10220908/6577398/a96a2d0e-c735-11e4-890c-6acb109f90f2.jpg)

**Comment by JackDandy** [comment]
[see How-to-Report-Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

**Comment by sendas** [comment]
Update:


Version:	BRANCH: (master) / COMMIT: (836c378e4ee000f644e6b35fcec37bbc44b26089) 
This is BETA software.
Config file:	/home/pi/gear/config.ini
Database file:	/home/pi/gear/sickbeard.db
Cache Dir:	/home/pi/gear/cache
Arguments:	['-d', '--nolaunch']
Web Root:	
Python Version:	2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]

The error is still the same....

**Comment by Supremicus** [comment]
Click the edit checkbox on top left, goto bottom and select edit all, enable subtitles.
Those checkboxes are to search for subtitles nothing more.

**Comment by sendas** [comment]
thank you!
