### ISSUE TITLE
Can't browse dirs containing accented characters.

### ISSUE THREAD

**Issue by belima** [SickGear/SickGear#343]
Python Version: 2.7.9
Operating System: Windows 8.1
Locale: ('pt_BR', 'cp1252')
Branch: master
Commit: SickGear/SickGear@7e2a8f7
There's nothing related to this issue in sickrage.log

Hello everyone!
When trying to configure SickGear (or SickRage), I can't browse directories with accented characters in their names.
It's a problem to me since my user folder has an accented character in it's name and both my downloads and TV Shows folder are inside my user dir.

e.g. When adding a New Show Root Directory, I can select "C:\", then "Users", but, when I click "Bê" (that's my user folder) nothing happens at all.

I tried with different folders and the problem is def related to the accented chars..

I don't think it's some system related problem since I used Pistachito's SickBeard for a long time and never had problems concerning accented chars in folder names.

Hope you guys can help me ;)

**Comment by JackDandy** [comment]
Hello,

Please use a path without accented characters, SG is targeted for English and therefore ASCII.

**Comment by belima** [comment]
I would if I knew how to!

Thank you!
