### ISSUE TITLE
Shows with season suffix get processed wrong

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [SickGear/SickGear#360]
BRANCH: (develop) / COMMIT: (0ccd58bf4bbaba975a7d8f5397b4e603a224ba54) 

When Anime shows have a 2nd season with a suffix after the showname(example: Love Live! being season 1 and Love Live! S2 being season 2), SickGear will not know the difference between the two and process Love Live S2 episodes as season 1 rather than season 2

Reproduction steps:
- Add show with a 2nd season(or more) with different shownames per season
- Download an episode of one of the seasons with a suffix after the showname
- Postprocess the downloaded episode

LOG:
<pre>Found release name [FFF] Love Live! S2 - 02 [DD19054D]
No release found in snatch history
Destination folder for this episode is X:\test\Love Live!\Season 01
Copied file from X:\test\PPing\[FFF] Love Live! S2 - 02 [DD19054D].mkv
.. to X:\test\Love Live!\Season 01\Love Live! - S01E02 - Let's Start Becoming Idols!.mkv
Successfully processed [FFF] Love Live! S2 - 02 [DD19054D</pre>

The same issue persists when searching for episodes.

Reproduction steps:
- Add show with a 2nd season(or more) with different shownames per season
- Search for an episode

Log:
https://gist.github.com/CtrlAltDefeat94/81956a7d2d757da7b7c8

Additional info:
I used Love Live! as show and episode 007 (S01E07) for testing

**Comment by CtrlAltDefeat94** [comment]
The same issue persists when searching for episodes.

Reproduction steps:
- Add show with a 2nd season(or more) with different shownames per season
- Search for an episode

Log:
https://gist.github.com/CtrlAltDefeat94/81956a7d2d757da7b7c8

Additional info:
I used Love Live! as show and episode 007 (S01E07) for testing

**Comment by adam111316** [comment]
episode filename: love live! s2
namecache: love live s2

**Comment by adam111316** [comment]
Probably ^
