### ISSUE TITLE
Tweak scene exceptions from name function

### ISSUE THREAD

**Issue by adam111316** [SickGear/SickGear#361]
https://github.com/SickGear/SickGear/blob/0a7c594a6fe415ba53bf1b82f10926a49a78f438/sickbeard/scene_exceptions.py#L126

How about instead of hitting the db every time, we just use the name cache?

TODO
- [x] Examine namecache / exceptionscache code
- [x] Attempt to consolidate functions where possible
- [x] Time fetching a name/season tuple before code changes
- [x] Time fetching a name/season tuple after code changes

**Comment by adam111316** [comment]
Actually, seems the name cache only holds names and tvdbids

**Comment by JackDandy** [comment]
wrap functions that call the function under investigation in order to be able to prove that an actual saving of time would be achieved or that by showing that some other issue occurs, then all good, however, to do such a change without a proof is asking for trouble, imo.
