### ISSUE TITLE
Error updating on Raspberry Pi

### ISSUE THREAD

**Issue by sendas** [SickGear/SickGear#366]
My actual version:

Version:	BRANCH: (master) / COMMIT: (7e2a8f7b6642dc6f6cf45b1f18f9b3f78a89db40) 
This is BETA software.
Config file:	/home/pi/.sickgear/config.ini
Database file:	/home/pi/.sickgear/sickbeard.db
Cache Dir:	/home/pi/.sickgear/cache
Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickbeard.pid', '--datadir=/home/pi/.sickgear/']
Web Root:	
Python Version:	2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]

When I try to update I get this error:

2015-05-18 21:38:10 ERROR    TORNADO :: git pull -f origin master returned : From https://github.com/SickGear/SickGear
AAUpdating 7e2a8f7..3dc43aa
AAAborting
AA	lib/requests/packages/chardet/mbcss
AA	lib/requests/packages/chardet/latin1prober.py
AA	lib/requests/packages/chardet/jpcntx.py
AA	lib/requests/packages/chardet/chardetect.py
AA	lib/requests/packages/chardet/__init__.py
AA	lib/requests/models.py
AA	lib/requests/exceptions.py
AA	lib/requests/cookies.py
AA	lib/requests/compat.py
AA	lib/requests/cacert.pem
AA	lib/requests/auth.py
AA	lib/requests/api.py
AA	lib/requests/adapters.py
AA	lib/requests/__init__.py
AA	lib/chardet/utf8prober.py
AA	lib/chardet/universaldetector.py
AA	lib/chardet/sjisprober.py
AA	lib/chardet/sbcsgroupprober.py
AA	lib/chardet/sbcharsetprober.py
AA	lib/chardet/mbcssm.py
AA	lib/chardet/mbcsgroupprober.py
AA	lib/chardet/mbcharsetprober.py
AA	lib/chardet/latin1prober.py
AA	lib/chardet/langthaimodel.py
AA	lib/chardet/langhungarianmodel.py
AA	lib/chardet/langhebrewmodel.py
AA	lib/chardet/langgreekmodel.py
AA	lib/chardet/langcyrillicmodel.py
AA	lib/chardet/langbulgarianmodel.py
AA	lib/chardet/jpcntx.py
AA	lib/chardet/jisfreq.py
AA	lib/chardet/hebrewprober.py
AA	lib/chardet/gb2312prober.py
AA	lib/chardet/gb2312freq.py
AA	lib/chardet/euctwprober.py
AA	lib/chardet/euctwfreq.py
AA	lib/chardet/euckrprober.py
AA	lib/chardet/euckrfreq.py
AA	lib/chardet/eucjpprober.py
AA	lib/chardet/escsm.py
AA	lib/chardet/escprober.py
AA	lib/chardet/cp949prober.py
AA	lib/chardet/constants.py
AA	lib/chardet/compat.py
AA	lib/chardet/codingstatemachine.py
AA	lib/chardet/charsetprober.py
AA	lib/chardet/charsetgroupprober.py
AA	lib/chardet/chardistribution.py
AA	lib/chardet/chardetect.py
AA	lib/chardet/big5prober.py
AA	lib/chardet/big5freq.py
AA	lib/chardet/__init__.py
AA	lib/certifi/cacert.pem
AA	lib/cachecontrol/wrapper.py
AA	lib/cachecontrol/session.py
AA	lib/cachecontrol/serialize.py
AA	lib/cachecontrol/patch_requests.py
AA	lib/cachecontrol/controller.py
AA	lib/cachecontrol/compat.py
AA	lib/cachecontrol/caches/redis_cache.py
AA	lib/cachecontrol/caches/file_cache.py
AA	lib/cachecontrol/cache.py
AA	lib/cachecontrol/adapter.py
AA	lib/cachecontrol/__init__.py
AA	gui/slick/js/config.js
AA	gui/slick/interfaces/default/viewlogs.tmpl
AA	gui/slick/interfaces/default/testRename.tmpl
AA	gui/slick/interfaces/default/restart.tmpl
AA	gui/slick/interfaces/default/manage_torrents.tmpl
AA	gui/slick/interfaces/default/manage_subtitleMissed.tmpl
AA	gui/slick/interfaces/default/manage_massEdit.tmpl
AA	gui/slick/interfaces/default/manage_manageSearches.tmpl
AA	gui/slick/interfaces/default/manage_failedDownloads.tmpl
AA	gui/slick/interfaces/default/manage_episodeStatuses.tmpl
AA	gui/slick/interfaces/default/manage_backlogOverview.tmpl
AA	gui/slick/interfaces/default/manage.tmpl
AA	gui/slick/interfaces/default/inc_top.tmpl
AA	gui/slick/interfaces/default/inc_qualityChooser.tmpl
AA	gui/slick/interfaces/default/inc_bottom.tmpl
AA	gui/slick/interfaces/default/inc_addShowOptions.tmpl
AA	gui/slick/interfaces/default/home_trendingShows.tmpl
AA	gui/slick/interfaces/default/home_recommendedShows.tmpl
AA	gui/slick/interfaces/default/home_postprocess.tmpl
AA	gui/slick/interfaces/default/home_newShow.tmpl
AA	gui/slick/interfaces/default/home_addShows.tmpl
AA	gui/slick/interfaces/default/home_addExistingShow.tmpl
AA	gui/slick/interfaces/default/home.tmpl
AA	gui/slick/interfaces/default/history.tmpl
AA	gui/slick/interfaces/default/genericMessage.tmpl
AA	gui/slick/interfaces/default/errorlogs.tmpl
AA	gui/slick/interfaces/default/episodeView.tmpl
AA	gui/slick/interfaces/default/editShow.tmpl
AA	gui/slick/interfaces/default/displayShow.tmpl
AA	gui/slick/interfaces/default/config_subtitles.tmpl
AA	gui/slick/interfaces/default/config_providers.tmpl
AA	gui/slick/interfaces/default/config_postProcessing.tmpl
AA	gui/slick/interfaces/default/config_notifications.tmpl
AA	gui/slick/interfaces/default/config_general.tmpl
AA	gui/slick/interfaces/default/config_anime.tmpl
AA	gui/slick/interfaces/default/config.tmpl
AA	gui/slick/interfaces/default/cache.tmpl
AA	gui/slick/interfaces/default/apiBuilder.tmpl
AA	gui/slick/interfaces/default/404.tmpl
AA	gui/slick/images/providers/thepiratebay.png
AA	gui/slick/images/providers/scc.png
AA	gui/slick/images/providers/kat.png
AA	gui/slick/images/providers/animenzb.gif
AA	gui/slick/css/style.css
AA	HACKS.txt
AA	CHANGES.md
AA	.travis.yml
AAerror: Your local changes to the following files would be overwritten by merge:
AA * branch            master     -> FETCH_HEAD
2015-05-18 21:36:51 INFO     RECENT-SEARCH :: Updating provider caches with recent upload data
2015-05-18 21:36:50 INFO     RECENT-SEARCH :: No unaired episodes marked wanted
2015-05-18 21:33:37 ERROR    CHECKVERSION :: git pull -f origin master returned : From https://github.com/SickGear/SickGear
AAUpdating 7e2a8f7..3dc43aa

**Comment by adam111316** [comment]
drop down into commandline in your sickgear folder and run:
```
git reset --hard origin/master
```

**Comment by JackDandy** [comment]
added to faq: (fetch_head-error)[https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#fetch_head-error]
