### ISSUE TITLE
The Pirate Bay

### ISSUE THREAD

**Issue by sendas** [SickGear/SickGear#379]
I found this in the logs: 

2015-06-02 18:48:24 WARNING  PROPER-SEARCH :: [The Pirate Bay] :: Connection error ('Connection aborted.', error(104, 'Connection reset by peer')) while loading URL https://thepiratebay.se/search/Silicon.Valley.S02E08%7C2x08.PROPER%7CREPACK/0/7/200

Is something wrong ?

thanks

Version:	BRANCH: (master) / COMMIT: (24b2938c9c45cb34285687a1d7d52bd90936cd5d) 
This is BETA software.
Config file:	/home/pi/.sickgear/config.ini
Database file:	/home/pi/.sickgear/sickbeard.db
Cache Dir:	/home/pi/.sickgear/cache
Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickbeard.pid', '--datadir=/home/pi/.sickgear/']
Web Root:	
Python Version:	2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]

**Comment by JackDandy** [comment]
Yeah, this site is the issue.

**Comment by sendas** [comment]
I've done that... Is there anything I can do to fix it ?

**Comment by JackDandy** [comment]
Yes if you know what you are doing, go into the provider and change its URL, note this will will be changed soon, so be prepared. If what I say here means nothing to you, then ignore this text and wait for a fix (which I have completed already and is currently in testing)

**Comment by JackDandy** [comment]
The source is back up again now.
