### ISSUE TITLE
Using mass-update shows with "anime" dropdown set to "enable" breaks the "edit" button on anime

### ISSUE THREAD

**Issue by Rawh** [SickGear/SickGear#467]
# BRANCH: (develop) / COMMIT: (1333b9234483c26e4574bbac194fe1e2991d2b3f) 

Expectation | Result
------------ | -------------
Wanted to mass-update all shows to mark them as anime and edit all the shows to put in the white/blacklist, so it would download the releases I want. | White page with an error, including stacktrace, when clicking on "edit" with(in) a show, after using mass update.

Steps:
1. Click on Manage -> Mass Update 
2. Click on edit (top left) to select everything. 
3. Click on edit selected (bottom left) 
4. Scroll down to "Show is anime" and put it to "enable". 
5. Go back to the show overview, click on an anime title there, click on "edit" inside and get the error.

Logs: https://gist.github.com/Rawh/893d978345f8d8bfd0d6
Error page text: https://gist.github.com/Rawh/48411761a97460355b1f

I am able to do what I want, but not massively. So right now I update it per show -> Edit, tick the "show as anime box", save, click edit again and fill up the white/blacklist.

It seems the mass-update part is not doing something the "save" button does (when editing just one show).

**Comment by Rawh** [comment]
Sorry about the markup spam, trying to figure out how to make the reports a bit readable :)

**Comment by JackDandy** [comment]
#468
