### ISSUE TITLE
Search Provider TokyoToshokan issues; Search results can't be parsed, gives an error.

### ISSUE THREAD

**Issue by Rawh** [SickGear/SickGear#469]
# BRANCH: (develop) / COMMIT: (1121b0c5a7c5be2cf6858c0e6c06a1abbe0e4eeb) 

Expectation | Result
------------ | -------------
Added a new show (Gundam Reconguista in G) and wanted to get the first episode, to see which groups were available for grabbing. SG queried the torrent Search Provider TokyoToshokan (TT), TT reported an error in with the returned search results  | Download continued from a different torrent Search Provider.

Steps:
1. Make sure you have Tokyo Toshokan (TT) configured as a Search Provider
  (Configure -> Search Provider -> Provider Priorities tab,)
  (Select at least 2 and have Tokyo Toshokan in the list.)
2. Add new Anime show (I used Gundam Reconguista in G)
3. Click on "search" icon for the first episode
4. Click on the logs (+ use "debug" in the dropdown)
5. Click refresh a few times till you see the search for TT comes up.
6. Notice the trackback error.

Logs: https://gist.github.com/Rawh/ce198fe02017e9b46d6e

Downloading did continue as it found a good Torrent from a different Search Provider. Although I would love to also have TT in the list as it is one of my favorite anime sources!

**Comment by JackDandy** [comment]
#470
