### ISSUE TITLE
Wanted to download three episodes; SG decided to download the entire batch instead (overwriting earlier downloaded eps)

### ISSUE THREAD

**Issue by Rawh** [SickGear/SickGear#471]
# BRANCH: (develop) / COMMIT: (1121b0c5a7c5be2cf6858c0e6c06a1abbe0e4eeb) 

Expectation | Result
------------ | -------------
Added a new show (Gundam Reconguista in G) and wanted to get the second, third and fourth episodes (I have put HorribleSubs on the blacklist, because the first ep was quite badly translated) | Instead of downloading three more eps it decided to download an entire season batch, marking everything as snatched.

Steps:
1. Make sure you have Horriblesubs on the blacklist
  (Click the anime on the "show list" page.)
  (Click Edit -> Go to the bottom of the page -> Enter "Horriblesubs" and click on the "Blacklist button".)
  (Save your results.)
2. Select the second, third and fourth ep, select "Watched" at the top, followed by "Go".
3. Click on the logs (+ use "debug" in the dropdown)
4. Notice how the logs use your Search Indexers, and in my case select the batch (instead of three episodes seperatly).

Logs: [**confusing log includes a fixed issue, get another**]

**Comment by CtrlAltDefeat94** [comment]
By any chance, do you have the Season search mode set to Season packs only with Season search fallback enabled? (Provider options)

**Comment by adam111316** [comment]
If what @CtrlAltDefeat94 says is applicable, then it is normal behavior.
