### ISSUE TITLE
NZB search doesn't find anime shows, while they are present.

### ISSUE THREAD

**Issue by Rawh** [SickGear/SickGear#472]
BRANCH: (Develop + pull/470/feature/FixTokyoParsing) / COMMIT: (b7cf3fb1e8acb29bff50a29aeb6711c4caf7b15f) 

Expectation | Result
------------ | -------------
Noticed a few shows weren't downloaded yet, so I did a manual search. Expected the file to be found, downloaded and added to my show overview.  | Instead the logs show it can't any find the show by the used search parameters / strings. I have three NZB Search Indexers specified.

Steps:
1. Click on History.
2. Click on magnifying glass of the shows that are red.
3. Watch the logs / Watch the notification pop-up tell you it doesn't get downloaded.

Logs: [**log removed - not needed in this case to repro at sbi, dog, or 6b**]
Snapshot of the show being present on DOGnzb: http://i.imgur.com/gs0LywX.jpg

Might it have something to do with what we search on? Looks to me it can't find '002' but if it used '02' it would've been found.

**Comment by adam111316** [comment]
Please provide logs.

**Comment by adam111316** [comment]
09:21:35 DEBUG::MANUAL-295224 :: [sixbox] :: Search url: https://6box.me/api?apikey=XXXX&maxage=500&cat=5040%2C5070&q=God.Eater.02&limit=100&attrs=rageid&offset=0&t=tvsearch

09:21:38 INFO::MANUAL-295224 :: Downloading [HorribleSubs].GOD.EATER.-.02.[1080p] from sixbox

We search using 02, works fine for me.
