### ISSUE TITLE
New episodes of existing show added as 'skipped' - have I missed a setting?

### ISSUE THREAD

**Issue by jillmess** [SickGear/SickGear#479]
It seems that when a new episode for an existing show is slow in being added to theTVDB and is therefore not picked up by SickGear until after the air time/date it is being added as 'skipped' rather than 'wanted'.  Is this because of a setting I have missed somewhere or a bug?

**Comment by JackDandy** [comment]
The initial status of missing episodes are set to skipped by default. This initial state can set by the very first option on the third step when adding a show. No, this is not a bug.

**Comment by jillmess** [comment]
I understand the reasoning for not having 'wanted' as the default when adding new shows, but the situation I am interested in is for a show that already exists.  I have changed my default setting to 'wanted' but this apparently does not change the behaviour for *existing shows* when new episodes are added (to theTVDB & via the nightly update to SickGear) after the air date has passed.

For example I have just discovered that the first 4 episodes of Season 2 of The Librarians (2014) have been 'skipped'.  I assume this is because these episodes were added to theTVDB after their air date, and that when I originally added the show I had the default behaviour for the initial status of missing episodes set to 'skipped'?  If so, how can I now change this behaviour so that these would be added as 'wanted'?

**Comment by JackDandy** [comment]
You can change the statuses very easily with Manage/Episode Status Management.

**Comment by JackDandy** [comment]
Nice, you are now a Jedi user by using **all** available statuses fully, including the "Ignored" status.  Your use of the status is finally complete with correct values so that you can now see a properly "Skipped" episode and an "Ignored" episode.  To set episodes that are in the past as "Wanted" would be bad, and is not the original design that promotes good practices of using all statuses properly.
