### ISSUE TITLE
Add IMDB watchlist support for adding new shows

### ISSUE THREAD

**Issue by p0psicles** [SickGear/SickGear#481]
I'd like to request for the feature to use your IMDB watchlist, for auto-magically add new shows.

The idea is a user can use his IMDB watchlist to add shows he's interested in.

The following requirements are 
Must Have:
- The solution should provide the option to the user to configure a watchlist, using the csv link, like it's implemented in CP.
- The solution should provide the option to the use to configure more then 1 watchlist
- The solution should provide the option to the user to use his default options for adding shows.
   * This means shows are added using the default configured: location, indexer, etc..
- The solution should provide the option to override options specific for auto adding from IMDB
- The solution should provide the option to choose an interval for scraping and processing the watchlist

Nice to have:
- The solution could provide users (a user friendly) inside into the shows in the watchlist, that could not be added.
- The solution could provide users the option to remove shows from the imdb watchlist, when the show is removed from SG. (preferable with an additional prompt). But then need to think how to handle multiple configured imdb watchlists.
- The solution could provide the option to the user to enable a specific notification when a show is successfully added through an imdb watchlist.

Old commits that can be reused for pats of code:
9eb9400c7400019e522aeaceadd0733427b2c821
7165df7405ffb7c9601d78f640808d9d8bcaff2c
And the revert: 6c8d72b9c18ad6200c9cabe9bd5c9842cf499ce5

If anyone has any ideas for additional functional/non-functional requirements, be my guest!

**Comment by JackDandy** [comment]
This idea was not followed up on, therefore, closing.

**Comment by p0psicles** [comment]
well I mentioned this was a "longer term" thing. I also didn't create a thorough requirements list, just for show. But okay. I'll just continue this as a private project.

**Comment by JackDandy** [comment]
Yup, I know, and I get it @p0psicles  No worries, we can open this again when you are ready with tangible progress :)

**Comment by p0psicles** [comment]
i've started on this. I have chosen to add a new table named "imdb_watchlist" to sickbeard.db. To keep track of the shows that have been (attempted) for automatically adding, through one of the watchlists.

Create statement:
CREATE TABLE "imdb_watchlist" (
	`imdb_id`	TEXT,
	`indexer`	INTEGER,
	`indexer_id`	INTEGER,
	`watchlist_id`	TEXT,
	`show_id`	NUMERIC,
	`last_added`	NUMERIC,
	PRIMARY KEY(imdb_id)
)
Going to reuse as much as possible of traktChecker.py. But with a new page below Manage: http://home.headshots.nl/sickgear/manage/imdbWatchlists/ witch a list of IMDB shows that could not be mapped to an indexer show. I'll create a link for that show, that will navigate the user to the Add Show page.

**Comment by p0psicles** [comment]
Please note! I've upped the db version to 20004!
MAX_DB_VERSION = 20004

**Comment by JackDandy** [comment]
Looking good, have a nice Christmas :)
