### ISSUE TITLE
Anime Proper no results

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [SickGear/SickGear#486]
BRANCH: (master) / COMMIT: (1e6c1618871f8cb5781d35114f21d249c270245f) 

When running a proper search for anime episodes I get no (positive) results, even though I know there are propers available.

After digging into the log(see bottom of this post) I noticed that SG looks for results with "proper" or "repack"  in the it. This will never work as in the magical world of anime "V" followed by a number is used, rather than the word proper or repack.

Reproduction steps:
- Have an anime show added to SG
- Have Nyaa(or any other anime provider) enabled
- Start a Proper search(or wait for it to kick in)

Log:
2015-08-18 21:56:32 DB       PROPER-SEARCH :: [NyaaTorrents] :: cache.db: SELECT * FROM provider_cache WHERE name LIKE '%.PROPER.%' OR name LIKE '%.REPACK.%' AND provider = ? AND time >= 1439754992 with args ['nyaatorrents']

**Comment by adam111316** [comment]
@CtrlAltDefeat94 plz post that log that you posted ages ago when you said it didn't work hue

**Comment by JackDandy** [comment]
#549
