### ISSUE TITLE
Add ability to add v number to renaming pattern (anime)

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [SickGear/SickGear#487]
Currently SG is able to detect what version a release is, and by my knowledge also stores this in the database, but it is currently not possible to add this to the filename(s)(in the naming pattern).

As there is no way of checking what version a file is at this point, it is quite difficult to determine what version a file is(you'd have to go through snatch history or look in the database yourself).
When readding a show to a (clean) database it'll currently result in SG thinking all files are v1 as there is no sign of this being not true as there is no snatch history to check from and it's not listed in the filename.

This is why I'd like to have the ability added to add the v number to the (re)naming pattern.

**Comment by adam111316** [comment]
#548
