### ISSUE TITLE
Postprocessing keeps polling indexers on unknown matches

### ISSUE THREAD

**Issue by ressu** [SickGear/SickGear#495]
This was reproduced with
BRANCH: (develop) / COMMIT: (80527a2f4393c3048d0a0ecd91f7ca8911187d9d) 

There is a problem with file parsing that causes a lot of queries to be made on indexers. As simple way to reproduce this is to create a season pack with filenames not containing the series name. For example:

    Miss.Fishers.Murder.Mysteries.S02.720p.BluRay.x264-PFa/
    Miss.Fishers.Murder.Mysteries.S02.720p.BluRay.x264-PFa/pfa-mfmm.s02e01.720p.mkv
    Miss.Fishers.Murder.Mysteries.S02.720p.BluRay.x264-PFa/pfa-mfmm.s02e02.720p.mkv

This will cause the PP to query indexer for the filename:

    DEBUG    POSTPROCESSER :: Using ALL regexes
    DEBUG    POSTPROCESSER :: Trying to find pfa mfmm on theTVDB
    DEBUG    POSTPROCESSER :: Trying to find pfa mfmm on TVRage
    DEBUG    POSTPROCESSER :: Using ALL regexes
    DEBUG    POSTPROCESSER :: Parsed /srv/videos/incoming/downloaded/Sick-TV/Miss.Fishers.Murder.Mysteries.S02.720p.BluRay.x264-PFa into Miss Fishers Murder Mysteries - S2 [GROUP: PFa] [ABD: False] [ANIME: False] [whichReg: ['season_only']]
    DB       POSTPROCESSER :: sickbeard.db: SELECT * FROM tv_episodes WHERE release_name = ? with args [u'/srv/videos/incoming/downloaded/Sick-TV/Miss.Fishers.Murder.Mysteries.S02.720p.BluRay.x264-PFa']
    DB       POSTPROCESSER :: sickbeard.db: SELECT * FROM tv_episodes WHERE release_name = ? with args [u'pfa-mfmm.s02e12.720p']
    DEBUG    POSTPROCESSER :: Found a video, but that release for "Miss Fisher's Murder Mysteries" was already processed, skipping: pfa-mfmm.s02e12.720p.mkv

The log shows 2 queries being sent out. This is repeated with all the files in the directory.

**Comment by adam111316** [comment]
I say we remove this indexer polling completely, we should have the show names / scene exceptions all stored already. 

If we didn't have the information already, the show would not have snatched. If the show is one that was manually downloaded and it isn't recognized automatically, I don't think it would be matched from a indexer search....

**Comment by adam111316** [comment]
@JackDandy thoughts?

**Comment by ressu** [comment]
@adam111316 Removing indexer polling was in my mind with PR #493 but it turns out that there is no separate method for fetching data from the database and from the index. I would have fixed that pull request to work both ways, but after a bit of searching, I was unable to find the other code paths that should be polling the indexers.

I ended up giving up due to lack of time to investigate further.

**Comment by adam111316** [comment]
I didn't think anything was wrong with that PR...(Didn't take a look too closely but still looked fine..)

**Comment by ressu** [comment]
Turns out the get_show method fetches data from the indexer as well as from the database. And is apparently the main method for data refresh. It's quite perverse in a way, but that's legacy code for you...

**Comment by adam111316** [comment]
There's only one call to helpers.getshow() and that's inside parser.py. The data refresh doesn't call that method.

**Comment by ressu** [comment]
I was told otherwise and quick testing showed that things broke down quite a bit with my PR. But yeah, you are better judge of the code than me :D

**Comment by adam111316** [comment]
Trust no-one :P I'll have a look in the next few days and check it a bit more thoroughly

**Comment by adam111316** [comment]
Implemented in #520
