### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by mkools** [SickGear/SickGear#528]
Hi,

I'm pretty sure this is not a bug but is my own issue. Still posting it since I can't find it elsewhere. Sickgear doesn't want to unpack my downloaded stuff any longer and gives this error message on every archive:

Failed to unpack archive tvshow.2015.s02e03.720p.hdtv.x264.rar: time data '2015-10-08 03:05' does not match format '%d-%m-%y %H:%M'

So what I do now is manually unpack and post process which works.

Any idea how to fix this?

**Comment by mkools** [comment]
Seems like this is caused by an upgrade of the unrar upgrade. Downgrading unrar solved the issue.

**Comment by JackDandy** [comment]
Hiya, 

curious, did you try to upgrade the one inside \lib\unrar2 ?

Was there a particular reason that prompted you to try this, an actual release name that i could test here would be useful.

**Comment by mkools** [comment]
Hi, no I haven't touched lib\unrar2. I only upgraded the rar-package on FreeBSD 10.2 (with pkg upgrade). Then it said:

Installed packages to be UPGRADED:
        unrar: 5.21_1,5 -> 5.30,5

After that I was getting the format issue so I manually downgraded back to 5.21 and it started working again. I wasn't even aware sickgear is using its own rar package.

Let me know if you need more information. Thanks.

**Comment by JackDandy** [comment]
In General/Advanced settings, you can select and Checkout 530: feature/UpdateUnrar to test and make sure that the issue you reported is fixed. Please let me know the result.

**Comment by JackDandy** [comment]
#530

**Comment by mkools** [comment]
Yes that did it! I have updated unrar now and post processing / unpacking works. I didn't have 530 branch btw but I can see you already committed it to develop which I was already running.

Thanks appreciate it!

**Comment by JackDandy** [comment]
Yup, someone else was able to confirm the fix so I merged, once merged it's removed and that's why the branch was no longer available.

Your welcome, enjoy.
