### ISSUE TITLE
unable to check 'Unpack' in post processing configuration

### ISSUE THREAD

**Issue by paericksen** [SickGear/SickGear#529]
looks like a date format bug in unrar2, I was able to get it working by changing lib/unrar2/unix.py as follows:

```
diff --git a/lib/unrar2/unix.py b/lib/unrar2/unix.py
index bd9ee85..a0ebe42 100644
--- a/lib/unrar2/unix.py
+++ b/lib/unrar2/unix.py
@@ -168,7 +168,10 @@ class RarFileImplementation(object):
                 data['size'] = int(fields[1])
                 attr = fields[0]
                 data['isdir'] = 'd' in attr.lower()
-                data['datetime'] = time.strptime(fields[2]+" "+fields[3], '%d-%m-%y %H:%M')
+               try:
+                       data['datetime'] = time.strptime(fields[2]+" "+fields[3], '%d-%m-%y %H:%M')
+               except ValueError:
+                       data['datetime'] = time.strptime(fields[2]+" "+fields[3], '%Y-%m-%d %H:%M')
                 data['comment'] = None
                 yield data
                 i += 1
```

**Comment by JackDandy** [comment]
Hi, it would be best to understand the steps how an issue is triggered by this in order to know whether it really is a fault inside of unrar2 or something else that we can change to fit better. Therefore, can you supply a test scenario when you see an actual exception raised by unrar2.

**Comment by paericksen** [comment]
why close it if you need more info?

I'm not at my system so I'm going from memory.

After installing SickGear, and navigating to localhost:8081 then configuration Post Processing, click the check box for Unpack, it unchecks itself and shows an error message.

Checking that box ultimately runs a test unrar on the test.rar file in lib/unrar2 so I navigated to that directory, ran the same test manually, and got the exception indicating that the date format didn't match the date string.

I'll post more info when I can get in front of the system.

**Comment by JackDandy** [comment]
I see this only affects unix because it uses the command line tool and the tool affected is version 5 and up. Using version 4 lower will fix the issue for now. I have all the info needed, thank you for your detailed information.

**Comment by JackDandy** [comment]
In General/Advanced settings, you can select the pull request **# 530 feature/UpdateUnrar** to test and make sure that the issue you reported is fixed. Please let me know the outcome.

**Comment by JackDandy** [comment]
#530
