### ISSUE TITLE
Series with '+' in the name are not supported correctly

### ISSUE THREAD

**Issue by vergessen** [SickGear/SickGear#531]
Expectation | Result
------------ | -------------
Adding a existing show with a + in the folder name should carry that + through the tvdb search and parent folder   |  + is stripped out on the tvdb search requiring the user to change the name, folder defaults to a folder without the plus

Steps:
1. Add new show Peg + Cat http://thetvdb.com/?tab=series&id=273993&lid=7
2. Delete that show but keep the directory
3. Re-add via existing shows. 

The initial search will fail because of the missing plus.  This can be mitigated by the end user by changing the string. The folder selection is locked though and it is incorrect. Final folder results as "Peg Cat" when it should be "Peg + Cat"  all episodes in the correct folder are now missed. 

Tested on Develop - bc007ab70b79fa54db97387533178afe2e575dd7 and Current master.  Same results.

**Comment by JackDandy** [comment]
#533
