### ISSUE TITLE
Promotional video replacing episode from RARBG releases

### ISSUE THREAD

**Issue by ItsMeMike** [SickGear/SickGear#532]
# Branch: (develop) / Commit: (8aaa72f)
Expectation | Result
------------ | -------------
When a RARBG download is snatched from SickGear and contains the episode (big .MKV), and a promo video (small .MP4) inside a folder named after the release, the promo video should be ignored because of the smaller filesize  | SickGear starts processing the smaller .MP4 after the larger .MKV, and matches it with the release in the snatch history based on the name of the folder. It then disregards the filesize check and starts copying/moving/linking the bad .MP4, deleting the larger .MKV.

**Steps to reproduce:**
*1)* Enable RARBG provider
*2)* Add The Blacklist as a show in 1080p quality
*3)* Search for S03E02 (it should snatch The.Blacklist.S03E02.1080p.WEB-DL.DD5.1.H264-RARBG)
*4)* Wait for SickGear to process the folder
*5)* Check the processed file

**Notes:**
Make sure SickGear has the release in it's history.
Also check if your downloaded episode contains the file RARBG.com.mp4

**Logfile** showing it goes wrong can be found [here](http://pastebin.com/RDBxsVfY)

**Comment by JackDandy** [comment]
#533
