### ISSUE TITLE
Show will change to skipped afther air date

### ISSUE THREAD

**Issue by Martijn085** [SickGear/SickGear#542]
Any show will change the status from wanted to skipped when the aire date is reached. How to change to keep the wanted status?

**Comment by adam111316** [comment]
https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues

**Comment by JackDandy** [comment]
The behavior of an episode changing to "Skipped" some time after the episode has aired is correct and logical.  This will not be changed, and is exactly the same as SickBeard.  You may display a show and change an individual episode status inside that view.
