### ISSUE TITLE
Process episode method when using torrent/usenet

### ISSUE THREAD

**Issue by Martijn085** [SickGear/SickGear#543]
Would it be possible to make a choice when you are using torrents to copy the files and when you are using usenet to move the files. I think there should be two diffrent folder to choose with post-processing, one for usenet and one for torrents.

**Comment by adam111316** [comment]
@JackDandy: Thoughts no this one? I think it would be better suited to have a parameter on the 'autopp scripts' that overwrite the default behaviour?

**Comment by JackDandy** [comment]
this is way to edge case
