### ISSUE TITLE
NZB search not working

### ISSUE THREAD

**Issue by Martijn085** [SickGear/SickGear#547]
It seems that the NZB search is not working. With Torrents the same releases is working fine.
The releases are avalible on the indexer omgwtfnzbs but are not being found. I have tried WEB-DL en HD720 on different shows.

2015-10-26 13:37:13 INFO     MANUAL-257655 :: Unable to find a download for: [Arrow - 4x03 - Restoration]
2015-10-26 13:37:12 INFO     MANUAL-257655 :: [omgwtfnzbs] :: Performing episode search for Arrow
2015-10-26 13:37:12 INFO     MANUAL-257655 :: Beginning manual search for: [Arrow - 4x03 - Restoration]

My SickGear version: BRANCH: (master) / COMMIT: (1e6c1618871f8cb5781d35114f21d249c270245f) i also tried the last developer branch, with the same problem.

**Comment by Martijn085** [comment]
Found the problem. The omgwtfnzbs.py seems to have the wrong url.

self.url = 'https://omgwtfnzbs.org/' must be changed to self.url = 'https://api.omgwtfnzbs.org/' and also self.url_base = 'https://omgwtfnzbs.org/' must be changed to self.url_base = 'https://api.omgwtfnzbs.org/'

**Comment by JackDandy** [comment]
These suggestions are incorrect and fail to show an understanding of the codebase, therefore. I think it's time you come to irc and discuss this further.

**Comment by Martijn085** [comment]
Incorrect? Strange, i have edit the file and everything works for me. When i don`t use the changes i get a 404 error on the website when i check the debug log (links).

**Comment by JackDandy** [comment]
Come to irc to discuss this further.
