### ISSUE TITLE
CentOS 6, sha hashlib error mentioned when starting SickGear

### ISSUE THREAD

**Issue by bakmanhans** [SickGear/SickGear#551]
<h1>Branch: master (1e6c1618871f8cb5781d35114f21d249c270245f)</h1>
Expectation | Actual result
------------ | -------------
When typing command <pre># service SickGear start</pre> I expect the program to start without error. | Instead the command errors with the text: <pre>Starting sickbeard: /usr/share/SickGear/lib/trakt/__init__.py:4: DeprecationWarning: the sha module is deprecated; use the hashlib module instead from sha import new as sha1</pre>
Steps: Following normal installation procedure as stated in the howto's for Fedora/Redhat/CentOS.
After fresh installation start the program via <pre># service SickGear start</pre> gives the result entered above.

Version details:
<pre># python -V
Python 2.6.6</pre>
<pre># cat /etc/*-release
ClearOS Community release 6.6.0 (Final)</pre>

**Comment by bakmanhans** [comment]
When changing line 4 in ../SickGear/lib/trakt/__init__.py
<pre>from sha import new as sha1</pre>
into
<pre>from hashlib import new as sha1</pre>
SickGear starts without errors.

**Comment by JackDandy** [comment]
You will experience other issues with SSL, please upgrade python to 2.7.10 and see if the issue you report persists.
