### ISSUE TITLE
Shownames containing "Sample" don't snatch/PP

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [SickGear/SickGear#552]
BRANCH: (develop) / COMMIT: (d60180b36638f7108c5d56fd1710baad9a922a51) 

When a showname contains the word "Sample", no episodes will snatch and nothing will post process.

Reproduction steps:
- Add "Shomin Sample"
- Search for an episode
- See log

Log verifies that it's because of the word "sample" in the title.
MANUAL-284073 :: Invalid scene release: [HorribleSubs].Shomin.Sample.-.03.[720p] contained: (^|[\W_])sample($|[\W_]), ignoring it

**Comment by JackDandy** [comment]
Rename and remove "sample" from file to process, this behaviour is correct and intended.

**Comment by vergessen** [comment]
before just closing it we may want to consider future issues...  If a tv show called the white wash sample comes out.  That show will never get picked up.  possibly an exception if the shows name contains sample?

**Comment by JackDandy** [comment]
Ah, if that occurs, then sure.

**Comment by Hellowlol** [comment]
Isnt it a simple fix to just verify the filesize of the file containing the word sample?
