### ISSUE TITLE
Kodi notifier doesn't send a single-show library update command correctly

### ISSUE THREAD

**Issue by harrv** [SickGear/SickGear#578]
**My Environment**

SickGear version: BRANCH: (master) / COMMIT: (1e6c1618871f8cb5781d35114f21d249c270245f)
(Note that the relevant portion of sickbeard/notifiers/kodi.py does not appear to have changed from the master to the develop branch, so I believe the same issue likely exists in the develop branch too.)

Kodi version: 15.2 (Isengard), running on OpenELEC 6.0.0, on Raspberry Pi (1st gen). Kodi listens for commands on port 80, no authentication required, and is configured to accept local and remote commands.

**Issue Description**

The Kodi notifier knows how to do three things:
1. Send Kodi an on-screen notification message when a show is snatched or downloaded.
2. Send Kodi a single-show library update command after an episode of that show is downloaded.
3. Send Kodi a system-wide update command if the single-show update command fails.

This issue is about the second thing the Kodi notifier knows how to do, the single-show library update command. It doesn't work because of a data formatting issue. When I look in the debug log, the relevant log entry looks like this:

`2015-11-30 10:53:18 DEBUG    TORNADO :: KODI: JSON command: {"params": {"directory": "\"/storage/mediafull/tv/Talking Dead/\""}, "jsonrpc": "2.0", "method": "VideoLibrary.Scan", "id": 1}`

Notice that the show's directory path is a string and not only does the directory string have quotes around it, but the value inside the quotes also has quotes. That is what is causing Kodi to fail the library update. Kodi actually returns OK for that command...

`2015-11-30 11:09:14 DEBUG    TORNADO :: KODI: JSON response: {u'jsonrpc': u'2.0', u'id': 1, u'result': u'OK'}`

...but even though it has returned an "OK" response, Kodi did not successfully update its library because the value for directory was quoted twice. (And because Kodi sent OK as the response, SickGear doesn't try to do the system-wide update command because it doesn't know that the command really failed, but that's a separate issue.)

The command needs to have just a single set of quotation marks around the directory value, rather than two sets, as so:

`{"params": {"directory": "/storage/mediafull/tv/Talking Dead/"}, "jsonrpc": "2.0", "method": "VideoLibrary.Scan", "id": 1}`

**Steps to Reproduce**

1. Install Kodi 15.2 on any platform, or use an existing Kodi 15.2 installation.
2. Add at least one TV show to Kodi's video library by adding the directory it is in as a video source, and configuring that video source as having TV content. Kodi and SickGear can run on different systems, provided they can both access the same file system containing the TV shows (Kodi can be configured to use SMB or NFS shares). http://kodi.wiki/view/Adding_video_sources
3. Verify that you can see the TV show and its episodes in Kodi through the main TV Shows menu accessible from the main Kodi interface.
4. Configure SickGear with a Kodi notifier, and configure that notifier to update the Kodi video library.
5. Configure SickGear to manage the same TV show (and location) as the show you added to Kodi in step 2.
6. Add a new episode to a show that already exists in both Kodi and SickGear. Either let the regular post-processing flow send the library update command to Kodi, or in SickGear navigate to the displayShow page for the show and click "Update show in Kodi" near the top of the page.
7. In Kodi, from the TV Shows page, navigate to the show and check if the new episode is in the library. In my experience, it will not be.

**Testing**

I can send the same command SickGear is sending to my Kodi for testing purposes using a web browser if I url-encode the command first:

Command: `{"params":{"directory":"\"/storage/mediafull/tv/Talking Dead/\""},"jsonrpc":"2.0","method":"VideoLibrary.Scan","id":1}`

URL: `http://192.168.1.125/jasonrpc?request=%7B%22params%22%3A%7B%22directory%22%3A%22%5C%22%2Fstorage%2Fmediafull%2Ftv%2FTalking%20Dead%2F%5C%22%22%7D%2C%22jsonrpc%22%3A%222.0%22%2C%22method%22%3A%22VideoLibrary.Scan%22%2C%22id%22%3A1%7D`

Kodi returns: `{"id":1,"jsonrpc":"2.0","result":"OK"}`

Test result: The new episode is NOT added to Kodi's video library.

If I modify the command to leave out the extra quotation marks:

Command: `{"params":{"directory":"/storage/mediafull/tv/Talking Dead/"},"jsonrpc":"2.0","method":"VideoLibrary.Scan","id":1}`

URL: `http://192.168.1.125/jasonrpc?request=%7B%22params%22%3A%7B%22directory%22%3A%22%2Fstorage%2Fmediafull%2Ftv%2FTalking%20Dead%2F%22%7D%2C%22jsonrpc%22%3A%222.0%22%2C%22method%22%3A%22VideoLibrary.Scan%22%2C%22id%22%3A1%7D`

Kodi returns: `{"id":1,"jsonrpc":"2.0","result":"OK"}`

Test result: The new episode IS added to Kodi's video library.

**Proposed Fix**

In the file `sickbeard/notifiers/kodi.py` combining lines 151-152 you will find the following line of python code:

`updateCommand = {'jsonrpc': '2.0', 'method': 'VideoLibrary.Scan', 'params': {'directory': json.dumps(path)}, 'id': 1}`

If I change the line to the following, the command will succeed:

`updateCommand = {'jsonrpc': '2.0', 'method': 'VideoLibrary.Scan', 'params': {'directory': path}, 'id': 1}`

I would do this myself and submit a pull request, but I am unsure what else json.dumps() might be doing. I thought it best to leave this for someone who knows that code better than I do to decide if the right fix is just removing the json.dumps() from the path value, or something else.

**Comment by JackDandy** [comment]
@harrv thanks for the comprehensive report. :+1: 

I've rewritten Kodi notifier but not yet pushed due to it not quite ready. If you want in on the testing, come meet us in IRC or wait.

**Comment by karl0ss** [comment]
I just want to confirm that I am now running the develop version and this still doesn't work properly..

**Comment by JackDandy** [comment]
@karl0ss Thank you.

I've been updating Kodi manually.  The new code will be pushed, the delay was because of a new feature that was added to SG that unfortunately failed to work smoothly in Kodi UI due to how Kodi is set up to behave with skins etc.  Kodi devs were contacted and it turns out that there will be no change to address the issue found by SG, therefore, we have to strip out the funky code we created - not nice.

**Comment by karl0ss** [comment]
@JackDandy  Ok, Not a problem, I have made the change suggested in this post and its working again without me having to manually scan for new files.

Out of interest, how long are the cycles generally?

Thanks for your great work :)

**Comment by JackDandy** [comment]
Thanks for the feedback on the suggested fix.

To your question, It varies, here are [past releases](https://github.com/SickGear/SickGear/releases)

**Comment by JackDandy** [comment]
@harrv @karl0ss looking for Kodi notifier testers, if interested, see wiki homepage to come IRC.

**Comment by harrv** [comment]
Thanks, Jack. I'm glad you've worked on that. Sorry I didn't volunteer to help test, but I'm now using Emby as my metadata/media manager so I no longer need SickGear to notify Kodi directly.

**Comment by thrca** [comment]
This issue appears to either A) still be in the current code as of 10/7/2016, or has snuck its way back into the kodi.py notifier.  The notifier is still using "json.dumps(path)" and not properly triggering a single-show library update.

I have applied the OP original workaround and will report back if it still applies as the correct fix.

**Comment by JackDandy** [comment]
Hello @thrca

"Current code" ? What commit hash # ? and are you sure that you didn't accidentally use master as the change is in develop. Also, there is nothing wrong with python "json.dumps", that wasn't the cause.

Thanks.

**Comment by thrca** [comment]
You are correct, I am on branch master, and kodi is not running the single-update properly.. I hadn't debugged it yet, just discovered this issue when searching for a cause/solution for kodi not running the updates.. The notifications are showing up and I manually update the library and the new shows show up.
