### ISSUE TITLE
[Enhancement] Replace original if "INTERNAL" available

### ISSUE THREAD

**Issue by sweatherlyuk** [SickGear/SickGear#581]
A lot of releases get 'internaled' if the original release cannot be officially nuked but is considered poor for some reason, for recent examples and discussion of this see:
https://www.reddit.com/r/trackers/comments/3r9hin/asapfleetreleases_getting_internald_afterwards/

Currently the only(?) way to ignore these is to add these poor release groups' names to the list of ignore words, however, in the case where an INTERNAL is not released then obviously nothing is downloaded.

In much the same way as there is an option in the search setting to replace a download if a PROPER or REPACK is available, a second option to replace a download if an INTERNAL becomes available would address this issue and be a great addition to SickGear.

**Comment by adam111316** [comment]
My 2c, this option would prob need a user list of "good" groups to get internals off.  Wouldn't want bad internals

**Comment by JackDandy** [comment]
Keep an eye out, the logic is under discussion. However, for the foreseeable, we live with manual intervention in the small number of cases where an INTERNAL is *not* release *and* a release has been ignored.
