### ISSUE TITLE
Improve multiple indexer support

### ISSUE THREAD

**Issue by adam111316** [SickGear/SickGear#589]
Just a list of items that should probably be fixed / enhanced before the addition of multiple indexers:

Database fields:
 - [ ] There really needs to be some consolidation and standardization of how we refer to the show and episode indexes and ids. Having references to indexerid, indexer_id and indexer can be confusing. Not really a high priority however, may cause more grief than anything if there are many references around.

Scene exceptions:
- [ ] Scene exceptions are currently loaded into the database and are indexed purely by an indexer id. Ideally we should we should really store this against indexer number + indexer id

Show 'indexerids':
- [ ] There needs to be adjustment to code to handle the fact that two indexers may have the same 'indexerid' for two different shows. Eg both Tvmaze and Anidb start their show ids at 1 and increment onwards. Currently the only was I see this working is removing all reference to indexerid in a fair chunk of all gui / backend code that we perform and replacing it with the unique database index

Duplicate show detection:
- [ ] There may be duplicate shows added over two or more indexers. Eg adding family guy on Tvdb and Tvmaze. Whether we completely block this ever happening or add code to deal with this needs to be sorted.

**Comment by JackDandy** [comment]
+1

**Comment by ezar** [comment]
+1
