### ISSUE TITLE
Newznab providers search for tvdbid even if unsupported 

### ISSUE THREAD

**Issue by adam111316** [SickGear/SickGear#590]
BRANCH: pull/588/feature/ChangeStarifyNN / COMMIT: 1811f7176ef14551e7337086f28e253946e0af57

Expectation | Actual Result
------------ | -------------
Provider should not attempt to search using tvdbid | Provider attempts to search using tvdbid and causes excessive searching and does not give a result.

Steps:
1. Add a custom newznab provider which does not support tvdbids
2. Add a show (I have used an anime in this case)
3. Perform a manual search using the magnifying glass on an episode.
4. Check logs for result

Logs: https://gist.github.com/adam111316/89a6dd3128e17c61a1b4

Possible solutions
1. Have add a new attribute to newznab providers for 'tvdbid enabled' and allow this to be set by the user on a per provider basis.
2. As above but automatically check the newznab providers search abilities. The NN api will return if tvdbid is supported (https://www.usenet-crawler.com/api?t=caps) and return for example:
        ```<tv-search available="yes" supportedParams="q,rid,tvdbid,tvmazeid,season,ep" />```
This could be checked on a daily? weekly? basis to check if support has been added or not by the NN provider.

**Comment by JackDandy** [comment]
Can not be done. It is unreasonable to expect the user to know if a provider has changed their code base to support tvdbid or not. The caps cannot be trusted to reflect its use either. Basically, over time, more will update and this becomes a non issue anyway.
