### ISSUE TITLE
Nice to have TV(5000) category for some Newznab providers

### ISSUE THREAD

**Issue by vajonam** [SickGear/SickGear#594]
Some shows aren't properly indexed, for example they only show up in the TV category not the TV/SD or TV/HD cats. Spotweb is one such example. 

As a work around would be nice to have the TV(5000) category show up as well.

```
diff --git a/sickbeard/providers/newznab.py b/sickbeard/providers/newznab.py
index 929187a..ddc0262 100755
--- a/sickbeard/providers/newznab.py
+++ b/sickbeard/providers/newznab.py
@@ -97,6 +97,7 @@ class NewznabProvider(generic.NZBProvider):
         try:
             for category in xml_categories.iter('category'):
                 if 'TV' == category.get('name'):
+                    return_categories.append(category.attrib)
                     for subcat in category.findall('subcat'):
                         return_categories.append(subcat.attrib)
```

That diff works nicely.

**Comment by JackDandy** [comment]
@vajonam Thank you for the suggestion.

Cat 5000 was never added because nnab keeps stuff there that have not been filtered into a finale category, therefore, it is up to a Spotweb installation to have proper filtering in order for shows to reach their proper nnab mapped finale category.  It saves time, processing effort and user confusion by **not** processing cat 5000.

**Comment by vajonam** [comment]
While I understand why its "Wontfix", Spotweb doesn't seem have that level of  filtering to segregate tvshows into HD and SD so think its a limitation of that. I dont think its a case of mis configuration. this makes it not very useful with SG.

Also spotweb needs the show title to passed in as "&q=Homeland" or whatever, which is missing. I understand these are all spotweb specific, do you have any other thoughts how to get spotweb better supported w/ SG? I am open to creating a new spotweb provider if you think there is value in it, if not then I will just maintain my own local branch that includes these hacks and workaround .

**Comment by JackDandy** [comment]
Good idea. I agree that a Spotweb specific class would be the far better option for this, it's a small user-base but will no doubt grow.

**Comment by p0psicles** [comment]
hi vajonam, I'm also interested in a dedicated Spotweb provider class. If your still interested, I can help you with it. I'll first need to finish my current project tough. But maybe you can make a start in creating the feature request?

**Comment by p0psicles** [comment]
The spotweb provider seems to work for a couple of shows and an anime show.
Need to test allot, for doing a PR

**Comment by vajonam** [comment]
I have moved over to a differnt fork of sickbeard in which all this already works. which is why I am not really working on this anymore. Good luck with your provider. 

also agree the you the n "q=My_Query" for the best results, including a cat=5000 will also narrow it down a bit.
