### ISSUE TITLE
Rescanning files does not update status

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [SickGear/SickGear#597]
Branch: Develop - 2a762ae7db287fa0719196e55399e56eb06b4332

If the quality in the name of a file is changed (example change "SD TV" to "HD TV"), the quality isnt updated in the episode list on SickGear after a rescan(It will remain "Downloaded SD TV" rather than update to "Downloaded HD TV")

Reproduction steps:
Change the quality in a file name(add it before this step and rescan if not already present)
Rescan
See displayShow page

If an episode is listed as Ignored, rescanning won't update to the corresponding status either.

**Comment by JackDandy** [comment]
instead of your step...
```
Change the quality in a file name
```
Change the quality in the display show page.

ignored = ignore the item completely from **all** operations, surprise.

**Comment by vergessen** [comment]
Then the re-scan option should be removed.  The intended function of this is to allow a user to force SG to update data without forcing an entire PP import.  If we are going to recommend a PP import as the proper use then the re-scan function is just extra code that can be shelved.

**Comment by JackDandy** [comment]
Yup that suggestion was a workaround.

The actual issue has been identified on this... basically we have missing logic when a re-scan is performed for status "Skipped".

**Comment by vergessen** [comment]
Oh, i was reading it as a solution.   Basically if it is outside of ignore it is almost like Rescan should trigger a pp for that directory.  Use the logic that we already have built instead of a creating two sets of logic paths...

**Comment by JackDandy** [comment]
I'm sure you are not saying this, and I do see how my (poor) suggestion can be interpreted to lead to the thought, but can't pp a child folder of a parent root, that would lead to other shenanigans. I meant to move funky eps to an external pp folder and pp that. Still, that suggestion is academic now that we know what actually needs to be done.

**Comment by JackDandy** [comment]
#635 
One caveat, if only manually renaming an episode you must set the status "Skipped" before rescan.
