### ISSUE TITLE
Failed handling from Sabnzbd results in Error

### ISSUE THREAD

**Issue by MacPat** [SickGear/SickGear#626]
BRANCH: (master) / COMMIT: (3dd1386)

When using sabToSickBeard.py I receive an error. The download has failed, but because of this error that information never reaches SickGear. I've setup Sabnzbd as stated on the config pages.

My setup is on Mac OS X 10.8.5, Python 2.7.11, Sabnzbd 0.7.20.

Below is the transcript of the sabToSickBeard.py.

<pre>Loading config from /sabnzbd/scripts/autoProcessTV.cfg

Opening URL: http://localhost:8081/home/postprocess/processEpisode
Traceback (most recent call last):
  File "/sabnzbd/scripts/sabToSickBeard.py", line 30, in <module>
    autoProcessTV.processEpisode(sys.argv[1], sys.argv[2], sys.argv[7])
  File "/sabnzbd/scripts/autoProcessTV.py", line 133, in processEpisode
    sess.post(login_url, data={'username': username, 'password': password}, stream=True, verify=False)
  File "/Library/Python/2.7/site-packages/requests-0.14.2-py2.7.egg/requests/sessions.py", line 284, in post
    return self.request('post', url, data=data, **kwargs)
TypeError: request() got an unexpected keyword argument 'stream'</pre>

**Comment by JackDandy** [comment]
[How to report issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

**Comment by MacPat** [comment]
Sorry, I thought that was clear.

Reproduced by: Download nzb and process it using sabToSickBeard.py from Sabnzbd.

**Comment by JackDandy** [comment]
are you saying that every download using sabToSickBeard.py fails? If only in specific cases, then I need the specific set of repro steps to get what you are seeing so that i can look further.

**Comment by JackDandy** [comment]
Marked invalid as no response.
