### ISSUE TITLE
[question] contributing to install wiki for OS X

### ISSUE THREAD

**Issue by elgallo** [SickGear/SickGear#631]
To install SickGear on OS X I referred to the sickbeard page, which gives a method of installing "python-cheetah" that will not work with 10.10 or 10.11 (I don't have a machine to test any previous versions) 

However on both of these one can install SickGear easily with two lines in terminal.

<code>sudo pip install cheetah</code>

<code>git clone http://path/to/sickgear/</code>

and of course a third to run SG.

<code>python /path/to/SickGear/SickBeard.py</code>

**Comment by JackDandy** [comment]
@elgallo 
Thank you...
[I added your instructions here](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B5%5D-OS-X)
Please comment here if there is more detail that can improve on it.
