### ISSUE TITLE
Scan doesn't detect episodes with unicode characters in episode title

### ISSUE THREAD

**Issue by nloding** [SickGear/SickGear#633]
BRANCH: master / COMMIT: 87b915e450f5bb2a5e384599248a6d2414688425

What I expect to see: a rescan of an existing show find these episodes.
What I'm seeing: episodes with unicode characters in the title are not detected, though they exist on the file system with the right naming convention.

Steps/details:
1. Have NBC's "Hannibal" season 1 already downloaded and named per the renamer rules (see screenshot below).
2. Add Existing Show > Hannibal
3. Rescan

NBC's "Hannibal" is a prime example. Season one has episodes named "Apéritif" and "Œuf" and "Entrée" for instance. That is how these files are named on my local file system, and that is how the episodes are named after updating from [theTVDb](http://thetvdb.com/?tab=season&seriesid=259063&seasonid=493342&lid=7).

I've rescanned numerous times. I've toggle the episode status between several states, including manually tying to set it to "Downloaded (HD)" before running the scans, all with the same end result. This also affects some other shows in my list, such as "The West Wing" S02E10 "Noël".

The log shows no errors after a rescan, and the info displays only this:

```
2016-01-26 22:54:25 INFO     SHOWQUEUE-REFRESH :: No new cache images needed, not retrieving new ones
2016-01-26 22:54:25 INFO     SHOWQUEUE-REFRESH :: Checking & filling cache for show Hannibal
2016-01-26 22:54:25 INFO     SHOWQUEUE-REFRESH :: 259063: Writing NFOs for all episodes
2016-01-26 22:54:25 INFO     SHOWQUEUE-REFRESH :: 259063: Writing NFOs for show
2016-01-26 22:54:25 INFO     SHOWQUEUE-REFRESH :: 259063: Loading all episodes with a location from the database
2016-01-26 22:54:14 INFO     SHOWQUEUE-REFRESH :: 259063: Loading all episodes from the show directory /media/6tb/TV Shows/Hannibal
2016-01-26 22:54:14 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Hannibal
```

Attached is a screenshot of the file on my file system (Ubuntu/ext4, using `ls -al`) and the SickGear web interface.

![screen shot 2016-01-26 at 10 49 42 pm](https://cloud.githubusercontent.com/assets/328425/12603279/43c06502-c47f-11e5-9446-5556ab08a669.png)
<img width="1613" alt="screen shot 2016-01-26 at 10 50 27 pm" src="https://cloud.githubusercontent.com/assets/328425/12603280/43c8f1f4-c47f-11e5-85f7-49e279b51d37.png">

**Comment by nloding** [comment]
And just after I submitted this, I realized that it did detected Hannibal s01e11 ("Rôti") and s01e12 ("Relevés"). The names match on my file system (`Hannibal - s01e11 - Rôti.mkv` and `Hannibal - s01e12 - Relevés.mkv`). Perhaps it's not unicode like I thought. I did verify file system permissions - all are identical. Happy to switch branches, try out some code, whatever is needed.

**Comment by JackDandy** [comment]
@nloding Hello, can you come to IRC so we can discuss this better. Thanks.

**Comment by JackDandy** [comment]
#635

**Comment by nloding** [comment]
I updated to the most recent release (BRANCH: master / COMMIT: c86ea4be0f0aef067a3e70162f5d398dffec47a5) and the issue still exists as described above. All the debug log files look identical to before. It locates the file (the tooltip is there). If I set all of season 1 to skipped, it will always find episodes 2, 5, 8, and 13 - the rest are marked as skipped still.

**Comment by JackDandy** [comment]
Hmm, we cannot reproduce this and your observations show no pattern of unicode verses non unicode in the eps listed, also eps 3, 7, 9 and 10 are not unicode - this is perplexing.

**Comment by nloding** [comment]
I don't believe it's related to the unicode characters any longer. If it was, it wouldn't pick up the file name. Have any steps you'd like me to try?

**Comment by JackDandy** [comment]
IRC please.

**Comment by JackDandy** [comment]
@nloding can you add the output of ```export``` and ```locale``` commands to your gist, thanks

**Comment by nloding** [comment]
@JackDandy - added to the gist; I can't hop on IRC until this evening (8PM EST or so)

**Comment by JackDandy** [comment]
can you test with updated PR, thanks

**Comment by nloding** [comment]
This, sir, fixes it! I tested with the couple other shows that were affected too, like "The West Wing," and it works across all of them.

**Comment by JackDandy** [comment]
@nloding and the expected Quality is also attributed to the episode that is tagged "Downloaded" ?

**Comment by nloding** [comment]
@JackDandy - yes it did
