### ISSUE TITLE
WIKI add - OS X launch Deamon

### ISSUE THREAD

**Issue by elgallo** [SickGear/SickGear#636]
open TextEdit 

in **LINE 10** replace "/Applications/SickGear/SickBeard.py" with the location of YOUR INSTALLATION. which COULD be "~/SickGear/SickBeard.py"

 ```
 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
 <dict>
   <key>Label</key>
   <string>sickbeard</string>
   <key>ProgramArguments</key>
   <array>
        <string>/usr/bin/python</string>
        <string>/Applications/SickGear/SickBeard.py</string>
   </array>
   <key>RunAtLoad</key>
   <true/>
 </dict>
 </plist>
 ```
 

save as "com.sickbeard.sickbeard.plist" to "~/Library/LauchAgents/" MAKE sure you change the extension to **plist**

open Terminal
run `$ launchctl load ~/Library/LaunchAgents/com.sickbeard.sickbeard.plist`
If you are already running sickGear you may get an error that it is already running, it will still work on restart.

on your next restart sickgear should load within a few minutes.

**Comment by JackDandy** [comment]
Thank you, the above has been edited and reworked into the OS X install page.
