### ISSUE TITLE
Install Documentation for RHEL doesn't address the needed version of python

### ISSUE THREAD

**Issue by jmp242** [SickGear/SickGear#637]
Python on RHEL7 is 2.7.5. I'm getting warnings that it needs 2.7.8 and your docs suggest 2.7.9. The install doc on your wiki doesn't address this issue at all. There are Software Collection Libraries that can get you python 2.7.8 and maybe eventually newer pythons, but then there isn't a package for cheetah, and darned if documentation is very good out there about installing modules into a SCL. You probably ought to update your docs, or re-consider dropping support for Python 2.7.5 if you want installs to be simple.

--- Edit
Well, and my hope of using SCL is thwarted as it is 2.7.8 and you want 2.7.9... I guess SickGear isn't to be for RHEL7 and earlier...

**Comment by JackDandy** [comment]
wiki updated ;)
