### ISSUE TITLE
Shows in library showing in "Add existing shows" section

### ISSUE THREAD

**Issue by zanesc** [SickGear/SickGear#641]
I just tried adding Pokemon Origins and Pokemon Chronicles to my SickGear Library. They added ok and are in my library but if i go to " Add existing shows" these two shows show up there. Even if i try to add them from there they do not disappear from that list. I checked for an update of SickGear and i am on the latest release.

PS. i just switched from SickRage to SickGear today so i'm not sure if that has something to do with it. Everything else seems to be fine though.

**Comment by JackDandy** [comment]
Check the two real examples (especially his steps to reproduce section) .. [How to report issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)
