### ISSUE TITLE
Certain episode filenames cause process hang

### ISSUE THREAD

**Issue by c---** [SickGear/SickGear#643]
This is the log where the error occurs:

    10:50:47 DEBUG::SHOWQUEUE-ADD :: 71470: Creating episode from /media/Star Trek The Next Generation/star_trek_tng-S01E15-11001001.avi
    10:50:47 DEBUG::SHOWQUEUE-ADD :: 71470: Creating episode object from /media/Star Trek The Next Generation/star_trek_tng-S01E15-11001001.avi
    10:50:47 DEBUG::SHOWQUEUE-ADD :: Using NORMAL regexs

python process goes to 100% CPU, hangs, and can't be stopped except by kill -9

Removing the episode name "11001001" prevents the issue so it's something to do with that.

**Comment by JackDandy** [comment]
[How to report issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

**Comment by c---** [comment]
Why was this closed? There is nothing more to report. It affects ALL versions of SickGear and is super easy to re-create. Just add a show with a filename like that and when it scans the existing episodes it will hang.

In the code it's parsing the "11001001" as "extra_ep_num" then when it does the range it thinks the file has all episodes from 15 to 11001001 (ie. 11 million episodes in this one file). sickbeard/name_parser/parser.py line 142 of current git is where it creates the bad range.

Then it hangs trying to log the result of all those episodes.

**Comment by JackDandy** [comment]
#656
