### ISSUE TITLE
Daily show downloading the same episode over and over

### ISSUE THREAD

**Issue by embalmed** [SickGear/SickGear#647]
BRANCH: develop  COMMIT: 9e540ff

Expectation:  Sickgear downloads daily episodes of airbydate show The Daily show
Result: For all february episodes sickgear seems to download the same October episode

Steps:  Add the daily show to your shows, set it to airbydate
            Enable searching of season packs in both torrent and nzb provider
            Search for a February episode of The Daily Show

### **[edit] only happens when season pack is enabled**

**Comment by JackDandy** [comment]
@embalmed i cannot repro this issue on the latest dev, can you trigger it with just one nzb provider enabled ?
