### ISSUE TITLE
SickGear downloads already snatched/downloaded episodes

### ISSUE THREAD

**Issue by jonas78** [SickGear/SickGear#653]
Hi,

I had an incident aprox 2 weeks ago, where SickGear started do download already "downloaded" shows, it was from various tv series. I did manage to stop it and afterwards I changed the status for all shows to Archived. I have not had that problem again yet, but a friend of mine got the same problem, this time it was Jimmy Fallon. It tried to download 500 episodes from 2014, it managed to download 130 of them before he noticed it.

This is a quite serious problem and it's hard to "trust" the application at the moment. Unfortuanaly I dont have any logs to provide you with.

**Comment by JackDandy** [comment]
Hello @jonas78 Can you check the two real examples (especially his "*steps to reproduce*" section) .. [How to report issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues) 

**IF** you have season packs enabled, then disable. I have Fallon on my production server with no issue at all.
