### ISSUE TITLE
Post processing script can hang the web ui if it is waiting for a response from kodi notifcation

### ISSUE THREAD

**Issue by sanderant** [SickGear/SickGear#658]
I had an issue where Kodi became unresponsive and if the post-processing script was called the web interface would hang. There should be some timeout on this, maybe for other notifications as well.

**Comment by JackDandy** [comment]
Can you check the two real examples (especially his "*steps to reproduce*" section) .. [How to report issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)
