### ISSUE TITLE
Love to have rename options per show

### ISSUE THREAD

**Issue by seabert** [SickGear/SickGear#659]
Some shows just need some special love for whatever reason and I'd really like to be able to set rename options for these individually. Using the sports or anime options for these just doesn't seem right.

**Comment by JackDandy** [comment]
@seabert Thanks for the idea. However, no one else has added to this FR therefore, closed due to lack of interest.

**Comment by JackDandy** [comment]
Its a shame that the "_for whatever reason_" was never made clear on this suggestion. For example, if reason was for an issue of search or media processing, then edit/alternative names can be used, therefore, reducing a need for this request.
