### ISSUE TITLE
db_minor_version value causing db version check fail.

### ISSUE THREAD

**Issue by Apocrathia** [SickGear/SickGear#666]
The last big commit changed something to where the db_minor_version value is now getting appended to db_version. So, when the db version check runs, it thinks the version is 2000301 instead of 20003, and SickGear fails to run. I've managed to narrow down the issue by modifying the sqlite database. Not sure how to correct it, but I'm looking into it now.

**Comment by Apocrathia** [comment]
I think I got it figured out. Not sure if maybe I had an old database from somewhere, but I dropped the db_version table, and recreated it without the db_minor_version column. Inserted the single value of 20003 into it, and it appears to be working. For anyone else having this problem, the error I was getting was `Your database version (2000301) has been incremented past what this version of SickGear supports` Hopefully this provides you with an answer.

**Comment by Apocrathia** [comment]
And this was issue #666. Awesome.

**Comment by Kuhlio** [comment]
I am having the same issue after the latest update, and therefore, do not believe this issue should be closed.

**Comment by Apocrathia** [comment]
The way that I fixed it was by opening the sickbeard.db file in sqlite and running the following queries.
```
drop table db_version;
create table db_version(db_version integer primary key);
insert into db_version(db_version) values(20003);
```

**Comment by JackDandy** [comment]
667
