### ISSUE TITLE
Your database version (2000301) has been incremented...

### ISSUE THREAD

**Issue by zanesc** [SickGear/SickGear#667]
Step 1
branch: master, commit hash: 2369b71a770adec29595725fc046b1dd9630f559, os: Windows 10

Step 2
I expect SickGear to launch but it does not

Step 3
- SickGear usually starts up automatically with my vbs script
- since it is not i tried starting SickGear through the command line with "python C:\SickGear\SickBeard.py"
- I get:
<pre>Starting up SickGear from C:\SickGear\config.ini
Your database version (2000301) has been incremented past what this version of SickGear supports
If you have used other forks of SG, your database may be unusable due to their modifications</pre>

Step 4
Since i can not get SickGear to launch I can not produce any logs

Additional Research
This post suggests that i was using one branch then switched to another but i have never touched any of the branch configuration information and have always been using the same branch (master), and i do not see the sickbeard.db.v11 or any sickbeard.db.vxx files. Only my main sickbeard.db and the sickbeard.db.bak ones exist: http://sickbeard.com/forums/viewtopic.php?p=32546#p32546

**Comment by JackDandy** [comment]
please come to IRC

**Comment by zanesc** [comment]
Thank you for replying. Your hot-fix seemed to have worked until this happened...

<pre>C:\SickGear>python SickBeard.py
Starting up SickGear from C:\SickGear\config.ini
13:14:34 INFO::MAIN :: Backing up database before upgrade
13:14:34 INFO::MAIN :: Proceeding with upgrade
13:14:34 INFO::MAIN :: Dropping redundant column
13:14:39 INFO::MAIN :: Backing up database before upgrade
13:14:39 INFO::MAIN :: Proceeding with upgrade
13:14:39 INFO::MAIN :: Dropping column default_ep_status from tv_shows
13:14:41 INFO::MAIN :: Backing up database before upgrade
13:14:41 INFO::MAIN :: Proceeding with upgrade
13:14:41 INFO::MAIN :: Bumping database version to new SickGear standards
13:14:41 INFO::MAIN :: Backing up database before upgrade
13:14:41 INFO::MAIN :: Proceeding with upgrade
13:14:41 INFO::MAIN :: Bumping database version to force a backup before new database code
13:14:44 INFO::MAIN :: Backing up database before upgrade
13:14:44 INFO::MAIN :: Proceeding with upgrade
13:14:44 INFO::MAIN :: Adding column overview to tv_shows
13:14:44 ERROR::MAIN :: DB error: duplicate column name: overview
13:14:44 ERROR::MAIN :: Failed to update database with error: duplicate column name: overview attempting recovery...
13:14:44 INFO::MAIN :: Restoring database before trying upgrade again
13:14:44 ERROR::MAIN :: Successfully restored database version: 20001</pre>

So i tried starting SickGear again and...

<pre>C:\SickGear>python SickBeard.py
Starting up SickGear from C:\SickGear\config.ini
13:16:02 INFO::MAIN :: Backing up database before upgrade
13:16:02 INFO::MAIN :: Proceeding with upgrade
13:16:02 INFO::MAIN :: Adding column overview to tv_shows
13:16:02 ERROR::MAIN :: DB error: duplicate column name: overview
13:16:02 ERROR::MAIN :: Failed to update database with error: duplicate column name: overview attempting recovery...
13:16:02 INFO::MAIN :: Restoring database before trying upgrade again
13:16:02 ERROR::MAIN :: Successfully restored database version: 20001
</pre>

**Comment by JackDandy** [comment]
@zanesc 
ok can you come to IRC, there seems to be stuff in that DB that i am not aware of.

**Comment by JackDandy** [comment]
Thank you @zanesc that is now fixed too.
