### ISSUE TITLE
Upgrade issues coming from SickBeard master

### ISSUE THREAD

**Issue by Morgon** [SickGear/SickGear#674]
Hello! I've recently rebuilt my Drobo NAS, which has support for SickBeard as an app, albiet on the 'master' branch, so it's very old. After resisting SickRage, I recently learned of SickGear, and thought maybe it would be a good opportunity to try something new.

It would seem that the database is not properly upgraded. I see the following in the logs when starting SG:

2016-03-28 13:20:39 MAIN :: DB error: no such column: indexer_id
2016-03-28 13:20:45 TORNADO :: DB error: no such table: network_timezones
2016-03-28 13:25:41 RECENT-SEARCH :: DB error: no such table: network_conversions

The two network tables are defined in `cache_db.py`

Since there's no `indexer_id`, I can't even click into my configured shows. Is there a way to try to force a database upgrade, so that these can be added...?

Thanks!

**Comment by JackDandy** [comment]
Seems like you failed to do the steps here [migrate](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B0%5D-Migrate)

**Comment by Morgon** [comment]
Oh, you mean a little RTFM would have saved us both some trouble? :)
Apologies, and thank you!
