### ISSUE TITLE
FDH Support for SABnzbd

### ISSUE THREAD

**Issue by cdloh** [SickGear/SickGear#679]
Currently if a download fails in SAB in requires manually going back into SickRage and searching for another.

Can we extend Failed Download Handling to detect if the download has failed in SAB and then searching for another?

**Comment by JackDandy** [comment]
When SAB can fully support it, see... https://github.com/sabnzbd/sabnzbd/issues/546

**Comment by cdloh** [comment]
Sorry didn't see any previous discussion. Sounds good.
