### ISSUE TITLE
Feature Request - Add customisable notification Provider

### ISSUE THREAD

**Issue by cdloh** [SickGear/SickGear#683]
Could a notification provider be added that just uses basic HTTP calls (POST, GET, PUT) and then lets us use variables as keywords ie [episodeTitle], [eventStatus] to either modify the URL we put data too or edit POST data, along with HTTP Headers.

This means that the the notification system can be extended to new services without having to add providers all the time.

**Comment by Hellowlol** [comment]
We use the script notifier to extend plexpy. Check it out.

**Comment by JackDandy** [comment]
Hello @cdloh  
There's no standard way with notification services to authenticate with, send to, and receive responses that can be acted on. This means it's not trivial to create a common "do it all" using only variables and is why creating a tailored based provider is more stable (until a provider changes).
