### ISSUE TITLE
120 folders and PostProcessing fails

### ISSUE THREAD

**Issue by rbhamilton** [SickGear/SickGear#686]
I can manually post-process a single folder at a time.  When I select my finished torrents folder SickGear appears to hang although it's eating up 58% of my CPU.  There are presently 120 folders to process but after 6 hours not a single file had been copied.  Selecting a single folder at a time, each one processes just fine.  I see the SickBeard people have a similar issue but released a patch.  Something to do with detecting which fork was being used?  HELP!?!  And yes, I know this isn't in the right format.

**Comment by JackDandy** [comment]
Hello,
I suggest to pp your folders in batches of say 12. Edge case and some more on top that you are trying to pp so many folders to begin with though.

**Comment by rbhamilton** [comment]
Yes solid suggestion and that does work.  Problem is when I'm finished downloading a torrent I need to seed it back.  I have Sickgear to post-process my downloaded torrents.  If I download even just one season of one TV show that's 22 folders.  Breaking that into two and copying the files and manually processing them defeats the purpose of post processing entirely.

**Comment by rbhamilton** [comment]
Wish you would have left this open as a bug.  It's a serious problem for anybody trying to use post processing.

**Comment by rbhamilton** [comment]
There is nothing written to the log file.  Sickgear just hangs forever.  Nothing displayed on screen.  It is doing something.  It's using a lot of CPU cycles but there's no way to know what it's doing.

**Comment by JackDandy** [comment]
come to irc

**Comment by rbhamilton** [comment]
Ok... will try to figure out how to do that.
