### ISSUE TITLE
Force post-processing not working as intented on full season

### ISSUE THREAD

**Issue by Ziggid** [SickGear/SickGear#692]
**1** 
_Branch_: Master 
_Commit hash_: e0573b8 
_OS_: Ubuntu 14.04.4 LTS

**2** 
_Expect to see_: SickGear replacing all existing "copied files" by hard links
_Actually see_: SickGear only replacing one copied file by a hard link and ignoring the rest

**3**
_Step 1_: Click post-processing
_Step 2_: Select the folder containing the episodes (1 folder containing 24 episodes of 1 season of 1 show)
_Step 3_: Choose process method: hard link
_Step 4_: Check the boxes next to "Force already processed" and "Force replace existing"
_Step 5_: Click Process

**4**
<pre>
Postprocessing results
Processing folder... /storage/utorrent/newcomplete/Series/Friends.S01.To.S10.720p.BluRay.x264-Mixed/Friends.S01.720p.BluRay.x264-PSYCHD
Process path: /storage/utorrent/newcomplete/Series/Friends.S01.To.S10.720p.BluRay.x264-Mixed/Friends.S01.720p.BluRay.x264-PSYCHD
Process files: ['friends.s01e15.720p.bluray.x264-psychd.mkv', 'friends.s01e07.720p.bluray.x264-psychd.mkv', 'friends.s01e10.720p.bluray.x264-psychd.mkv', 'friends.s01e12.720p.bluray.x264-psychd.mkv', 'friends.s01e11.720p.bluray.x264-psychd.mkv', 'friends.s01e02.720p.bluray.x264-psychd.mkv', 'friends.s01e23.720p.bluray.x264-psychd.mkv', 'friends.s01e19.720p.bluray.x264-psychd.mkv', 'friends.s01e16.720p.bluray.x264-psychd.mkv', 'friends.s01e09.720p.bluray.x264-psychd.mkv', 'friends.s01e08.720p.bluray.x264-psychd.mkv', 'friends.s01e04.720p.bluray.x264-psychd.mkv', 'friends.s01e22.720p.bluray.x264-psychd.mkv', 'friends.s01e24.720p.bluray.x264-psychd.mkv', 'friends.s01e20.720p.bluray.x264-psychd.mkv', 'friends.s01e01.720p.bluray.x264-psychd.mkv', 'friends.s01e21.720p.bluray.x264-psychd.mkv', 'friends.s01e03.720p.bluray.x264-psychd.mkv', 'friends.s01e06.720p.bluray.x264-psychd.mkv', 'friends.s01e13.720p.bluray.x264-psychd.mkv', 'friends.s01e14.720p.bluray.x264-psychd.mkv', 'friends.s01e17.720p.bluray.x264-psychd.mkv', 'friends.s01e18.720p.bluray.x264-psychd.mkv', 'friends.s01e05.720p.bluray.x264-psychd.mkv']
Process video files: ['friends.s01e15.720p.bluray.x264-psychd.mkv', 'friends.s01e07.720p.bluray.x264-psychd.mkv', 'friends.s01e10.720p.bluray.x264-psychd.mkv', 'friends.s01e12.720p.bluray.x264-psychd.mkv', 'friends.s01e11.720p.bluray.x264-psychd.mkv', 'friends.s01e02.720p.bluray.x264-psychd.mkv', 'friends.s01e23.720p.bluray.x264-psychd.mkv', 'friends.s01e19.720p.bluray.x264-psychd.mkv', 'friends.s01e16.720p.bluray.x264-psychd.mkv', 'friends.s01e09.720p.bluray.x264-psychd.mkv', 'friends.s01e08.720p.bluray.x264-psychd.mkv', 'friends.s01e04.720p.bluray.x264-psychd.mkv', 'friends.s01e22.720p.bluray.x264-psychd.mkv', 'friends.s01e24.720p.bluray.x264-psychd.mkv', 'friends.s01e20.720p.bluray.x264-psychd.mkv', 'friends.s01e01.720p.bluray.x264-psychd.mkv', 'friends.s01e21.720p.bluray.x264-psychd.mkv', 'friends.s01e03.720p.bluray.x264-psychd.mkv', 'friends.s01e06.720p.bluray.x264-psychd.mkv', 'friends.s01e13.720p.bluray.x264-psychd.mkv', 'friends.s01e14.720p.bluray.x264-psychd.mkv', 'friends.s01e17.720p.bluray.x264-psychd.mkv', 'friends.s01e18.720p.bluray.x264-psychd.mkv', 'friends.s01e05.720p.bluray.x264-psychd.mkv']
Processing /storage/utorrent/newcomplete/Series/Friends.S01.To.S10.720p.BluRay.x264-Mixed/Friends.S01.720p.BluRay.x264-PSYCHD/friends.s01e15.720p.bluray.x264-psychd.mkv
Parsed friends - S1E15 [GROUP: psychd] [ABD: False] [ANIME: False] [whichReg: ['standard']]
.. from friends.s01e15.720p.bluray.x264-psychd.mkv
Retrieving episode object for 1x15
Using "720p BluRay" quality from the snatch history
Force replace existing episode option is enabled, marking it safe to replace
Deleted file /storage/video/Series/Friends/Season 01/Friends - S01E15 - The One With The Stoned Guy.mkv
Found release name friends.s01e15.720p.bluray.x264-psychd
Destination folder for this episode is /storage/video/Series/Friends/Season 01
Hard linked file from /storage/utorrent/newcomplete/Series/Friends.S01.To.S10.720p.BluRay.x264-Mixed/Friends.S01.720p.BluRay.x264-PSYCHD/friends.s01e15.720p.bluray.x264-psychd.mkv to /storage/video/Series/Friends/Season 01/Friends - S01E15 - The One With The Stoned Guy.mkv
Successfully processed friends.s01e15.720p.bluray.x264-psychd.mkv
Found a video, but that release Friends was already processed,
.. skipping: friends.s01e14.720p.bluray.x264-psychd.mkv
Found a video, but that release Friends was already processed,
.. skipping: friends.s01e24.720p.bluray.x264-psychd.mkv
Found a video, but that release Friends was already processed,
.. skipping: friends.s01e12.720p.bluray.x264-psychd.mkv
...
...
...
Found a video, but that release Friends was already processed,
.. skipping: friends.s01e06.720p.bluray.x264-psychd.mkv
---------------------------------------------------------------------
Successfully processed at least one video file , others were skipped.
</pre>

**Comment by JackDandy** [comment]
Hello @Ziggid 

Strange that his issue has never come up with copy or move given the base processing is the shared, so, can you create the same effect with "Copy" or "Move" or is this issue purely isolated to hard links ?

I do hope you **can** create the same effect because it may take some time to find otherwise :|

**Comment by Ziggid** [comment]
Hi @JackDandy 

Thanks for the reply. Just checked and the same happens with "Copy". Guess it's something on my side, but eager to find out what it is.

**Comment by Ziggid** [comment]
Interestingly enough, even when I delete the destination files, and mark them as "skipped", SickGear still won't copy them. Additionally after this, regardless of whether I removed the destination files, the episodes are no longer marked as skipped, but as downloaded again and trying to mark them "skipped" doesn't do anything.

**Comment by JackDandy** [comment]
Excellent, ok that's good news and something to bite into.

**Comment by JackDandy** [comment]
#694

@Ziggid Come to IRC if you are unsure how to test that this fix works
