### ISSUE TITLE
A custom initial quality is and must be set something or SG wont know what to download

### ISSUE THREAD

**Issue by mayoko185** [SickGear/SickGear#695]
First off thanks for all your work on sickgear!

For some reason episodes no longer download on their own, I have to either ask it to search for an episode or wait for/force a backlog search.

I'm running Ubuntu Server 16.04 fully updated and on branch master (although I did switch to develop and had the same issue). I did notice since ive had this issue I get the following error in my logs not sure if its releated:
BACKLOG :: Exception generated in thread BACKLOG: max() arg is an empty sequence

[edit] ```(log received)```

I appreciate any help with this issue, its not a big deal since manual / backlog search still works but id like to try and fix it if I can.

**Comment by JackDandy** [comment]
Hello @mayoko185 

The logs indicate that you have two shows that don't have at least one initial quality set.

Can you confirm ?

**Comment by mayoko185** [comment]
Yes that is correct I have two shows set to custom, and it looks like one of them didn't have a initial quality set.

**Comment by JackDandy** [comment]
The ui does say ```An Initial quality episode must be found before an Upgrade to selection is considered.``` so marking this thread "question" rather than an issue to look further into.

Enjoy.
