### ISSUE TITLE
Unable to change Episode Status

### ISSUE THREAD

**Issue by tordormore** [SickGear/SickGear#696]
When attempted to manually change the status of a Skipped season to Downloaded, I keep getting an error stating "Refusing to change status of 1x10 to DOWNLOADED because it's not SNATCHED/DOWNLOADED".

I understand that it does not see that it was previously snatched or downloaded, because I did not allow SickGear to grab this episode.  I grabbed the whole season outside of SickGear, and now I want to change the status so that I can visually see in SickGear that I already have that episode and don't need to worry about telling SickGear to go back and fetch it for me.  My season is already complete.

I can probably work around this by stopping my NZB service, then setting the status to wanted, then wait for it to snatch the episode, then change the status to downloaded, but why am I being restricted from changing the status to whatever I want?  I should not be restricted in any way whatsoever.  Even  if I have never downloaded an episode, I should still be able to change the status to whatever I want.

**Comment by JackDandy** [comment]
>  I grabbed the whole season outside of SickGear

Be sure to import the episodes properly into SickGear. For example, through post processing or add existing shows.

**Comment by JackDandy** [comment]
While editing the changes text on the develop branch I noticed the following...

* Allow episode status "Skipped" to be changed to "Downloaded"
* Allow found "Skipped" episode files to be set "Unknown" quality

switch to develop to use that change that was committed months ago.
