### ISSUE TITLE
small graphical glitch with a national flag

### ISSUE THREAD

**Issue by martin-cz** [SickGear/SickGear#711]
Hi guys,
  there's one small glitch, that if you'll choose subtitles in Czech, it'll show you Serbian flag (cs.png), instead of the right Czech (cz.png).

I think, it's due to this line in the lib\subliminal\languages.py

             ('cze', 'ces', 'cs', u'Czech', u'tchèque'),

We used to have CS, however it's not our ISO country code anymore.

it would be great, if you could fix this up :)

**Comment by JackDandy** [comment]
hello @martin-cz 

> it would be great, if you could fix this up :)

What should be changed ?

**Comment by martin-cz** [comment]
Hi Jack,
   it should load the right one flag, cz.png instead of cs.png it loads now, when you chosen Czech subtitles

**Comment by JackDandy** [comment]
Hi, I mean do you know the actual changes that i should apply to the code that works for you ?

**Comment by martin-cz** [comment]
Hi Jack,
  to be honest, I'm not a python guy, so I just workarounded it by renaming the flag. But if I'm getting it right, the code / web chooses the right icon according the two digit code so, what I was thinking of, would be to try to change:


 ('cze', 'ces', 'cs', u'Czech', u'tchèque'),

to 

 ('cze', 'ces', 'cz', u'Czech', u'tchèque')

**Comment by JackDandy** [comment]
Hi Martin,

> what I was thinking of, would be to try to change:

**YOU** try it, test it, if it works, let me know.

**Comment by martin-cz** [comment]
Hi Jack,
   tried it,  it doesn't work. Then I've checked up the subliminal and babelfish source codes and all the country and language codes are acording the respective ISOs.

The main problem is, that the AJAX import two digits language codes, and the flags are actually 2 digit country codes, so this is the difference:
COUNTRY:
   ('CZ', 'CZE', '203', u'Czech Republic'),
LANGUAGE:
  ('cze', 'ces', 'cs', u'Czech', u'tchèque'),

The very same problem is for the arabic for example, where it would be hard to find the appropriate flag, but now it shows ar.png - Agentina.

There's a note in the subliminal code about improving the country / language matching, but I think, it won't help.

So let's keep it closed. Btw thanks for maintaning this piece of code :)
