### ISSUE TITLE
TorrentDay authentication issues

### ISSUE THREAD

**Issue by justinan7** [SickGear/SickGear#718]
Can't authenticate with torrentday.com; perhaps their new login which requires captcha is the problem?

**Comment by JackDandy** [comment]
Hello @justinan7 
[[How to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

**Comment by JackDandy** [comment]
Any authentication issues are due to either **incorrect** user data or not being on **develop** branch.

The captcha change was dealt with 16 days ago here... https://github.com/SickGear/SickGear/pull/698/files

**Comment by JackDandy** [comment]
[Change to handle the TD captcha addition](https://github.com/SickGear/SickGear/pull/698/commits
) was added Jun 8, 2016 (16 days ago at time of writing).

TD authentication issues **_do not exist_** on the **develop** branch with correctly entered data... [how to use Cookies (e.g. TorrentDay)](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#cauth)

**Comment by JackDandy** [comment]
@sund00bie the TD issue was reported, we fixed it, "some" over there lie to you and say we haven't fixed it in order to keep you over there, come on over, you're more than welcome.

**Comment by sund00bie** [comment]
@jackDandy such nice words! Thanks..

I've already migrated over =)  The arch Linux guide was super easy to
follow.

Keep up the good work

**Comment by Fungie** [comment]
I have no idea whats going on here.

**Comment by JackDandy** [comment]
@Fungie Your TD issue thread that duramato linked from above was opened May 30th, we fixed the TD issue a few days later without even knowing about your post.  Some 34 days after your post was created, our weeks old fix was used in their repo.  Therefore, if you want the stability and support that inspire other sick* forks to copy from, then their actions prove that this repo is their source, so come on over, you're more than welcome.

**Comment by sund00bie** [comment]
Just an update. After migrating across i confirm TD *DOES NOT* work. Its
best to stay with SickRage

2016-07-07 18:50:15 BACKLOG-264586 :: [TorrentDay] :: Failed to
authenticate with TorrentDay, abort provider"

**Comment by JackDandy** [comment]
@sund00bie thanks for the feedback.

Have you only just tried TD, or was it working and then failed ? Ive been using it without issue, as have others.

**Comment by JackDandy** [comment]
@sund00bie thanks for the feedback.  Have you only just tried TD, or was it working and then failed ? I've been using it without issue, as have others.

My findings...
<pre>
11:02:43 INFO::BACKLOG-269750 :: Beginning backlog search for: [Wayward Pines]
11:02:43 INFO::BACKLOG-269750 :: [TorrentDay] :: Performing episode search for Wayward Pines
11:02:45 INFO::BACKLOG-269750 :: [TorrentDay] :: 8 episode items in response from https://torrentday.eu/t?2;7;24;26;32;q=Wayward.Pines+S02E07;o=seeders
11:02:48 INFO::BACKLOG-269750 :: Quality is 720p WEB-DL for Wayward.Pines.S02E07.720p.WEB-DL.x264-FUM
11:02:48 INFO::BACKLOG-269750 :: Quality is 1080p HD TV for Wayward.Pines.S02E07.1080p.HDTV.x264-CRAVERS
11:02:48 INFO::BACKLOG-269750 :: Quality is HD TV for Wayward.Pines.S02E07.720p.HDTV.x264-AVS
11:02:48 INFO::BACKLOG-269750 :: Downloading Wayward.Pines.S02E07.720p.WEB-DL.x264-FUM from TorrentDay
</pre>

**Comment by JackDandy** [comment]
@sund00bie could you please correct your statement at [...] given you made a user error.

**Comment by JackDandy** [comment]
@sund00bie could you please correct your statement at [...] given you made a mistake. ty.

Funny that even up until today, that fork fix still didn't work, imitators try but the source is the sauce.

**Comment by Fungie** [comment]
How is sickgear different to sickrage?

**Comment by p0psicles** [comment]
I know we've had our differences. But there is no reason to call me an imitator. The idea of using the cookie field was not yours. In fact it was already used for the rss torrent providers. But if your claiming the source is the sauce, then we should all move back to sickbeard right?

Every fork has it's pro's and con's. For example I bet SG doesn't support manual search (and picking your own releases/results right?). Well Medusa does. And then SickRage has made allot of improvements to a fully responsive UI and localisation.

Also I know that I made a mistake implementing the TD fix for sickrage. But that's mostly because i'm working actively on Medusa. And by the way. It's working perfectly there.

That said, I do need to defend sickgear here. Sundoobie's made his conclusion too quick. You've got this TD stuff working out for your users, with a clear wiki. Got to give you that. But there is no reason to be so defensive towards the other forks.

**Comment by JackDandy** [comment]
@p0psicles you wanna debate, come find me. i Have no issue to talk to you. but not here.

**Comment by matthijsvh** [comment]
@Fungie In my opinion sickgear looks more proffesional. Sickrage just seems like one big drama-disco.

**Comment by Imnotgoodathis** [comment]
> matthijsvh commented 12 minutes ago • edited
> @Fungie In my opinion sickgear looks more professional. Sickrage just seems like one big drama-disco.

Most of the drama is from users of other forks though. Would also call it kinda unprofessional to try "steal" users :p

**Comment by JackDandy** [comment]
@Imnotgoodathis you remember the wholesale "user stealing" that sr did in the last year, that wasn't to inform uses of a genuine fix, it was a full on mission by at least 5 guys against one.

**Comment by Fungie** [comment]
Can I unsubscribe from this?

**Comment by JackDandy** [comment]
Fungie, i will lock it.
