### ISSUE TITLE
Error when performing backlog-search for anime-series on nzbs.org

### ISSUE THREAD

**Issue by aMvEL2** [SickGear/SickGear#724]
BRANCH: develop / COMMIT: abb6a52d3203d3eaa417c0cca417f7f942e58816

**Issue:**
SickGear errors out when performing manual backlog-search for an episode of a series that is marked as anime.

**Reproduction:**
- Add series to Sickgear, and mark to treat as anime.
- Make sure nzbs.org is set as provider. (I only have that provider active, so can't say if it happens with other providers).
- Mark an episode as wanted (Or manually force backlog search for an already wanted episode)
- Nothing is snatched, and error is presented in log: _"TypeError: %d format: a number is required, not str"_

If you remove the checkmark to treat as anime, search is performed without error, but of course does not give any matches.

**Log:**
[edit] can be deleted. thank you. JD

**Comment by JackDandy** [comment]
#726
