### ISSUE TITLE
'Update Now' Fails

### ISSUE THREAD

**Issue by 88keyz** [SickGear/SickGear#729]
On develop branch and when I receive an update notification I get an error after I click 'Update Now'

    Updating b02b8a1..012c12e
    2016-07-05 07:35:01 CHECKVERSION :: git pull -f origin develop returned : From https://github.com/SickGear/SickGear
     * branch            develop    -> FETCH_HEAD
    error: Your local changes to the following files would be overwritten by merge:
	CHANGES.md
	gui/slick/interfaces/default/config_providers.tmpl
	gui/slick/js/configSearch.js
	sickbeard/clients/__init__.py
	sickbeard/nzbget.py
	sickbeard/properFinder.py
	sickbeard/providers/generic.py
	sickbeard/search.py
	sickbeard/webserve.py
    Please, commit your changes or stash them before you can merge.
    Aborting

I am not running any modified files, this is a fresh pull from git.  Have to update manually and run the 'git reset --hard' command before running 'git pull'.  Would it be possible to perform the 'reset --hard' option before running the update command to prevent code update failures.

**Comment by Hellowlol** [comment]
That would be really bad imo

**Comment by 88keyz** [comment]
Why, you could always disable automatic updates and do it manually if you are the sort of person who alters the code.  But if you're going to do that why not just fork it and run your own version.

**Comment by Hellowlol** [comment]
Git is very resilient, at least my experience so it better to fix what ever reason it wouldn't update rather doing a hard reset automatically.

**Comment by JackDandy** [comment]
@88keyz for that error to appear, you must have changed files locally, that is fine if you do not want the upgrader to work, we do not force an overwrite as your edits are, well, yours. Therefore, either stash or backoff the files you edited. This is not an issue with the updater.
