### ISSUE TITLE
Unable to install Cheetah on python 2.7.11

### ISSUE THREAD

**Issue by merlin1320** [SickGear/SickGear#735]
I cannot even get the python installation to complete. I keep getting errors when setting up Cheetah so I cannot run SickGear. Here is the error I'm getting when following the commands listed "error: Setup script exited with error: [Error 2] The system cannot find the file specified". This is only when I try to run command easy_install cheetah. 

Steps 

1. Install python 2.7.11 Active State
2. Run the following commands
3. python -m pip install --upgrade pip
4. pip install --upgrade pyopenssl
5. easy_install ndg-httpsclient
6. Attempt to run Cheetah install
7. Receive error

Attempting to install SickGear since SickRage isn't working properly for me. 
![cheetah](https://cloud.githubusercontent.com/assets/20392039/16720784/c959120a-46f6-11e6-91a1-e8aad33f8a17.PNG)

**Comment by Hellowlol** [comment]
I would download https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266

Then:
pip uninstall Cheetah
pip install setuptools --upgrade
pip install Cheetah

SG will feel much more snappy ^^

**Comment by JackDandy** [comment]
Hello @merlin1320 

Please follow [every step here](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B1%5D-Windows)

If that does not work for you, please state windows version.

**Comment by Hellowlol** [comment]
You should consider adding it to your windows guide because you product feels much better when cheetah is fast :)

**Comment by JackDandy** [comment]
@Hellowlol ahh thanks. I will try it out :)

**Comment by merlin1320** [comment]
@JackDandy I did follow all the steps and when I ran the steps it told me I now have Python 2.7.11. It was actually @Hellowlol 's suggestion that allowed me to install Cheetah and get it running. Thank you for your help.
![python](https://cloud.githubusercontent.com/assets/20392039/16745904/46d621ae-4775-11e6-9600-933a1a1fdc5a.PNG)

**Comment by JackDandy** [comment]
@merlin1320 As I said, the official download is 2.7.10 on the ActiveState webpage.  You have installed a custom set up that may now introduce it's own set of issues that a system without those files doesn't have.
