### ISSUE TITLE
IRC

### ISSUE THREAD

**Issue by tpitman** [SickGear/SickGear#738]
I opened an issue and got an email from JackDandy saying to go to IRC because it would be easier to help me there. The issue was closed so I couldn't respond.

I have no idea how to get to the IRC and am not at home right now anyway where the device is I need help with.

Someone please let me know how to get to IRC for help with SickGear and if later tonight would still be a good time to get help.

**Comment by JackDandy** [comment]
Scroll down for IRC details at [the main project page](https://github.com/SickGear/SickGear)
