### ISSUE TITLE
Signal handler code is broken

### ISSUE THREAD

**Issue by gsly** [SickGear/SickGear#739]
I'm running SickGear under systemd on Ubuntu 16.04 and I noticed systemd couldn't properly stop the service (it sends SIGTERM first) until a timeout occurs and then it just kills it with SIGKILL,. I looked at the code and the sig_handler method looks to have incorrect logic. This patch makes it work for me:

```
diff --git a/sickbeard/__init__.py b/sickbeard/__init__.py
index 7fd8c7a..d8480a8 100755
--- a/sickbeard/__init__.py
+++ b/sickbeard/__init__.py
@@ -1339,7 +1339,7 @@ def halt():


 def sig_handler(signum=None, frame=None):
-    if isinstance(signum, type(None)):
+    if not isinstance(signum, type(None)):
         logger.log(u'Signal %i caught, saving and exiting...' % int(signum))
         events.put(events.SystemEvent.SHUTDOWN)
```

**Comment by JackDandy** [comment]
@gsly can you try develop, there was already a  push for this the other day
