### ISSUE TITLE
Issue with handling of UnRar files during Post Processing.

### ISSUE THREAD

**Issue by x-zempt** [SickGear/SickGear#741]
Hi SickGear team, just moved over from SickRage, loving the move so far. I moved over to the develop branch to make use of the TD auth working :D
Unfortunately I have run into a little issue.

Previously I would have my downloads copied to my 'show directory' leaving the original intact to seed. With Rar files it would previously process in one of two ways (can't recall which one it was, but both are effective).

1. Extract to current download directory, copy to 'show directory' and then delete the original extracted files.

2. Extract direct to 'show directory', leaving rar files intact to seed.

From what I can see, there is only an option/tickbox to extract rar into download directory so it will than copy to 'show directory'. Unfortunately it doesn't cleanup the extracted file/s once it has copied. Leaving the original RAR and extracted files in the download directory.

I hope what I am saying makes sense. 

Thanks!

**Comment by JackDandy** [comment]
Hello @x-zempt yup, makes sense, can you come to IRC so that you can test the change to address this issue when it is ready.  Thanks.

**Comment by JackDandy** [comment]
@x-zempt Try setting pp to **Move** not _Copy_. I still think a little logic is missing, but **Move** should work for some releases.  I still haven't seen you in IRC.

**Comment by JackDandy** [comment]
@x-zempt the logic for this feature is complete awaiting testing.

**Comment by JackDandy** [comment]
#757
