### ISSUE TITLE
Sickrage PP ignored the remove_filename_chars

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#742]
I just noticed that a few shows with episodes containing an ' where processed with one again even though the remove_filename_chars= "'" which worked perfectly fine after you added it.
I don't exactly know in which release it happened (the one from yesterday I think) but could you check if the code picks it up and removes it again?

Didn't have any issues with PPing after the option got added so it really does work for me :+1:

**Comment by JackDandy** [comment]
Wrong tracker

**Comment by Th3MadHatter** [comment]
Let me do it again then, because you know the issue already. you know what version i'm on because its always the latest dev and yet you seem to not take me seriously at all.

The problem exists in BRANCH: develop / COMMIT: 6a6fd914b65c68ed508c7c498c883a582f22f9b9
The problem is It ignores remove_filename_chars command added by JackDandy (you) in every single case, 

E.g. Original name Gamers.Guide.to.Pretty.Much.Everything.S02E02.The.Olym-pig.Torch.720p 

PP result **Gamer’s** Guide to Pretty Much Everything - S02E02 - The Olym-pig Torch.

Reproduce steps:
Click post processing, go to directory, post process.

Straight from the log:
Hard linked file from C:\complete\processed\tv\Gamers.Guide.to.Pretty.Much.Everything.S02E02.The.Olym-pig.Torch.mkv\Gamers.Guide.to.Pretty.Much.Everything.S02E02.The.Olym-pig.Torch.720p.mkv to G:\videos\tv\Gamers Guide to Pretty Much Everything\Season **02\Gamer’s** Guide to Pretty Much Everything - S02E02 - The Olym-pig Torch.mkv

Conclusion, it ignores remove_filename_chars or the command has been removed.

**Comment by JackDandy** [comment]
The command has not been removed, it was added over 6 weeks ago as a special feature for you.

[Add config.ini file only setting "remove_filename_chars"](https://github.com/SickGear/SickGear/pull/707)

IF you want to investigate this issue further, then please come to IRC.

**Comment by Th3MadHatter** [comment]
Will do as soon as i have a moment :)
