### ISSUE TITLE
[Anime] Torrent providers throw error, not snatching.

### ISSUE THREAD

**Issue by ItsMeMike** [SickGear/SickGear#746]
# Branch: develop (fd325c5cfabf59bf8c1abb504ae7014ccfa856ee)
Expectation | Result
------------ | -------------
When searching for an anime (in this example Taboo Tattoo E05 in HD1080p quality, wanted group "HorribleSubs") and checking the logs, it seems that SG finds some results, and tries to snatch the best hit. I expect it to send it to µtorrent. | SickGear does not send it to µtorrent, and sometimes does not give an error, but looking deeper in the logs there is one. I got this error with both NyaaTorrents and TokyoToshokan on multiple tries on different days. After that it seems to do some query that it keeps doing over and over again? Not sure why that is done.

**Steps to reproduce:**
*1)* Enable NyaaTorrents or TokyoToshokan (or both, whatever) provider
*2)* Add an anime as a show (see expectation for my example)
*3)* Search for an ep
*4)* Check the logs on Db level to see the error.

**Logfile** showing it goes wrong with NyaaTorrents can be found here [edit] ** data removed, thanks
**Logfile** showing it goes wrong with TokyoToshokan can be found here [edit] ** data removed, thanks.

I tried this with One Piece ep751 and Naruto Shippuden ep470 and the results were the same.

**Comment by JackDandy** [comment]
#748
