### ISSUE TITLE
Language indicator

### ISSUE THREAD

**Issue by msurg** [SickGear/SickGear#747]
Sorry for writing here if it is not appropriate but couldn't find any other source to request this feature.

Sickgear 0.11.14 on Centos 6.8. While downloading subtitles sickgear puts two letter language indicator into the filename. Is it possible to make it optional like sickrage do on subtitles configuration page (multi-language vs single-language)?

**Comment by JackDandy** [comment]
Hello @msurg 

SG will not improve subtitle support because specialist subtitle management tools exist.

Thank you.
