### ISSUE TITLE
config.ini should not be world-readable by default perhaps?

### ISSUE THREAD

**Issue by HyperBaton** [SickGear/SickGear#759]
I noticed that config.ini is world-readable by default. Would it perhaps be a good idea to make it not world-readable? I know it's possible to encrypt the passwords, but some users might not notice this option. Just a thought!

**Comment by JackDandy** [comment]
Hello @HyperBaton 
Development is on Windows, how files are chmodded under Linux is an end user matter.  However, if you look at the install guides in the wiki and can recommend a step to insert that would generally help all users that install under Linux, then please do.
