### ISSUE TITLE
Add IMDB or TV.com link to show page

### ISSUE THREAD

**Issue by hobojoe720** [SickGear/SickGear#760]
Something that seems to be missing is that when you view a show and want to find out more info on it, is to have a link to IMDB or TV.com. 

TV.com is way more useful as they have info such as if a show has been renewed or canceled.

**Comment by JackDandy** [comment]
Hi @hobojoe720 

Do you mean like these?
<img src="http://i.imgur.com/zlPCO3N.png">

**Comment by hobojoe720** [comment]
I see 2 didnt notice them before, is TV.com possible?

**Comment by JackDandy** [comment]
Added to list of potential todo's. :)
