### ISSUE TITLE
Cant switch to develop branch

### ISSUE THREAD

**Issue by justinan7** [SickGear/SickGear#763]
![config](https://cloud.githubusercontent.com/assets/20049106/17945834/647dda56-69fa-11e6-9b4e-baa5c8c6bc87.png)
![error](https://cloud.githubusercontent.com/assets/20049106/17945833/6479dee2-69fa-11e6-8528-7307073a4f37.png)

**Comment by JackDandy** [comment]
@justinan7 See the wiki for various install guides or go to IRC for help.
