### ISSUE TITLE
IPTorrents searches not finding shows.

### ISSUE THREAD

**Issue by st0neh** [SickGear/SickGear#765]
Hi,

I haven't seen any shows actually manage to download from IPTorrents for the past week or so, possibly longer. Manually checking out the searches listed in the SickGear logs shows episodes available, but they're just not actually downloading. I suspect this may be related to the website changes that have been happening at IPTorrents recently.

It looks like SickGear is searching for show.title.with.periods while IPTorrents itself is listing show titles with spacing instead of periods as separators.

**Comment by JackDandy** [comment]
Hello @st0neh 
I can't help without [missing report details](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)
