### ISSUE TITLE
Downloads with the year in the name

### ISSUE THREAD

**Issue by hobojoe720** [SickGear/SickGear#769]
Some shows tend to have a year in the name. As an example "Ballers". Every episode of Ballers has 2015 in the file name. Which for some reason means that SickGear wont download it, and if it does it wont process it. There are no logs as it doesnt find the show. 

The latest filename is: Ballers.2015.S02E08.720p.HDTV.x264-KILLERS

**Comment by JackDandy** [comment]
Simply edit the show, and add the "Alternative.Showname.2015"
