### ISSUE TITLE
release group not recognized from filename if file downloaded manually

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [SickGear/SickGear#77]
BRANCH: (master) / COMMIT: (8bc6e7bbea76d566a66a09e00a5a401ff096cd90) 
Issue: release group not recognized from filename if file downloaded manually

When SG processes episode(files) it did not snatch itself(so for example you manually added it), SG is unable to figure out what the release group of an episode is. This happens for both anime as for non-anime
example file names:
two.and.a.half.men.1201r.hdtv-lol.mp4
[HorribleSubs] Sword Art Online II 21 [720p].mkv

Steps to reproduce:
1. Add release group to the file renaming string
2. Add a show
3. Manually download something to the processing folder

**Comment by CtrlAltDefeat94** [comment]
BRANCH: (develop) / COMMIT: (b28efcbfb042ebc2eb09f51f70388aae7bd6a40c) 

The issue can be reproduced in two ways, both the earlier steps given by @vergessen and the steps by me.

Log:
https://gist.github.com/CtrlAltDefeat94/922fa3b93d7c142b62ed
File that is being processed: [Exiled-Destiny]_Fairy_Tail_S01E01_(8EF5A66B).mkv

The release group here is Exiled-Destiny, yet during post processing the release group becomes SickGear.

The renaming pattern in this case is:
Season %S\%RN
This is an example of an anime episode BUT IT HAPPENS WITH NON-ANIME AS WELL

I will try the same with a non-anime file now.

**Comment by adam111316** [comment]
repo'd on: develop 9a95b7f2a123724c37d8fcf166f7e6ff818e11a5

**Comment by CtrlAltDefeat94** [comment]
Updated previous post with the latest discoveries.
