### ISSUE TITLE
Unable to add Custom Torrent Provider

### ISSUE THREAD

**Issue by theimmortal68** [SickGear/SickGear#781]
1. BRANCH: Develop; COMMIT: 527cc06f07af5ddd421a4101b55768219db6ae18; OS: Arch Linux

2. When attempting to add an RSS feed for Xspeeds, I get the following pop-up message:
Error when trying to load RSS: 'NoneType' object is not iterable

3. On the Configure Custom Torrent Provider screen, I enter the following info:
Provider Name: Xspeeds
RSS URL: https://www.xspeeds.eu/rss.php?secret_key=XXXXXXXXXX&feedtype=download&timezone=-8&showrows=50&categories=47
Cookies: uid=XXXXX; pass=XXXXX

In my browser, the cookies for Xspeeds are listed as c_secure_uid and c_secure_pass.  I tried both.  The RSS Feed is viewable in my browser (Chrome).  To ensure it was not an issue with Xspeeds specifically, I also tried adding an RSS feed from IPTorrents and PrivateHD, both with the same results.

4. I have the log set to Db and the next 4 levels, however nothing in the log corresponds to my attempts to add an RSS feed.

**Comment by JackDandy** [comment]
Hello @theimmortal68 

fyi, You are aware IPTorrents and PrivateHD are built in and provide full search capabilities, I guess you were just testing the RSS feeds thoughm but im just saying - just in case. 

XS doesn't need cookies but there was no good way for the user to know, this and other things have been addressed so now the overall UX of this feature is improved.

Thanks.

**Comment by theimmortal68** [comment]
Works beautifully!  Thank you!
