### ISSUE TITLE
Issues with IPT

### ISSUE THREAD

**Issue by anakaine** [SickGear/SickGear#787]
Constant errors when attempting to retrieve results from IPT. Unsure of the cause

Checking the first URL below in a browser, results are actually returned

```
17:43:11 INFO::BACKLOG-110381 :: [IPTorrents] :: No episode items in response from https://iptorrents.eu/t?4;5;22;23;24;25;26;55;65;66;73;78;79;q=Archer.2009 S03E04;qf=ti;o=seeders#torrents
17:43:11 INFO::BACKLOG-110381 :: Falling back to season pack search ...
17:43:11 INFO::BACKLOG-110381 :: Performing season pack search for Archer (2009)
17:43:12 INFO::BACKLOG-110381 :: No season items in response from https://iptorrents.eu/t?4;5;22;23;24;25;26;55;65;66;73;78;79;q=Archer.2009 S03;qf=ti;o=seeders#torrents
```

**Comment by JackDandy** [comment]
Help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

**Comment by anakaine** [comment]
Followed the directions for specifying alternate names. Still no dice. 

The following is a screenshot including relative terminal output and browser check of the search URL, and another screenshot of the alternate naming scheme. Despite results being found SickGear does not appear to be picking the results up. Log includes no discernable reason for not finding an episode (no results returned / results returned do not match episode pattern name / etc).

![sickgear_not_finding_ipt](https://cloud.githubusercontent.com/assets/7123659/19017386/d59ca390-887a-11e6-8da6-b2de1810bba6.JPG)
![sickgear_alt_naming](https://cloud.githubusercontent.com/assets/7123659/19017387/de749c98-887a-11e6-83fb-e61724c95df6.JPG)

**Comment by anakaine** [comment]
This was the answer, from 2-3 days ago. 
https://github.com/SickGear/SickGear/issues/765

Incidently you've had this issue quite a bit recently judging by the closed requests of late. Probably would have been better to link to that rather than to an FAQ about incorrect search terms.

**Comment by JackDandy** [comment]
2-3 days ago ?  today is Oct 2, that answer was Aug 29, so over 30 days ago, and still my answer to you yesterdays holds true, had you have supplied the branch info, you would have been directed the same way, but you didn't so i needed more info - this is why we say, please do not guess what info we need as it simply prevents us from helping you faster,
