### ISSUE TITLE
SickGear to Deluge Label appointment not occuring

### ISSUE THREAD

**Issue by anakaine** [SickGear/SickGear#790]
Branch: BRANCH: master / COMMIT: b9e31eca2814b144d193ab7bc8385a192896c3ae (Downloaded from the develop branch, but the about/info still says master, despite evident changes)
Windows 10, x64
Deluge 1.3.13

Expectation: SickGear provides a label to Deluge for the downloaded torrent file. Label matches an existing deluge label, which subsequently has a 'move on complete' rule attached to it. Imported torrent is assigned the label.

Result: SickGear successfully passes torrent to Deluge. The label however is not passed to Deluge successfully, and thus torrent is imported without label - thus no move on complete / post processing trigger.
------------ | -------------

**Steps to reproduce:**
*1)* Assign label "TV" under "Search Settings --> Torrent Search --> Set Torrent Label" in SickGear
*2)* Create label "TV" in Deluge. Optionally, apply a "move to completed folder" rule to this label.
*3)* Ensure SickGear and Deluge are linked. In this case, Deluge resides at: http://127.0.0.1:8112/ and has a default password of 'deluge'. Connection test should be successful.
*3)* Force a search on a new/old/missing episode in SickGear so that a torrent download is triggered and the torrent is passed to Deluge.
*4)* Observe no category assigned in Deluge

GIST
https://gist.github.com/anakaine/631bbc86ef00c6e22911fb98d4781f01.js"

**Comment by JackDandy** [comment]
Sounds like you did not switch to using develop inside SG itself... you also must have git installed to switch and to accurately show what branch you are on otherwise a default master will be used, (see Windows install guide in Wiki), if you do have git correctly installed, then...
<a name=""><img src="http://i.imgur.com/5mGWD4b.png"></a>

**Comment by JackDandy** [comment]
Scratch my previous answer, looking into this...

**Comment by JackDandy** [comment]
It works fine... see the label on the right..
<a name=""><img src="http://i.imgur.com/huaChUn.png"></a>

Please make sure you are on develop...
<a name=""><img src="http://i.imgur.com/5mGWD4b.png"></a>

Also, check that you actually saved the label in your search settings, and that you have enabled the label plugin as directed in the tip.
<a name=""><img src="http://i.imgur.com/bAIb1nf.png"></a>

**Comment by JackDandy** [comment]
It works fine... tested and the label on the right is as expected.
Image 1
<a name=""><img src="http://i.imgur.com/tcBRBWv.png"></a>

Please **make sure** you are on develop. If you don't see expected version, that can indicate perhaps git is not installed correctly, you may need to install from the beginning to ensure everything is correct - see wiki.
Image 2
<a name=""><img src="http://i.imgur.com/5mGWD4b.png"></a>

Also, check that you actually saved the label in your search settings, and that you have enabled the label plugin as directed in the tip. (SSL not enabled in Deluge WebUi settings)
Image 3
<a name=""><img src="http://i.imgur.com/AsBLSrO.png"></a>

**Comment by anakaine** [comment]
Thanks. 
Changing to dev branch in general settings was the key.
