### ISSUE TITLE
Error when opening "Episodes"-tab on Synology NAS

### ISSUE THREAD

**Issue by aMvEL2** [SickGear/SickGear#793]
BRANCH: develop / COMMIT: 8a2d04125d30518a7b9e66beb1a5628f7431400d

**Issue:**
SickGear throws an error when trying to open the Episodes-tab, when installed on a Synology NAS.
"Can't compare offset-naive and offset-aware datetimes".

Tried it on my windows pc, it did not give an error.

Maybe this datetime error is also the reason for why no episodes have been moved from unaired to wanted today? i.e. Westworld episode 1 is still marked as unaired even though it aired last night.

**Reproduction:**
Open SickGear (develop) installed on a synology nas. 
Try to open the "Episodes"-page.
See error.

**Error:**
https://gist.github.com/aMvEL2/e7c4ef94e2342e7a1726ea016a8652fc

**Comment by JackDandy** [comment]
#794
