### ISSUE TITLE
Show can't be added or deleted

### ISSUE THREAD

**Issue by rbhamilton** [SickGear/SickGear#796]
Something messed up with my database.  I do a search for Saturday - nothing.  Try adding Saturday Night Live - already in database skipped.  Can't display it, add it or remove it.  Any ideas?

**Comment by JackDandy** [comment]
Go to your parent TV folder and delete the subfolder that relates to the show you are trying to add.

For future reference, user support questions should be asked in IRC - this is for actual issues.

Thanks for your understanding.
