### ISSUE TITLE
Episodes keep "snatched" status, after downloaded and moved into proper location

### ISSUE THREAD

**Issue by jesperrasmussen** [SickGear/SickGear#802]
BRANCH: master / COMMIT: c86ea4be0f0aef067a3e70162f5d398dffec47a5

Expected | Actual
------------ | -------------
Downloading an episode and moving it through postprocessing, should mark it as downloaded| Multiple times, an episode is found, when browsing the show - but status is 'snatched'

Steps to reproduce:
1. Go to a specific shows list of episodes
2. Sometimes an episode will show up as "Snatched", but the episode number will be marked bold, having the path to the videofile, actually moved by post-processing.
3. Rescanning the show does not change the status.

I'm basically unsure if this is a bug or intended behaviour caused by something in the download process, but I've experienced this a few times, causing shows to appear more incomplete than they actually are.

Attached screenshot shows the issue.

![sickgear-issue](https://cloud.githubusercontent.com/assets/144712/19419672/ba6d3a72-93dc-11e6-8444-9b4e50c7ef07.png)

**Comment by JackDandy** [comment]
Hello @jesperrasmussen 

Can you switch to develop, the issue may well have already been fixed in that branch.
