### ISSUE TITLE
Plex Media Server notification only works when said PMS is set to http. https causes problems.

### ISSUE THREAD

**Issue by qorron** [SickGear/SickGear#803]
# Branch: master (48cb3008cf85f06cdc2e5d4f9627f7dff96de74a)

Expectation | Result
------------ | -------------
proper urls on pms get called | urls are called but with http thus getting no reply from pms which expects https

**Steps to reproduce:**
*1)* set up plex to use https
*2)* set up sg to notify said pms to update its library 
*3)* wait for something to download
*4)* check the logs for that error
*5)* observe pms not being updated

logging in that part of the code is not very verbose:
<pre>
2016-10-17 13:10:03 DEBUG    TORNADO :: PLEX: fetching plex.tv credentials for user: user
2016-10-17 13:10:04 ERROR    TORNADO :: PLEX: Error while trying to contact Plex Media Server: http protocol error : error 0 : got a bad status line
2016-10-17 13:10:04 INFO     TORNADO :: PLEX: Updating all hosts with TV sections: 
</pre>

Additional notes: that's how I fixed it:
<pre>
# git diff
diff --git a/sickbeard/notifiers/plex.py b/sickbeard/notifiers/plex.py
index 694fcb3..b239cb7 100644
--- a/sickbeard/notifiers/plex.py
+++ b/sickbeard/notifiers/plex.py
@@ -18,6 +18,7 @@
 
 import urllib
 import urllib2
+import ssl
 import base64
 import re
 
@@ -213,11 +214,16 @@ class PLEXNotifier:
             hosts_all = {}
             hosts_match = {}
             hosts_failed = []
+
+            ctx = ssl.create_default_context() # assumption: 99% of all ssl users have a selfsigned cert
+            ctx.check_hostname = False         # so skip checks
+            ctx.verify_mode = ssl.CERT_NONE    # easy mitm is still better than plaintext
+
             for cur_host in host_list:
 
-                url = 'http://%s/library/sections%s' % (cur_host, token_arg)
+                url = 'https://%s/library/sections%s' % (cur_host, token_arg)
                 try:
-                    xml_tree = etree.parse(urllib.urlopen(url))
+                    xml_tree = etree.parse(urllib.urlopen(url, context=ctx))
                     media_container = xml_tree.getroot()
                 except IOError as e:
                     logger.log(u'PLEX: Error while trying to contact Plex Media Server: ' + ex(e), logger.ERROR)
@@ -251,9 +257,9 @@ class PLEXNotifier:
             host_list = []
             for section_key, cur_host in hosts_try.items():
 
-                url = 'http://%s/library/sections/%s/refresh%s' % (cur_host, section_key, token_arg)
+                url = 'https://%s/library/sections/%s/refresh%s' % (cur_host, section_key, token_arg)
                 try:
-                    force and urllib.urlopen(url)
+                    force and urllib.urlopen(url, context=ctx)
                     host_list.append(cur_host)
                 except Exception as e:
                     logger.log(u'PLEX: Error updating library section for Plex Media Server: ' + ex(e), logger.ERROR)
</pre>

Of course this hardcodes plex notifications to https but this is the first time I've had a look at a python script. well.. actually the second time but it is save to assume that I do not know the language at all.
so I stopped after it started working for me.

sr has a config option for that and toggles the 's' after http based upon that. unfortunately the code differs so much that I didn't dare to copy&paste anything from there.

**Comment by JackDandy** [comment]
Can you come to IRC so that we can progress this feature request

**Comment by JackDandy** [comment]
hi @qorron ready for testing, can you come to IRC

**Comment by qorron** [comment]
# Branch: develop (ef76c38b807f00f4db3ee5125f6938b23d45c149)

manual pp, forcing the overwrite of a file:
<pre>
2016-10-19 00:20:23 INFO     TORNADO :: PLEX: No successful Plex host updated
2016-10-19 00:20:23 ERROR    TORNADO :: PLEX: Error updating library section for Plex Media Server: https://192.168.1.23:32400
2016-10-19 00:20:23 ERROR    TORNADO :: PLEX: Error with Plex Media Server response http://192.168.1.23:32400
2016-10-19 00:20:23 DEBUG    TORNADO :: PLEX: fetching plex.tv credentials for user: user
</pre>

test says:
<pre>
Test result for Plex server(s) ... 
OK (secure connect): https://192.168.1.23:32400
Fail (legacy connect): http://192.168.1.23:32400
</pre>

**Comment by JackDandy** [comment]
@qorron do make sure you checkout back to develop and "Check Update" there to get the Plex addition, otherwise you won't receive new releases
