### ISSUE TITLE
Morethan.tv Search problem

### ISSUE THREAD

**Issue by scouseman** [SickGear/SickGear#820]
From the log I have got the following failed search for the MoreThan.tv site.

http://pastebin.com/3Drvnbd5

But when I paste into the browser:

https://www.morethan.tv/torrents.php?searchstr=Cant.Pay.Well.Take.it.Away S04E01&tags_type=1&order_by=time&&order_way=desc&filter_cat[2]=1&action=basic&searchsubmit=1

I get one result on the site, in sickgear I get none

https://postimg.org/image/x240tf639/

I am using version: BRANCH: master / COMMIT: 48cb3008cf85f06cdc2e5d4f9627f7dff96de74a

**Comment by JackDandy** [comment]
Switch to branch develop, the providers in there are newer and mtv passed testing only 2 days ago.

Marking this as 'invalid' unless you come back and say otherwise.

**Comment by scouseman** [comment]
I have updated to BRANCH: develop / COMMIT: 0536f8da198069701abcd533430e05af9eee92a9
But the problem remains.
Here is the log:
https://gist.github.com/scouseman/eff66451dc31139fdf5123a0eac75d8f

The search from the log:
https://www.morethan.tv/torrents.php?searchstr=Cant.Pay.Well.Take.It.Away%20S04E01&tags_type=1&order_by=time&order_way=desc&filter_cat[2]=1&action=basic&searchsubmit=1
This should return a result.
https://postimg.org/image/um5t36sdp/6c8d0bf4/

**Comment by JackDandy** [comment]
Using your exact detail... http://i.imgur.com/xOUeFVl.png ... proves there is no issue.

Therefore, you must have something else set that is actively excluding the result. This can be quality setting, require/ignore words or something else you have set.

**Comment by JackDandy** [comment]
Using your exact details (click image for full)... <img alt="Click for full image" src="http://i.imgur.com/xOUeFVl.png"> ... proves that there is no issue (at least ~5 hours ago there wasn't).
Here, I clicked the checkbox to the left of the ep S4 Ep1, then clicked "Go" to trigger backlog.

Therefore, you must have something else set that is actively excluding the result. Perhaps the provider is set to filter out releases with less than x number of seeders and/or leechers ? Maybe your SickGear install is not on the same machine as your browser, and therefore, maybe an issue exists with that machine.

**Comment by scouseman** [comment]
I am not sure exactly what else could be causing the problem then, I have quality set to SD, there are no excluded or included words. The only thing I have set is the alternative show name  'Cant Pay Well Take It Away' as the default title would not work.

**Comment by JackDandy** [comment]
Without no-way to make the error here, this thread cannot constructively progress, I suggest you come to IRC.

**Comment by JackDandy** [comment]
With no-way to make the error here, this thread cannot constructively progress, 

Please **come to IRC** for this type of support.With no-way to make the error here, this thread cannot constructively progress, 

Please **come to IRC** for this type of support.

**Comment by JackDandy** [comment]
"**I have set the seeders to only 1, so that wouldn't cause the problem**"

1) You should never assume.  Look at the mtv image you sent, 1 is greater than 0. Everything is working fine at yours. 
2) And why would you need ep fallback? You should have ep as standard search and only use fallback to season packs when needed.
