### ISSUE TITLE
omgwtfnzbs error

### ISSUE THREAD

**Issue by mkools** [SickGear/SickGear#829]
Hi seems like omgwtfnzbs has a new owner, they now changed the website and it gives an error:

2016-11-18 10:30:19 PROPER-SEARCH :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: tuple index out of range

Thanks!

**Comment by JackDandy** [comment]
Sorry, not enough info, essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)
