### ISSUE TITLE
Rename files without moving?

### ISSUE THREAD

**Issue by nosmokingbandit** [SickGear/SickGear#833]
Would it be possible to have SickGear simply rename the files in-place? I have additionally scripts that move the files after SickGear sorts them, so being able to move the file one less time would make my media workflow a whole lot easier.

**Comment by JackDandy** [comment]
As standard across all operating systems, a rename in-place will not move a file.  Settings for the renamer are on the pp settings. Sounds like you need to rethink your workflow and settings as everything is already there for you.

**Comment by nosmokingbandit** [comment]
Please help me set Sickgear to rename in place. Every post-processing option (move, copy, hardlink, symbolic link) seems to move the video file to its show folder, leaving a hard or sym-link behind if set, or leaving a copy behind if set. I seem to be unable to simply rename the download in place without moving or creating additional file elsewhere.

**Comment by JackDandy** [comment]
Yes, SickGear places post processed shows into a folder below the respective parent show folder - this is by design.  If you don't want that, then disable post-processing.

**Comment by deed02392** [comment]
You will have problems with SickGear thinking that your existing media content is freshly downloaded shows. That is why post-processing implies moving your media files - the input directory is only supposed to be a temporary location for files.
