### ISSUE TITLE
Sickgear quit responding RPi

### ISSUE THREAD

**Issue by tpitman** [SickGear/SickGear#838]
I have been using SickGear every day to get shows for the last year or more.

Suddenly today I tried to browse to http://IPADDRESSOFPI:8081 and I simply get a "connection refused" error.

I tried rebooting the Pi and still get the same.

I have no idea even where to start to figure out what is going on.

Any ideas?

**Comment by JackDandy** [comment]
Please manually update using git - this is a one off.

**Comment by tpitman** [comment]
After git pull and raspberry pi update this fixed it. You are awesome!!!

**Comment by tpitman** [comment]
I started getting this error lately. Is something broken that I / we can fix?

2017-03-23 17:21:26 MANUAL-268592 :: [The Pirate Bay] :: Failed to identify a "The Pirate Bay" page with 4 different URLs (local network issue, site down, or ISP blocked)

**Comment by JackDandy** [comment]
There is nothing to fix, the message is clear. At that time (17:21:26) every effort to connect to TPB failed. It is up to you to then find out why only a couple of guesses can be entered, else i would end up writing a book of possiblities as to why your netowrk failed at the time, for example...


there was a news article about the IP range of TBP servers being put out by a blockade made by Cogent who lease IP ranges to Cloudflare. this block was done for an unrelated site thanks to Spanish authorities, and TPB was collateral damage,

Now how do i put that in the error message ? I am being anecdotal, but you get the real point. There is no bug here.

**Comment by tpitman** [comment]
Sorry to bug you about something that is probably very obvious to you. Thank you for your great work.

**Comment by JackDandy** [comment]
Doesn't bug me, I believe in helping people fend for themselves. I try to remove myself from the equation of you and your software so that you can get on and quickly adjust stuff yourself. Thank you.
