### ISSUE TITLE
bugs with special characters

### ISSUE THREAD

**Issue by thib3113** [SickGear/SickGear#847]
I see some bugs with special characters, for example 
this tv show don't work :  "Il était une fois... la vie", a folder is created "Il Ã©tait une fois... la vie" but the files are not moved . ( I've tried to edit the path in the webUI , but the special char don't work too )

I have some problems with some tv show episode : 
For the show "c'est pas sorcier"

![image](https://cloud.githubusercontent.com/assets/5489218/21459848/63e336fc-c942-11e6-88e6-2f2631d86696.png)
I have this log : 

> 18:44:21 INFO TORNADO :: Processing... Le tunnel sous la manche (lÔÇÖeurotunnel).mkv
> 18:44:21 INFO TORNADO :: Analyzing name None
> 18:44:21 INFO TORNADO :: Analyzing name u'Le tunnel sous la manche (l\u2019eurotunnel).mkv'
> 18:44:21 INFO TORNADO :: Analyzing name u"C'est pas sorcier"
> 18:44:21 INFO TORNADO :: Analyzing name u"D:\\downloads\\Series\\C'est pas sorcier\\Le tunnel sous la manche (l\u2019eurotunnel).mkv"
> 18:44:21 INFO TORNADO :: Analyzing name u"C'est pas sorcier Le tunnel sous la manche (l\u2019eurotunnel).mkv"
> 18:44:21 WARNING TORNADO :: Must add show to SickGear before trying to post process an episode
> 18:44:21 WARNING TORNADO :: Warning fail for D:\downloads\Series\C'est pas sorcier\Le tunnel sous la manche (lÔÇÖeurotunnel).mkv Post Processing Failed

**Comment by JackDandy** [comment]
essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)
