### ISSUE TITLE
Must add show to SickGear before trying to post process an episode

### ISSUE THREAD

**Issue by Fire69** [SickGear/SickGear#851]
Branch
--------
# Branch: develop / COMMIT: 9d27f6a9cbb3c47a74529c2aaff2fc5ab231328f

Expectation
-------------
When using the Post Media function to process manually downloaded episodes (or episodes where processing failed due to weird naming scheme) I expected it to find and process the files and move/rename them to the correct folder

Result
-------
The files are not processed and the error below is shown

Steps to reproduce
---------------------
*1)* Select 'Process Media' on main page
*2)* Browse to folder with the downloaded episode
*3)* Select 'Move'

Error Log
----------
```
Checking folder... C:\Users\Public\Videos\Series\Dirk.Gentlys.Holistic.Detective.S01E04
Processing folder... C:\Users\Public\Videos\Series\Dirk.Gentlys.Holistic.Detective.S01E04
Process files: [u'Dirk.Gentlys.Holistic.Detective.S01E04.mkv', u'Dirk.Gentlys.Holistic.Detective.S01E04.nfo']
Process video files: [u'Dirk.Gentlys.Holistic.Detective.S01E04.mkv']
Processing... Dirk.Gentlys.Holistic.Detective.S01E04.mkv
Must add show to SickGear before trying to post process an episode
Did not use file C:\Users\Public\Videos\Series\Dirk.Gentlys.Holistic.Detective.S01E04\Dirk.Gentlys.Holistic.Detective.S01E04.mkv
.. Post Processing Failed
----------------------------------
Failed! Did not process any files.
```

Additional notes  
------------------
Obviously, this is a show that has been added already.
![image](https://cloud.githubusercontent.com/assets/1757287/21561224/25d377e6-ce6a-11e6-9200-238dcabf9fc0.png)

In the case of the example in the above log, 3 episodes had been correctly downloaded and processed already.
I've had this problem with other shows already also (Jay Leno's Garage, The Grand Tour, ...)

**Comment by JackDandy** [comment]
Hello,

Sounds like you haven't set the [SickGear alternative release name](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#not-process) feature.

**Comment by Fire69** [comment]
I'll give that a try, thanks.
I figured it would be a little more intelligent to be honest. :-)
You think it's not working because the 'agency' is missing in the file name?

**Comment by JackDandy** [comment]
> a little more intelligent
start adding wildcards for "intelligence" and quickly end up with no intelligence. If the release file name does not have "agency" and the title on edit page does, then an alternative name candidate would be to omit "agency"

**Comment by Fire69** [comment]
Hope you didn't take it wrong, it wasn't meant as criticism or anything :-)

True, using IDs would be great, but we all now that's not going to happen :-)

I added the 'agency' to the filename, processing went as expected.
I'll add it as alternative, problem solved then ;-)

Thanks for the info and your time!
