### ISSUE TITLE
Files with seasonal scene exceptions not recognised as shows

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [SickGear/SickGear#852]
BRANCH: master / COMMIT: dd0d12f72c95a1d9a4f95f2e6be1aae41fe71f68

When a show has season specific show names( for example Pokémon XY being Pokémon season 17), files named accordingly are not recognised as shows added to SickGear.

Reproduction steps:
- Add Pokémon with the Anime checkbox enabled.
- Wait for the show to be added and the scene exceptions to fill(http://i.imgur.com/P7EeV4k.png)
- Try to import "[PM] Pokémon XY - 01 [720p].mkv"
- See that it fails

"[PM] Pokémon - 01 [720p].mkv" will process just fine (but as S01E01 obviously), so the naming pattern looks legit to me.

log
```
Processing... [PM] Pokémon XY - 01 [720p].mkv  
Must add show to SickGear before trying to post process an episode  
Did not use file /opt/SickGear/ImportFolder/[PM] Pokémon XY - 01 [720p].mkv
```

**Comment by deed02392** [comment]
I guess we need to implement show aliases (like alternative show names) that work on the season level.

**Comment by JackDandy** [comment]
I don't think so, season XY is listed at XEM http://thexem.de/xem/show/4042 Looks like the filename in the OP may have been superseded in a release with a better name. Therefore, closing this edge-case issue.

**Comment by JackDandy** [comment]
meh i cant get my head around this...
even if the regedx is made aware of the xy part, then it would likely break a show that had roman numerals as part of the show title, and then there are so many combinations of where xy could be used. Basically, either an anime expert can fix this, or rename files and manually import.
