### ISSUE TITLE
Question about sickbeard mp4 automator

### ISSUE THREAD

**Issue by nogardvfx** [SickGear/SickGear#855]
Hi there, been a sickbeard user for years and decided to give sickgear a try.  Love what I am seeing so far.  Just a quick question (I hope).  I am wondering if there is anything special I need to do to get sickbeard mp4 automator running properly? 

I originally had it running under sickbeard and it would fail out while calling up the sickgear webpage to begin the conversion process.  I changed mp4 automator to use sickrage instead and now it will run a bit further through the process.  I can see it convert the video file to an MP4, move it to the proper directory, inform plex and kodi, but it seems after that process it just sits.  SabNZBD still thinks it is running.

Will be asking this same question on the mp4 auotmator git as well.

Thanks in advance.

**Comment by JackDandy** [comment]
Hi @nogardvfx 

Sorry, never found a need for this third part tool so no idea how it works.

**Comment by nogardvfx** [comment]
Thanks to the reply.  This might be whats holding things up...should have explained this in more details previously.

I did upgrade from sickbeard and am trying to keep my old database.  I do have a lot of TV shows, so it seems to be taking time to go through everything (longer than I expected).  If I looks at the terminal Sickgear is running through a process of copying the artwork, checking & filling cache, etc...  This is preventing me from getting to any additional web pages once this process has started.  Which I suspect might be what is holding up the mp4 process in SabNZB.  With the number of shows I have. I cannot tell if it is still going through the processing/updating or is it just in a loop of some kind.  I do have sickgear set to modify the file system time/date to correspond to the episode air time/date and it seems to be still picking a few of these up.

Any way of stopping this process (at least temp) just to see if this might be it?

**Comment by JackDandy** [comment]
Sounds like you are trying to do way too much at once. One thing at a time, do NOT connect SAB to SG to begin with, simply start with a fresh SG install and copy your sickbeard.db to the datadir you use for SG, fire up sg and it will take care of things. Then once done, set up other stuff. See the wiki for migration guides.
