### ISSUE TITLE
Force Poster Update

### ISSUE THREAD

**Issue by shuntera** [SickGear/SickGear#858]
>>You can update sooner by using 'Force' in Daily Show Update under menu Manage/SearchQueueOverview

I'm not seeing that option in the current version that I have just installed. Under the Manage menu item there is no "SearchQueueOverview"

**Comment by JackDandy** [comment]
Hi,

If you View Changes you will observe...

* Change rename "Manage Searches" -> "Media Search"

**Comment by JackDandy** [comment]
Hi, renamed "Show Processes"

also, where did you read that text?

**Comment by shuntera** [comment]
Thanks.

It is at the bottom of this page:

https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B0%5D-Migrate
