### ISSUE TITLE
SickGear keeps processing one file

### ISSUE THREAD

**Issue by oppiz2** [SickGear/SickGear#859]
# Branch: BRANCH: master / COMMIT: bc7b6ff2dc8a460047011863fc17714e0d87e8b5

**Steps to reproduce:**
*1)* SickGear auto-downloads one episode (in the log "The OA S01E01" and "Marvels Agents(...) S04E10"
*2)* Every 10 minutes I was getting a Pushbullet with "Episode downloaded"

Link to gist https://gist.github.com/anonymous/1c050f5d7c875a1c4809df8bf215f2e8 

Additional notes:  
I've since disabled Pushbullet. That's why it doesn't show in logs

**Comment by JackDandy** [comment]
Have your client copy each download complete to a folder for SG to process,
then have SG use the "move" method so that the folder is kept clean.
