### ISSUE TITLE
Preferred keywords

### ISSUE THREAD

**Issue by mrowlinson** [SickGear/SickGear#861]
It would be great to have an option for preferred keywords in addition to required keywords. A scenario this would be helpful is choosing which item to download when multiple are available. For instance, Web-DL copies of shows ripped from Amazon have started to show up in increasing frequency. These tend to be a lot higher quality than the standard Web-DLs that are ripped from iTunes. It would be great to be able to set a preferred keyword of "AMZN", which these rips contain in their name, so it would try to grab those Web-DLs first. Another example might be choosing a release with DD5.1 audio over DTS, or a remux over a normal recompressed 1080p. Since they are just preferred keywords and not required, if no results match the preferred keyword the standard algorithm that selects the copy to download would apply.

**Comment by JackDandy** [comment]
Yup, this type of logic is on the todo list, its not so trivial to implement **properly** but will certainly happen.

**Comment by mrowlinson** [comment]
Great to hear it's already in the radar.

By the way, the speed with which you responded to this is really impressive! I love this project. Keep up the good work!

**Comment by JackDandy** [comment]
See what you think... https://gist.github.com/JackDandy/023034389c099fae5a400e38c2b737f2

I think this will blend your idea into the existing framework and cover other scenarios too.

**Comment by aphex3k** [comment]
Did I miss it or has not been added yet?

**Comment by JackDandy** [comment]
Nope you didn't miss it, there have simply been far more time absorbing things to that we have been developing, and this feature idea has not been in the same scale of importance.
