### ISSUE TITLE
Fails to add show

### ISSUE THREAD

**Issue by MCMic** [SickGear/SickGear#862]
Hello, it always fail to add the show «Le bureau des légendes», I’m guessing that has to do with the «é»?
Got no problem with the other shows.
With SickBeard this show was added with no problem at the time, it’s the only show I could not add since I switched to SickGear

**Comment by JackDandy** [comment]
How are you trying to "add" - do you really mean "Import" or do you mean "Add from TV info source" ?

**Comment by MCMic** [comment]
I mean add by searching for it.
The search finds it but then I get:
2017-02-01 01:18:35 SHOWQUEUE-ADD :: Show in /home/share/Video/Le bureau des légendes has no name on TheTVDB, probably the wrong language used to search with.

I tried first with fr and then with en. (deleted the folder between attempts)

**Comment by JackDandy** [comment]
<img src="http://i.imgur.com/1RxmICx.png">

**Comment by MCMic** [comment]
# BRANCH: master / COMMIT: bc7b6ff2dc8a460047011863fc17714e0d87e8b5

**Steps to reproduce:**
*1)* Click Shows -> search
*2)* Fill in «Le bureau des légendes» and select «fr» (or «en», same result)
*3)* Select le bueau des légendes
*4)* Click «Add Show»

<pre>2017-02-01 01:18:35 SHOWQUEUE-ADD :: Show in /home/share/Video/Le bureau des légendes has no name on TheTVDB, probably the wrong language used to search with.</pre>

Additional notes:  
Fails with both fr or en. Importing fails too. (show is not «known»)

**Comment by MCMic** [comment]
Hum ok
I did not guess this was the same one as the search also lists the french name

**Comment by MCMic** [comment]
Selecting «The bureau» and «fr» I do get the correct show with the french name, thank you for your help.
Not sure why there is the second result with empty info from the search.

**Comment by JackDandy** [comment]
There is only one result here, I guess the tvdb api is working based on your geo location. Remember, SG is for English content, we can't support non-English, but if it works for you, then great.
