### ISSUE TITLE
Could not open the page, too many redirects

### ISSUE THREAD

**Issue by Bm4n** [SickGear/SickGear#900]
After the last update (develop, e75a5d7c3426a3d7d473336eafc2dfa85caf1d31) I can't log in because this error: "Could not open the page, too many redirects". I clean "cheetah", "sessions" and cookies but doesn't work.

Any idea?
Thanks.

**Comment by JackDandy** [comment]
Yeah, we updated the tornado web server and it has raised an issue on some configurations. Please switch to master for now, thanks for reporting.

**Comment by Bm4n** [comment]
Ok, if you can tell me when the issue is solved, then I will manually replace new files over terminal.

Thank you ;)

**Comment by JackDandy** [comment]
Idle in the sg IRC for that type of notification.

**Comment by JackDandy** [comment]
Idle in the SG IRC for that type of notification. And you can switch in the general/adv tab.

**Comment by Bm4n** [comment]
No, I can't open the UI, is installed on a Synology NAS. I can change config.ini manually but I don't know how to force update to change the server without the interface.

**Comment by JackDandy** [comment]
Okay, like i said, come to IRC and idle, Github is not a messenger platform.

**Comment by JackDandy** [comment]
#901
