### ISSUE TITLE
Does not listen to IPv4 when Listen on IPv6 is activated

### ISSUE THREAD

**Issue by jfjallid** [SickGear/SickGear#905]
I'm running dual stack with IPv4 and IPv6 and noticed that when enabling the option to Listen on IPv6 sickgear stops listening or accepting connections over IPv4. I'm just assuming this is a bug and not by design as it makes more sense to me being able to connect over both with this feature enabled.

**Comment by JackDandy** [comment]
essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

**Comment by JackDandy** [comment]
#907
