### ISSUE TITLE
Web interface does not listen to IPv4 when Listen on IPv6 is activated

### ISSUE THREAD

**Issue by jfjallid** [SickGear/SickGear#907]
**Branch: master** (bc7b6ff2dc8a460047011863fc17714e0d87e8b5)
OS: Fedora 24
 
Expected: When I enable the option Listen on IPv6 I expect to be able to connect to the webinterface via IPv4 and via IPv6. 
What is see: When I enable the option Listen on IPv6 trying to connect over IPv4 returns a message "Unable to connect" in Firefox. Trying to connect over IPv6 using Firefox succeeds.

**Steps to reproduce:**
1. Enable Settings - General - Interface - Web Interface - Listen on IPv6 and save changes.
2. Restart SickGear
3. Try to access webgui over IPv4 address.

Log:
https://gist.github.com/jfjallid/adc5e1f37502bdb2411fb0d148deeb8c

**Comment by JackDandy** [comment]
Can you come to IRC to perform a test I have for this.

**Comment by JackDandy** [comment]
#910
