### ISSUE TITLE
No new episodes being snatched\unable to find results with manual search. Python error in log

### ISSUE THREAD

**Issue by joshoram80** [SickGear/SickGear#908]
# Branch: develop / COMMIT: fa303ef9620799b3a8669501afe6f0c0ebfab8fd

Expectation | Result
------------ | -------------
To have SickGear snatch new episodes and to be able to manually search for and snatch new episodes. (The episode does exist on the tracker). This has always worked previously | No episodes found. Python error in log

**Steps to reproduce:**
*1)* Deleted .cleaned.tmp from base SickGear directory as instructed
*2)* Restarted SickGear
*3)* In Show List, Clicked on a TV Show to get to Show Information page
*4)* Clicked on "Search" link to search for an episode that I knew existed on the tracker for testing purposes
*5)* Recieved notification stating no episode was found.
*6)* Viewed logs to find error. Noticed python error
*7)* Copy\Pasted Search URL from log to browser an confirmed that there IS an episode existing, which there was.

https://gist.github.com/joshoram80/ffa2e935e845e234dc3fdf4303fe5278

Additional notes: 
OS is Windows 10 with Python 2.7.10
This has always worked in the paste and has only recently stopped working. As far as I know nothing at all has changed on the PC that is running SickGear. Error previously posted but closed due to improper formatting and information given. Followed instructions given to fix problem but it still persists. Problem also existed on Master branch. I changed to Dev branch today to see if it would fix it but it did not.

**Comment by JackDandy** [comment]
Fine here. 

Therefore, I suggest looking at your settings, ignore words, quality, etc etc.
```
17-02-06 14:44:04 INFO     MANUAL-262407 :: Downloading Black.Sails.S04E02.WEBRip.X264-DEFLATE from IPTorrents
2017-02-06 14:44:04 INFO     MANUAL-262407 :: Preferring Black.Sails.S04E02.WEBRip.X264-DEFLATE (x264 over xvid)
2017-02-06 14:44:04 INFO     MANUAL-262407 :: Quality is SD TV for Black.Sails.S04E02.WEBRip.X264-DEFLATE
2017-02-06 14:44:04 INFO     MANUAL-262407 :: Quality is SD TV for Black.Sails.S04E02.XviD-AFG
2017-02-06 14:44:04 INFO     MANUAL-262407 :: [IPTorrents] :: 4 episode candidates
2017-02-06 14:44:03 INFO     MANUAL-262407 :: [IPTorrents] :: 10 episode items in response from http://--------------/t?4;5;22;23;24;25;26;55;65;66;78;79;99;q=Black.Sails S04E02;qf=ti;o=seeders#torrents
2017-02-06 14:44:01 INFO     MANUAL-262407 :: [IPTorrents] :: Performing episode search for Black Sails
2017-02-06 14:44:01 INFO     MANUAL-262407 :: Beginning manual search for: [Black Sails - 4x02 - XXX]
```

**Comment by DogSledder** [comment]
I've got the same problem, except I've been running the Development branch for many months. Happened after I upgraded to the latest Development release.

Tried upgrading my Python libraries, then tried deleting cleaned.tmp, but the problem is still there.

**Comment by JackDandy** [comment]
1) Stop SG... 

2) From <sg_program_files_dir> delete all python compiled/optimised files
  
**[edit Windows]** command prompt
  * `cd <sg_program_files_dir>`
  * `del /s *.pyc`
  * `del /s *.pyo`
  
**[edit Linux]** commands (thanks prinz23)...
  * `cd <sg_program_files_dir>`
  * `find . -name "*.pyc" -type f -delete`
  * `find . -name "*.pyo" -type f -delete`

3) Start up SG devel

**Comment by DogSledder** [comment]
Ran the commands for Windows. Still getting Python errors in the log whenever I do a backlog search. The Python error messages are the same as described above, except for the show and provider names.

**Comment by JackDandy** [comment]
Please come to IRC if you want help fixing your set up.

**Comment by DogSledder** [comment]
Sorry I didn't get back to you sooner. I'm digging out after a snow storm. I'm not familiar with IRC. Backlog search works ok with my nzb provider, just not with my torrent providers. Will look at this again when I have time.

Thanks for your efforts and quick responses.

**Comment by JackDandy** [comment]
The steps in this thread have proven to resolve torrent search, anything else is best resolved in IRC.

There is detail in these pages on where to find us in IRC. Here is *not* a place for chat, so I will lock this thread as everything is very clear.
