### ISSUE TITLE
failed to parse during recent-search

### ISSUE THREAD

**Issue by shortbus** [SickGear/SickGear#909]
BRANCH: master / COMMIT: bc7b6ff2dc8a460047011863fc17714e0d87e8b5

2017-02-08 05:01:33 RECENT-SEARCH :: [Transmithe.net] :: Failed to parse. Traceback: Traceback (most recent call last):
  File "/home/jobman-example-only/.sickgear/sickbeard/providers/transmithe_net.py", line 80, in _search_provider
    for item in data_json['response'].get('results', []):
TypeError: string indices must be integers

**Comment by JackDandy** [comment]
Yup, that is a correct action.

The log there is telling you that at that time the response from that provider "Failed to parse".
The log is also telling you that the json response was a string (a normal response would not be a string),  the string could have been "Server Error 500", "Out for Maintenance" or whatever.

You will notice that those log messages will have stopped some time later when the site resumed normal responses. it would have been useful if you had added that to this message to save me time looking into this false positive.
