### ISSUE TITLE
Issue saving custom Newznab provider

### ISSUE THREAD

**Issue by colbsure** [SickGear/SickGear#920]
Added a custom Newznab provider.  After a restart I get the following error when saving the "Media Providers" details:

>Traceback (most recent call last):
>  File "/root/SickGear/tornado/web.py", line 1417, in _execute
>  File "/root/SickGear/tornado/gen.py", line 920, in run
>  File "/root/SickGear/tornado/concurrent.py", line 223, in result
>  File "/root/SickGear/tornado/gen.py", line 235, in wrapper
>  File "/root/SickGear/sickbeard/webserve.py", line 314, in get
>   result = method(**kwargss)
>  File "/root/SickGear/sickbeard/webserve.py", line 5415, in saveProviders
>    sickbeard.NEWZNAB_DATA = '!!!'.join([x.config_str() for x in sickbeard.newznabProviderList])
>  File "/root/SickGear/sickbeard/providers/newznab.py", line 297, in config_str
>    self.search_mode or '', self.search_fallback, self.enable_recentsearch, self.enable_backlog)
>TypeError: %d format: a number is required, not str`

I took a look at the source and the issue seems to be that the method "**makeNewznabProvider**" in "/sickbeard/providers/_ _init_ _.py" loads the settings as strings.  

This then causes an issue with the method "**configStr**" in "/sickbeard/providers/newznab.py" as line  295 assumes the "self.search_fallback", "self.enabledrecent" and "self.enabled.backlog" are integers when building the setting string in order to save it.  Net result is an exception.

I fixed it by casting the values to integer before the save - this is not the most robust way, however (I just wanted a quick fix):

>def config_str(self):
>    return '%s|%s|%s|%s|%i|%s|%i|%i|%i' \
>        % (self.name or '', self.url or '', self.maybe_apikey() or '', se    lf.cat_ids or '', self.enabled,
>               self.search_mode or '', int(self.search_fallback), int(self.enable_recentsearch), int(self.enable_backlog))`

**Comment by JackDandy** [comment]
Fixed: [Release 0.12.9](https://github.com/SickGear/SickGear/releases/tag/release_0.12.9)

**Comment by colbsure** [comment]
Thanks for this - much appreciated.
