### ISSUE TITLE
Request: Disk Space Used

### ISSUE THREAD

**Issue by scotepi** [SickGear/SickGear#921]
I just upgraded from SickBeard and SickGear is awesome! I love the delete whole show option.

My request is seeing the space used by a show folder. Possibly take it a step further and give the anticipated size if the show is 100% complete. You could see & sort by the value in Simple List and show details page.

Due to the time it takes to compute, especially if you are running on/off a NAS (like me), maybe updated daily or weekly.

**Comment by JackDandy** [comment]
ps. a note about [feature requests](https://github.com/SickGear/SickGear/issues/770) :)

**Comment by JackDandy** [comment]
I see too many issues around developing this feature in a useful reliable manner...

1) If the quality list of a show is varied, how to forsee which release will be snatched
2) If wanted and upgrade episodes are varied, how to forsee which release will be snatched
3) If episode lengths are non-uniform and/or don't match published length

simply for the reasons above, how would code logic forsee file size. 

Conclusion; This is not an idea that can be implemented in a way that can be considered reliable enough for SickGear.
