### ISSUE TITLE
[wiki] Arch Linux installation guide

### ISSUE THREAD

**Issue by carlwgeorge** [SickGear/SickGear#922]
Currently the [Arch Linux installation guide](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B4%5D-Arch-Linux) on your wiki has quite a few steps.  If you like, you can direct users to use the [AUR package](https://aur.archlinux.org/packages/sickgear/) instead.  It automatically accomplishes these manual steps from the wiki:

* installs python2 and python2-cheetah
* [creates a sickgear user](https://aur.archlinux.org/cgit/aur.git/tree/sickgear.sysusers?h=sickgear)
* [sets ownership of the data directory](https://aur.archlinux.org/cgit/aur.git/tree/sickgear.tmpfiles?h=sickgear)
* [creates the systemd service unit file](https://aur.archlinux.org/cgit/aur.git/tree/sickgear.service?h=sickgear)

In addition to those things, it also:

* [runs the appropriate systemctl commands on upgrade and removal](https://aur.archlinux.org/cgit/aur.git/tree/sickgear.install?h=sickgear)
* installs the app to /usr/share/sickgear instead of /opt/sickgear/app
* stores the data at /var/lib/sickgear instead of /opt/sickgear/data
* [removes several bundled dependencies](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sickgear#n47) and [imports them from the system instead](https://aur.archlinux.org/cgit/aur.git/tree/0001-fix-imports.patch?h=sickgear)

**Comment by JackDandy** [comment]
Hi, 

Thanks for bringing this to our attention.

At first glance, removing dependencies is none starter.  SG is carefully tested with deps and breaks do happen when upgrades are applied, if deps are not tied to the project then all manner of instabilities will arise that is counter to our philosophy.

**Comment by carlwgeorge** [comment]
Thanks for the "fanatical" response @JackDandy.  Sorry it has taken me a little while to respond.

> However, at first glance, removing dependencies is a none starter.

It's unfortunate you feel the way you do about bundled libraries.  That's a very old debate, and I don't expect to be able to sway your opinion, but be aware that most Linux distributions have documented policies to [remove](https://fedoraproject.org/wiki/Packaging:Guidelines#Bundling_and_Duplication_of_system_libraries) [bundled](https://fedoraproject.org/wiki/Bundled_Libraries) [libraries](https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code) [whenever](https://en.opensuse.org/openSUSE:Packaging_guidelines#Bundling_of_multiple_projects) [possible](https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies).  As a packager I'll continue to stick to packaging best practices and remove the non-customized bundled libraries.  For what it's worth, I've been using SickGear with that setup (non-customized bundled libraries removed, and fixing the imports to use the system copies) for a few weeks now, and it works perfectly.  I'll also note that since Arch closely follows upstream releases for most of it's packages, Arch users are usually familiar with having to periodically roll back individual packages when things don't work correctly.  Bugs get reported upstream, and things get fixed.  As long as upstreams are active and responsive to bug reports, this cycle doesn't hurt anybody's impression of the upstream software.  Basically this is a way for you to get early notification of breaking changes in your dependencies.

> Not sure why use `/usr/share/` instead of `/opt/` and splitting the `/data` files away from `/app` files is probably more cumbersome for the administrator. Be nice to admins, keep files close is current thinking.

I made that change to align with the [Filesystem Hierarchy Standard](https://wiki.linuxfoundation.org/lsb/fhs).  Most Linux distributions have policies that prevent packages from placing files in `/opt`.  Instead, `/usr/share` is the standard location for ["read-only architecture independent data files"](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html), and `/var/lib` is the standard location for ["data that programs modify while they run"](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html).  Administrators are well accustomed to this standard (look at mysql, nginx, haproxy, php, postfix, etc.).

> Also, the unit file with SG (`/init-scripts/init.systemd`) should be used. The one at that Aur does not run in the tried and tested way for smooth SG restarting (and upgrading) when run from a unit file. Daemon mode is not recommended (again see the Debian guide) I see the Arch guide has it, but it's not good.

The [service unit file](https://aur.archlinux.org/cgit/aur.git/tree/sickgear.service?h=sickgear) I'm using doesn't use `--daemon` mode like the Arch guide suggests.  My unit file has effectively the same `ExecStart` command as your `init-scripts/init.systemd` file and the Debian guide.
```
ExecStart={{ python binary }} {{ SickBeard.py file }} --systemd --datadir {{ data directory location }}
```

As a small side note, I think it's an neat approach to use the the port number as the instance string for template unit files (`sickgear@{{ port }}.service`) the way the Debian guide suggests.  That said, I can't see a scenario where a user needs to run multiple instances of SickGear (which is the real purpose of template unit files).  For single instance applications, it's recommended to use a normal unit file (`/usr/lib/systemd/system/sickgear.service`), and let administrators override it if customization is needed (such as adding the `--port` flag), either with a local unit file (`/etc/systemd/system/sickgear.service`) or with "drop-ins" (`/etc/systemd/system/sickgear.service.d/override.conf`).

> Before we know it, support questions will come in with complaints why SG is not shutting down, upgrading, or restarting properly on Arch, and that has been put to bed.

I've been using this package in it's current state with that unit for several weeks now without any problems at all.  It installs, upgrades, and removes without issue, and [runs the appropriate commands during each of those actions](https://aur.archlinux.org/cgit/aur.git/tree/sickgear.install?h=sickgear).  On the off chance that something doesn't work right, Arch users will typically just leave a comment on the AUR page, rather than file an upstream bug.  If someone reports a bug via AUR comment, I'll validate it's reproducible with your recommended filesystem layout and bundled libraries to ensure it's not an error with packaging.  Then I'll direct the user to file an upstream bug (or just do it myself).  This is a standard procedure for packagers for many distributions.

Thanks for reading my long response.  Hopefully some or all of it seems reasonable to you, but even if not, the discussion is still enjoyable.

**Comment by JackDandy** [comment]
A very intersting read, and yeah, it all sounds reasonable.

> Basically this is a way for you to get early notification of breaking changes in your dependencies.

Yeah, that's the concern, the current flow ensures that there's no nagging from vendor changes. As a side note, I once flashed my Android, installed x amount of apps and soon found myself updating every day, even several times per day, it became a nightmare - fast. SG is not forced to update its code on anyones timescale, for exactly the same reason as the Android case. Instead, SG deps are updated occasionally and in one sitting. The goal is a balance of keeping fairly current, not getting bogged down, and maintaining stability for the user.

The port number system in the template files is very useful for firing up multiple instances on the same machine without hassle. E.g. prod and dev/test, or person (1) and person (2).

Anyway, you have processes in hand so I will simply link to your Aur from the install page as per your OP for users that want to follow your approach, fingers crossed that this doesn't come back to bite.  More than that though, thanks for putting your time and effort in.

**Comment by carlwgeorge** [comment]
> updating every day

Most Arch users I know update daily.  It's really a different mindset, and it certainly isn't for everyone.

> I will simply link to your Aur from the install page

Thanks!  I'll be sure to let you know if I notice any upcoming dependency problems that you haven't encountered yet.
