### ISSUE TITLE
Request: Notification on outdated Wanted status

### ISSUE THREAD

**Issue by hobojoe720** [SickGear/SickGear#925]
Within <del>SR</del> :( is a release date, and a show goes to the status of Wanted. It would be useful to have it so that if a show is "Wanted" and the release date was more than say a week ago, then send a Notification.

Saves having to login every day to check if everything is downloaded.

**Comment by JackDandy** [comment]
so you would want a noftication for all the items as EACH get added in turn to ...

SICKGEAR>:8081/manage/backlogOverview/

i'm not sure if that is rational - but idea is noted in case someone else agrees or can build on this idea.

Thanks.

**Comment by hobojoe720** [comment]
Correct, however I have items in there that dont show up in the normal show pages. They look like specials

**Comment by JackDandy** [comment]
Specials aren't searched on, so there is no error to report for that. They aren't searched on because there is no release naming standards for specials from scene or in p2p circles.

**Comment by hobojoe720** [comment]
Not saying they are an issue just pointing out that in the BacklogOverview is stuff that is irrelevant for the purpose of a notification

**Comment by JackDandy** [comment]
ahh gotchya :)
