### ISSUE TITLE
Copies of same quality are being replaced when a higher quality snatch fails

### ISSUE THREAD

**Issue by mrowlinson** [SickGear/SickGear#926]
This issue is still occurring. I just updated a bunch of shows to 1080p Bluray as the highest desired quality, from 720p Bluray, and after the backlog search it's doing the same thing again. When all of the 1080p copies are downloaded and fail it then tries to redownload the best quality copy in reverse order. This time it replaced some existing 720p bluray copies with lower quality copies and the higher quality copies are no longer available so I'm stuck with inferior quality episodes. In two instances the 720p bluray was unavailable too and it actually tried to replace my 720p bluray copy with a 720p HDTV copy. Thank god I caught that before they downloaded and they could be replaced.

**Comment by JackDandy** [comment]
duplicate.
