### ISSUE TITLE
Automatically populate SG with Trakt watchlist data

### ISSUE THREAD

**Issue by barbequesauce** [SickGear/SickGear#927]
Currently, adding shows from Trakt is limited to the service's recommendations and most popular shows. The ability to populate SickGear with shows added to a user's watchlist on Trakt would be helpful. 

Ideally, the addition to SG from a Trakt watchlist should be automatic; the goal would be to allow one-touch submission to a tool chain (add a show in your Trakt watchlist and it auto-populates in SG, then SG searches and pushes a torrent to your torrent client of choice and then post-processes it into your media server of choice).

Note this functionality already exists in SG's IMDB watchlist.

**Comment by JackDandy** [comment]
The model of SG is never to auto add from any external source.
However, to add a watchlist to SG so the user can choose what to add from that list is something to consider.

**Comment by JackDandy** [comment]
@barbequesauce 

#936 - should be close enough to your request.

**Comment by barbequesauce** [comment]
Thank you!
