### ISSUE TITLE
Qualities management

### ISSUE THREAD

**Issue by sdhull** [SickGear/SickGear#929]
Feature request:
Qualities management, in order to tune search params, as well as size limits like couchpotato has:
![couchpotato quality settings](http://i59.tinypic.com/n3874i.jpg)

**Comment by JackDandy** [comment]
See #770 if you are puzzled how we handle FR - suffice to say, your request is noted.

**Comment by sdhull** [comment]
@JackDandy interesting! I'm not sure what you mean by `a false +ve`, but personally I just saw a HD720 show get snatched today that was 22GB, so this is the sort of thing I'd like to be able to prevent.

**Comment by JackDandy** [comment]
@sdhull 1) Which exact episode 2) Provider

**Comment by sdhull** [comment]
1. Fargo S01E01
2. nzbs.org

**Comment by sdhull** [comment]
But really -- isn't it true that you can't solve for file size by grepping the name? The solution to ensure you don't get episodes that are absurdly small or large is to limit file size. I don't understand why this is even a question.

**Comment by JackDandy** [comment]
Discussion is limited in Github, if you want to talk about this come to IRC.

**Comment by JackDandy** [comment]
To summarize our IRC convo ...

1) Size limits per quality create more issues than they solve
2) Episodes with different lengths of time can get wildly different file size, so false positives still occur
3) The purpose of this request is to filter releases out, the same is achieved using ignore words

This feature request can not be added to SG for release matching/filtering.
