### ISSUE TITLE
Regular expression used in custom RSS feeds doesn't catch all kinds of magnet links

### ISSUE THREAD

**Issue by lbeltrame** [SickGear/SickGear#930]
I've experienced this with latest master (as of 2017-05-03).

The code goes

```python
if url.startswith('magnet:'):
    if re.search('urn:btih:([0-9a-f]{32,40})', url):
        break
```

However I've seen magnet links in the form of (link truncated to only show the relevant part):

```
magnet:?xt=urn:btih:WSDOYTZ433AWV2QJ7M3434WL3HOZVEQR&tr
```

So there are two problems that the regex is not catching:

1. The match is case-sensitive but some feeds use capital letters
2. The match only uses a-f while some use `A-Za-z`

Note: I'm not familiar with the format of magnet links, so whatever I posted may violate their syntax. However in this case there's no way to tell why the feed fails validation, because it has items, it contains URLs, but the regex isn't catching them.

If you think this needs fixing in SickGear, I can cook up a PR.

**Comment by JackDandy** [comment]
We would need the feed URL, come to IRC if you feel more comfortable posting it there.

**Comment by JackDandy** [comment]
Complete; Change improve RSS validation (particularly for anime)
