### ISSUE TITLE
Issue with inSpeed_speedian cookie

### ISSUE THREAD

**Issue by pears0** [SickGear/SickGear#931]
Hi,

I keep seeing the following error in my logs for searches:
<pre>
2017-05-05 12:16:20 BACKLOG-114801 :: [SpeedCD] :: Error while searching SpeedCD, skipping: There are multiple cookies with name, 'inSpeed_speedian'
</pre>
When I check my config.ini file and search for the cookie name, I'm only returning a single result. The issue doesn't always show up, and seems to go away when I reset my cookie details via the config pages, but re-appears after a restart I believe.

**Comment by JackDandy** [comment]
Fix in release 0.12.16
