### ISSUE TITLE
Rename .torrents as torrent.fail when there is nothing wrong with the .torrent

### ISSUE THREAD

**Issue by wylde780** [SickGear/SickGear#938]
BRANCH: master / COMMIT: f1550e4ebcd93adab7a22174eb3922c766cfcee0
** This was happening on the previous version as well but an upgrade did not resolve the issue**

Expected Result
Suddently SG is renaming ALL failed with .failed yet i'm able to load those same .fail torrents into rtorrent and they download without issue. Zero logging information about why nor does it even log that the rename occurred. The expected result would be for SG to download and have the torrent load in rtorrent as it use to do or produce some logged event telling what went wrong.	
Steps to reproduce:

1) start SG
2) let it search for a episode to fetch
3) look in the download folder and you'll find the torrent appended with .fail
4) you'll notice your torrenting application will not load this torrent

Additional notes:
Nothing fancy here

**Comment by JackDandy** [comment]
dupe #937
