### ISSUE TITLE
Jackett?

### ISSUE THREAD

**Issue by barbequesauce** [SickGear/SickGear#939]
Any thoughts about Jackett support?

**Comment by JackDandy** [comment]
We maintain native providers, [requests considered](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#can-you-please-add-a-provider).

**Comment by untoreh** [comment]
@JackDandy do you mean that you don't add support for meta providers? "only native providers" ?
medusa supports jackett https://github.com/pymedusa/Medusa/wiki/Using-Jackett-with-Medusa

**Comment by JackDandy** [comment]
See [https://github.com/SickGear/SickGear/wiki/%5BWarning%5D-Using-External-Search-Tools](here)
