### ISSUE TITLE
Error: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by barbequesauce** [SickGear/SickGear#940]
Hi - 

Two shows in my library were added from Trakt search. When I click on them, I receive a [white browser error](https://pastebin.com/XC7kWEAX): "__init__() got an unexpected keyword argument 'encoding'". Log error is [here](https://pastebin.com/kuMtG5hr).

I have no underlying data in either show's folder; I'm happy enough to delete and re-add the shows, but I can't figure out how...

BRANCH: develop / COMMIT: 7c0faec835b5154764d642947e4f9c0752d2cad8

**Comment by JackDandy** [comment]
Delete the newly create folder in your parent tv show folder and add the show another way for now.

**Comment by barbequesauce** [comment]
I deleted both directories, then tried to re-add from TVDB. It indicated that they already existed in the database...

**Comment by barbequesauce** [comment]
New log [here](https://pastebin.com/KqYBWuAk)

**Comment by JackDandy** [comment]
Try force a "show update" - if you get lost at this point, come to IRC.
