### ISSUE TITLE
Add EZTV?

### ISSUE THREAD

**Issue by barbequesauce** [SickGear/SickGear#945]
Can EZTV.ag be added as a media provider please?

**Comment by JackDandy** [comment]
Can you name a release that is only available on that provider and not any other PA provider?

**Comment by barbequesauce** [comment]
There are a number of shows for which I'm struggling to fill backlog, and the older episodes do not seem to be seeded anywhere else - season 2 eps 20-23 of Hawaii Five-O,  season 2 eps 7 & 22 of Marvel's Agents of Shield, S03E01 of The Tudors...

**Comment by JackDandy** [comment]
With 7 (pa) providers. I enabled just one and found s2e20 of Hawaii in seconds.  Unless mistaken, I cannot believe that any of the releases you mention are so exclusive to be not available on any of the other 7 in the same quality as on eztv. I won't check them all, proving the first release was enough. My original question remains for you to prove conclusively - NO guessing allowed ;) Oh and make sure you set correct qualities when testing your searches, i.e. initial, custom -> HD and SD.

**Comment by JackDandy** [comment]
Added [here](https://github.com/SickGear/SickGear/commit/12363d01d5476abf30cabde9ee16c6ef49ffab57#diff-df4c0baab6c2897b8609063ebd8a8ea6)
