### ISSUE TITLE
Deluge and HTTPS

### ISSUE THREAD

**Issue by Mericko** [SickGear/SickGear#95]
BRANCH: (develop) / COMMIT: (1aa07940af93e037e10934a22b301811490c74fe)

**Deluge Client:** 1.3.11-py2.7 (Windows 8.1 x64)
**Deluge Web:** 1.3.11 (Ubuntu 14.04, Python 2.7.6) 

ISSUE:

After enabling HTTPS in `deluge-web` on my remote seedbox and setting up SickGear to connect over HTTPS it will fail to send torrents to Deluge when they are snatched. Disabling HTTPS on both and using plain old HTTP works as expected without a hitch.

LOG:

```
2014-12-11 12:46:54 ERROR    SEARCHQUEUE-MANUAL-82696 :: Deluge: Authentication Failed
2014-12-11 12:46:54 DEBUG    SEARCHQUEUE-MANUAL-82696 :: Calling Deluge Client
```

WHAT I HAVE TRIED:

* Checking `Verify certificate` in the options and also disabling it
* Using the automatically generated and self signed certificate provided by `deluge-web`
* Using a certificate signed by Verisign
* Proxying `deluge-web` through `Nginx` so `Nginx` handles SSL
 * With this setup it receives an A+ the Qualys Labs SSL test.

SICKGEAR CONFIGURATION:

```
[General]
enable_https = 0

[TORRENT]
torrent_username = ""
torrent_password = REDACTED
torrent_host = https://seedbox.com:45025/
torrent_path = ""
torrent_verify_cert = 1
```
ADDITIONAL NOTES:

With HTTPS enabled the `Test Connection` button seems to have no problem connecting. It only fails when you actually try to snatch torrents

The `Deluge username` field should also probably be removed until you properly add support for `deluged`. I don't know much Python, but glancing at the code it looks like the only way to talk to Deluge is using `deluge-web`.

The web client only supports the `Deluge password` field and does not support usernames at all. `Deluge username` field would would be used with `deluged` but it doesn't seem to be supported at the moment.

This field made it very very annoying to troubleshoot until I glanced at the code trying to figure why it would not connect to `deluged` but would authenticate just fine with `deluge-web`

**Comment by adam111316** [comment]
Gui has been fixed, however you need to use the deluge web-ui for interfacing with deluge
