### ISSUE TITLE
[REQUEST] Add support for Slack as a notifier

### ISSUE THREAD

**Issue by Fahl-Design** [SickGear/SickGear#959]
Hey there
greate job so far! But I'm missing the Slack notifier from Sickbeard you can find the original PR here: https://github.com/midgetspy/Sick-Beard/pull/968

would be nice to see it in the next version

thanks

**Comment by JackDandy** [comment]
I read that PR way back and waited for the promised token addition, care to finish it off ?

**Comment by JackDandy** [comment]
#989
