### ISSUE TITLE
Read Timeout

### ISSUE THREAD

**Issue by RemonH** [SickGear/SickGear#960]
Can someone help me to find where i can change the read timeout? I need to change this from 30 to more minutes. This is the only way to make spotwep work for me. 

I receive the message below: 
Read timed out msg:HTTPConnectionPool(host='192.168.178.138', port=80): Read timed out. (read timeout=30) while loading URL http://192.168.178.138/spotweb/api?apikey=xxxx&limit=500&attrs=rageid%2Ctvmazeid&offset=0&t=tvsearch&maxage=1500&cat=5030%2C5040

In the settings i also changed the limit to 1500. I the log this is stil 500.

**Comment by JackDandy** [comment]
Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

Thanks.
