### ISSUE TITLE
Mapped network drive

### ISSUE THREAD

**Issue by donbrew1** [SickGear/SickGear#962]
This is strange, I don't know  if it has anything to do with SickGear.
I installed SickGear on windows 10 on 6/21/16 it is now updated to  BRANCH: master / COMMIT: 9c3a158a5df3aea9f438e3038074282e2fbe5f44.

It can see and use my mapped network drive in post processing.

I installed a new fresh instance alongside same hash different port.  It cannot see the mapped network drive, but works fine otherwise.  I copied the entire contents of the old SickGear folder into the folder of the new install.  It is still not working. I did edit the port.

What could be the difference?

**Comment by JackDandy** [comment]
Rather than go back and forwards and make a messy thread here, best you come to IRC to try and thrash this one out.
