### ISSUE TITLE
Problems with post processing

### ISSUE THREAD

**Issue by rvoosterhout** [SickGear/SickGear#970]
Hello,

I get a recurring error while post processing.

2017-08-22 15:13:31 POSTPROCESSER :: Unable to move file  D:\Completed\Stargate SG-1\Season10\stargate_sg-1.10x06.200.dvdrip_xvid-fov.avi to E:\Series\Stargate SG-1\Season 10\Stargate SG-1 S10E06 - 200.avi [Errno 13] Permission denied: u'E:\\Series\\Stargate SG-1\\Season 10\\Stargate SG-1 S10E06 - 200.avi'

I wonder where the double \\ comes from, and if this is the reason causing this issue.

Kind regards

**Comment by JackDandy** [comment]
Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

Thanks.

**Comment by rvoosterhout** [comment]
Ok, I see that the double \ \ are changed to single \, so thats a bit hard to debug..

**Comment by JackDandy** [comment]
For your first release, I tested same filename in same folder, works as seen in the following log...
<pre>
Destination folder for this episode is D:\_Video\tv\Stargate SG-1\Season 10
Copied file from D:\_incoming\pp\Stargate SG-1\Season5\stargate_sg-1.10x06.200.dvdrip_xvid-fov.avi
.. to D:\_Video\tv\Stargate SG-1\Season 10\Stargate.SG-1.s10e06.200.SD.DVD.avi
Successfully processed stargate_sg-1.10x06.200.dvdrip_xvid-fov.avi
</pre>
and for you second example, also success...
<pre>
Destination folder for this episode is D:\_Video\tv\Stargate SG-1\Season 05
Moved file from D:\_incoming\pp\Stargate SG-1\Season5\Stargate.SG1.S05E04.AC3.DivX.DVDRip-AMC.avi
.. to D:\_Video\tv\Stargate SG-1\Season 05\Stargate.SG-1.s05e04.The.Fifth.Man.SD.DVD.avi
Successfully processed Stargate.SG1.S05E04.AC3.DivX.DVDRip-AMC.avi
</pre>
I also have a strange feeling you are runnign sickgear as a service, if you are, this is very incorrect and will cause permission and other issues, please uninstall all that badness and reinstall using the guide provided in the wiki.  Other than that, everything works as expected here.

**Comment by rvoosterhout** [comment]
Thanks for your reply. I'm not running sickgear as a service and i followed the install instructions. I reinstalled sickgear and i moved my processed folder to the same drive as where the series are located, to see if that helps.
