### ISSUE TITLE
Post processing aborts when encountering a broken symlink

### ISSUE THREAD

**Issue by deed02392** [SickGear/SickGear#981]
During file post processing, an enumeration of the post process directory is first recorded to be subsequently iterated over.

During this loop, if a symlink in the post process directory was pointing to a file that didn't exist, this will cause the post processor to abort. This can be found with a WARNING log entry.

`WARNING  POSTPROCESSER :: Batch skipped, error 2 : No such file or directory (file /incoming/foo.bar.mkv)`

Where `/incoming/foo.bar.mkv` is a symlink pointing to a location which doesn't exist.

This can be easily tested by attempting to post process a directory with a symlink pointing to a file that doesn't exist. If it is sorted before any other files in the directory, files will **never** be processed.

Such files could come from unraring of downloads, or in the case where the symlink post process mode of sickgear is used and that episode is subsequently renamed (for example officially on tvdb, prompting sickgear to recommend a rename).

This issue could be addressed by ignoring the file not found error if the file was referenced by a symlink. However, I cannot think of a good reason to abort the post processing regardless of whether the suddenly non-existent file has been deleted. This could legitimately occur as a race condition where the user removes a downloaded file during post processing that was present during dir enumeration and then missing by the time processing of that directory entry was due.

**Comment by JackDandy** [comment]
There are many hypotheticals here with the main ideas not confirmed to have actually occurred with an actual release so maybe this is a case of reading code, and considering possibilities over likelihood of occurrence. That said, I totally appreciate the approach, that is, defensive design; if you can submit a PR to cover the issue where an abort of process is curtailed into a skip of bad file, then that makes sound sense.

Anything further to this type of thread is best continued in IRC :)
