### ISSUE TITLE
Feature Request: Add xspeeds.eu torrent provider

### ISSUE THREAD

**Issue by jtwill** [SickGear/SickGear#986]
Xspeeds.eu is one of the largest private general trackers, it has great pre-times, and it has all unRARed content. I'm actually surprised that it is not already supported by the various Sick- forks.

It currently has open signups, so if any developers are lacking accounts, now is the time to get one:

https://www.reddit.com/r/OpenSignups/comments/6zkj8y/open_xspeeds_general/

**Comment by JackDandy** [comment]
Add as RSS ?
<img src="https://github.com/SickGear/SickGear/issues/986">

**Comment by JackDandy** [comment]
Add as RSS. Confirmed (with the cookie field addition)

<a name"xs"><img src="https://vgy.me/9DxDqT.png"></a>
