### ISSUE TITLE
Post Process failed

### ISSUE THREAD

**Issue by JaRiL** [SickGear/SickGear#992]
1. BRANCH: develop / COMMIT: b6806359cf2e267ad87a4962f9cece6b4813ef31
2. expected SG to postprocess todays shows:
Bull.2016.S02E02.720p.HDTV.X264-DIMENSION.mkv
The.Mick.S02E02.720p.WEB.x264-TBS.mkv
Lethal.Weapon.S02E02.720p.HDTV.X264-DIMENSION
from downloaded shows folder(X:\Downloading\Torrents\TV(all files in this folder is moved there on completion)) 
i saw that some files where never copied/postprocessed to the Series folder(G:\"showName"\Season\)
the files in question that did work from todays list of shows are
Lethal.Weapon.S02E02.720p.HDTV.X264-DIMENSION

shows that did not work
Bull.2016.S02E02.720p.HDTV.X264-DIMENSION.mkv
The.Mick.S02E02.720p.WEB.x264-TBS.mkv

3. same thing happended yesterday but i manually postprocessed the shows because i wanted to see them and knew that i should try to reproduce the issues again today anyway..
4. https://gist.github.com/JaRiL/e4d76cf314c8ad09dd2591de71459c07

**Comment by JaRiL** [comment]
i've narrowed the error a bit more, it seems its only a problem with torrents that are not in a folder, IE just the MKV file... and only the second of the kind, fx today
i've downloaded 
The.Blacklist.S05E02.720p.HDTV.x264-AVS - which is rar files in a folder
Designated.Survivor.S02E02.720p.HDTV.x264-AVS - also in a folder
Seal.Team.S01E02.720p.HDTV.X264-DIMENSION.mkv - not in a folder but seemed to work fine
Chicago.PD.S05E02.720p.HDTV.x264-KILLERS.mkv not in a folder and did not post process correct

but according to the log file it is again looking at Seal team to compare the chicago files with... 
https://gist.github.com/JaRiL/f31ed779599696a9503f0ae271327f4a

**Comment by dkyr1968** [comment]
Following yesterday's update to COMMIT: e96f5420216cd32ddc0576ed69e4c3d743e3dc2b, i have the same problem - currently there are 11 episodes in the Completed TV downloads that do not get postprocessed. If i manually run the postprocess media i get below message for all of them

-----
Unable to move file  C:\Users\XBMC\Downloads\complete\tv\Blackish.S04E01.HDTV.x264-SVA[eztv].mkv
.. to F:\TV Shows\Black-ish\Season 04\Black-ish S04E01 - 	Juneteenth.mkv
.. [Errno 22] invalid mode ('wb') or filename: u'F:\\TV Shows\\Black-ish\\Season 04\\Black-ish S04E01 - \tJuneteenth.mkv'
Did not use file C:\Users\XBMC\Downloads\complete\tv\Blackish.S04E01.HDTV.x264-SVA[eztv].mkv
--------

**Comment by JackDandy** [comment]
@dkyr1968 
can you look at your history page and find provider that release came from ?

**Comment by JackDandy** [comment]
@dkyr1968 
Can you look at your pp naming pattern, maybe you have added a tab char in there ?

**Comment by JackDandy** [comment]
@JaRiL @dkyr1968 can either/both of you come to IRC for testing a fix we have.

**Comment by dkyr1968** [comment]
Just checked - using one of the predefined naming schemes it works fine, so
it is probably the custom naming defined by me.

thanks

**Comment by JackDandy** [comment]
#993
