### ISSUE TITLE
Post processing fails

### ISSUE THREAD

**Issue by kitten77** [SickGear/SickGear#998]
Version:	BRANCH: develop / COMMIT: 76f766fb5d8fbd7f27f16a97ce0326ea91aec62d

Checking folder... /usr/home/sickgear/SickGear/sortme
Processing folder... /usr/home/sickgear/SickGear/sortme
Processing sub dir: Marvels.Agents.of.S.H.I.E.L.D.S04E09.1080p.WEB-DL.DD5.1.H264-RARBG
Processing sub dir: .Trash-1001
Processing... e3a3192760c52d2b3f35bd0946370887aeb39176433ffd1d7fc2bd4c891e7838.mkv
Found a match in history for Marvel's Agents of S.H.I.E.L.D.
Parsed E3 [ABD: False] [ANIME: False] [whichReg: ['no_season_general']]
.. from e3a3192760c52d2b3f35bd0946370887aeb39176433ffd1d7fc2bd4c891e7838.mkv
Retrieving episode object for 4x3
Using "1080p WEB-DL" quality from the snatch history
An episode exists in the database with the same quality as the episode to process
New file /usr/home/sickgear/SickGear/sortme/Marvels.Agents.of.S.H.I.E.L.D.S04E09.1080p.WEB-DL.DD5.1.H264-RARBG/e3a3192760c52d2b3f35bd0946370887aeb39176433ffd1d7fc2bd4c891e7838.mkv
.. is smaller than /home/sickgear/media/Marvel's Agents of S.H.I.E.L.D/Season 04/S04E03.Uprising.mkv
Checking size of existing file /home/sickgear/media/Marvel's Agents of S.H.I.E.L.D/Season 04/S04E03.Uprising.mkv <-- this is not E03 it is E09
.. marking it unsafe to replace the existing larger file
Quitting this post process
Did not use file /usr/home/sickgear/SickGear/sortme/Marvels.Agents.of.S.H.I.E.L.D.S04E09.1080p.WEB-DL.DD5.1.H264-RARBG/e3a3192760c52d2b3f35bd0946370887aeb39176433ffd1d7fc2bd4c891e7838.mkv

The same file during post processing just without the e first:

Checking folder... /usr/home/sickgear/SickGear/sortme
Processing folder... /usr/home/sickgear/SickGear/sortme
Processing sub dir: Marvels.Agents.of.S.H.I.E.L.D.S04E09.1080p.WEB-DL.DD5.1.H264-RARBG
Processing sub dir: .Trash-1001
Processing... 3a3192760c52d2b3f35bd0946370887aeb39176433ffd1d7fc2bd4c891e7838.mkv
Found a match in history for Marvel's Agents of S.H.I.E.L.D.
Parsed Marvels Agents of S H I E L D - S4E9 [GROUP: RARBG] [ABD: False] [ANIME: False] [whichReg: ['standard']]
.. from Marvels.Agents.of.S.H.I.E.L.D.S04E09.1080p.WEB-DL.DD5.1.H264-RARBG
Retrieving episode object for 4x9
Using "1080p WEB-DL" quality from the snatch history
An episode exists in the database with the same quality as the episode to process
File doesn't exist /home/sickgear/media/Marvel's Agents of S.H.I.E.L.D/Season 04/S04E09.Broken.Promises.mkv
.. there is no file to replace, marking it safe to continue
Found release name Marvels.Agents.of.S.H.I.E.L.D.S04E09.1080p.WEB-DL.DD5.1.H264-RARBG
Destination folder for this episode is /home/sickgear/media/Marvel's Agents of S.H.I.E.L.D/Season 04
Copied file from /usr/home/sickgear/SickGear/sortme/Marvels.Agents.of.S.H.I.E.L.D.S04E09.1080p.WEB-DL.DD5.1.H264-RARBG/3a3192760c52d2b3f35bd0946370887aeb39176433ffd1d7fc2bd4c891e7838.mkv
.. to /home/sickgear/media/Marvel's Agents of S.H.I.E.L.D/Season 04/S04E09.Broken.Promises.mkv
Successfully processed 3a3192760c52d2b3f35bd0946370887aeb39176433ffd1d7fc2bd4c891e7838.mkv

As you can see it now process the file as E09 not as E03 all because i removed the leading e from the filename it was processing.

**Comment by kitten77** [comment]
sorry it took me so long too confirm this, but i can now say that i have seen this multiple times

**Comment by JackDandy** [comment]
Can you confirm that they are all from rarbg ? 

If yes, ignore those releases for now.

**Comment by kitten77** [comment]
no this also happens on a few of the Ntb-pre releases as well, the worst part is that i now have episodes called 3753 and specials that shouldnt even be aired yet. seems like all the releases where the e# is first will fail this way or end up as wrong episode blocking the real episode from downloading

**Comment by kitten77** [comment]
Checking folder... /usr/home/sickgear/SickGear/sortme
Processing folder... /usr/home/sickgear/SickGear/sortme
Processing sub dir: Marvels.Agents.of.S.H.I.E.L.D.S04E09.1080p.WEB-DL.DD5.1.H264-RARBG
Processing sub dir: .Trash-1001
Processing... e3a3192760c52d2b3f35bd0946370887aeb39176433ffd1d7fc2bd4c891e7838.mkv
Found a match in history for Marvel's Agents of S.H.I.E.L.D.
Parsed Marvels Agents of S H I E L D - S4E9 [GROUP: RARBG] [ABD: False] [ANIME: False] [whichReg: ['standard']]
.. from Marvels.Agents.of.S.H.I.E.L.D.S04E09.1080p.WEB-DL.DD5.1.H264-RARBG
Retrieving episode object for 4x9
Using "1080p WEB-DL" quality from the snatch history
An episode exists in the database with the same quality as the episode to process
File doesn't exist /home/sickgear/media/Marvel's Agents of S.H.I.E.L.D/Season 04/S04E09.Broken.Promises.mkv
.. there is no file to replace, marking it safe to continue
Found release name Marvels.Agents.of.S.H.I.E.L.D.S04E09.1080p.WEB-DL.DD5.1.H264-RARBG
Destination folder for this episode is /home/sickgear/media/Marvel's Agents of S.H.I.E.L.D/Season 04
Copied file from /usr/home/sickgear/SickGear/sortme/Marvels.Agents.of.S.H.I.E.L.D.S04E09.1080p.WEB-DL.DD5.1.H264-RARBG/e3a3192760c52d2b3f35bd0946370887aeb39176433ffd1d7fc2bd4c891e7838.mkv
.. to /home/sickgear/media/Marvel's Agents of S.H.I.E.L.D/Season 04/S04E09.Broken.Promises.mkv
Successfully processed e3a3192760c52d2b3f35bd0946370887aeb39176433ffd1d7fc2bd4c891e7838.mkv
-----------------------
Successfully processed.

Found the bugger, it as simple as processing the folder before the file in the lambda statements:

postProcessor.py
:531
        attempt_list = [self._history_lookup,

                        # try to analyze the nzb name
                        lambda: self._analyze_name(self.nzb_name),

                        # try to analyze the file name
                        #lambda: self._analyze_name(self.file_name),
                        lambda: self._analyze_name(self.folder_name),
                        
                        # try to analyze the dir name
                        # lambda: self._analyze_name(self.folder_name),
                        lambda: self._analyze_name(self.file_name),
                        
                        # try to analyze the file + dir names together
                        lambda: self._analyze_name(self.file_path),

                        # try to analyze the dir + file name together as one name
                        lambda: self._analyze_name(self.folder_name + u' ' + self.file_name)]

**Comment by JackDandy** [comment]
#993
